### ISSUE TITLE
Something about parameters like frameSize, hopSize, patchSize, numberBands etc. 

### ISSUE THREAD

**Issue by VickyChing** [MTG/essentia#1000]
Sorry, there's still an issue to be resolved.

For now, we have separate feature extraction and model prediction process by using TensorflowInputVGGish/TensorflowInputMusiCNN and TensorflowPredict, the prediction result is close to TensorflowPredictVGGish/TensorflowPredictMusiCNN, but it is not the same, we guess it is due to the different parameter setting, could you tell us the parameter values like frameSize, hopSize, patchSize, numberBands?

Thank you very much!

**Comment by pabloEntropia** [comment]
TensorflowPredictVGGish/TensorflowPredictMusiCNN are just wrappers for the whole processing chain.
You can simply inspect the code to see the particular parametrization they use:
https://github.com/MTG/essentia/blob/8ae940e717c6b6565a3e988ba834aca38f0c4246/src/algorithms/machinelearning/tensorflowpredictmusicnn.cpp#L99

https://github.com/MTG/essentia/blob/8ae940e717c6b6565a3e988ba834aca38f0c4246/src/algorithms/machinelearning/tensorflowpredictvggish.cpp#L98
