### ISSUE TITLE
Improve logging on Android devices

### ISSUE THREAD

**Issue by amCap1712** [MTG/essentia#1008]
Android discards all log output to stdio and stderr by default. There is an option to modify this behaviour but it is only available on rooted devices. Android NDK provides a logging library to be used instead.

**Comment by fcfrt** [comment]
> Android discards all log output to stdio and stderr by default. There is an option to modify this behaviour but it is only available on rooted devices. Android NDK provides a logging library to be used instead.

amCap1712, could you please send me a copy of your compiled Android library Thank you very much! E-mail：AlanPaine@163.com

**Comment by dbogdanov** [comment]
Closing as the PR #1009 was merged.
