### ISSUE TITLE
Couple of questions regarding this project

### ISSUE THREAD

**Issue by Joe23232** [MTG/essentia#1020]
I have a couple of questions regarding this project.

- Am I able to import this library to the [Rust](https://www.rust-lang.org) programming language and for the [Processing](https://processing.org) programming language (which is Java based language)?
- Am looking for a high level audio crate library that allows me to easily get various information about an audio such as its loudness, tempo, current key/pitch etc? Can this library do this? If so is it ok I can get a sample code as to how do I do this?

**Comment by pabloEntropia** [comment]
Hello! Essentia is a C++ library and so far we just provide wrappers for [Python](https://essentia.upf.edu/essentia_python_tutorial.html) and [JavaScript](https://github.com/MTG/essentia.js).

And yes, with Essentia you can easily extract those audio descriptors. We have examples for most of those in [C++](https://github.com/MTG/essentia/tree/master/src/examples) and [Python](https://essentia.upf.edu/essentia_python_examples.html).

**Comment by Joe23232** [comment]
Hey man :)

> And yes, with Essentia you can easily extract those audio descriptors. We have examples for most of those in C++ and Python.

Ah I see thanks :)
