### ISSUE TITLE
Windows builds

### ISSUE THREAD

**Issue by anchpop** [MTG/essentia#1021]
I see [way back when it was the plan to bring back windows native builds](https://github.com/MTG/essentia/issues/204#issuecomment-69561706). Is this still on the roadmap? I'd love to use this from python but I'm a little intimidated at the idea of firing up MinGW and trying to cross-compile. Or, if there were precompiled binaries available anywhere, that would be awesome.

**Comment by goloskokovic** [comment]
https://github.com/MTG/essentia/issues/330#issuecomment-581362303
