### ISSUE TITLE
pip install essentia failed of RPi

### ISSUE THREAD

**Issue by FunkyKwak** [MTG/essentia#1028]
Hi,

I am trying to install essentia on my Raspberry Pi with Raspbian. I want to use the essentia module in a python program.
Unfortunately I am getting this error durnig the installation (started with `pip install essentia`) :

> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8afp49/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-55GYZV-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code -9 in /tmp/pip-build-8afp49/numpy/
[pip insatll essentia - complete log.txt](https://github.com/MTG/essentia/files/5112270/pip.insatll.essentia.-.log.txt)

Do you have any idea what's wrong ?

**Comment by dbogdanov** [comment]
No packages for ARM yet, you need to build Essentia from source.
