### ISSUE TITLE
Is possible conect to Live Video??

### ISSUE THREAD

**Issue by sanvir10** [MTG/essentia#1048]
For example, is possible connect to https://www.bloomberg.com/live(ot youtube bloomberg live), and downloading the stream with Essentia??.

I want connect to live Audio/Video and save all the audio/video.

For help thanks so much.

**Comment by alastair** [comment]
Essentia can open a remote audio stream as supported by [ffmpeg's http loader](https://ffmpeg.org/ffmpeg-protocols.html#http), but cannot discover a stream from a website. Essentia doesn't support loading video.
