### ISSUE TITLE
 OnsetRate error

### ISSUE THREAD

**Issue by lazumbra** [MTG/essentia#107]
I got this mensage : what():  In OnsetRate::onsets::set(): Output not bound to concrete object
who know what does it mean??
as input for this algorithm I filled with the signal I got from the AudioLoader.

**Comment by ImSeenOne** [comment]
I'd like to know where are those discussions. I've just discovered this amazing thing and would like to know how to solve this issue, I'm not a pro in C++ and would like to approach something using JNI.

**Comment by dbogdanov** [comment]
@ImSeenOne Not related to this specific issue, but have a look at [setting inputs and outputs for algorithms in the standard mode in C++](https://essentia.upf.edu/howto_standard_extractor.html#connecting-the-algorithms).
