### ISSUE TITLE
ClickDetector output error

### ISSUE THREAD

**Issue by skrowten-hermit** [MTG/essentia#1074]
I was trying to use the audio problem algorithm [ClickDetector](https://essentia.upf.edu/reference/std_ClickDetector.html) to detect a click/pop I had artificially created in a speech file at 19774th sample using audacity (with an amplitude of 1 and a length of 20 samples - [-1, 0, 1, 0, -1, 0, 1, 0, -1, 0, 1, 0, -1, 0, 1, 0, -1, 0, 1, 0]). The input file had 64000 samples (8k sampled file of length 8 seconds). But I don't understand the output. It returns the positions/indices as mentioned in the attached files.
[clickstart.log](https://github.com/MTG/essentia/files/5526545/clickstart.log)
[clickend.log](https://github.com/MTG/essentia/files/5526547/clickend.log)

Aren't indices supposed to be integers? Here, the output clearly shows Real (float) valued indices for the clicks. I'm assuming it is in seconds. Even so, I find that:
1. there are repeating indices/positions.
2. the position of the click/pop I generated is shifted. For example, the output says end of my click/pop is at 2.46525001526s which translates to 19722th sample, but my click/pop itself starts at 19774th sample.

The following is the code I wrote:

    int frameSize = 2048;
    int hopSize = 1024;
    sampleSize = monoVectorSource.size();
    
    vector<Real> CDframe;
    vector<Real> clickStartvec, clickEndvec;
    vector<Real> clickStarts, clickEnds;
    
    Algorithm* fcC = factory.create("FrameCutter",
                                    "frameSize", frameSize,
                                    "hopSize", hopSize);
    
    Algorithm* cdProb = factory.create("ClickDetector",
                                       "frameSize", frameSize,
                                       "hopSize", hopSize,
                                       "sampleRate", sourceSampleRate);
    
    fcC->input("signal").set(monoVectorSource);
    fcC->output("frame").set(CDframe);
    
    cdProb->input("frame").set(CDframe);
    cdProb->output("starts").set(clickStartvec);
    cdProb->output("ends").set(clickEndvec);
    
    while (true)
    {
      fcC->compute();
    
      if (!CDframe.size())
      {
        break;
      }
    
      cdProb->compute();
    
      clickStarts.insert(clickStarts.end(), clickStartvec.begin(), clickStartvec.end());
      clickEnds.insert(clickEnds.end(), clickEndvec.begin(), clickEndvec.end());
    }

I haven't set any of the parameters `detectionThreshold`, `powerEstimationThreshold`, `order` or `silenceThreshold` and let them retain the default values. Being a speech file, do I need to pass values other than the default values to these parameters to get the expected output? If yes, please suggest the ideal values. If not, is this algorithm intended to be used differently? Any suggestions and help will be great.

Attaching the code and the input test `wav` file herewith:
[click.zip](https://github.com/MTG/essentia/files/5532849/click.zip)

**Comment by palonso** [comment]
1. You are right. The start/end positions are expressed in seconds. This should be clarified in the documentation.

2. Respect to the repetitions, the algorithm `push_back()` to the `starts` and `ends` vectors on each call to `compute()` so in your code, you can use the resulting `clickStartvec` without needing to accumulate by yourself. This is not an intuitive behaviour, so we should improve the documentation about it.

Regarding the thresholds I don't know the optimal values, but they should be optimized for each application. I recommend setting them as input parameters of your program so you can try several values to find the one that works for you.
