### ISSUE TITLE
GapsDetector output error

### ISSUE THREAD

**Issue by skrowten-hermit** [MTG/essentia#1075]
I was trying to use the audio problem algorithm [GapsDetector](https://essentia.upf.edu/reference/std_GapsDetector.html) to detect gaps I had artificially created in a speech file at multiple locations to create a broken words in the speech using audacity (by removing samples). The input file had 64000 samples (8k sampled file of length 8 seconds). But my output shows that the algorithm seems to detect only the gap I created around 5.25 seconds, that too with a shift or mistakenly detects an original/intended silence as a gap.

The following is the code I wrote:

    int frameSize = 2048;
    int hopSize = 1024;
    sampleSize = monoVectorSource.size();
    
    vector<Real> GDframe;
    vector<Real> gapStartvec, gapEndvec;
    vector<Real> gapStarts, gapEnds, gapLengths;
    
    Algorithm* fcG = factory.create("FrameCutter",
                                  "frameSize", frameSize,
                                  "hopSize", hopSize);
    
    Algorithm* gdProb = factory.create("GapsDetector",
                                     "frameSize", frameSize,
                                     "hopSize", hopSize,
                                     "sampleRate", sourceSampleRate);
    
    fcG->input("signal").set(monoVectorSource);
    fcG->output("frame").set(GDframe);
    
    gdProb->input("frame").set(GDframe);
    gdProb->output("starts").set(gapStartvec);
    gdProb->output("ends").set(gapEndvec);
    
    while (true)
    {
      fcG->compute();
    
      if (!GDframe.size())
      {
        break;
      }
    
      gdProb->compute();
    
      gapStarts.insert(gapStarts.end(), gapStartvec.begin(), gapStartvec.end());
      gapEnds.insert(gapEnds.end(), gapEndvec.begin(), gapEndvec.end());
    }

I haven't set any of the parameters other than `frameSize`, `hopSize` and `sampleRate` and let the other parameters retain the default values. Being a speech file, do I need to pass values other than the default values to these parameters to get the expected output? If yes, please suggest the ideal values. If not, is this algorithm intended to be used differently? Any suggestions and help will be great.

Attaching the code and the input test `wav` file herewith:
[gaps.zip](https://github.com/MTG/essentia/files/5532841/gaps.zip)

**Comment by palonso** [comment]
You should optimize the algorithm parameters for your case. To do this we provide [Python script](https://github.com/MTG/essentia/blob/master/test/src/QA/gaps/test_gaps.py) that allows to compute several metrics for a given group of input audio files. You could use it to find the optimal parameters for your application.
