### ISSUE TITLE
What is the current Tensorflow implementation? Examples using TensorflowPredict TensorflowPredictMusiCNN and TensorflowPredictVGGish do not work. 

### ISSUE THREAD

**Issue by JCurtisRMIT** [MTG/essentia#1076]
I can't seem to use any of the following with essentia 2.1b6.dev234

 `TensorflowPredict` `TensorflowPredictMusiCNN` and `TensorflowPredictVGGish`

or run the Tensorflow examples shown here: https://github.com/MTG/essentia/blob/master/src/examples/tutorial/essentia_python_examples.ipynb

The directions to build from source in https://github.com/MTG/essentia/issues/1027 and [here](https://mtg.github.io/essentia-labs/news/tensorflow/2019/10/19/tensorflow-models-in-essentia/) do not work as `tensorflow==1.15` is no longer available.

`ERROR: Could not find a version that satisfies the requirement tensorflow==1.15.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0, 2.4.0rc1)
ERROR: No matching distribution found for tensorflow==1.15.0`

does the essentia-tensorflow package contain these methods?  are they deprecated?

I've tried solutions offered in https://github.com/MTG/essentia/issues/977 and other issues on this repo and the package does not seem to be available. `ERROR: No matching distribution found for essentia-tensorflow`

Can you advise?

Ubuntu 20.04
pip 20.2.4
Python 3.8.5
essentia 2.1b6.dev234

**Comment by JCurtisRMIT** [comment]
Creating a new `virtualenv` with Python 3.7.9 allows `pip` to find the `essentia-tensorflow` package and install it

 `TensorflowPredict` `TensorflowPredictMusiCNN` and `TensorflowPredictVGGish` are now available!

**Comment by francossavella** [comment]
I am getting the following error: 
RuntimeError: Error while configuring TensorflowPredictMusiCNN: TensorflowPredict: could not open the Tensorflow graph file.
While running the example code on a Collab Notebook and having installed both essentia and essentia-tensorflow through pip
Thoughts?
