### ISSUE TITLE
Cross-compiling from ubuntu to windows broken

### ISSUE THREAD

**Issue by nelemans1971** [MTG/essentia#1080]
Downloaded and compiled essentia (beta 5) for linux on ubuntu 18.04 LTS, without to much problems.
Then I tried to compile it for windows, and failed misserbely.

I tried to run ./packaging/build_3rdparty_static_win32.sh but almost all builds failed.

- eigen failed because the download location doesn't exist anymore, I think I fixed this with some changes to the download path
- fftw3 failer because a libfftw3f-3.dll doesn't exists which the script expects it does
- ffmpeg is also missing dll it expects to find 
- chromaprint can't be compiled because fftw isn't available

The download location https://essentia.upf.edu/extractors/ only has beta2 binary versions for windows.

I'd really like to compile it for windows, so I can use multiple pc's to process a large amount (about 8 million) of audio files.

**Comment by dbogdanov** [comment]
Thanks for noticing that. We'll review the build scripts. 

Updated Eigen build in 2978c9454bcebf2d2e6e1534199b4663489149f0.

**Comment by dbogdanov** [comment]
Pre-compiled extractors added for the latest master:
https://essentia.upf.edu/extractors/essentia-extractors-v2.1_beta5-356-g673b6a14-win-i686/
