### ISSUE TITLE
FreesoundExtractorSVM Algorithm in FreeSoundExtractor missing although Gaia2 is found

### ISSUE THREAD

**Issue by davidriederer** [MTG/essentia#1083]
Dear Essentia Team,
thank you for the nice framework!
Unfortunately I got a issue I could not figure out myself.

After successfully building essentia on Linux Debian (`./waf configure --build-static --with-python --with-static-examples --with-gaia`) I want to use the FreesoundExtractor binary to analyse files and add highlevel descriptors with a SVM.
The extractor itselfs works as expected for lowlevel and tonal descriptors etc., but when I add a profile to the extractors call to generate highlevel descriptors the following error is shown:

```
./essentia_streaming_extractor_freesound myFile.mp3 myFile.yaml ./extractor_profile_svm.yaml
```
leads to
```
Identifier 'FreesoundExtractorSVM' not found in registry...
Available algorithms: ...
```
where FreesoundExtractorSVM is not included in the long list of available algorithms.

When doing the same thing with the **MusicExtractor**, everything works as expected, including the highlevel descriptors. Both extractors where built with the same version of essentia, and during the same compile.

As far as I can tell from the code and loggings, Gaia should have been detected, and the FreesoundExtractorSVM Algorithm should be created for the given models through the AlgorithmFactory.
I can't figure out, why the extractor doesn't accept the highlevel-descriptor parameter in the profile.

After searching the web, I both tried a static and non-static build and different configurations. According to the code in freesoundextractor.h the highlevel parameter should be added to the extractor, when HAVE_GAIA2 is set. This seems to be the case judging by the `config.log`. 

**Excerpts from my `config.log`:**
```
Checking for 'gaia2'
['/usr/bin/pkg-config', '--cflags', '--libs', 'gaia2']
out: -I/usr/local/include -I/usr/include/qt4 -I/usr/include/qt4/QtCore -L/usr/local/lib -L\[QtCore\] -lgaia2 -lQtCore -lyaml

yes
```
and
```
[...'-DHAVE_EIGEN3=1', '-DEIGEN_PERMANENTLY_DISABLE_STUPID_WARNINGS', '-DHAVE_AVCODEC=1', '-DHAVE_AVFORMAT=1', '-DHAVE_AVUTIL=1', '-DHAVE_AVRESAMPLE=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_TAGLIB=1', '-DHAVE_YAML=1', '-DHAVE_FFTW=1', '-DHAVE_LIBCHROMAPRINT=1', '-DHAVE_GAIA2=1', '-D__STDC_CONSTANT_MACROS',
...]
```

**When configuring the build:**
```
...
- TagLib detected!
  The following algorithms will be included: ['MetadataReader', 'MusicExtractor', 'FreesoundExtractor']
...
- Gaia2 detected!
  The following algorithms will be included: ['GaiaTransform', 'MusicExtractorSVM']
```
In the list of algorithms to ignore (when using `./waf`) FreeSoundExtractorSVM does not show up (as expected):

```
Ignoring the following algorithms: FFTK, IFFTA, FFTKComplex, IFFTK, IFFTAComplex, TensorflowPredict, FFTAComplex, TensorflowPredictMusiCNN, IFFTKComplex, FFTA, TensorflowPredictVGGish
```

Any help on how to get the highlevel parameter working in the FreesoundExtractor with a profile would be greatly appreciated!

**Comment by dbogdanov** [comment]
Hi, @davidriederer. There was a call to a non-existing FreesoundExtractorSVM, fixed that with 867dfa474292e035a27f44a233d0b321d42e5688. 

Note that we do not provide any pretrained SVM models for FreesoundExtractor. That is, you cannot simply re-use the SVM models we have for MusicExtractor, because the descriptors they compute and use in SVMs are different. You'll have to train your own models.
