### ISSUE TITLE
repeated runs of essentia on the same audio file give different outputs

### ISSUE THREAD

**Issue by nelemans1971** [MTG/essentia#1087]
Hello,
I downloaded the latest compiled windows version (beta5-356-g673b6a14-win-i686), and compared the output result with the version on linux which I compiled myself. The output was different, although I would expect them to be the same.

After some more testing, I ran the same command twice (with the same executable). The output is different every time on the same audio file. 
I did this for the linux version and for the windows version. Multiple runs on the same audio file give different results.

I've included the result of two consecutive runs on the audio file "Drowned world; Substitue for love / Madonna". The input was a WAV file, 44,1 kHz with a length of 5 minutes and 8 seconds.

[Lowlevel-json-result.zip](https://github.com/MTG/essentia/files/5652247/Lowlevel-json-result.zip)

Is this normal?

**Comment by dbogdanov** [comment]
Hi @nelemans1971,

One issue there could be is that MusicExtractor is using [FrameCutter](https://essentia.upf.edu/reference/streaming_FrameCutter.html) with `silentFrames` = `noise` by default. For a track with silent frames this will provide slightly different results. Please double-check if you get the same kind of differences in Linux outputs on multiple runs. If the results on Linux are stable, then we have an issue.

Besides, you can configure the `silentFrames` behavior in the [profile configuration file](https://essentia.upf.edu/streaming_extractor_music.html#configuration).

**Comment by nelemans1971** [comment]
Did some testing with the option silentFrames = keep & silentFrames = drop, the default is indeed noise

beta2, beta5 and beta6 binary tested under linux (ubuntu LTS 18.04)
Settings silentFrames = keep or drop gave reproducible results with the same binary

With the windows binary I also got reproducible results with these settings. unfortunately mixing beta 6 linux with the windows version gave different result.

Compiling myself the windows version did get me succesfully past running ./packaging/build_3rdparty_static_win32.sh
But after running
./waf configure --with-static-examples --cross-compile-mingw32
./waf
It stopped because of missing header files. I can find the header file under wingw, but geting the enviroment to finding  repairing this is out of my league

In file included from /usr/share/mingw-w64/include/time.h:293:0,
                 from ../src/essentia/streaming/../utils/tnt/tnt_stopwatch.h:24,
                 from ../src/essentia/streaming/../utils/tnt/tnt.h:57,
                 from ../src/essentia/streaming/../essentiautil.h:27,
                 from ../src/essentia/streaming/phantombuffer.h:27,
                 from ../src/essentia/streaming/source.h:138,
                 from ../src/essentia/streaming/streamingalgorithm.h:271,
                 from ../src/algorithms/standard/silencerate.h:62,
                 from ../src/algorithms/standard/silencerate.cpp:20:
/usr/include/x86_64-linux-gnu/sys/timeb.h:21:10: fatal error: features.h: No such file or directory
 #include <features.h>
          ^~~~~~~~~~~~
