### ISSUE TITLE
RhythmExtractor2013 on IOS runs faster than on Android

### ISSUE THREAD

**Issue by MinskyChu** [MTG/essentia#1107]
I compiled it on IOS and Android successfully (fft-acc on IOS and fft-kiss on Android) . But when I test on the same level of CPU, Android consumes a lot more time than IOS. RhythmExtractor2013 and Resample runs very slowly on Android device.
I don't know what went wrong. Is there anyone who can help me?

**Comment by dbogdanov** [comment]
Is this behavior specific to certain algorithms? Which dependencies are included in your build?

**Comment by MinskyChu** [comment]
> Is this behavior specific to certain algorithms? Which dependencies are included in your build?

@dbogdanov Thank you for your reply. It is not  specific to certain algorithms. The test found that the time spent on running RhythmExtractor2013 and Resample is particularly large. Dependencies included libav and libsamplerate. The algorithm works well on Android devices, and I get the correct results。

./waf configure --cross-compile-android \
                --build-static \
                --fft=KISS \
                --pkg-config-path=/Users/abc/Library/Android/essentia/pkgconfig \
                --prefix=/Users/abc/Library/Android/essentia \
                --include-algos=FFT,Windowing,Onsets,OnsetDetection,CartesianToPolar,Resample,RhythmExtractor2013,MonoLoader,Duration,AudioLoader,MonoMixer,BeatTrackerMultiFeature,FrameCutter,NoiseAdder,HFC,Flux,MelBands,TriangularBands,TempoTapDegara,IIR,MovingAverage,AutoCorrelation,OnsetDetectionGlobal,Spectrum,Magnitude,ERBBands,TempoTapMaxAgreement,Scale

Is there anything wrong？

**Comment by fcfrt** [comment]
> > Is this behavior specific to certain algorithms? Which dependencies are included in your build?
> 
> @dbogdanov Thank you for your reply. It is not specific to certain algorithms. The test found that the time spent on running RhythmExtractor2013 and Resample is particularly large. Dependencies included libav and libsamplerate. The algorithm works well on Android devices, and I get the correct results。
> 
> ./waf configure --cross-compile-android
> --build-static
> --fft=KISS
> --pkg-config-path=/Users/abc/Library/Android/essentia/pkgconfig
> --prefix=/Users/abc/Library/Android/essentia
> --include-algos=FFT,Windowing,Onsets,OnsetDetection,CartesianToPolar,Resample,RhythmExtractor2013,MonoLoader,Duration,AudioLoader,MonoMixer,BeatTrackerMultiFeature,FrameCutter,NoiseAdder,HFC,Flux,MelBands,TriangularBands,TempoTapDegara,IIR,MovingAverage,AutoCorrelation,OnsetDetectionGlobal,Spectrum,Magnitude,ERBBands,TempoTapMaxAgreement,Scale
> 
> Is there anything wrong？

Minskychu, could you please send me a copy of your compiled Android library Thank you very much! E-mail：AlanPaine@163.com

**Comment by MinskyChu** [comment]
> --fft=KISS
> --pkg-config-path=/Users/abc/Library/Android/essentia/pkgconfig
> --prefix=/Users/abc/Library/Android/essentia
> --include-algos=FFT,Windowing,Onsets,OnsetDetection,CartesianToPolar,Resample,RhythmExtractor2013,MonoLoader,Duration,AudioLoader,MonoMixer,BeatTrackerMultiFeature,FrameCutter,NoiseAdder,HFC,Flux,MelBands,TriangularBands,TempoTapDegara,IIR,MovingAverage,AutoCorrelation,OnsetDetectionGlobal,Spectrum,Magnitude,ERBBands,TempoTapMaxAgreement,Scale

**Comment by MinskyChu** [comment]
I've solved the problem of Resample，but the problem of RhythmExtractor2013 still exists. For the same audio, the time spent on Android devices is twice that on IOS. Because FFT is different？

**Comment by MinskyChu** [comment]
Because FFT is different. It took a lot of time to run the function in FFT-KISS.
