### ISSUE TITLE
REQ 16kHz support in EqualLoudness

### ISSUE THREAD

**Issue by jpauwels** [MTG/essentia#1108]
Feature request: it would be nice to be able to use EqualLoudness (and consequently EqLoudnessLoader) with signals sampled at 16kHz. Right now there's a big gap between the lowest and second lowest supported sample rates: 8000, 32000, 44100, 48000.

**Comment by dbogdanov** [comment]
I agree this should be very useful as 16KHz is frequently used in many analysis applications. The filter values are hardcoded: https://github.com/MTG/essentia/blob/master/src/algorithms/filters/equalloudness.cpp#L54.

A pull request is welcome.

**Comment by jpauwels** [comment]
I'd happily add it myself if I knew how those hardcoded values were calculated for the other samplerates.

**Comment by dbogdanov** [comment]
@jpauwels We had a similar update in https://github.com/MTG/essentia/pull/362. There is a matlab script that can be used to compute the coefficients.

**Comment by dbogdanov** [comment]
Thanks for the PR @jpauwels.  Can you send a CLA following our [contribution policy](http://essentia.upf.edu/contribute)?

**Comment by jpauwels** [comment]
Done. FYI, the link you sent is dead, but I found a link to the form in the contributor guidelines

**Comment by dbogdanov** [comment]
That was a bad copy-paste. Thanks!
