### ISSUE TITLE
YamlInput with python

### ISSUE THREAD

**Issue by Tiago622** [MTG/essentia#1119]
Hello, I am using essentia with python to obtain music features and then I am saving the pool in JSON files with the YamlOutput algorithm.
Now I wanted to get these features from the JSON files and I think I can do it using YamlInput algorithm, but aparently I'm not doing it correctly.

I am executing the following code and I think the result should be in the pool, how can I see the data?
Thanks.
```
pool = essentia.Pool ()

pool = es.YamlInput (filename = './features.json', format = 'json')
```

**Comment by dbogdanov** [comment]
Hi @Tiago622,

The `pool` variable in your code snippet is a configured instance of an algorithm, not its Pool output. Make sure you execute the instance by a function call.

For example:

```
import essentia.standard as es
features_aggregated, features_frames = es.MusicExtractor()("audiofile.wav")

# Save pool to a JSON file
es.YamlOutput(filename="/tmp/test.json", format="json")(features_aggregated)

# Load pool from a JSON file
new_pool = es.YamlInput(filename="/tmp/test.json", format="json")()
new_pool.descriptorNames()
```
