### ISSUE TITLE
Illegal hardware instruction

### ISSUE THREAD

**Issue by adamjakab** [MTG/essentia#1122]
Hi,

I am compiling the 2.1 beta5 branch on mac. The os is macOS Catalina (10.15.6) installed on an unsupported iMac Late 2009 - I used the [DosDude](http://dosdude1.com/catalina/) patcher to do this.
 
I compile and install without errors:
> python waf configure --with-examples --mode=release
> python waf build
> python waf install

I get a lot of warnings (no errors) when I compile the examples:
`../src/essentia/algorithmfactory_impl.h:27:8: warning: instantiation of variable 'essentia::EssentiaFactory<essentia::standard::Algorithm>::_instance' required here, but no definition is available [-Wundefined-var-template]`

When I run `/usr/local/bin/essentia_streaming_extractor_music` without arguments all is ok:
```
Error: wrong number of arguments
Usage: /usr/local/bin/essentia_streaming_extractor_music input_audiofile output_textfile [profile]

Music extractor version 'music 2.0'
built with Essentia version v2.1_beta5

This software uses code of Libav (https://libav.org) licensed under the
LGPLv2.1 (see: https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html)
```

However if I try to use it as intended `/usr/local/bin/essentia_streaming_extractor_music audio.mp3 out.json` I get:
```
[   INFO   ] MusicExtractor: Read metadata
[   INFO   ] MusicExtractor: Compute md5 audio hash, codec, length, and EBU 128 loudness
zsh: illegal hardware instruction  essentia_streaming_extractor_music audio.mp3 out.json
```

That **"illegal hardware instruction"** makes me think that it has to do with my unusual environment and probably the compiler adding instructions to the compiled code that is not supported by my cpu.
Can you help me how to track down what the issue is and how to solve it?

**Comment by alastair** [comment]
At a guess, for some reason your compiler has used one of the extensions that your CPU doesn't support. 
From a very quick look it seems like the 2009 imac has a Core 2 Duo CPU? That dates from ~2006, and means that it could be any of the later extensions listed here: https://en.wikichip.org/wiki/x86/extensions

I'm not sure why the compiler didn't pick up that some extensions aren't available, and it's possible that your patcher has confused it in this regard.

It seems like you should be able to [disable specific extensions](https://stackoverflow.com/questions/30716321/how-can-i-compile-without-various-instruction-sets-enabled), for example [somewhere around here](https://github.com/MTG/essentia/blob/master/wscript#L121), but I don't know which extensions are in use, or if it's possible to disable all of the ones listed in the first link.

It's also possible that one of the dependencies is compiled with these extensions enabled (for example ffmpeg for reading audio). How did you install the dependencies? Did you also compile from scratch?

**Comment by adamjakab** [comment]
Hey @alastair - thanks. I also think that it is strange my compiler would do such a "mistake". My gut feeling says that you are probably right in saying that it could be a compiled dependency that is causing the issue. In fact, I did not compile any of the dependencies but I installed them with homebrew. Maybe my patcher confused pkg-config or something related to it. I will try to investigate in this sense. If that does not produce any results I will try disabling specific extensions... but it look hairy.

**Comment by adamjakab** [comment]
This is clearly not an Essentia issue so I am closing it here.

In my current environment I am unable to compile gcc failing with a similar `Illegal Instruction: 4`. error.
Just for anyone ending up on this thread I leave a couple of links to resoursec pointing to the possible causes and solutions one could adopt:

- https://github.com/dosdude1/macos-catalina-patcher/issues/26
- https://github.com/Homebrew/linuxbrew-core/issues/1683
- https://discourse.brew.sh/t/almost-all-applications-crash-with-illegal-hardware-instruction-on-old-2009-macbook-pro/4089
