### ISSUE TITLE
MusicExtractor: Take audio from array instead of reading it from file

### ISSUE THREAD

**Issue by baronefr** [MTG/essentia#1124]
I use essentia MusicExtractor in a python script, as in the following code:

`essfeat, essfeatframes = es.MusicExtractor(lowlevelStats=['mean', 'stdev'],
                                              rhythmStats=['mean', 'stdev'],
                                              tonalStats=['mean', 'stdev'])(file_name_temp)`

in which _file_name_temp_ is an audio file. But I want the function to **take the input audio from an array**, instead of reading it from the file. Is there any way to do this?

**Comment by dbogdanov** [comment]
You cannot do it with our current pipeline inside the `MusicExtractor` algorithm. It is designed to work with audio files and extracts audio and metadata. The audio is first normalized by the loudness (replay gain).

Do you have specific descriptors in mind that you want to compute? You can use our other algorithms for particular features, including `KeyExtractor`, `TonalExtractor`, `RhythmExtractor2013`, `LowLevelSpectralExtractor` and `LowLevelSpectralEqloudExtractor`. The configurations for features in these algorithms aren't exactly equivalent to `MusicExtractor`.
