### ISSUE TITLE
Perform es.MusicExtractor on a silent file

### ISSUE THREAD

**Issue by Tiago622** [MTG/essentia#1129]
Hello,
I am using es.MusicExtractor to extract the features of a song. But before doing this process, I am separating the audio into sources (vocals and accompaniment) and when the original song has only instrumental, the vocals audio comes absolutely silent has expected, and then executing the feature extraction on silent file results in crash.
Is this the expected result? The framework is supposed to crash on silent files or should at least return all features with '0' or NaNs values and don't crash?
**Output:** 
RuntimeError: In MusicExtractor.compute: File looks like a completely silent file... Aborting...

**Comment by dbogdanov** [comment]
Hi @Tiago622,

Yes, this is expected. We normalize the input audio by the replay gain value [computed for the input audio file](https://github.com/MTG/essentia/blob/master/src/algorithms/extractor/musicextractor.cpp#L538). Replay gain values above the threshold of `40 dB` will lead to this exception.

We decided to opt for an exception for (almost) silent files as the analysis results on such files can be unreliable. The extractor was initially designed to analyze (commercial) music recordings with an expectation of a proper loudness of the signal.
