### ISSUE TITLE
ImportError: No module named essential when running python test

### ISSUE THREAD

**Issue by ghost** [MTG/essentia#113]
Help! I got the following error when running python test:
.........................................
$./waf run_python_tests
Traceback (most recent call last):
  File "test/src/unittest/all_tests.py", line 27, in <module>
    import essentia
ImportError: No module named essential
.........................................
Then which python gives me:
$which python
/usr/bin/python
.........................................
Seems python doesn't find essential
$python
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import essentia
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named essentia
> > > .........................................

This is my configuring of essential
$./waf configure --mode=release --with-python --with-cpptests --with-examples --with-vamp
Checking for 'g++' (c++ compiler)        : clang++ 
Checking for 'gcc' (c compiler)          : clang 
Checking for program pkg-config          : /usr/local/bin/pkg-config 
Checking for 'libavcodec'                : yes 
Checking for 'libavformat'               : yes 
Checking for 'libavutil'                 : yes 
Checking for 'libswresample'             : yes 
Checking for 'taglib'                    : yes 
Checking for 'yaml-0.1'                  : yes 
Checking for 'fftw3f'                    : yes 
Checking for 'samplerate'                : yes 
Checking for 'gaia2'                     : not found 
Checking for program python              : /usr/bin/python 
Checking for python version              : (2, 7, 5, 'final', 0) 
Checking for library python2.7 in LIBDIR : yes 
Checking for program /usr/bin/python-config,python2.7-config,python-config-2.7,python2.7m-config : /usr/bin/python-config 
Checking for header Python.h                                                                     : yes 

================================ CONFIGURATION SUMMARY ================================
- FFmpeg / libav detected!
  The following algorithms will be included: ['AudioLoader', 'MonoLoader', 'EqloudLoader', 'EasyLoader', 'MonoWriter', 'AudioWriter']
- libsamplerate (SRC) detected!
  The following algorithms will be included: ['Resample']
- TagLib detected!
  The following algorithms will be included: ['MetadataReader']
- Gaia2 seems to be missing.
  The following algorithms will be ignored: ['GaiaTransform']
  .........................................

I've followed the documentation in detail except the gaia which I considered it is independent from essentia and ignored then. What do I miss? I am fairly new to the environment of terminal or python, please help me.

**Comment by savovs** [comment]
Keep in mind Essentia doesn't work with Python 3 yet
