### ISSUE TITLE
ConstantQ leaks object

### ISSUE THREAD

**Issue by jpcima** [MTG/essentia#1143]
Based on a quick examination of `constantq`, it appears that a FFT object does not get freed.

https://github.com/MTG/essentia/blob/52aa2604144bda0aa6a9e3af8c76d376a0081e67/src/algorithms/standard/constantq.h#L72-L84

**Comment by cvf-bcn-gituser** [comment]
@dbogdanov PR #1160 added to fix this.  If merged please close.
