### ISSUE TITLE
Chords sometimes not recognized accuracy

### ISSUE THREAD

**Issue by kevinszjmm** [MTG/essentia#1146]
hi, Dear
When i use my piano to play some music , some chords can not recognized accuracy，for example: i played 4C & 4D & 4E, it recognized 4C& 4D, it not appears every time.
how to resolve this question
shall i get more sounds of my piano to train the model?

**Comment by imiskolee** [comment]
absolutely. Essentia has not a powerful chord detection that can be working on production, and I am also working on the task and get a better result used Tensorflow Lite on mobiles.

**Comment by dbogdanov** [comment]
Definitely, chords is the area that should be improved. Adding a new algorithm/model is on the wishlist.
