### ISSUE TITLE
question for HPCP feature

### ISSUE THREAD

**Issue by imiskolee** [MTG/essentia#1149]
Hello, all:

I am used the HPCP feature extractor, and have a question on param `size`. I tried change the `size` to 24 or 36, the results also is 24 or 36 vector, but looks like them also on  1 octave.

How to do for get 2 or more octaves HPCP feature, because the 1-octave HPCP missing frequency order information.

**Comment by dbogdanov** [comment]
This parameter affects bin resolution. We've updated the documentation to clarify this further.
