### ISSUE TITLE
Model prediction differs from demo

### ISSUE THREAD

**Issue by gabrielcrds** [MTG/essentia#1152]
I'm trying essentia in a colab for gtzan genre prediction, but all the models achieve terrible results and differ from the demo. What am I doing wrong?
```
!pip3 install essentia-tensorflow
```
```
import os
import essentia
import json
import essentia.standard as es
from essentia.standard import *
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
```
```
base_path = '/content/drive/MyDrive/gtzan/'
classes = ["blu", "cla", "cou", "dis", "hip", "jaz", "met", "pop", "reg", "roc"] # from model json
predictor = es.TensorflowPredictMusiCNN(graphFilename=base_path + " model/genre_tzanetakis-musicnn-msd-1.pb")
audio = MonoLoader(filename=base_path + "song/disco/disco.00000.wav")()
genre_pred = predictor(audio)
scores = list(zip(np.mean(genre_pred, axis=0), classes))
max(scores)
```
This code outputs:
```
(0.34047183, 'blu')
```
While the [live demo](https://essentia.upf.edu/demos/deep-learning/genre_tzanetakis) returns the correct label. I also tried other models, but not a single one predicts the song correctly as 'dis', while they do in the demo. This model is predicting 28% of the songs correctly.

**Comment by palonso** [comment]
Hello @gabrielcrds,
`TensorflowPredictMusiCNN` expects audio at 16kHz. Notice that by default [MonoLoader](https://essentia.upf.edu/reference/std_MonoLoader.html) resamples the audio to 44.1kHz, so you have to modify the `sampleRate`  parameter
```Python
audio = MonoLoader(filename=base_path + "song/disco/disco.00000.wav", sampleRate=16000)()
```

**Comment by gabrielcrds** [comment]
That was it, thank you!
