### ISSUE TITLE
PyQT5 compatibility issues

### ISSUE THREAD

**Issue by gbibbo** [MTG/essentia#1171]
I'm having a strange problem when running NNLSChroma from Essentia.

I have written a program that calculates the Tonal Interval Vectors of an audio file. The complete program can be found in my Github repository (https://github.com/gbibbo/harmonic_mix). All the analysis functions are defined in "`main.py`". Then I made a graphical interface to run the program, using PyQT5.

The problem is that the functions in `main.py` run correctly, but when I call them from GUI.py, I get a very strange error message:

```
Traceback (most recent call last):
  File "/home/gabriel/PycharmProjects/testing_get_max_compatibility/GUI.py", line 101, in analyze_click
    analyze_song(song_path)
  File "/home/gabriel/PycharmProjects/testing_get_max_compatibility/main.py", line 121, in analyze_song
    chroma = audio_to_nnls(harmonic)
  File "/home/gabriel/PycharmProjects/testing_get_max_compatibility/main.py", line 35, in audio_to_nnls
    nnls = NNLSChroma(frameSize=frameSize, spectralShape=0.7, useNNLS=True)
  File "/home/gabriel/anaconda3/envs/mt/lib/python3.6/site-packages/essentia/standard.py", line 44, in __init__
    self.configure(**kwargs)
  File "/home/gabriel/anaconda3/envs/mt/lib/python3.6/site-packages/essentia/standard.py", line 64, in configure
    self.__configure__(**kwargs)
RuntimeError: Error while configuring NNLSChroma: Parameter spectralShape = 0.700000011921 is not within specified range: (0.5,0.9)

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

It is strange that the value of the spectralShape is equal to 0.700000011921 when I defined it as 0.7.
It is also strange that it returns an error because the value is not within the range, when the value actually falls in the allowed range.
But finally I don't understand why NNLSChroma works in one situation (from main.py) but not in the other (from GUI.py).

**Comment by dbogdanov** [comment]
Have a look at the similar issue: https://github.com/MTG/essentia/issues/866

Can you reproduce it with the basic code mentioned there?

**Comment by dbogdanov** [comment]
I have reproduced and isolated this issue to the following:
```
import essentia.standard as ess
import sys
from PyQt5.QtWidgets import QApplication

app = QApplication(sys.argv)
nnls_all_default = ess.NNLSChroma()
```

> Traceback (most recent call last):
  File "/tmp/harmonic_mix/foo.py", line 6, in <module>
    nnls_all_default = ess.NNLSChroma()
  File "/usr/local/lib/python3.9/dist-packages/essentia/standard.py", line 44, in __init__
    self.configure(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/essentia/standard.py", line 64, in configure
    self.__configure__(**kwargs)
RuntimeError: Error while configuring NNLSChroma: Parameter spectralShape = 0.699999988079 is not within specified range: (0.5,0.9)

**Comment by dbogdanov** [comment]
Another example of issues with Range: https://github.com/MTG/essentia/issues/500

**Comment by dbogdanov** [comment]
Affected algorithms:

```
src/algorithms/tonal/nnlschroma.h:    declareParameter("spectralShape", " the shape of the notes in the NNLS dictionary", "(0.5,0.9)", 0.7);
src/algorithms/tonal/harmonicpeaks.h:    declareParameter("tolerance", "the allowed ratio deviation from ideal harmonics", "(0,0.5)", 0.2);
```
