### ISSUE TITLE
How to use mfcc for sbic?

### ISSUE THREAD

**Issue by mctyro** [MTG/essentia#118]
mfcc->output("mfcc")      >>  sbic->input("features");

this code will raise as follows.

terminate called after throwing an instance of 'essentia::EssentiaException'
  what():  While connecting MFCC::mfcc to SBic::features:
Error when checking types. Expected: std::vector<Real>, received: TNT::Array2D<float>

how to fix it?
Thanks!

**Comment by dbogdanov** [comment]
MFCC outputs vectors of Reals while SBic expects to receive a matrix (Array2D). It was unclear from the error message (fixed in master branch).
