### ISSUE TITLE
Complete example on OpenL3

### ISSUE THREAD

**Issue by eatsleepraverepeat** [MTG/essentia#1180]
Guys, first of all I'd like to thank you for your outstanding efforts on building such a useful tools,

and ask you to **provide a complete example on OpenL3 embedder model** usage.

I tried to follow documentation on using Tensorflow models in Standard mode (with generic `TensorflowPredict`) and stuck on audio preprocessing stage. Also, didn't find any helper class for inferencing from OpenL3 such the ones you did for other nn models.

Checked on `2.1-beta6-dev`

Best of luck

**Comment by palonso** [comment]
Yes, currently we do not have a dedicated algorithm to extract OpenL3 embeddings and reproducing the mel-spectrograms specific to this model is not straight forward.
For now I can share this [gist](https://gist.github.com/palonso/cfebe37e5492b5a3a31775d8eae8d9a8) with our internal code to extract OpenL3 embeddings, although we plan to create a dedicated algorithm as for the rest of models.
