### ISSUE TITLE
Cannot use onsetStart = peakEnergy for SingleBeatLoudness in python bindings

### ISSUE THREAD

**Issue by ChlorideCull** [MTG/essentia#1182]
Using 2.1b6.dev374 from pypi.

Simple reproduction:

````python3
import essentia.standard
audio = essentia.standard.MonoLoader(filename="test.wav")()
essentia.standard.SingleBeatLoudness(onsetStart='peakEnergy')(audio[:int(0.2*44100.)])
````

When trying to initialize `SingleBeatLoudness`, it will throw `RuntimeError: Error while configuring SingleBeatLoudness: Parameter onsetStart = "peakEnergy" is not within specified range: {sumEnergy, peakEnergy}`

It passes validation with a leading space (but does not do anything), so I guess the issue is with the space in the third argument to `declareParameter` in the header: https://github.com/MTG/essentia/blob/07d089fe0fea04cd654b24e2f518775322ff85bb/src/algorithms/rhythm/singlebeatloudness.h#L74

**Comment by dbogdanov** [comment]
Fixed now, thanks for spotting this!
