### ISSUE TITLE
Extract MFCC standard deviation and second derivative in python

### ISSUE THREAD

**Issue by Rashikumra** [MTG/essentia#1187]
Hi,

How can we extract mfcc Standard deviation in python using essentia?
I was trying to use direct' lowlevel.mfcc.stdev' but it is throwing an error : "KeyError: "no key found named 'lowlevel.mfcc.stdev' "".

Also is there any direct way to calculate mfcc variance, its first and second derivative in python .

**Comment by dbogdanov** [comment]
You can use [PoolAggregator](https://essentia.upf.edu/reference/std_PoolAggregator.html) to computed stats over a pool of values. [Here is an example for MFCC](https://essentia.upf.edu/essentia_python_tutorial.html#aggregation-and-file-output) (to compute MFCCs see the previous section of this tutorial).
