### ISSUE TITLE
Unable to repeat MusicExtractor results with individual algorithms (Python)

### ISSUE THREAD

**Issue by jkranabetter** [MTG/essentia#1189]
Im having trouble getting the results of the music extractor and the individual algorithms to line up. As a result I have lost considerable model prediction accuracy. I have tried different windowing, equal loudness filtering, normalizing, and DC removal. 

My feature extraction code and the results are below. 

Replicating the music extractors 'lowlevel.silence_rate_60dB.stdev' value is particularly important as it is ranked number 1 for class prediction. Also the gfcc result is considerably off.

Any information is greatly appreciated!

**RESULTS**

        feature                                      music extractor     individual          
        lowlevel.silence_rate_60dB.stdev             0.49986782          0.0                 
        lowlevel.spectral_flux.mean                  0.04855299          0.001923265867      
        lowlevel.spectral_rms.mean                   0.00208200          8.239784802e-05     
        metadata.audio_properties.replay_gain        22.0854625          22.05553436         
        lowlevel.gfcc.mean.0                         -81.79491425        -436.5969543        
        lowlevel.spectral_contrast_valleys.mean.0    -7.460084915        -9.298451424        
        lowlevel.spectral_contrast_valleys.stdev.2   0.594517231         0.5614771247        
        lowlevel.spectral_contrast_valleys.stdev.3   0.6901482344        0.7174130082        
        lowlevel.spectral_contrast_valleys.stdev.4   0.8201224208        0.820630312         
        lowlevel.spectral_contrast_valleys.stdev.5   0.4651556909        0.4815360904 

**CODE**

        import essentia
        import essentia.standard as engine
        import essentia.utils as utils
        
        excludedMetrics = ['rhythm.beats_position', 'rhythm.bpm_histogram',
                           'lowlevel.mfcc.icov', 'lowlevel.mfcc.cov', 'lowlevel.gfcc.icov', 'lowlevel.gfcc.cov']
        
        selectMetrics = ['lowlevel.silence_rate_60dB.stdev', 'lowlevel.spectral_contrast_valleys.mean.0', 'metadata.audio_properties.replay_gain', 'lowlevel.spectral_contrast_valleys.stdev.2',
                         'lowlevel.spectral_contrast_valleys.stdev.3', 'lowlevel.spectral_contrast_valleys.stdev.4', 'lowlevel.spectral_contrast_valleys.stdev.5', 'lowlevel.spectral_flux.mean', 'lowlevel.gfcc.mean.0', 'lowlevel.spectral_rms.mean']
        
        sampleRate = 44100
        frameSize = 2048
        hopSize = 1024
        
        def getEverything(directory):
            # Compute all features, aggregate only 'mean' and 'stdev' statistics for all low-level, rhythm and tonal frame features
            features, features_frames = engine.MusicExtractor(lowlevelStats=['mean', 'stdev'],
                                                              rhythmStats=[
                'mean', 'stdev'],
                tonalStats=['mean', 'stdev'])(directory)
        
            descriptorNames = features.descriptorNames()
        
            descriptorList = []
            values = []
        
            # unpack features in lists and return only select features
            for descriptor in descriptorNames:
                value = features[descriptor]
                # exclude certain metrics for now (list of lists)
                if(descriptor in excludedMetrics):
                    continue
                if (str(type(value)) == "<class 'numpy.ndarray'>"):
                    for idx, subVal in enumerate(value):
                        descriptor1 = descriptor + '.' + str(idx)
                        if(descriptor1 in selectMetrics):
                            descriptorList.append(descriptor + '.' + str(idx))
                            values.append(subVal)
                    continue
                else:
                    if(descriptor in selectMetrics):
                        descriptorList.append(descriptor)
                        values.append(repr(value))
        
            return descriptorList, values
        
        
        def getIndividualFeatures(file):
            loader = engine.MonoLoader(filename=file, sampleRate=sampleRate)
            # and then we actually perform the loading:
            audio = loader()
            # create algorithm instances
            window = engine.Windowing(type='blackmanharris62',
                                      zeroPadding=0, size=frameSize)
            spectral_contrast = engine.SpectralContrast(frameSize=frameSize,
                                                        sampleRate=sampleRate,
                                                        numberBands=6,
                                                        lowFrequencyBound=20,
                                                        highFrequencyBound=11000,
                                                        neighbourRatio=0.4,
                                                        staticDistribution=0.15)
            spectrum = engine.Spectrum(size=frameSize)
            # silence rate
            thresholds = [utils.db2lin(val/2.0) for val in [-60.0]]
            silence_rate = engine.SilenceRate(thresholds=thresholds)
            # spectral flux
            spectral_flux = engine.Flux()
            # Gammatone-frequency cepstral coefficients
            gfcc = engine.GFCC(sampleRate=sampleRate)
            # spectral RMS
            rms = engine.RMS()
            # replay gain
            rgain = engine.ReplayGain(sampleRate=sampleRate)
            # create pool for storage and aggregation
            pool = essentia.Pool()
        
            pool.add('metadata.audio_properties.replay_gain', rgain(audio))
        
            for frame in engine.FrameGenerator(audio, frameSize=frameSize, hopSize=hopSize, startFromZero=True, lastFrameToEndOfFile=True):
                # spectral contrast valleys
                frame_windowed = window(frame)
                frame_spectrum = spectrum(frame_windowed)
                sc_coeff, sc_valley = spectral_contrast(frame_spectrum)
                pool.add('lowlevel.spectral_contrast_valleys', sc_valley)
        
                # silence rate
                pool.add('lowlevel.silence_rate_60dB', silence_rate(frame))
        
                # spectral flux
                pool.add('lowlevel.spectral_flux', spectral_flux(frame_spectrum))
        
                # Gammatone-frequency cepstral coefficients
                bands, gfccs = gfcc(frame_spectrum)
                pool.add('lowlevel.gfcc', gfccs)
        
                # spectral RMS
                pool.add('lowlevel.spectral_rms', rms(frame_spectrum))
        
            # compute mean and variance of the frames
            aggrPool = engine.PoolAggregator(defaultStats=['mean', 'stdev'])(pool)
            features = {}
            features['lowlevel.silence_rate_60dB.stdev'] = aggrPool['lowlevel.silence_rate_60dB.stdev']
            features['lowlevel.spectral_flux.mean'] = aggrPool['lowlevel.spectral_flux.mean']
            features['lowlevel.spectral_rms.mean'] = aggrPool['lowlevel.spectral_rms.mean']
            features['metadata.audio_properties.replay_gain'] = pool['metadata.audio_properties.replay_gain'][0]
            features['lowlevel.gfcc.mean.0'] = aggrPool['lowlevel.gfcc.mean'][0]
            features['lowlevel.spectral_contrast_valleys.mean.0'] = aggrPool['lowlevel.spectral_contrast_valleys.mean'][0]
            features['lowlevel.spectral_contrast_valleys.stdev.2'] = aggrPool['lowlevel.spectral_contrast_valleys.stdev'][2]
            features['lowlevel.spectral_contrast_valleys.stdev.3'] = aggrPool['lowlevel.spectral_contrast_valleys.stdev'][3]
            features['lowlevel.spectral_contrast_valleys.stdev.4'] = aggrPool['lowlevel.spectral_contrast_valleys.stdev'][4]
            features['lowlevel.spectral_contrast_valleys.stdev.5'] = aggrPool['lowlevel.spectral_contrast_valleys.stdev'][5]
        
            descriptorList = list(features.keys())
            values = list(features.values())
        
            return descriptorList, values
        
        d1, v1 = getEverything('BF200Corpus/background/aiff/11.aiff')
        d2, v2 = getIndividualFeatures('BF200Corpus/background/aiff/11.aiff')
        
        print ('{:<45s}{:<20.15}{:<20.10}'.format('feature', 'music extractor', 'individual'))
        for idx, item in enumerate(d1):
            print ('{:<45s}{:<20.10}{:<20.10}'.format(d1[idx], v1[idx], v2[idx]))

**Comment by jkranabetter** [comment]
Using an extractor instead, answer not needed.

**Comment by dbogdanov** [comment]
Consult the implementation C++ code for the exact parameters and processing pipeline to be able to reproduce descriptor values.
