### ISSUE TITLE
How to turn of the INFO when reading the audio?

### ISSUE THREAD

**Issue by xiaozhah** [MTG/essentia#1213]
When I using `EasyLoader(filename=xxx, sampleRate=16000)` to load audio, the essentia prints these infos.

![image](https://user-images.githubusercontent.com/7589403/147644729-7205cdcd-ef6e-4cd7-815f-751d8e6ebb2b.png)

how to turn off these infos?

**Comment by palonso** [comment]
Assuming you are using the Python bindings:
```Python
import essentia
essentia.log.infoActive = False
```

Note that the same can be applied for warnings (`essentia.log.warningActive`) and errors (`essentia.log.errorActive`)
