### ISSUE TITLE
Microphone stream and -lasound option

### ISSUE THREAD

**Issue by feltrinm** [MTG/essentia#123]
Hi, I'm using Essentia to build an Extractor, but I'd like using the stream coming from the microphone. There is an alghorithm which does this?? 
I try to do, with a inputRingBuffer, a thread that insert into this buffer the microphone's stream with ALSA libraries (with Ubuntu), but when I compile (with ./waf) I should insert in the gcc (or g++) compiler the option -lasound to include the ALSA libraries. How I can insert this option in the ./waf compiler??

**Comment by dbogdanov** [comment]
You should be able to modify waf scripts if you are using them, but you can write code using Essentia without relying on them.
