### ISSUE TITLE
Segmentation Fault when using MonoWriter

### ISSUE THREAD

**Issue by urinieto** [MTG/essentia#125]
I am trying to use ```MonoWriter``` to hear some of my results but I get a segmentation fault error. I narrowed down the problem to facilitate reproduction:

    import essentia.standard as ES
    SAMPLE_RATE = 44100
    audio = ES.MonoLoader(filename=audio_file, sampleRate=SAMPLE_RATE)()
    ES.MonoWriter(filename='output.wav', sampleRate=SAMPLE_RATE)(audio)

which outputs:
    
    Segmentation fault: 11

In my case, the audio file is a mono file sampled at 44.1kHz with 32 bits. I am using Essentia 2.0.1 on a Mac OS X 10.9.4 with Python 2.7.6.

Any help would be appreciated. Thanks!

**Comment by umezo** [comment]
I had same problem. It will be caused by ffmpeg version.
I installed old version of ffmpeg 1.x and it works now.
try old version with ``` brew versions``` and checkout target rivision manually.

**Comment by dbogdanov** [comment]
I am refactoring AudioWriter, which will solve these issues

**Comment by dbogdanov** [comment]
The same issue reported in #86, refactored AudioWriter in the latest master
