### ISSUE TITLE
RhythmExtractor2013 cannot convert argument UNDEFINED to VECTOR_REAL

### ISSUE THREAD

**Issue by Galvo87** [MTG/essentia#1254]
When trying to extract bpm/beats/beats_confidence from any son using RhythmExtractor2013 following the docs, I get the following:

`Traceback (most recent call last):
  File "/home/developer/.local/lib/python3.8/site-packages/essentia/standard.py", line 97, in compute
    convertedData = _c.convertData(arg, goalType)
  File "/home/developer/.local/lib/python3.8/site-packages/essentia/common.py", line 349, in convertData
    raise TypeError('Cannot convert data from type %s (%s) to type %s' %
TypeError: Cannot convert data from type UNDEFINED (<class 'essentia.standard._create_essentia_class.<locals>.Algo'>) to type VECTOR_REAL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tempo.py", line 13, in <module>
    bpm, beats, beats_confidence, _, beats_intervals = rhythm_extractor(song)
  File "/home/developer/.local/lib/python3.8/site-packages/essentia/standard.py", line 123, in __call__
    return self.compute(*args)
  File "/home/developer/.local/lib/python3.8/site-packages/essentia/standard.py", line 99, in compute
    raise TypeError('Error cannot convert argument %s to %s' \
TypeError: Error cannot convert argument UNDEFINED to VECTOR_REAL
`
Any clue of what's going on?

**Comment by Galvo87** [comment]
Any hint about this issue please?

**Comment by stonelazy** [comment]
Facing this issue in https://github.com/MTG/essentia/blob/master/src/examples/python/essentia_python_tutorial.ipynb 
Any fixes yet ?

**Comment by stonelazy** [comment]
> Facing this issue in https://github.com/MTG/essentia/blob/master/src/examples/python/essentia_python_tutorial.ipynb Any fixes yet ?

Turns out, Essentia requires audio to be loaded using it's own audio loader. Worked after using MonoLoader to load the audio file.
