### ISSUE TITLE
Can't install Essentia on MacOS catalina

### ISSUE THREAD

**Issue by bclark288** [MTG/essentia#1258]
I'm trying to install Essentia on my mac and I'm getting the following error:
Installing essentia from mtg/essentia
==> Downloading https://homebrew.bintray.com/bottles/isl-0.23.catalina.bottle.tar.gz
Warning: Transient problem: HTTP error Will retry in 1 seconds. 3 retries     
Warning: left.
Warning: Transient problem: HTTP error Will retry in 2 seconds. 2 retries     
Warning: left.
Warning: Transient problem: HTTP error Will retry in 4 seconds. 1 retries     
Warning: left.
-=O=-    #    #    #    #                                                     
curl: (22) The requested URL returned error: 502 Bad Gateway
Error: Failed to download resource "isl"
Download failed: https://homebrew.bintray.com/bottles/isl-0.23.catalina.bottle.tar.gz

Any idea what I should do?

**Comment by andresbrocco** [comment]
You should install essentia via homebrew: check out https://github.com/MTG/homebrew-essentia/issues/32.

Then, you should point your pythonpath to the installation folder, (in my case opt/homebrew/lib/python3.9/site-packages/essentia). Follow [this tutorial](https://k0nze.dev/posts/python-relative-imports-vscode/), which advises you to create the .vscode/settings.json and launch.json files.
