### ISSUE TITLE
essentia build fail 

### ISSUE THREAD

**Issue by turobiter** [MTG/essentia#1276]
Following along the Essentia documentation to install essentia on my macOS Big Sur. Compiling configurations and run into this:

> Build failed
 -> task in 'essentia_streaming_spectrogram' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_streaming_spectrogram' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_streaming_extractor_music' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_streaming_extractor_music' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_streaming_extractor_freesound' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_streaming_extractor_freesound' failed with exit status 1 (run with -v to display more information)

I'm not sure what to do now. I'm a beginner, so please explain as simply as you can :)

**Comment by dbogdanov** [comment]
To identify the problem, run `python3 waf -v` (or with the `-vv`` flags) for more verbose output when building Essentia.
