### ISSUE TITLE
RuntimeError: Error running the Tensorflow session. 2 root error(s) found.

### ISSUE THREAD

**Issue by GeorgeMcIntire** [MTG/essentia#1277]
I'm trying to run a VGG genre classifier in Google Colab but I keep use it because this error keeps popping up and I don't know what to do.
Thanks.

`RuntimeError: In TensorflowPredictVGGish.compute: TensorflowPredict: Error running the Tensorflow session. 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node model/1CNN/Conv2D}}]]
	 [[model/Sigmoid/_3]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node model/1CNN/Conv2D}}]]
0 successful operations.
0 derived errors ignored.`

**Comment by palonso** [comment]
Could you provide a link to the Colab and the CUDA/CuDNN versions you are using?

**Comment by GeorgeMcIntire** [comment]
[Here is the link to the colab](https://colab.research.google.com/drive/1ltZSQdb9traUvZSVMM68Xr9ZmEFcAH60?usp=sharing)

And here's the cuda version:

`Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0`

**Comment by palonso** [comment]
Essentia [was built with CUDA 11.2](https://github.com/MTG/essentia-builds/blob/2c63617dd7b04bee5b21fc7b1dab91f6e4cb1492/build_scripts/install_cuda.sh#L4) and it is incompatible with CUDA 11.1. While I couldn't find an easy way to update the CUDA version in colab, by [coping you colab](https://colab.research.google.com/drive/1xOjtnM3W5iQGzlxUNmm85uIFeE7xJr-3?usp=sharing) I was assigned a machine with CUDA 11.2 and your code ran smoothly.

Just one note: `TensorflowPredictVGGish` is reserved for VGGish based models,  the VGG ones are intended to be used with `TensorflowPredictMusiCNN`.
