### ISSUE TITLE
Streaming ReplayGain fails with a segfault. Missing python unit test.

### ISSUE THREAD

**Issue by yamKing** [MTG/essentia#129]
In [1]: from essentia.streaming import *
^[[A[ WARNING  ] ARGLLLLLL

In [2]: rp = ReplayGain(applyEqloud=False)
Segmentation fault: 11

Standard ReplayGain is fine, any Help?

**Comment by dbogdanov** [comment]
The same problem on Linux when using ReplayGain in python. However, it does work in our ```streaming_extractor_music```.

**Comment by dbogdanov** [comment]
Python test for ReplayGain streaming is missing, therefore we have not tracked this bug before.
