### ISSUE TITLE
Error while configuring StartStopCut

### ISSUE THREAD

**Issue by jmarcosfer** [MTG/essentia#1291]
Found error when instantiating StartStopCut (from its configure method):

`RuntimeError: Error while configuring StartStopCut: Parameter maximumStartTime = 10 is not within specified range: [0,inf))`

Code to reproduce:

```python
import essentia.standard as estd
startstopcut_algo = estd.StartStopCut()
```

Python version: 3.8.10
OS: Ubuntu 20.04.5

**Comment by palonso** [comment]
Nice to find this out!
I guess the problem is that the parameter's range is not valid, it should be`[0,inf)` instead of `[0,inf))`.
I can see from that code that other parameters have the same issue.

**Comment by jmarcosfer** [comment]
thanks for such quick fix @dbogdanov!

I was about to open a PR, I'll close the branch I'd opened
