### ISSUE TITLE
can't install Essentia on m1

### ISSUE THREAD

**Issue by jechavv99** [MTG/essentia#1302]
I'm trying to install Essentia on MacOS m1 and I'm getting this error:

> 2023-02-02 14:26:16 +0000

/opt/homebrew/opt/python@3.9/bin/python3
waf
configure
--mode=release
--with-examples
--with-vamp
--prefix=/opt/homebrew/Cellar/essentia/HEAD-f2e2d9d

HOMEBREW_VERSION: 3.6.20
ORIGIN: https://github.com/Homebrew/brew
HEAD: 344d32bf7f40183359592ef81ca6486e0587981b
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 35f3b4e39973e351152da5d55b7d38dc92abf03e
Core tap last commit: 22 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_BOOTSNAP: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0.1-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: 14.2
Rosetta 2: false

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /opt/homebrew/opt/openssl@1.1:/opt/homebrew/opt/icu4c:/opt/homebrew/opt/ffmpeg@2.8:/opt/homebrew/opt/m4:/opt/homebrew/opt/readline:/opt/homebrew/opt/libarchive:/opt/homebrew/opt/ffmpeg@4:/opt/homebrew/opt/sqlite:/opt/homebrew/opt/openblas:/opt/homebrew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /opt/homebrew/opt/python@3.9/Frameworks
PKG_CONFIG_PATH: /opt/homebrew/opt/libyaml/lib/pkgconfig:/opt/homebrew/opt/gmp/lib/pkgconfig:/opt/homebrew/opt/isl/lib/pkgconfig:/opt/homebrew/opt/mpfr/lib/pkgconfig:/opt/homebrew/opt/lz4/lib/pkgconfig:/opt/homebrew/opt/xz/lib/pkgconfig:/opt/homebrew/opt/zstd/lib/pkgconfig:/opt/homebrew/opt/hwloc/lib/pkgconfig:/opt/homebrew/opt/openssl@1.1/lib/pkgconfig:/opt/homebrew/opt/libevent/lib/pkgconfig:/opt/homebrew/opt/open-mpi/lib/pkgconfig:/opt/homebrew/opt/fftw/lib/pkgconfig:/opt/homebrew/opt/libpng/lib/pkgconfig:/opt/homebrew/opt/freetype/lib/pkgconfig:/opt/homebrew/opt/fontconfig/lib/pkgconfig:/opt/homebrew/opt/frei0r/lib/pkgconfig:/opt/homebrew/opt/fribidi/lib/pkgconfig:/opt/homebrew/opt/pcre2/lib/pkgconfig:/opt/homebrew/opt/glib/lib/pkgconfig:/opt/homebrew/opt/libxau/lib/pkgconfig:/opt/homebrew/opt/libxdmcp/lib/pkgconfig:/opt/homebrew/opt/libxcb/lib/pkgconfig:/opt/homebrew/opt/libx11/lib/pkgconfig:/opt/homebrew/opt/libxext/lib/pkgconfig:/opt/homebrew/opt/libxrender/lib/pkgconfig:/opt/homebrew/opt/lzo/lib/pkgconfig:/opt/homebrew/opt/pixman/lib/pkgconfig:/opt/homebrew/opt/cairo/lib/pkgconfig:/opt/homebrew/opt/graphite2/lib/pkgconfig:/opt/homebrew/opt/icu4c/lib/pkgconfig:/opt/homebrew/opt/harfbuzz/lib/pkgconfig:/opt/homebrew/opt/libunibreak/lib/pkgconfig:/opt/homebrew/opt/libass/lib/pkgconfig:/opt/homebrew/opt/libvo-aacenc/lib/pkgconfig:/opt/homebrew/opt/libogg/lib/pkgconfig:/opt/homebrew/opt/libvorbis/lib/pkgconfig:/opt/homebrew/opt/libvpx/lib/pkgconfig:/opt/homebrew/opt/opencore-amr/lib/pkgconfig:/opt/homebrew/opt/opus/lib/pkgconfig:/opt/homebrew/opt/rtmpdump/lib/pkgconfig:/opt/homebrew/opt/sdl2/lib/pkgconfig:/opt/homebrew/opt/sdl12-compat/lib/pkgconfig:/opt/homebrew/opt/speex/lib/pkgconfig:/opt/homebrew/opt/theora/lib/pkgconfig:/opt/homebrew/opt/x264/lib/pkgconfig:/opt/homebrew/opt/x265/lib/pkgconfig:/opt/homebrew/opt/ffmpeg@2.8/lib/pkgconfig:/opt/homebrew/opt/libsamplerate/lib/pkgconfig:/opt/homebrew/opt/taglib/lib/pkgconfig:/opt/homebrew/opt/brotli/lib/pkgconfig:/opt/homebrew/opt/highway/lib/pkgconfig:/opt/homebrew/opt/imath/lib/pkgconfig:/opt/homebrew/opt/jpeg-turbo/lib/pkgconfig:/opt/homebrew/opt/libtiff/lib/pkgconfig:/opt/homebrew/opt/little-cms2/lib/pkgconfig:/opt/homebrew/opt/openexr/lib/pkgconfig:/opt/homebrew/opt/webp/lib/pkgconfig:/opt/homebrew/opt/jpeg-xl/lib/pkgconfig:/opt/homebrew/opt/libvmaf/lib/pkgconfig:/opt/homebrew/opt/aom/lib/pkgconfig:/opt/homebrew/opt/dav1d/lib/pkgconfig:/opt/homebrew/opt/bdw-gc/lib/pkgconfig:/opt/homebrew/opt/readline/lib/pkgconfig:/opt/homebrew/opt/guile/lib/pkgconfig:/opt/homebrew/opt/libidn2/lib/pkgconfig:/opt/homebrew/opt/libtasn1/lib/pkgconfig:/opt/homebrew/opt/nettle/lib/pkgconfig:/opt/homebrew/opt/p11-kit/lib/pkgconfig:/opt/homebrew/opt/libnghttp2/lib/pkgconfig:/opt/homebrew/opt/unbound/lib/pkgconfig:/opt/homebrew/opt/gnutls/lib/pkgconfig:/opt/homebrew/opt/libbluray/lib/pkgconfig:/opt/homebrew/opt/cjson/lib/pkgconfig:/opt/homebrew/opt/cmocka/lib/pkgconfig:/opt/homebrew/opt/librist/lib/pkgconfig:/opt/homebrew/opt/libsoxr/lib/pkgconfig:/opt/homebrew/opt/libvidstab/lib/pkgconfig:/opt/homebrew/opt/openjpeg/lib/pkgconfig:/opt/homebrew/opt/rav1e/lib/pkgconfig:/opt/homebrew/opt/flac/lib/pkgconfig:/opt/homebrew/opt/mpg123/lib/pkgconfig:/opt/homebrew/opt/libsndfile/lib/pkgconfig:/opt/homebrew/opt/rubberband/lib/pkgconfig:/opt/homebrew/opt/srt/lib/pkgconfig:/opt/homebrew/opt/leptonica/lib/pkgconfig:/opt/homebrew/opt/libb2/lib/pkgconfig:/opt/homebrew/opt/libarchive/lib/pkgconfig:/opt/homebrew/opt/pango/lib/pkgconfig:/opt/homebrew/opt/tesseract/lib/pkgconfig:/opt/homebrew/opt/libsodium/lib/pkgconfig:/opt/homebrew/opt/zeromq/lib/pkgconfig:/opt/homebrew/opt/zimg/lib/pkgconfig:/opt/homebrew/opt/ffmpeg@4/lib/pkgconfig:/opt/homebrew/opt/chromaprint/lib/pkgconfig:/opt/homebrew/opt/sqlite/lib/pkgconfig:/opt/homebrew/opt/python@3.9/lib/pkgconfig:/opt/homebrew/opt/openblas/lib/pkgconfig:/opt/homebrew/opt/eigen/share/pkgconfig:/opt/homebrew/opt/xorgproto/share/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/13
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
ACLOCAL_PATH: /opt/homebrew/share/aclocal
PATH: /opt/homebrew/Library/Homebrew/shims/mac/super:/opt/homebrew/opt/pkg-config/bin:/opt/homebrew/opt/gcc/bin:/opt/homebrew/opt/lz4/bin:/opt/homebrew/opt/xz/bin:/opt/homebrew/opt/zstd/bin:/opt/homebrew/opt/hwloc/bin:/opt/homebrew/opt/openssl@1.1/bin:/opt/homebrew/opt/libevent/bin:/opt/homebrew/opt/open-mpi/bin:/opt/homebrew/opt/fftw/bin:/opt/homebrew/opt/libpng/bin:/opt/homebrew/opt/freetype/bin:/opt/homebrew/opt/fontconfig/bin:/opt/homebrew/opt/lame/bin:/opt/homebrew/opt/fribidi/bin:/opt/homebrew/opt/pcre2/bin:/opt/homebrew/opt/gettext/bin:/opt/homebrew/opt/glib/bin:/opt/homebrew/opt/cairo/bin:/opt/homebrew/opt/graphite2/bin:/opt/homebrew/opt/icu4c/bin:/opt/homebrew/opt/harfbuzz/bin:/opt/homebrew/opt/rtmpdump/bin:/opt/homebrew/opt/sdl2/bin:/opt/homebrew/opt/sdl12-compat/bin:/opt/homebrew/opt/speex/bin:/opt/homebrew/opt/x264/bin:/opt/homebrew/opt/x265/bin:/opt/homebrew/opt/ffmpeg@2.8/bin:/opt/homebrew/opt/taglib/bin:/opt/homebrew/opt/brotli/bin:/opt/homebrew/opt/giflib/bin:/opt/homebrew/opt/jpeg-turbo/bin:/opt/homebrew/opt/libtiff/bin:/opt/homebrew/opt/little-cms2/bin:/opt/homebrew/opt/openexr/bin:/opt/homebrew/opt/webp/bin:/opt/homebrew/opt/jpeg-xl/bin:/opt/homebrew/opt/libvmaf/bin:/opt/homebrew/opt/aom/bin:/opt/homebrew/opt/dav1d/bin:/opt/homebrew/opt/m4/bin:/opt/homebrew/opt/libtool/bin:/opt/homebrew/opt/guile/bin:/opt/homebrew/opt/libidn2/bin:/opt/homebrew/opt/libtasn1/bin:/opt/homebrew/opt/nettle/bin:/opt/homebrew/opt/p11-kit/bin:/opt/homebrew/opt/gnutls/bin:/opt/homebrew/opt/libbluray/bin:/opt/homebrew/opt/mbedtls/bin:/opt/homebrew/opt/librist/bin:/opt/homebrew/opt/openjpeg/bin:/opt/homebrew/opt/rav1e/bin:/opt/homebrew/opt/flac/bin:/opt/homebrew/opt/mpg123/bin:/opt/homebrew/opt/libsndfile/bin:/opt/homebrew/opt/rubberband/bin:/opt/homebrew/opt/srt/bin:/opt/homebrew/opt/leptonica/bin:/opt/homebrew/opt/libarchive/bin:/opt/homebrew/opt/pango/bin:/opt/homebrew/opt/tesseract/bin:/opt/homebrew/opt/zeromq/bin:/opt/homebrew/opt/ffmpeg@4/bin:/opt/homebrew/opt/chromaprint/bin:/opt/homebrew/opt/gdbm/bin:/opt/homebrew/opt/sqlite/bin:/opt/homebrew/opt/python@3.9/bin:/opt/homebrew/opt/numpy/bin:/opt/homebrew/opt/python@3.9/libexec/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by dbogdanov** [comment]
I assume it is the `waf configure` step failing? Can you provide more verbose output for the error? (`brew install -v ...`)

Btw, if you are going to use Essentia in Python, we have experimental [Python wheels build](https://essentia.upf.edu/downloads/python-wheels/) (we haven't pushed them yet to PyPI).

**Comment by xfengv** [comment]
> I assume it is the `waf configure` step failing? Can you provide more verbose output for the error? (`brew install -v ...`)
> 
> Btw, if you are going to use Essentia in Python, we have experimental [Python wheels build](https://essentia.upf.edu/downloads/python-wheels/) (we haven't pushed them yet to PyPI).

nice! I installed it successfully！

**Comment by xfengv** [comment]
> I assume it is the `waf configure` step failing? Can you provide more verbose output for the error? (`brew install -v ...`)
> 
> Btw, if you are going to use Essentia in Python, we have experimental [Python wheels build](https://essentia.upf.edu/downloads/python-wheels/) (we haven't pushed them yet to PyPI).

nice! I installed it successfully！

**Comment by xfengv** [comment]
> I assume it is the `waf configure` step failing? Can you provide more verbose output for the error? (`brew install -v ...`)
> 
> Btw, if you are going to use Essentia in Python, we have experimental [Python wheels build](https://essentia.upf.edu/downloads/python-wheels/) (we haven't pushed them yet to PyPI).

nice! I installed it successfully！

**Comment by xfengv** [comment]
> I assume it is the `waf configure` step failing? Can you provide more verbose output for the error? (`brew install -v ...`)
> 
> Btw, if you are going to use Essentia in Python, we have experimental [Python wheels build](https://essentia.upf.edu/downloads/python-wheels/) (we haven't pushed them yet to PyPI).

nice! I installed it successfully！
cpu:apple m2
system_version:13.1
