### ISSUE TITLE
Is the slow speed due to my calling method?

### ISSUE THREAD

**Issue by fanjink** [MTG/essentia#1326]
Recently, I am going to extract a large amount of mel feature data. I just saw 
[https://github.com/libAudioFlux/audioFlux/tree/master/benchmark](https://github.com/libAudioFlux/audioFlux/tree/master/benchmark)

After running the test demo, I found that essentia is slower than audioflux and librosa when extracting long audio.

![mac_x86](https://user-images.githubusercontent.com/40558250/234656410-90fab756-664f-4e14-a058-ff2a48c93974.png)
Then I used the method of extracting mel in the document and found that it was still very slow. Is it because I used something wrong?

```python
import time
import numpy as np
import essentia
import essentia.standard as es
import librosa
import audioflux as af

frameSize = 2048
hopSize = 512
sample_rate = 32000
data_len = frameSize + hopSize * 999

windowing = es.Windowing(type='blackmanharris62', zeroPadding=0)
spectrum = es.Spectrum(size=frameSize)
melbands = es.MelBands(inputSize=frameSize // 2 + 1, sampleRate=sample_rate, numberBands=128, type='power',
                       lowFrequencyBound=0, highFrequencyBound=16000, warpingFormula='slaneyMel')

use_time = 0
for _ in range(10):
    audio = np.random.randn(data_len).astype(np.float32)
    pool = essentia.Pool()
    s = time.time()
    for frame in es.FrameGenerator(audio, frameSize=frameSize, hopSize=hopSize, startFromZero=True,
                                   lastFrameToEndOfFile=False):
        frame_spectrum = spectrum(windowing(frame))
        frame_mel = melbands(frame_spectrum)
        pool.add('mel128', frame_mel)
    mel128 = np.array(pool['mel128'])
    use_time += time.time() - s
    # print(mel128.shape)
print('essentia use time:', use_time)
```

essentia use time: 0.5148606300354004

**Comment by palonso** [comment]
Hi @fanjink ,
your Essentia code looks correct.

By looking at your code and the chart I wonder if `TimeStep` axis corresponds with the `data_len` variable. If so, why is essentia's use time ~50 in the chart and ~0.5 in your code?

Also, if you are analyzing a large amount of encoded data (e.g., mp3) I recommend that you also consider the audio decoding/resampling time into account, which may consume a significant fraction of the analysis time.
