### ISSUE TITLE
Essentia.js - Issues using FrequencyBands()

### ISSUE THREAD

**Issue by TakingFire** [MTG/essentia#1327]
I have been attempting to capture a binned spectrum from an external audio stream (Naudiodon), using `Spectrum` and `FrequencyBands`.
The documentation for `FrequencyBands` mentions the power spectrum, so I have opted to use that algorithm specifically.
(In practice, though, this has not made any difference.)

``` js
const vector = essentia.arrayToVector(inData);  // (Int16LE / 32768.0) @ 48000Hz
let spectrum = essentia.PowerSpectrum(vector, 16384);
let bands = essentia.FrequencyBands(spectrum.powerSpectrum); // Failure here
```

I have also tried providing additional arguments to `FrequencyBands` as well as bypassing the spectrum transform entirely, though all of these have resulted in failure with no further information.

Below is a sample of the `PowerSpectrum` output (size 8193), using the transformed data from the buffer.
I'm unsure if the issue is in the data being provided, or simply improper use of the function.

``` json
{ 9.951899528503418,  21.195903778076172, 19.127695083618164,
  31.86044692993164,  145.32106018066406,      7818.74609375,
  321.2476806640625,   96.25711822509766,  74.23585510253906,
  45.33600997924805,  108.92033386230469,  5.975621223449707 }
```

Any information would be greatly appreciated.

**Comment by dbogdanov** [comment]
Closing this issue. Please, use https://github.com/MTG/essentia.js for Essentia.js related issues. The library is currently in the refactor, @jmarcosfer may be able to provide you more details on this issue.
