### ISSUE TITLE
RDF output

### ISSUE THREAD

**Issue by echo66** [MTG/essentia#134]
It would be great if Essentia could output RDF. Even better: RDF data that follow Audio Features Ontology definitions. Nowadays, the only available (open source) solutions that do that is: Sonic Annotator/Visualizer, SAWA and VAMP Plugins.

The big issue with VAMP Plugins is that we can't define workflows that reuse results from other VAMP Plugins...

**Comment by dbogdanov** [comment]
Is this still relevant for any applications?
