### ISSUE TITLE
[Wishlist] - MonoLoader and AudioLoader accept Path as filename

### ISSUE THREAD

**Issue by xaviliz** [MTG/essentia#1356]
Usually we use `MonoLoader` or `AudioLoader` as audio reader with `pathlib`.
`audio_reader.configure(filename=str(root_folder_path / audio_fn))`

It would be nice if we can use `Path` instances as filename, without `str` conversion.
`audio_reader.configure(filename=root_folder_path / audio_fn)`
`TypeError: Cannot convert data from type UNDEFINED (<class 'pathlib.PosixPath'>) to type STRING`

Thanks in advance.

**Comment by dbogdanov** [comment]
This would be nice, however it it will make our interactive Python documentation (e.g., `es.AudioLoader?`) which is generated directly from the C++ algorithm files inconsistent. Instead, we could add a helper function for loading audio [here](https://github.com/MTG/essentia/blob/master/src/python/essentia/pytools/io.py). 

Closing this issue for now, as this feature has not been requested by more users.

**Comment by xaviliz** [comment]
Thank you :)
