### ISSUE TITLE
Compile with Eigen without using pkg-config

### ISSUE THREAD

**Issue by jamiebullock** [MTG/essentia#1359]
Eigen is a header-only library, it is therefore sufficient to simply specify the include path to the headers. It doesn't even need to be installed on the user's system. In fact it is convenient not to do so.

However, AFAICT, Essentia requires `pkg-config` to find the Eigen build flags.

Is there any way to avoid this pkg-config dependency and tell `waf` the header location?

**Comment by dbogdanov** [comment]
You can disable the pkg-config check [here](https://github.com/MTG/essentia/blob/master/src/wscript#L146) and edit `LIBPATH` and `INCLUDES` waf variables to include necessary paths somewhere [here](https://github.com/MTG/essentia/blob/master/src/wscript#L490).
