### ISSUE TITLE
Is there a model to determine the time-stamps to beat mapping?

### ISSUE THREAD

**Issue by Bug-Reaper** [MTG/essentia#1385]
Curious if there are any models that determine a time-stamp to beat mapping for a given audio file?

I'm looking for major beat events where say an audience might clap along in the audio and not just BPM. Think [this](http://www.eecs.qmul.ac.uk/~simond/pub/2001/icmc.pdf) is the closest thing I've found so far.

If any one has any insight, I'd appreciate it and happy to report back anything I find here.

---

Unrelated huge appreciation to this project and contributors. I'm in awe of what you've created 🔥

**Comment by dbogdanov** [comment]
Hi @Bug-Reaper. You can use one of our beat trackers for this purpose: 
- [BeatTrackerDegara](https://essentia.upf.edu/reference/std_BeatTrackerDegara.html)
- [BeatTrackerMultiFeature](https://essentia.upf.edu/reference/std_BeatTrackerMultiFeature.html)
- Both are also available via [RhythmExtractor2013](https://essentia.upf.edu/reference/std_RhythmExtractor2013.html)
