### ISSUE TITLE
Build failed on Ubuntu

### ISSUE THREAD

**Issue by liofeu** [MTG/essentia#139]
Hi,

I'm on Ubuntu 14.04 (through a virtualmachine hosted on a MacOSX) and I don't manage to compile Essentia.

I've followed the procedure on http://essentia.upf.edu/documentation/installing.html.

The configuration and the compilation commands give the result below. The configuration works fine except with the libswresample lib ("Checking for 'libswresample' : not found). The build should be the issue ("Build failed -> task in 'essentia' failed (exit status 1)).

lionel@Ubuntu-50Go:~/Bureau/essentia-2.0.1$ ./waf configure --mode=release
Setting top to                           : /home/lionel/Bureau/essentia-2.0.1 
Setting out to                           : /home/lionel/Bureau/essentia-2.0.1/build 
→ configuring the project in /home/lionel/Bureau/essentia-2.0.1
→ Building in release mode
Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for 'libavcodec'                : yes 
Checking for 'libavformat'               : yes 
Checking for 'libavutil'                 : yes 
Checking for 'libswresample'             : not found 
Checking for 'taglib'                    : yes 
Checking for 'yaml-0.1'                  : yes 
Checking for 'fftw3f'                    : yes 
Checking for 'samplerate'                : yes 
Checking for 'gaia2'                     : yes 

================================ CONFIGURATION SUMMARY ================================
- FFmpeg / libav detected!
  The following algorithms will be included: ['AudioLoader', 'MonoLoader', 'EqloudLoader', 'EasyLoader', 'MonoWriter', 'AudioWriter']

- FFmpeg install with swresample support seems to be missing.
  Will be using an embedded copy for doing audio conversion

- libsamplerate (SRC) detected!
  The following algorithms will be included: ['Resample']

- TagLib detected!
  The following algorithms will be included: ['MetadataReader']

- Gaia2 detected!
  The following algorithms will be included: ['GaiaTransform']

=======================================================================================
'configure' finished successfully (0.131s)
lionel@Ubuntu-50Go:~/Bureau/essentia-2.0.1$ ./waf
Waf: Entering directory `/home/lionel/Bureau/essentia-2.0.1/build'
→ building from /home/lionel/Bureau/essentia-2.0.1
→ building from /home/lionel/Bureau/essentia-2.0.1/src
Building all the algorithms
[  1/196] cxx: src/essentia/algorithm.cpp -> build/src/essentia/algorithm.cpp.1.o
[  2/196] cxx: src/essentia/configurable.cpp -> build/src/essentia/configurable.cpp.1.o
[  3/196] cxx: src/essentia/connector.cpp -> build/src/essentia/connector.cpp.1.o
[  4/196] cxx: src/essentia/debugging.cpp -> build/src/essentia/debugging.cpp.1.o
[  5/196] cxx: src/essentia/essentia.cpp -> build/src/essentia/essentia.cpp.1.o
[  6/196] cxx: src/essentia/essentiautil.cpp -> build/src/essentia/essentiautil.cpp.1.o
[  7/196] cxx: src/essentia/parameter.cpp -> build/src/essentia/parameter.cpp.1.o
[  8/196] cxx: src/essentia/pool.cpp -> build/src/essentia/pool.cpp.1.o
[  9/196] cxx: src/essentia/range.cpp -> build/src/essentia/range.cpp.1.o
[ 10/196] cxx: src/essentia/scheduler/network.cpp -> build/src/essentia/scheduler/network.cpp.1.o
[ 11/196] cxx: src/essentia/scheduler/networkparser.cpp -> build/src/essentia/scheduler/networkparser.cpp.1.o
[ 12/196] cxx: src/essentia/streaming/accumulatoralgorithm.cpp -> build/src/essentia/streaming/accumulatoralgorithm.cpp.1.o
[ 13/196] cxx: src/essentia/streaming/algorithms/devnull.cpp -> build/src/essentia/streaming/algorithms/devnull.cpp.1.o
[ 14/196] cxx: src/essentia/streaming/algorithms/poolstorage.cpp -> build/src/essentia/streaming/algorithms/poolstorage.cpp.1.o
[ 15/196] cxx: src/essentia/streaming/sinkbase.cpp -> build/src/essentia/streaming/sinkbase.cpp.1.o
[ 16/196] cxx: src/essentia/streaming/sourcebase.cpp -> build/src/essentia/streaming/sourcebase.cpp.1.o
[ 17/196] cxx: src/essentia/streaming/streamingalgorithm.cpp -> build/src/essentia/streaming/streamingalgorithm.cpp.1.o
[ 18/196] cxx: src/essentia/streaming/streamingalgorithmcomposite.cpp -> build/src/essentia/streaming/streamingalgorithmcomposite.cpp.1.o
[ 19/196] cxx: src/essentia/streaming/streamingalgorithmwrapper.cpp -> build/src/essentia/streaming/streamingalgorithmwrapper.cpp.1.o
[ 20/196] cxx: src/essentia/stringutil.cpp -> build/src/essentia/stringutil.cpp.1.o
[ 21/196] cxx: src/essentia/utils/asciidag.cpp -> build/src/essentia/utils/asciidag.cpp.1.o
[ 22/196] cxx: src/essentia/utils/asciidagparser.cpp -> build/src/essentia/utils/asciidagparser.cpp.1.o
[ 23/196] cxx: src/essentia/utils/audiocontext.cpp -> build/src/essentia/utils/audiocontext.cpp.1.o
In file included from ../src/essentia/utils/ffmpegapi.h:100:0,
                 from ../src/essentia/utils/audiocontext.h:26,
                 from ../src/essentia/utils/audiocontext.cpp:20:
/home/lionel/Bureau/essentia-2.0.1/src/3rdparty/audioconvert.h:55:6: error: use of enum ‘SampleFormat’ without previous declaration
 enum SampleFormat avcodec_get_sample_fmt(const char* name);
      ^
/home/lionel/Bureau/essentia-2.0.1/src/3rdparty/audioconvert.h:55:59: error: invalid type in declaration before ‘;’ token
 enum SampleFormat avcodec_get_sample_fmt(const char* name);
                                                           ^
/home/lionel/Bureau/essentia-2.0.1/src/3rdparty/audioconvert.h:94:45: error: use of enum ‘SampleFormat’ without previous declaration
 AVAudioConvert *av_audio_convert_alloc(enum SampleFormat out_fmt, int out_channels,
                                             ^
/home/lionel/Bureau/essentia-2.0.1/src/3rdparty/audioconvert.h:95:45: error: use of enum ‘SampleFormat’ without previous declaration
                                        enum SampleFormat in_fmt, int in_channels,
                                             ^
../src/essentia/utils/audiocontext.cpp: In member function ‘void essentia::AudioContext::encodePacket(int)’:
../src/essentia/utils/audiocontext.cpp:278:17: warning: ‘int avcodec_encode_audio(AVCodecContext*, uint8_t*, int, const short int*)’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3968) [-Wdeprecated-declarations]
   packet.size = avcodec_encode_audio(_codecCtx, _outputBuffer, frame_bytes, (short*)_inputBuffer);
                 ^
../src/essentia/utils/audiocontext.cpp:278:97: warning: ‘int avcodec_encode_audio(AVCodecContext*, uint8_t*, int, const short int*)’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3968) [-Wdeprecated-declarations]
   packet.size = avcodec_encode_audio(_codecCtx, _outputBuffer, frame_bytes, (short*)_inputBuffer);
                                                                                                 ^
../src/essentia/utils/audiocontext.cpp: In member function ‘void essentia::AudioContext::writeEOF()’:
../src/essentia/utils/audiocontext.cpp:323:14: warning: ‘int avcodec_encode_audio(AVCodecContext*, uint8_t*, int, const short int*)’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3968) [-Wdeprecated-declarations]
       size = avcodec_encode_audio(_codecCtx, _outputBuffer, frame_bytes, (short*)_inputBuffer); // outputs remaining samples
              ^
../src/essentia/utils/audiocontext.cpp:323:94: warning: ‘int avcodec_encode_audio(AVCodecContext*, uint8_t*, int, const short int*)’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3968) [-Wdeprecated-declarations]
       size = avcodec_encode_audio(_codecCtx, _outputBuffer, frame_bytes, (short*)_inputBuffer); // outputs remaining samples
                                                                                              ^
../src/essentia/utils/audiocontext.cpp:327:14: warning: ‘int avcodec_encode_audio(AVCodecContext*, uint8_t*, int, const short int*)’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3968) [-Wdeprecated-declarations]
       size = avcodec_encode_audio(_codecCtx, _outputBuffer, frame_bytes, NULL); // sets EOF
              ^
../src/essentia/utils/audiocontext.cpp:327:78: warning: ‘int avcodec_encode_audio(AVCodecContext*, uint8_t*, int, const short int*)’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3968) [-Wdeprecated-declarations]
       size = avcodec_encode_audio(_codecCtx, _outputBuffer, frame_bytes, NULL); // sets EOF
                                                                              ^
Waf: Leaving directory `/home/lionel/Bureau/essentia-2.0.1/build'
Build failed
 -> task in 'essentia' failed (exit status 1): 
	{task 139829139567568: cxx audiocontext.cpp -> audiocontext.cpp.1.o}
['/usr/bin/g++', '-pipe', '-Wall', '-O2', '-fPIC', '-I/home/lionel/Bureau/essentia-2.0.1/build/src', '-I/home/lionel/Bureau/essentia-2.0.1/src', '-I/home/lionel/Bureau/essentia-2.0.1/build/src/essentia', '-I/home/lionel/Bureau/essentia-2.0.1/src/essentia', '-I/home/lionel/Bureau/essentia-2.0.1/build/src/essentia/scheduler', '-I/home/lionel/Bureau/essentia-2.0.1/src/essentia/scheduler', '-I/home/lionel/Bureau/essentia-2.0.1/build/src/essentia/streaming', '-I/home/lionel/Bureau/essentia-2.0.1/src/essentia/streaming', '-I/home/lionel/Bureau/essentia-2.0.1/build/src/essentia/streaming/algorithms', '-I/home/lionel/Bureau/essentia-2.0.1/src/essentia/streaming/algorithms', '-I/home/lionel/Bureau/essentia-2.0.1/build/src/essentia/utils', '-I/home/lionel/Bureau/essentia-2.0.1/src/essentia/utils', '-I/home/lionel/Bureau/essentia-2.0.1/build/src/3rdparty', '-I/home/lionel/Bureau/essentia-2.0.1/src/3rdparty', '-I/usr/include/taglib', '-I/usr/local/include/gaia2', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-DHAVE_AVCODEC=1', '-DHAVE_AVFORMAT=1', '-DHAVE_AVUTIL=1', '-DHAVE_TAGLIB=1', '-D__STDC_CONSTANT_MACROS', '-DHAVE_YAML=1', '-DHAVE_FFTW=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_GAIA2=1', '../src/essentia/utils/audiocontext.cpp', '-c', '-o', 'src/essentia/utils/audiocontext.cpp.1.o']

**Comment by dbogdanov** [comment]
We have fixed that. Compiles fine for me on Ubuntu 14.04. Try the latest master or v2.1-beta2 release.

**Comment by liofeu** [comment]
Thanks, it solved this issue, but another appeared in the building (i opened a new issue https://github.com/MTG/essentia/issues/210)
