### ISSUE TITLE
cannot import name 'TensorflowPredictMusiCNN' from 'essentia.standard'

### ISSUE THREAD

**Issue by tanalpha-aditya** [MTG/essentia#1397]
I have been trying this and not even this almost all tensorflow relatd libraries are not getting imported. 

i have installed using 

`!pip install essentia-tensorflow` and even 
`pip install -f https://essentia.upf.edu/python-wheels/ essentia-tensorflow
`
but still not working

**Comment by palonso** [comment]
Can you provide us with more information about your environment? OS, architecture, python version.
Can you use essentia.standard algorithms not related to TensorFlow?

**Comment by palonso** [comment]
let's start by making sure that `essentia-tensorflow` (and not `essentia`) is the library installed in your `<your-python-interpreter>`'s path.
Assuming `<your-python-interpreter>` is `python3`, can you run:
```bash
python3 -m pip install essentia-tensorflow
```
and then execute the code above using a `python3` session?

**Comment by tanalpha-aditya** [comment]
Thanks a lot. I did followed ur advice and did tried a few things more. It worked 👍🏻
