### ISSUE TITLE
speech vs music algorithms

### ISSUE THREAD

**Issue by flckv** [MTG/essentia#1406]
Hi, could you please list which tools are designed for speech audios, please?

**Comment by dbogdanov** [comment]
Hi @flckv. Do you have specific analysis task in mind?

Algorithms such as LPC, MFCC compute features commonly used in speech analysis.  Also [pitch detection algorthims](https://essentia.upf.edu/algorithms_reference.html#pitch)  can be relevant.

**Comment by flckv** [comment]
hi @dbogdanov, thank you for followup. I am interested in detecting the speech onset automatically, specifically the beat of speech.

**Comment by dbogdanov** [comment]
For onsets detection, Essentia provides various detection methods that might be useful: 
https://essentia.upf.edu/tutorial_rhythm_onsetdetection.html
https://essentia.upf.edu/reference/std_OnsetDetection.html
https://essentia.upf.edu/reference/std_OnsetDetectionGlobal.html
https://essentia.upf.edu/reference/std_SuperFluxExtractor.html
