### ISSUE TITLE
Get rid of "MusicExtractorSVM: no classifier models were configured by default"

### ISSUE THREAD

**Issue by EvgeniyDoctor** [MTG/essentia#1418]
I use essentia for python3. Like this: `import essentia.standard as es`

When i run my script, i always see this line first:
`[   INFO   ] MusicExtractorSVM: no classifier models were configured by default`
and then my own output. And i really, really tired of this. I tried `logger` and
```
sys.stdout = open(os.devnull, 'w')
sys.stderr = open(os.devnull, 'w')
```
but still see this. How to get rid of it?

**Comment by dbogdanov** [comment]
You can hide it by 
```
import essentia
essentia.log.infoActive = False
import essentia.standard as es
```
[More info on logging](https://essentia.upf.edu/design_overview.html#logging-in-python).
