### ISSUE TITLE
pool.isSingleValue() error

### ISSUE THREAD

**Issue by neo01124** [MTG/essentia#143]
Is this function supposed to detect if the queried key has a single value (float,int,etc) or multiple values(list type) ?

If so then it has a bug:

In [43]: pol['signal.predominantPitch']
Out[43]: 
array([   0.        ,    0.        ,    0.        , ...,  193.74790955,
        194.87030029,    0.        ], dtype=float32)

In [44]: len(pol['signal.predominantPitch'])
Out[44]: 1298

In [45]: pol.isSingleValue('signal.predominantPitch')
Out[45]: True

Shouldn't the output be False in this case ?

**Comment by dbogdanov** [comment]
In this case ```signal.predominantPitch``` is single vector value. 

List values are creating using [Pool](http://essentia.upf.edu/documentation/design_overview.html)'s add() method, while single values by using set().
