### ISSUE TITLE
swr_convert fails with segfault on osx when loading some corrupt mp3s, add support for libavresample

### ISSUE THREAD

**Issue by dbogdanov** [MTG/essentia#144]
"AudioLoader: error while decoding, skipping frame: Invalid data found when processing input" warning is printed multiple times for some (potentially corrupt) mp3 files and [swr_convert](https://github.com/MTG/essentia/blob/master/src/algorithms/io/audioloader.cpp#L292) seems to fail with segfault in these cases. 

I have tried on one mp3 file on OSX, but I have not tried to reproduce this bug on Linux. 

If this is not a problem of Essentia, a  workaround would be to avoid using libswresample and go by default for libavresample. Anyways, we should add support for libavresample to get rid of depricated audioconvert.h code. Libavresample is already in wheezy-backports.

**Comment by dbogdanov** [comment]
Closing this issue because Essentia no longer uses libswresample.

**Comment by jbmaxwell** [comment]
Hmm... I know this is an old comment, but I just hit the same error.
