### ISSUE TITLE
Compilation on debian wheezy

### ISSUE THREAD

**Issue by g-roma** [MTG/essentia#150]
After the audioconvert commmit 0944a14c8e19ec2c6c38c508e7587b8e72e43d09 the master branch won't compile anymore on wheezy with the default libav*, versions:
libavcodec 53.35
libavformat 53.21

The error is:
essentia/src/3rdparty/audioconvert.h:34:38: fatal error: libavutil/channel_layout.h: No such file or directory

**Comment by dbogdanov** [comment]
Should be fixed.
