### ISSUE TITLE
Calculating Tempo with Python script - need example

### ISSUE THREAD

**Issue by jpdodel** [MTG/essentia#152]
Hi, I've been looking at the Python scripts but trying to get a simple example that just takes an mp3 and dumps out the estimated tempo of the song using the 
I looked at the example https://github.com/MTG/essentia/blob/master/src/examples/tutorial/example_beattrackermultifeature.py
but that generates a large binary output (beats data?), I'm looking for a global tempo value.

Thanks!

**Comment by alastair** [comment]
For historical information, this basic streaming example should work:
```
import essenta
import essentia.standard as es

audio = es.MonoLoader(filename=fn)
rhy = es.RhythmExtractor2013()
audio.audio >> rhy.signal
pool = essentia.Pool()

rhy.ticks >> None
rhy.confidence >> None
rhy.estimates >> None
rhy.bpmIntervals >> None

rhy.bpm >> (pool, 'bpm')
essentia.run(audio)
pool['bpm']
```

@dbogdanov is this an example which we should add? It seems like a pretty easy to understand example to include in a tutorial.

**Comment by heisler98** [comment]
Appreciate this being here. Wanted to leave a quick addendum for any fellow beginners using this issue. This example only appears to work with `Essentia.streaming`, not `Essentia.standard`, else we receive an "Algo attribute has no member 'audio'" error.

e.g.
```
import essentia
import essentia.streaming
...
```
