### ISSUE TITLE
error problem

### ISSUE THREAD

**Issue by lazumbra** [MTG/essentia#175]
terminate called after throwing an instance of 'essentia::EssentiaException'
  what():  While connecting MonoLoader::audio to Loudness::signal:
Error when checking types. Expected: Real, received: std::vector<Real>

I can't understand why Loudness expect a Real if the monoloader returns a vector<Real>. even the algorithm reference shows that the loudness Algorithm expects a vector<Real>.

How can I fix this error???

**Comment by dbogdanov** [comment]
MonoLoader outputs a stream of Real values while Loudness expects a stream of vector<Real>. Compute loudness on frames using FrameCutter instead.
