### ISSUE TITLE
OnsetDetection in StreamingMode

### ISSUE THREAD

**Issue by MR-T77** [MTG/essentia#176]
How may I use , ie the streaming counterpart of the following "standard-mode" code:
onsets = Onsets()
onsets_hfc = onsets(# this algo expects a matrix, not a vector
                    array([ pool['features.hfc'] ]), [ 1 ])

and
in streaming mode, if i just run the OnsetRates:
onsetRate = OnsetRate()
loader.audio >> onsetRate.signal
onsetRate.onsetTimes >> (pool,'onsets')

how do I change the default (I presume frame_size=1024 and hop_size=512) windowing parameters?

**Comment by dbogdanov** [comment]
There is no possibility to change frame_size / hop_size in OnsetRate currently. The algorithm was tested specifically for using current parameters. You can re-implement the  [OnsetRate](https://github.com/MTG/essentia/blob/master/src/algorithms/highlevel/onsetrate.cpp) in python though.
