### ISSUE TITLE
different results for 32 bit builds (and minor differences between runs)

### ISSUE THREAD

**Issue by JonnyJD** [MTG/essentia#179]
This is the result on a 64 bit build of v2.1_beta1-28-g21ef5f4 on Arch Linux:
https://gist.github.com/JonnyJD/fe9f07a8f48820307ee4#file-64bit_arch-json
_this is the *_base***

This is the 32 bit acousticbrainz-provied build (v2.1_beta1-28-g21ef5f4-dirty) on the same (64 bit Arch Linux) machine:
https://gist.github.com/JonnyJD/fe9f07a8f48820307ee4#file-32bit_provided-json
_this is the one *_off***
difference to _base_ (that is 64 bit vs. 32 bit):
https://gist.github.com/JonnyJD/fe9f07a8f48820307ee4#file-arch64_to_provided32-diff

This is the 64 bit acousticbrainz-provied build (v2.1_beta1-28-g21ef5f4-dirty) on the same machine:
https://gist.github.com/JonnyJD/fe9f07a8f48820307ee4#file-64bit_provided-json
difference to _base_:
https://gist.github.com/JonnyJD/fe9f07a8f48820307ee4#file-arch_to_provided-diff

The processed track is:
https://musicbrainzsoundteam.bandcamp.com/track/surprisingly-o-k-variations-on-this-shit
(free download, just set 0 $)

**Comment by dbogdanov** [comment]
No need for `--no-msse` flag for non-x86 architectures since the https://github.com/MTG/essentia/commit/8e5652c8fad054843b844e08037866ae5828a9ee commit.

**Comment by dbogdanov** [comment]
Closing this in favor of a more generic robustness evaluation (new issue).
