### ISSUE TITLE
Integrate essentia starting from the PCM buffer

### ISSUE THREAD

**Issue by q-depot** [MTG/essentia#184]
Hi,

I'm having a go with Essentia and Cinder, I managed to compile and link against the library.
Besides the two modes(standard/streaming) which still confuse me, I was wondering how I can use the Essentia features starting from a PCM buffer provided by the Cinder apis.

thanks.

**Comment by dbogdanov** [comment]
Closing this old issue. If still relevant, you can use both modes. In the streaming mode you should by able to use VectorInput algorithm to stream from a buffer. You'll have to convert  audio buffer to float vectors.
