### ISSUE TITLE
rtaudio example files are missing

### ISSUE THREAD

**Issue by y3i12** [MTG/essentia#185]
Hi, I'm pretty new to this library, but as far as I can see it is really terrific!

Well, while I was messing arround with the examples, I realized that some files are missing on the rtaudio example, the files that I can enumerate are:
audioengine.h
inputcopy.h
inputcopy.cpp

If it had a little more experience with your library, would have done as contrib, but I have no clue how to code InputCopy :p

Regards,
Yuri I.

**Comment by pstcliminal** [comment]
Please answer this topic, please.

**Comment by dbogdanov** [comment]
That code is a chunk of outdated code before essenita 2.0 public release. You can see example of running Essentia real time in [EssentiaRT~ code](https://github.com/GiantSteps/MC-Sonaar/tree/master/essentiaRT~)

**Comment by Okayuh** [comment]
Thank you!
