### ISSUE TITLE
[streaming_extractor_music] "terminate called after throwing an instance of 'std::bad_alloc'" trying to parse ~2 hour long MP3

### ISSUE THREAD

**Issue by Freso** [MTG/essentia#192]
This run was done using the MP3 downloadable at https://soundcloud.com/bag-fjendens-linjer/bag-fjendens-linjer-14-mund-de-carlo ([MusicBrainz](https://musicbrainz.org/recording/f4c9ed64-a4bb-4b8f-9eee-f5ddf0498d5c)), but all the others from https://musicbrainz.org/series/f158ad31-bc44-4b22-94a4-025a8d6375cf (except 3.5 and 5.5) break the extractor with the same error.

```
freso@kotake> time streaming_extractor_music bag-fjendens-linjer/bfl\ mund\ de\ carlo.mp3 output.json
Process step: Read metadata
Process step: Compute md5 audio hash and codec
Process step: Replay gain
Process step: Compute audio features
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
zsh: abort (core dumped)  streaming_extractor_music bag-fjendens-linjer/bfl\ mund\ de\ carlo.mp3 
streaming_extractor_music bag-fjendens-linjer/bfl\ mund\ de\ carlo.mp3   300,26s user 3,37s system 92% cpu 5:29,94 total
```

**Comment by dbogdanov** [comment]
How much memory do you have? Too long audio files may not be supported.

**Comment by Freso** [comment]
At the time I was doing it on an 8 GB RAM machine.

**Comment by dbogdanov** [comment]
Works well on my machine with 12 GB RAM.

**Comment by Freso** [comment]
If what is happening is that it's running out of memory, then the error message should say that. The current error message is bad UX.
