### ISSUE TITLE
Compilation on MacOSx 10.10.1 (yosemite) Issues with streaming python bindings..

### ISSUE THREAD

**Issue by deewuok** [MTG/essentia#193]
ran the run_python_tests.py (much of it ran except the tests at the end... which I listed above.

I believe this is a complete listing of what I ran (showing the dependencies).  I'm using python 2.7.8

brew install pkg-config gcc readline sqlite gdbm freetype libpng
brew install libyaml fftw ffmpeg libsamplerate libtag
brew doctor (looked good)
brew update
pip install sphinx pyparsing sphinxcontrib-doxylink docutils
pip install pyyaml # make sure to have libyaml installed first
git clone https://github.com/MTG/essentia.git
./waf configure --mode=release --with-python --with-cpptests --with-examples --with-vamp
./waf install
./waf run_tests
./waf run_python_tests
./waf doc

Note
  python mfcc.py from the plots-code folder in 9 (at least that ran fine it seems).

The ./waf run_python_tests
 HOWEVER< it was not passing certain tests  (and seems to do with streaming for the most part?)... see my previous posts for which ones weren't working.

i'm on 10.10.1 yosemite

i get these errors

./waf run_python_tests

produced these errors  (after some tests pass) and python quits...

....

testBitrate (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ERROR

testFlac (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ERROR

testInvalidFile (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ok

testLoadMultiple (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ERROR

testMD5 (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ERROR

testMp3 (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ERROR

testMultiChannel (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ok

testOgg (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ERROR

testPcm (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ERROR

testResetStandard (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ERROR

testEmpty (io.test_audioonsetsmarker.TestAudioOnsetsMarker) ... FAIL

testEmptyOnsets (io.test_audioonsetsmarker.TestAudioOnsetsMarker) ... 'run_python_tests' finished successfully (1m22.602s)

 Also see:
https://class.coursera.org/audio-001/forum/thread?thread_id=695

**Comment by dbogdanov** [comment]
This issue is outdated now. There were many updates in unit tests.
