### ISSUE TITLE
FrameCutter results size is 0

### ISSUE THREAD

**Issue by q-depot** [MTG/essentia#197]
Hi,

I'm having some problems with the FrameCutter, it seems to compute the pcm for the first bunch of frames, then suddenly the results vector size is 0.

Besides that everything else seems working fine, at the moment because of this issue, I'm passing the pcm directly to the windowing function.

this is how i set it up:

```
int SampleRate  = 44100;
int PcmSize     = 1024;
int FrameSize   = 1024;
int HopSize     = 512;
int FftSize     = 512;

// ...
// setup
mFactory        = &AlgorithmFactory::instance();
mWindow         = mFactory->create("Windowing", "type", "blackmanharris62");
mFrameCutter    = mFactory->create("FrameCutter", "frameSize", FrameSize, "hopSize", HopSize );

mPcmData.resize(PcmSize);

mFrameCutter->input("signal").set(mPcmData);
mFrameCutter->output("frame").set(mFrameData);
```

**Comment by dbogdanov** [comment]
FrameCutter will output the result vector of zero size in the case the whole input audio was already processed. You'll have to reset it with the ```reset()``` method in the case you want to process another input audio.

**Comment by hawl666** [comment]
@dbogdanov hello,can you tell me how to reset()?
