### ISSUE TITLE
Run C++ Extractor Client Code

### ISSUE THREAD

**Issue by loretoparisi** [MTG/essentia#20]
Looking at the examples like the rhythm extractor:

https://github.com/MTG/essentia/blob/master/src/examples/streaming_rhythmextractor_multifeature.cpp

in the essentia architecture an extractor is used in pipe with an audio input node:

Algorithm* mono  = factory.create("MonoMixer");
  Algorithm* rhythmextractor = factory.create("RhythmExtractor2013");
  rhythmextractor->configure("method", "multifeature");
  connect(audioloader->output("audio"),      mono->input("audio"));
connect(audioloader->output("numberChannels"),   mono->input("numberChannels"));
  connect(audioloader->output("sampleRate"), pool, "metadata.sampleRate");
  connect(mono->output("audio"), rhythmextractor->input("signal"));

and then connected to the ouput:

 connect(mono->output("audio"), rhythmextractor->input("signal"));

Finally the network run the nodes:

  Network network(audioloader);
  network.run();

Is it possible to run the extractor directly i.e. using the constructor class:

essentia::init();
essentia::streaming::RhythmExtractor2013 *rythmExt =
            new  essentia::streaming::RhythmExtractor2013();

/// pass the pcm input signal

rythmExt->process();

**Comment by debugworking** [comment]
@dbogdanov 
I compiled on iOS platform a static library .It can be work , but does not like the right results, I would like to use raw audio data to detect rhythm.I use the pcm data, but I feel the result is wrong, so I did a test, I used the zero pcm data, but the results still can output, to ask where I was set up wrong!
