### ISSUE TITLE
libyaml seems to be missing

### ISSUE THREAD

**Issue by slyfocks** [MTG/essentia#201]
There seems to be a problem with libyaml detection in the current master version. 

The output of  ./waf configure --mode=release --with-python --with-cpptests --with-examples --with-vamp --with-gaia

is:

- libyaml seems to be missing.
  The following algorithms will be ignored: ['YamlInput', 'YamlOutput']

**Comment by gopalkoduri** [comment]
I've had the same issue when configuring essentia on CentOS 6.5, and what @ronggong says seems to fix it.

**Comment by dbogdanov** [comment]
Fixed the typo, thanks for reporting that.
