### ISSUE TITLE
Use essentia for ios

### ISSUE THREAD

**Issue by ronggong** [MTG/essentia#206]
I want to use this library in an ios app. And due to architecture difference of ios (arm64, armv7, armv7s), it's not possible to link the compiled static .a library (which is i386 and x86_64 architectures) with ios project.

So I wander if there is a way to do this by modifier wscript?

**Comment by AnaTP** [comment]
I'm also interested in knowing how to use essentia in mobile apps for ios, android and windows phone. Is this possible?

**Comment by loretoparisi** [comment]
@AnaTP @ronggong Time ago I did a stripped down version of Essentia, removing all the dependencies that did not compile for different reasons. It basically worked until iOS 7.0. With a bit of work it should work on iOS 9 too:

https://github.com/loretoparisi/EssentiaTouch

**Comment by dbogdanov** [comment]
There is a new way to cross-compile for iOS, see the FAQ.md
