### ISSUE TITLE
error use of enum CodecID without previous declaration

### ISSUE THREAD

**Issue by sekozer** [MTG/essentia#207]
I installed ffmpeg libraries via the recommended way but still get this error while compiling on ubuntu 14.04 or 14.10

**Comment by dbogdanov** [comment]
Does it work with the latest master?

**Comment by sankalpg** [comment]
I get this issue even with the latest master. Is there any quick fix?

**Comment by sankalpg** [comment]
Seems like CodecID->AVCodecID and CODEC_ID_PCM_S* -> AV_CODEC_ID_PCM_S* does resolve this. The only issue left is that 'avcodec_encode_audio' is deprecated in this version and its advised to use avcodec_encode_audio2 instead. It has different set of input params though.

**Comment by alastair** [comment]
I just had a look with Sankalp - it looks like there's been another API change in the version of libavcodec that comes with ubuntu 14.10

**Comment by dbogdanov** [comment]
***libavresample_support***  branch contains refactored AudioLoader, AudioWriter is still not working though you can pass through compilation successfully.

**Comment by mellorf** [comment]
I have the same problem installing 2.1_beta2 on ubuntu 14.04, but I did not find the brach libavresample_support anywhere. Could you make a link available to it? Tks!

**Comment by dbogdanov** [comment]
https://github.com/MTG/essentia/tree/libavresample_support

**Comment by mellorf** [comment]
Thank you very much! It worked!

**Comment by dbogdanov** [comment]
The fixes are merged to master

**Comment by muhammadnaveedshaikh** [comment]
What should I do I recieve the following error while compiling qoe-monitor

../src/qoe-monitor/model/container.h:74:21: error: use of enum ‘CodecID’ without previous declaration
../src/qoe-monitor/model/container.h:78:26: error: use of enum ‘SampleFormat’ without previous declaration
../src/qoe-monitor/model/container.h:92:10: error: use of enum ‘CodecID’ without previous declaration
../src/qoe-monitor/model/container.h:96:10: error: use of enum ‘SampleFormat’ without previous declaration
../src/qoe-monitor/model/container.h:160:10: error: use of enum ‘CodecID’ without previous declaration
../src/qoe-monitor/model/container.h:162:10: error: use of enum ‘SampleFormat’ without previous declaration
../src/qoe-monitor/model/container.cc: In constructor ‘ns3::Container::Container(std::string, ns3::Container::Mode, AVMediaType)’:
../src/qoe-monitor/model/container.cc:41:17: error: ‘CODEC_ID_NONE’ was not declared in this scope
../src/qoe-monitor/model/container.cc:43:22: error: ‘SAMPLE_FMT_NONE’ was not declared in this scope
../src/qoe-monitor/model/container.cc: In destructor ‘virtual ns3::Container::~Container()’:
../src/qoe-monitor/model/container.cc:59:49: error: ‘av_close_input_file’ was not declared in this scope
../src/qoe-monitor/model/container.cc:64:50: error: ‘av_close_input_file’ was not declared in this scope
../src/qoe-monitor/model/container.cc: In member function ‘bool ns3::Container::InitForRead()’:
../src/qoe-monitor/model/container.cc:90:56: error: ‘av_find_stream_info’ was not declared in this scope
../src/qoe-monitor/model/container.cc:100:47: warning: ‘AVStream::codec’ is deprecated (declared at /usr/local/include/libavformat/avformat.h:893) [-Wdeprecated-declarations]
../src/qoe-monitor/model/container.cc:100:47: warning: ‘AVStream::codec’ is deprecated (declared at /usr/local/include/libavformat/avformat.h:893) [-Wdeprecated-declarations]
../src/qoe-monitor/model/container.cc:122:76: warning: ‘AVStream::codec’ is deprecated (declared at /usr/local/include/libavformat/avformat.h:893) [-Wdeprecated-declarations]
../src/qoe-monitor/model/container.cc:122:76: warning: ‘AVStream::codec’ is deprecated (declared at /usr/local/include/libavformat/avformat.h:893) [-Wdeprecated-declarations]
../src/qoe-monitor/model/container.cc: In member function ‘virtual bool ns3::Container::GetNextPacket(AVPacket*)’:
../src/qoe-monitor/model/container.cc:155:49: error: ‘av_close_input_file’ was not declared in this scope
../src/qoe-monitor/model/container.cc: At global scope:
../src/qoe-monitor/model/container.cc:194:30: error: use of enum ‘CodecID’ without previous declaration
../src/qoe-monitor/model/container.cc:206:35: error: use of enum ‘SampleFormat’ without previous declaration
../src/qoe-monitor/model/container.cc:229:8: error: use of enum ‘CodecID’ without previous declaration
../src/qoe-monitor/model/container.cc:241:8: error: use of enum ‘SampleFormat’ without previous declaration
