### ISSUE TITLE
standard.Extractor crashes after few calls from python.

### ISSUE THREAD

**Issue by seffka** [MTG/essentia#212]
I have no problems when call Extractor one time per python session, but it crashes,
if it's called several times (number of times depends on processed array size).

How to reproduce:

    import numpy as np
    import essentia.standard as ess

    x = np.arange(0, 100000, dtype=np.float32)
    extractor = ess.Extractor()
    for i in range(0,100):
        print('i =  %i'%i)
        extractor(x)

>python test.py
i =  0
i =  1
*** Error in `python': double free or corruption (out): 0x09466e30 ***
Aborted (core dumped)

**Comment by andimarafioti** [comment]
Hi, I tried to reproduce your error but it is working fine on my machine (ubuntu 14.04, ipython, 8gb RAM). Could you elaborate a little further on your settings?

**Comment by dbogdanov** [comment]
I cannot reproduce this issue as well (Debian Wheezy)

**Comment by seffka** [comment]
It was Ubuntu 14.04 LTS 32bit, Python 2.7.6. Also there were problems with command line examples (i.e.  ~/essentia/build/src/examples/streaming_extractor crashes on some mp3s with error:
*** Error in `/home/seva/essentia/build/src/examples/streaming_extractor': free(): invalid next size (normal): 0x0916d640 ***
Aborted (core dumped))

If you say it works, i'm going to try another installation.

**Comment by dbogdanov** [comment]
@seffka You can try the latest code in master branch with your installation first. You'll need to install libavcodec-dev, libavformat-dev, libavresample-dev, libavutil-dev from Ubuntu Utopic (14.10) repository.
