### ISSUE TITLE
Bug: CentralMoments function

### ISSUE THREAD

**Issue by BigCrunsh** [MTG/essentia#214]
Hey,

I compared the CentralMoments function in the essentia python library with the scipy implementation and results are significantly different: 
```python
a = essentia.array([0.0, 0.5, -0.5])
standard.CentralMoments()(a)
> array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ], dtype=float32)

[scipy.stats.mstats.moment(a, moment=i).data for i in range(0,6)]
>[array(1.0, dtype=float32),
 array(0.1666666716337204, dtype=float32),
 array(0.0, dtype=float32),
 array(0.0416666679084301, dtype=float32),
 array(0.0, dtype=float32)]
```
That seems like a bug, since the variance is apparently not zero.

**Comment by dbogdanov** [comment]
This is most probably related to issue #15

**Comment by andimarafioti** [comment]
I have the same problem.

**Comment by dbogdanov** [comment]
This is not a bug, but a feature of what the input array is considered to be. Commit cd203d1d14a46848f4419526a810fdd00cca6b08 addressed this, allowing a new mode "sample" to compute the central moments similarly to ```scipy.stats.mstats.moment``` function.
