### ISSUE TITLE
Build fails on osx yosemite, problems with taglib and libyaml

### ISSUE THREAD

**Issue by ffont** [MTG/essentia#216]
Hi,
building essentia following standard procedure on osx yosemite fails because of taglib and libyaml related problems.
Apparently, ./waf configure... generates a configuration which is not correct.
In order to fix the issue, I had to change the tagline include line (in the generated build/c4che/_cache.py file) from INCLUDES_TAGLIB = ['/usr/local/Cellar/taglib/1.9.1/include/taglib'] to INCLUDES_TAGLIB = ['/usr/local/Cellar/taglib/1.9.1/include'].
Also I had to add a line to specify libyaml include path INCLUDES_YAML = ['/usr/local/Cellar/libyaml/0.1.6_1/include']

**Comment by q-depot** [comment]
if you don't need those dependency you can build it only with fftw

`./waf configure --lightweight=fftw`

https://github.com/MTG/essentia/issues/198

**Comment by dbogdanov** [comment]
Thank you!

**Comment by alastair** [comment]
This is actually the same problem as #29 - at least for taglib
