### ISSUE TITLE
AudioLoader: loading mp3 files shifts audio down by an octave

### ISSUE THREAD

**Issue by tcwalther** [MTG/essentia#218]
**Update**: This is a problem specific to 2.1-beta2, it does not occur in 2.0.1.

Using Essentia 2.1-beta2 on my Mac, I can load mp3 files without problems. On a RHEL 6.5 machine, however, loading MP3 files shifts them down by an octave (without altering the speed). Sample rate is 44100, although I also tried resampling to different sample rates like 11025; made no difference, same bug.

This happens both in AudioLoader and MonoLoader.

I can read and write .wav files without problems.

Using ffmpeg 1.2.6 (I also tried 2.2.1, but MonoWriter doesn't work there; however a quick spectrogram shows the same octave shift):

    libavutil      52. 18.100 / 52. 18.100
    libavcodec     54. 92.100 / 54. 92.100
    libavformat    54. 63.104 / 54. 63.104
    libavdevice    54.  3.103 / 54.  3.103
    libavfilter     3. 42.103 /  3. 42.103
    libswscale      2.  2.100 /  2.  2.100
    libswresample   0. 17.102 /  0. 17.102
    libpostproc    52.  2.100 / 52.  2.100

Running an mp3->wav conversion on the terminal works fine (ffmpeg -i test.mp3 test.wav).

I can't directly upload audio files on Github; I hope these links work:

original stereo mp3: http://cl.ly/0w2M1v241v2Y
broken stereo wav (from AudioLoader + AudioWriter): http://cl.ly/3322402x071Z

**Update**: I also tried ffmpeg 1.1.9 now, same story. It may also be worth mentioning that I'm running Python 2.6.6.

**Comment by tcwalther** [comment]
I also tested it against Python 2.7.6 now; the problem is still there. Note that you can reproduce the problem via CentOS 6.5, too (the free alternative to RHEL)

**Comment by dbogdanov** [comment]
Can you test if the same happen with the latest master? I've refactored AudioLoader quite a lot.

**Comment by tcwalther** [comment]
@dbogdanov, could you tell me a commit that I should use? The current master branch doesn't compile. I also tried something older, like f1988e7 (19 days old), which also doesn't compile.

**Comment by dbogdanov** [comment]
libswresample part is not working fully yet, can you install libavresample via brew?

**Comment by tcwalther** [comment]
This is on the CentOS machine; I don't have libavresample in the RPM repo here. I have installed

```
libavcodec54.x86_64                1.2.6-61.el6                @atrpms          
libavdevice54.x86_64               1.2.6-61.el6                @atrpms          
libavfilter3.x86_64                1.2.6-61.el6                @atrpms          
libavformat54.x86_64               1.2.6-61.el6                @atrpms          
libavutil52.x86_64                 1.2.6-61.el6                @atrpms
```

as well as

```
libresample.x86_64                 0.1.3-12.el6                @epel/6.3        
libswresample0.x86_64              1.2.6-61.el6                @atrpms  
```

Do you know when libswresample will work again? What's the performance difference between libswresample and libavresample?

**Comment by dbogdanov** [comment]
I'll have a look at making sure libswresample works. I wouldn't expect much performance difference. libswresample was included in Essentia as a part of ffmpeg which is not inside debian/ubuntu repositories anymore. Therefore, we have added libavresample.

**Comment by dbogdanov** [comment]
Closing this issue because Essentia no longer uses libswresample.
