### ISSUE TITLE
Is it possible to use an IDE?

### ISSUE THREAD

**Issue by andimarafioti** [MTG/essentia#221]
I'm trying to build new c++ applications using the essentia library. I know from the documentation the easiest way would be to put them inside the examples folder and build them from the console. But I would like to use an IDE like CodeBlocks to test them. I managed to load the essentia library into the compiler/linker settings and set the project to work with them, but the CodeBlocks complained about not finding some fftwf libraries. I added those and now it is complaining about some undefined references to src_reset, src_process, etc... My question is, is there an easier way to get this done than manually searching all the requirements? Can it be done?

**Comment by gasper321** [comment]
@andimarafioti 

Hi, did you manage to solve this? I'm trying to use an IDE aswell (IntelliJ PyCharm), but even though the imports are successful (import essentia from the dist-packages), it fails to find essentia.standard.MonoLoader. Due to this error, i then cannot run a webapp with it.

Running the same code from the console works without a problem however.

Thank you.

**Comment by andimarafioti** [comment]
I know you already realized your issue is unrelated to the one I posted about. 
I do manage to get essentia working using the Python bindings and a Python IDE. The problem is related to building c++ applications. This is probably related to my lack of knowledge in this regard, but the documentation is pretty extensive and I feel like it could benefit from a tutorial to use essentia coding with c++.

**Comment by vanferry** [comment]
maybe you need to link samplerate library

**Comment by dbogdanov** [comment]
I have not tried yet but we should be able to generate projects for XCode and Eclips using [waf scripts](https://github.com/waf-project/waf/tree/17aff345eaa8d97afe2b8c530d4369072c901d1d/waflib/extras).

**Comment by dbogdanov** [comment]
Closing this as I've opened another issue related to generation of projects in waf.
