### ISSUE TITLE
Fix incorrect encoding of ogg files in AudioWrite

### ISSUE THREAD

**Issue by dbogdanov** [MTG/essentia#223]
Encoding OGG files is yet not correct (test sine wave sounds distorted), although the code seems to be appropriate. Does OGG codec has some specifics in parametrization? 

```
import essentia.standard as es
audio = es.MonoLoader(filename="sin440_0db.wav")()
es.MonoWriter(filename="test.ogg", format='ogg')(audio)
```

**Comment by tcwalther** [comment]
Using `ffmpeg 1.2.6` and Essentia 2.0.1 on a Mac, I had no trouble writing ogg files. Using `ffmpeg 2.6.3` (that's `libavcodec 56. 26.100`) on a Mac also works fine with the current master. I haven't tested a sine wave, but some regular audio files, and it works fine. I tested both MonoWriter and AudioWriter, using sample rates of 12000 and 44100.

**Comment by dbogdanov** [comment]
Still an error on Ubuntu (```LivAv 11.2```, ```libavcodec 56.1.0```)

**Comment by dbogdanov** [comment]
The same clipping can be reproduced using standalone ffmpeg conversion: 
```
ffmpeg -i sin440_0db.wav -acodec libvorbis foo.ogg
```
The sinewave is 0dBFS, so it may get clipped on encoding. The samples around the maximum amplitude of the sinewave are clipped when inspecting the resulting ogg file in Sonic Visualizer.
