### ISSUE TITLE
PitchYIN error on stationary signals 

### ISSUE THREAD

**Issue by faroit** [MTG/essentia#230]
Hello

lately we used the YIN implementation in essentia a lot. However for many applications (speech, instruments) I found an constant error compared to other pitch estimators like RAPT. 

I tried to produce some more systematic results by running a simple test script (https://gist.github.com/faroit/2ebcf956633f63d92ace) which generates a stationary sine wave of constant f0. The signal then is processed by the YIN algorithm and the mean of the estimate is compared to the (constant) ground truth. 

This is what I get:

![yin_error](https://cloud.githubusercontent.com/assets/72940/6462631/fe4f6554-c1aa-11e4-8b8b-aabbdbd35e4e.png)

Obviously the estimation error is frequency depended, which is expected. Over 1 Khz, however, the estimate looks to be unstable.

Did anyone have tested the estimate in comparison to the original C Yin implementation?

**Comment by dbogdanov** [comment]
PitchYinFFT is implemented based on the PhD thesis by Paul Brossier, in which he did provide evaluation details (see the [thesis](http://aubio.org/phd/thesis/brossier06thesis.pdf), page 91), but we did not carry out any further in-house evaluations. Looking at those graphs, we can expect YinFFT to work worse than Yin on lower notes. 

It will be so great to compare the plot you made for YinFFT to the one for the original Yin. I wonder if you are interested in running this evaluation. This will be very useful, as we are trying to understand if it's really worth implementing original Yin.

**Comment by faroit** [comment]
Sure, I can make this comparison. Might happen next week.

**Comment by oriolromani** [comment]
I made a comparison using http://aubio.org/ and a [script] (https://gist.github.com/oriolromani/ec600da55d544d3e2ef6) based on the one used by @faroit.

![pitch](https://cloud.githubusercontent.com/assets/8613135/6578897/289a9346-c747-11e4-8fbc-a24077ce3030.png)

It looks like the Yin is much better than its frequency-based version for lower frequencies, although the aubio implementation gives very bad result for the very first frames.
I think faroit is using [this implementation] (https://github.com/ashokfernandez/Yin-Pitch-Tracking). We'll see if it gives similar results

**Comment by faroit** [comment]
I compared with https://code.google.com/p/pysnail/ which is based on a modified version of fixed point implementation. It's not even worth showing the results. They are a lot more unstable than essentia and the version interfaced in aubio

**Comment by faroit** [comment]
Next up could be: [pYin](https://code.soundsoftware.ac.uk/projects/pyin) which includes a Yin implementation. I will try to interface it soon using CFFI. Other than that there is a bunch of MATLAB implementations but I'm sick of those matlabwrappers ;-)

**Comment by oriolromani** [comment]
I've tried the pYin Vamp plugin in Sonic Visualizer and it gives pretty good results for low frequencies but I still don't have comparable results.

**Comment by dbogdanov** [comment]
> It looks like the Yin is much better than its frequency-based version for lower frequencies, although the aubio implementation gives very bad result for the very first frames.

So, the implementation of Yin in aubio looks like the most promising. Are bad results in the first frames due to the specifics of how Yin algorithm works?

**Comment by dbogdanov** [comment]
The script in gist is not entirely correct, you should use FrameGenerator with startFromZero=True, othewise the first frame is centered aroudn zero-th sample

**Comment by dbogdanov** [comment]
I have added a new PitchYin algorithm (a1cd07573feba8c7cc275a7f4b82ed898688cd25). It works already although results are not that good in higher frequencies compared to the plot by @oriolromani

**Comment by faroit** [comment]
@dbogdanov thats right, thanks. (I updated the gist).
I'm still working on interfacing the pYin so we can have an ultimate yin shootout.

**Comment by faroit** [comment]
@dbogdanov thats right, thanks. (I updated the gist).
I'm still working on interfacing the pYin so we can have an ultimate yin shootout.

**Comment by dbogdanov** [comment]
Finished implementing PitchYin. Here are the evaluation results agains PitchYinFFT (using this test script: https://gist.github.com/dbogdanov/a7b78caa7c2df5cf45f3). Looks pretty good.

![pitchyin_vs_pitchyinfft](https://cloud.githubusercontent.com/assets/409668/6625151/6f023ca0-c8ee-11e4-958a-cb7c5a496be2.png)

**Comment by andimarafioti** [comment]
Hi @dbogdanov, when I try to implement PitchYin i get the following error 
``AttributeError: 'module' object has no attribute 'PitchYin' ``
I am trying to implement the Inharmonicity module and I need to detect the pitch beforehand. Do you have any idea why python can't find this module? It works fine with PitchYinFFT.

**Comment by dbogdanov** [comment]
It is in the master branch. You'll need to do ```./waf install``` in order to make this algorithm available in python.

**Comment by dbogdanov** [comment]
Unit tests for PitchYin are not finished yet, we still need to make sure it all works ok.

**Comment by dbogdanov** [comment]
Finished unit tests.
