### ISSUE TITLE
libav problem causes waf to fail

### ISSUE THREAD

**Issue by nlehrer** [MTG/essentia#232]
[UPDATE: Finally got this to work. Basically I figured out how to properly configure with fPIC:
` ` ` 
./configure cc="gcc -fPIC" [...]
` ` `
And then I had to do make clean , then make and then sudo make install. 

Let me know if you have the same problem and that's not working]

Hi, I've been having a problem installing essentia using ubuntu 14.04.2 and have tried lots of things on my own to no avail. It configures fine but then when I run ./waf at the very end [324/324] it spits out this error and fails:

/usr/bin/ld: /usr/local/lib/libavformat.a(allformats.o): relocation R_X86_64_32 against `ff_a64_muxer' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libavformat.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

I tried configuring with the option --share-pic but it didn't help, and then I tried adding --disable-static and --enable-shared to create .so files instead of .a but it basically wouldn't let me do that. I've tried various other ways to compile with -fPIC but it doesn't seem to help. It also doesn't seem to matter which version of libav or ffmpeg I install. 

Any suggestions? I wonder why nobody else seems to have had this issue with essentia, although google turns up a lot of similar results for other programs.

Note that it installs fine without libav or without installing python bindings but libav is necessary for me.

Thanks a bunch in advance!!
Nathan

**Comment by eldrin** [comment]
Hi, I have similar problem with libav. Especially in my case it crashes at compile objects refering functions like  ‘av_frame_unref’, 'av_frame_alloc', 'av_frame_free'...  After some searching on web, I found it may have something to do with the libavcodec's version. 

http://stackoverflow.com/questions/24057248/ffmpeg-undefined-references-to-av-frame-alloc

But even if I install latest ffmpeg(2.6), which has latest version of libavcodec(56.25), It doesn't works. May be I should change some configure to change the default libavcodec to new one installed with ffmpeg. I'm pretty new in Linux system :(

I tried to change some source code directly, for replacing new libavc related function names to older one, It wasn't helpful either.

Does anyone have similar problems? I'm still stuck in compilation.

Thanks!
Jaehun

**Comment by dbogdanov** [comment]
@nlehrer which version of Essentia did you use? -fPIC should be there by default when building the 2.1-beta2 or master branch.

**Comment by dbogdanov** [comment]
@eldrin which Essentia version are you using?

**Comment by nlehrer** [comment]
I'm pretty sure I just cloned the master branch. Maybe it's something weird about my linux system.

**Comment by dbogdanov** [comment]
You can double-check if you get the fPIC flag, it is added [here](https://github.com/MTG/essentia/blob/master/wscript#L78)
