### ISSUE TITLE
Missing dependency, tests still succeed

### ISSUE THREAD

**Issue by nils-werner** [MTG/essentia#233]
Even when a dependency is missing, tests still succeed:
    
    (essentia)[user@mac essentia (master)]$ ./waf run_python_tests
    invalid lock file in /Users/user/essentia/essentia
    TEST LIST []
    TEST EXCLUDE []
    Running tests normally
    ----------------------------------------------------------------------
    Running tests: ['aftermaxtobeforemaxenergyratio', 'aftermaxtobeforemaxenergyratio_streaming', 'allpass', 'attacktime', 'audioloader_streaming', 'audioonsetsmarker', 'audioonsetsmarker_streaming', 'audiowriter_streaming', 'autocorrelation', 'bandpass', 'bandreject', 'barkbands', 'beatsloudness_streaming', 'binaryoperator', 'bpf', 'bpmhistogram', 'bpmhistogramdescriptors', 'bpmrubato', 'cartesiantopolar', 'centralmoments', 'centroid', 'chordsdescriptors', 'chordsdetection_streaming', 'clipper_streaming', 'crest', 'crosscorrelation', 'cubicspline', 'danceability', 'dcremoval', 'dct', 'decrease', 'derivative_streaming', 'derivativesfx', 'derivativesfx_streaming', 'dissonance', 'distributionshape', 'duration', 'dynamiccomplexity', 'easyloader_streaming', 'effectiveduration', 'energy', 'energyband', 'energybandratio', 'envelope', 'eqloudloader_streaming', 'equalloudness', 'fadedetection', 'fft', 'flatness', 'flatnessdb', 'flatnesssfx', 'flatnesssfx_streaming', 'flux', 'framecutter', 'framecutter_streaming', 'frequencybands', 'gaiatransform', 'geometricmean', 'harmonicpeaks', 'hfc', 'highpass', 'highresolutionfeatures', 'hpcp', 'ifft', 'iir', 'inharmonicity', 'instantPower', 'intensity', 'key', 'larm', 'leq', 'leq_streaming', 'logattacktime', 'logattacktime_streaming', 'loudness', 'loudnessvickers', 'lowpass', 'lpc', 'magnitude', 'maxmagfreq', 'maxtototal', 'maxtototal_streaming', 'mean', 'median', 'melbands', 'metadatareader', 'mfcc', 'mintototal', 'mintototal_streaming', 'monoloader', 'monomixer', 'monomixer_streaming', 'monowriter', 'movingaverage', 'multiplexer', 'multiplexer_streaming', 'noiseadder', 'oddtoevenharmonicenergyratio', 'onsetdetection', 'onsetrate', 'onsetrate_streaming', 'onsets', 'panning', 'peakdetection', 'pitchsalience', 'pitchyinfft', 'polartocartesian', 'pool', 'poolaggregator', 'powermean', 'powerspectrum', 'rawmoments', 'realaccumulator_streaming', 'replaygain', 'resample_streaming', 'rhythmextractor', 'rms', 'rolloff', 'sbic', 'scale', 'silencerate', 'silencerate_streaming', 'singlebeatloudness', 'singlegaussian', 'slicer', 'slicer_streaming', 'spectralcomplexity', 'spectralcontrast', 'spectralpeaks', 'spectralwhitening', 'spectrum', 'spline', 'startstopsilence', 'startstopsilence_streaming', 'stereodemuxer', 'stereodemuxer_streaming', 'strongdecay', 'strongdecay_streaming', 'strongpeak', 'tctototal', 'tctototal_streaming', 'temposcalebands', 'tempotap', 'tempotapticks', 'trimmer_streaming', 'tristimulus', 'tuningfrequency', 'unaryoperator', 'utils', 'variance', 'vectorinput_streaming', 'warpedautocorrelation', 'windowing', 'yamlinput', 'yamloutput', 'zerocrossingrate']
    Traceback (most recent call last):
      File "test/src/unittest/all_tests.py", line 236, in <module>
        result1 = runTests(getTests(testList, exclude=testExclude))
      File "test/src/unittest/all_tests.py", line 83, in getTests
        importTest(test, strategy)
      File "test/src/unittest/all_tests.py", line 60, in importTest
        exec(cmd)
      File "<string>", line 1, in <module>
      File "/Users/user/essentia/essentia/test/src/unittest/highlevel/test_gaiatransform.py", line 24, in <module>
        import yaml
    ImportError: No module named yaml
    'run_python_tests' finished successfully (2.224s)
    (essentia)[user@mac essentia (master)]$ echo $?
    0

Expected behaviour:

Tests should fail and return an exit code != 0

**Comment by alastair** [comment]
see also https://github.com/MTG/essentia/issues/315
