### ISSUE TITLE
create brew formula for OSX installation

### ISSUE THREAD

**Issue by dbogdanov** [MTG/essentia#235]
Create brew formula to do 

```
brew install essentia
```

**Comment by faroit** [comment]
see https://github.com/audiolabs/homebrew-tap/blob/master/essentia.rb

**Comment by dbogdanov** [comment]
Excellent! I will test and adapt this for 2.1-beta2

**Comment by cyrilpoulet** [comment]
I tested https://github.com/audiolabs/homebrew-tap/blob/master/essentia.rb, and it would require uncommenting lines 83-94 in the wscript file at the base directory to work, which is not really standard brew, though a patch could be made for this  (tested by compiling essentia on the same computer, but not from brew).
Has anyone experienced this / has a patch ready ?
another solution would be to fork essentia with a version of the wscript whit these lines uncommented, and tap it from brew...

**Comment by dbogdanov** [comment]
There is a new formula here: https://github.com/MTG/homebrew-essentia

**Comment by dbogdanov** [comment]
Need to test if works OK

**Comment by dbogdanov** [comment]
Add ```--with-gaia```[option](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#specifying-other-formulae-as-dependencies) to the formula.

**Comment by dbogdanov** [comment]
Added support for Gaia in https://github.com/MTG/homebrew-essentia/commit/ff0c44d954a89f5aec53589d27ebced71a30bd67
