### ISSUE TITLE
Mac OS XCode building problems

### ISSUE THREAD

**Issue by AnaTP** [MTG/essentia#236]
Hello everyone. 

I'm having problems in using essentia in Mac OSX with XCode.
I followed jmt508 's instructions at https://github.com/MTG/essentia/issues/58, but I still could't manage to make it work. Right now I'm having problems with the linker, such as:

Undefined symbols for architecture x86_64:
  "_avresample_alloc_context", referenced from: essentia::AudioContext::create"....

I'm building for the x86_64 architecture. 

Does anyone have any idea to solve this?

**Comment by dbogdanov** [comment]
We have an example of XCode project to be  included to Essentia code after a review. For now, you can try it [here](https://www.dropbox.com/sh/sbdgktyeym6nn6z/AAD8KgsnQA8DHdLxXPcXvci2a?dl=0) (read the pdf).

**Comment by dbogdanov** [comment]
Some more info [here](https://github.com/MTG/essentia/issues/58#issuecomment-38530548) (Issue #58)

**Comment by dbogdanov** [comment]
You are building the master branch, there is a new dependency on libavresample, install it from brew.

**Comment by AnaTP** [comment]
Thank you very much @dbogdanov ! The project now builds fine, all I needed was to instal libvorbis from brew.
