### ISSUE TITLE
Times of Spectral Peaks

### ISSUE THREAD

**Issue by AnaTP** [MTG/essentia#239]
Hello everyone,

I'm new to essentia and I just made my first code with this library. I collected the frequencies and the magnitudes of the peaks (using the SpectralPeaks algorithm) and save them into a file. What I also need, is the time of those selected peaks in the input audio. Is there a way to have access to it?

I take this chance to also ask a doubt  on the PoolAggregator. When I collect the stats from the peaks, I get multiple valor for each stat (max, min, etc). Is each value relative to a frame, or to some other thing?  

Thanks in advance

**Comment by dbogdanov** [comment]
1) Just as with any other frame descriptors, you can manually compute time positions of your spectral peaks knowing the hop size used to cut frames. 

2) It depends how you store values in the pool. If you store the peaks each frame to a new pool, and run PoolAggregator on it, the statistics would be across the peaks in that frame.
