### ISSUE TITLE
I can't use the library svm.h and svm.o with essentia

### ISSUE THREAD

**Issue by lazumbra** [MTG/essentia#247]
Hey, I must to use the svm.h in my code, but I can't use it. When I try to link the svm.h and svo.o  with my code it is returned an error. The error says that svm.o and svm.cpp was fisrt difined in libgaia2.a 
I found the the svm.h and svm.o here -> /home/jefferson/gaia-master/src/3rdparty/libsvm

The big problem is because I want to use the functions of svm and I can not use it. What do I need to put in my makefile to link svm.h and svm.o with my code that uses essentia and gaia???
I REALLY need the answer.

**Comment by dbogdanov** [comment]
Closing this as svm.h is a third-party.
