### ISSUE TITLE
streaming_extractor_music_svm reads model files every time it is run

### ISSUE THREAD

**Issue by alastair** [MTG/essentia#251]
currently `streaming_extractor_music_svm` runs on a single input at a time. This means that if we run it lots of times we spend the majority of the computation time loading the models.
There are a few ways we could make this faster by processing many input files at the same time:

 * have a long-running process that reads from stdin and writes to stdout (would only work for json with no newlines)
 * have multiple input/output arguments
 * have a single argument that lists all input/output files (need to escape spaces, etc properly)

We have to decide if we should have a limit to the number of inputs you can give.

**Comment by dbogdanov** [comment]
Did you get the new version of streaming_extractor_music_svm?

**Comment by alastair** [comment]
This is done and is working (31770e1764eeb65a3c21f41c12fd3b4ec88dd3b1).
The only problem we're seeing is that if we pass 20 input files as arguments, and one input file fails, then we don't output any data after this failure. I don't know if this is the correct behaviour. I think It's ok. A calling process would have to split this into more pieces to find the bad input file (https://github.com/metabrainz/acousticbrainz-server/pull/88#issuecomment-97483661)

**Comment by dbogdanov** [comment]
I am ok with that too, but here is an alternative idea:

We could have an additional try/catch inside ```process_single_file()```  so that the function returns error code on fail. In the main code we can then through exception with a list of all failed files after the processing loop. 

This would make sense if we pass 1000 files as aguments

**Comment by alastair** [comment]
It looks like we did this last step in https://github.com/MTG/essentia/commit/8afff30593f64d76c9d1055318388726776dfd2d, we skip a single file if processing it fails.
