### ISSUE TITLE
Can't get python binding to import: ImportError: No module named essentia

### ISSUE THREAD

**Issue by greekgoddj** [MTG/essentia#252]
Hi everyone,

Been trying to install essentia and import it into Python. I have followed the instructions and no matter what, I always get "ImportError: No module named essentia" when trying to import essentia into python.. or trying to run the python tests. Initially I tried this on OS X and assumed it was not working due to a combination of Anaconda, Brew etc. 

Now however I made a brand new installation of Ubuntu 15.04, followed the installation instructions and still get the same issue. Any ideas? Below is the Python bit of the waf configuration in case its useful.

Thanks

Checking for program python              : /usr/bin/python 
Checking for python version              : (2, 7, 9, 'final', 0) 
Checking for library python2.7 in LIBDIR : yes 
Checking for program /usr/bin/python-config,python2.7-config,python-config-2.7,python2.7m-config : /usr/bin/python-config 
Checking for header Python.h                                                                     : yes

**Comment by ftzeng** [comment]
Why was this closed? Did you figure it out?
