### ISSUE TITLE
MonoWriter / AudioWriter crashes when writing mp3 files: "Error encoding last frames"

### ISSUE THREAD

**Issue by tcwalther** [MTG/essentia#255]
The following code crashes on Essentia 2.0.1 on OS X, 2.1-beta1 on a Raspberry Pi. Looking through the git commits, no code seems to have changed on AudioWriter or MonoWriter, so I assume this still occurs in the master branch:

``` python
filename = 'test.wav'
outFilename = 'test.mp3'
sampleRate = 44100

from essentia.standard import MonoLoader, MonoWriter
audio = MonoLoader(filename=filename, sampleRate=sampleRate)()
MonoWriter(filename=outFilename, sampleRate=sampleRate, format='mp3')(audio)
```

Here's the error:

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-3c0baa221f28> in <module>()
      5 from essentia.standard import MonoLoader, MonoWriter
      6 audio = MonoLoader(filename=filename, sampleRate=sampleRate)()
----> 7 MonoWriter(filename=outFilename, sampleRate=sampleRate, format='mp3')(audio)

/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/essentia/standard.pyc in __call__(self, *args)
     94 
     95         def __call__(self, *args):
---> 96             return self.compute(*args)
     97 
     98         def __str__(self):

/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/essentia/standard.pyc in compute(self, *args)
     83                 convertedArgs.append(convertedData)
     84 
---> 85             results = self.__compute__(*convertedArgs)
     86 
     87             # we have to make an exceptional case for YamlInput, because we need

RuntimeError: In MonoWriter.compute: Error encoding last frames
```

It works fine for `.wav` and `.ogg`, but not for `.mp3`.

Essentia writes an mp3 file to disk. The mp3 file contains all the audio, but when previewed in Mac OS X Finder, it has the wrong length - Finder guesses a length of 49:42:36 on one example file that is merely 9 seconds long.

**Comment by tcwalther** [comment]
Here's an update on the issue. Both test environments used libavcodec54 (on mac it was installed via ffmpeg-1.2.4, on the raspberry pi this is the newest libavcodec package available). The newest Essentia master requires libavcodec55, so on my Mac, I switched to ffmpeg 2.6.3 and recompiled it, and it works.

I get some weird warnings

    [mp3 @ 0x7f8e80ee9000] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
    [mp3 @ 0x7f8e80ee9000] Encoder did not produce proper pts, making some up.

but other than that it's fine.

**Comment by dbogdanov** [comment]
One issue you may still experience is with ogg files (#223)

**Comment by tcwalther** [comment]
Nope, I don't experience any issues with ogg files on a Mac (haven't tested on the Pi). See my comment in #223.
