### ISSUE TITLE
Open audio stream 

### ISSUE THREAD

**Issue by kangyou** [MTG/essentia#257]
Hi, I'm doing a project to detect the beats in an audio stream. The stream comes from an audio interface real-timely. I read the doc of audioLoader, all the description talks about audio files. Can anybody tell me, is it possible to read audio stream in Essentia?

**Comment by dbogdanov** [comment]
You need to use RingBufferInput as an input for you streaming network. See an example here:
https://github.com/GiantSteps/MC-Sonaar/blob/master/essentiaRT~/EssentiaOnset.cpp#L63
https://github.com/GiantSteps/MC-Sonaar/blob/master/essentiaRT~/EssentiaOnset.cpp#L112
https://github.com/GiantSteps/MC-Sonaar/blob/master/essentiaRT~/main.cpp#L74

**Comment by dbogdanov** [comment]
However our current beat detection algorithms are not suited for real-time, as they require the audio for the whole song. You can try using SuperFlux onset detection instead.
