### ISSUE TITLE
Path to AudioLoader

### ISSUE THREAD

**Issue by AnaTP** [MTG/essentia#269]
I'm sorry, this question sounds really dumb, but I tried a few things and no result.

The problem is, when I have spaces in the path for the file, AudioLoader can't load the file.

Example.
 AudioLoader: Could not open file "/Users/(...)I\ Want\ to\ Break\ Free-Queen-The\ Works-1984.wav", error = No such file or directory
(...) = middle path

I've tried with putting \ before the spaces as the terminal does (I'm in a Mac OS) or leaving it as it is. Is it possible to load an audio with spaces in the name? I can turn around this problem, although I would like to know if it possible to load a file in this conditions.

I found this in algorithm reference but still no clue. 
"This algorithm will throw an exception if it hasn't been properly configured which normally is due to not specifying a valid filename. Invalid names comprise those with extensions different than the supported formats and non existent files. Note: ogg files are decoded in reverse phase, due to be using ffmpeg library."

**Comment by dbogdanov** [comment]
No need to escape the spaces:
```
es.AudioLoader(filename='/tmp/foo test file.ogg')()
```
