### ISSUE TITLE
ERBBands and GFCC are missing unittests

### ISSUE THREAD

**Issue by dbogdanov** [MTG/essentia#270]
They should be similar to tests for MelBands and MFCC algorithms.

**Comment by dbogdanov** [comment]
The test for GFCC is done, but the test for ERBBand is still missing. 
It should be similar to the one for MelBands (```./test/src/unittest/spectral/test_melbands.py```)

**Comment by pabloEntropia** [comment]
Ok, i'm doing it! By the way, I was already assigned to it here #503

**Comment by pabloEntropia** [comment]
Doing the test I've realised that ERBBands is not checking that there is enough frequency resolution, should we implement it?

**Comment by dbogdanov** [comment]
Let's do that

**Comment by pabloEntropia** [comment]
I've gone trough the ERBBands code and I don't think the way the Gammatone filterbank is computed has the same problem with resolution lack as TriangularBands so I don't think it should be checked.

**Comment by dbogdanov** [comment]
True, as I remember now that's why the resolution check was not implemented before.
