### ISSUE TITLE
Essentia 2.1 beta2 Build Failed on osx 10.9.2 (fatal error: 'yaml.h' file not found)

### ISSUE THREAD

**Issue by yyf** [MTG/essentia#271]
I was having issue configuring Essentia 2.1 beta2, but resolved by making homebrew-installed python default. 

After 
brew install pkg-config gcc readline sqlite gdbm freetype libpng
brew install python --framework
pip install ipython numpy matplotlib pyyaml
brew install libyaml fftw ffmpeg libsamplerate libtag
./waf configure --mode=release --with-python --with-cpptests --with-examples

I did
./waf

and got Build failed at
...
[ 28/308] cxx: src/algorithms/rhythm/rhythmextractor2013.cpp -> build/src/algorithms/rhythm/rhythmextractor2013.cpp.1.o
In file included from ../src/essentia/utils/jsonconvert.cpp:20:
In file included from /.../essentia-2.1_beta2/src/essentia/utils/jsonconvert.h:25:
/.../essentia-2.1_beta2/src/essentia/utils/yamlast.h:28:10: fatal error: 'yaml.h' file not found
#include <yaml.h>
         ^
1 error generated.
In file included from ../src/essentia/utils/yamlast.cpp:20:
/.../essentia-2.1_beta2/src/essentia/utils/yamlast.h:28:10: fatal error: 'yaml.h' file not found
#include <yaml.h>
         ^
1 error generated.

Not sure if anyone has similar issue, any suggestion to fix this? Thanks.

**Comment by alastair** [comment]
Are you using the 2.1 beta2 tag from github, or the latest master? We recently made some changes to yaml detection on osx.

Can you run these commands:
`brew list libyaml`
`pkg-config --libs yaml-0.1`
`pkg-config --cflags yaml-0.1`

The last command should output nothing.

**Comment by yyf** [comment]
Thanks. The following is what I got from running those commands and the last command output nothing indeed. 

...:essentia-2.1_beta2 ...$ brew list libyaml
/usr/local/Cellar/libyaml/0.1.6_1/include/yaml.h
/usr/local/Cellar/libyaml/0.1.6_1/lib/libyaml-0.2.dylib
/usr/local/Cellar/libyaml/0.1.6_1/lib/pkgconfig/yaml-0.1.pc
/usr/local/Cellar/libyaml/0.1.6_1/lib/ (2 other files)

...:essentia-2.1_beta2 ...$ pkg-config --libs yaml-0.1
-L/usr/local/Cellar/libyaml/0.1.6_1/lib -lyaml 

...:essentia-2.1_beta2 ...$ pkg-config --cflags yaml-0.1

...:essentia-2.1_beta2 ...$

**Comment by alastair** [comment]
I had a look into this on OSX. The problem is that if you don't install the command line tools then the compiler doesn't look in `/usr/local/include` for header files (http://stackoverflow.com/a/26404710)

Run `xcode-select --install` and click OK, then try again. You might find that you have some further compilation problems. I recommend you try and install from latest master instead of beta2.

**Comment by yyf** [comment]
Thank you, the latest master works fine now.
