### ISSUE TITLE
Building C++ Example  - undefined reference error

### ISSUE THREAD

**Issue by yrr42** [MTG/essentia#272]
Hey Guys,

i have a "little" problem: 
I want to compile my own C++ Project but i always get the following error:

> /usr/bin/ld: /usr/local/lib/libessentia.a(audioloader.cpp.1.o): undefined reference to symbol 'avresample_alloc_context@@LIBAVRESAMPLE_2'
> //usr/lib/x86_64-linux-gnu/libavresample.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

I also get this error if i try to build one of the examples via
> g++ -pipe -Wall -O2  standard_mfcc.cpp -o standard_mfcc -L/usr/local/lib -lessentia -lfftw3 -lyaml -lavcodec -lavformat -lavutil -lsamplerate -ltag -lfftw3f

The building and install of Essentia showed no error.

Has anyone a solution or at least an idea for me?

Thank you!

**Comment by shernshiou** [comment]
@yrr42 I got this problem awhile ago, I solved it by adding -lavresample
