### ISSUE TITLE
FFmpeg (or LibAv on debian/ubuntu) seems to be missing

### ISSUE THREAD

**Issue by xudongli113** [MTG/essentia#273]
I am installing essentia on ubuntu 14.10, I have already install the dependency ffmpeg and all other dependencies, but when I run configure instruction:
 ./waf configure --mode=release --with-python --with-cpptests --with-examples --with-vamp --with-gaia

it gives the following result: 

pptests --with-examples --with-vamp --with-gaia
Setting top to                           : /home/ubuntu/essentia/essentia 
Setting out to                           : /home/ubuntu/essentia/essentia/build 
→ configuring the project in /home/ubuntu/essentia/essentia
→ Building in release mode
Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for 'libavcodec' >= 55.34.1     : not found 
Checking for 'libavformat'               : yes 
Checking for 'libavutil'                 : yes 
Checking for 'libavresample'             : yes 
Checking for 'libswresample'             : not found 
Checking for 'samplerate'                : yes 
Checking for 'taglib' >= 1.9             : yes 
Checking for 'yaml-0.1'                  : yes 
Checking for 'fftw3f'                    : yes 
Checking for 'gaia2'                     : yes 
Checking for program python              : /usr/bin/python 
Checking for python version              : (2, 7, 6, 'final', 0) 
Checking for library python2.7 in LIBDIR : yes 
Checking for program /usr/bin/python-config,python2.7-config,python-config-2.7,python2.7m-config : /usr/bin/python-config 
Checking for header Python.h                                                                     : yes 

================================ CONFIGURATION SUMMARY ================================
- using FFTW for FFT

 - fftw detected!
- FFmpeg (or LibAv on debian/ubuntu) seems to be missing.
  The following algorithms will be ignored: ['AudioLoader', 'MonoLoader', 'EqloudLoader', 'EasyLoader', 'MonoWriter', 'AudioWriter']

- libsamplerate (SRC) detected!
  The following algorithms will be included: ['Resample']

- TagLib detected!
  The following algorithms will be included: ['MetadataReader']

- libyaml detected!
  The following algorithms will be included: ['YamlInput', 'YamlOutput']

- Gaia2 detected!
  The following algorithms will be included: ['GaiaTransform']

but when I run ffmpeg: all of them are installed
'configure' finished successfully (0.300s)
ubuntu@ip-172-31-31-83:~/essentia/essentia$ ffmpeg
ffmpeg version 2.7.1 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libdcadec --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvo-aacenc --enable-libvidstab
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Any one knows how to solve this? it will be very helpful!

xudong

**Comment by dbogdanov** [comment]
Configure scripts looks for ```libavcodec.pc```, ```libavformat.pc```, ```libavutil.pc```  files and your ffmpeg installation was not found in a set of default installation paths.

You can use ```PKG_CONFIG_PATH``` variable to specify a correct path. 

http://askubuntu.com/questions/210210/pkg-config-path-environment-variable

**Comment by ykhorzon** [comment]
I encouter the same problem about libavcodec , but setting up  $PKG_CONFIG_PATH does not work for me.
My environment is ubuntu 14.04 LTS.

I found that ./waf find libavcodec.pc in /usr/lib/x86_64-linux-gnu/pkgconfig/
then I already had the  libavcodec.pc >= 55.34.1 in /opt/ffmpeg/lib/pkgconfig

Here is my solution:
1. backup the existed  /usr/lib/x86_64-linux-gnu/pkgconfig/libavcodec.pc 
2. copy the /opt/ffmpeg/lib/pkgconfig/libavcodec.pc  to  /usr/lib/x86_64-linux-gnu/pkgconfig/libavcodec.pc 
3. When you try to ./waf configure again, scrpit will said other library is not found
and copy all  .pc you need in /opt/ffmpeg/lib/pkgconfig/ until passing the configuration.

**Comment by prashant2018** [comment]
@ ykhorzon Hi your solution worked for me. I was having the same issue. Thankyou

**Comment by Toporot** [comment]
@ prashant2018, an easier work around is to just update your libavcodec 

http://askubuntu.com/questions/851190/how-to-update-libavcodec-on-ubuntu-14-04/851192
