### ISSUE TITLE
Essentia 2.1 beta2 Build Failed on osx 10.9.4 (fatal error: 'ext/atomicity' file not found)

### ISSUE THREAD

**Issue by FredomLuo** [MTG/essentia#274]
when build with ./waf I get the following message (only include the line occurring error):

    [ 55/315] cxx: src/algorithms/spectral/barkbands.cpp -> build/src/algorithms/spectral/barkbands.cpp.1.o
    In file included from ../src/algorithms/io/ringbufferoutput.cpp:21:
    In file included from /Users/fredomluo/Downloads/essentia-2.1_beta2/src/essentia/utils/ringbufferimpl.h:23:
    /Users/fredomluo/Downloads/essentia-2.1_beta2/src/essentia/utils/atomic.h:74:10: fatal error: 'ext/atomicity.h' file not found
    #include <ext/atomicity.h>
             ^
    1 error generated.
    Waf: Leaving directory `/Users/fredomluo/Downloads/essentia-2.1_beta2/build'
    Build failed
     -> task in 'essentia' failed (exit status 1):
	    {task 4493425296: cxx ringbufferoutput.cpp -> ringbufferoutput.cpp.1.o}
['/usr/bin/g++', '-pipe', '-Wall', '-msse', '-msse2', '-mfpmath=sse', '-O2', '-fPIC', '-    I/Users/fredomluo/Downloads/essentia-2.1_beta2/build/src', '-I/Users/fredomluo/Downloads/essentia-    2.1_beta2/src', '-I/Users/fredomluo/Downloads/essentia-2.1_beta2/build/src/essentia', '-    I/Users/fredomluo/Downloads/essentia-2.1_beta2/src/essentia', '-I/Users/fredomluo/Downloads/essentia-2.1_beta2/build/src/essentia/scheduler', '-I/Users/fredomluo/Downloads/essentia-2.1_beta2/src/essentia/scheduler', '-I/Users/fredomluo/Downloads/essentia-2.1_beta2/build/src/essentia/streaming', '-I/Users/fredomluo/Downloads/essentia-2.1_beta2/src/essentia/streaming', '-I/Users/fredomluo/Downloads/essentia-2.1_beta2/build/src/essentia/streaming/algorithms', '-I/Users/fredomluo/Downloads/essentia-2.1_beta2/src/essentia/streaming/algorithms', '-I/Users/fredomluo/Downloads/essentia-2.1_beta2/build/src/essentia/utils', '-I/Users/fredomluo/Downloads/essentia-2.1_beta2/src/essentia/utils', '-I/Users/fredomluo/Downloads/essentia-2.1_beta2/build/src/3rdparty', '-I/Users/fredomluo/Downloads/essentia-2.1_beta2/src/3rdparty', '-I/Users/fredomluo/Downloads/essentia-2.1_beta2/build/src/3rdparty/vamp-plugin-sdk-2.4', '-I/Users/fredomluo/Downloads/essentia-2.1_beta2/src/3rdparty/vamp-plugin-sdk-2.4', '-I/usr/local/Cellar/fftw/3.3.4_1/include', '-I/usr/local/Cellar/ffmpeg/2.5.4/include', '-I/usr/local/Cellar/libsamplerate/0.1.8/include', '-I/usr/local/Cellar/taglib/1.9.1/include/taglib', '-DGTEST_HAS_TR1_TUPLE=0', '-DHAVE_AVCODEC=1', '-DHAVE_AVFORMAT=1', '-DHAVE_AVUTIL=1', '-DHAVE_SWRESAMPLE=1', '-DHAVE_FFTW=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_TAGLIB=1', '-D__STDC_CONSTANT_MACROS', '-DHAVE_YAML=1', '-DPYTHONDIR="/usr/local/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/site-packages"', '-DHAVE_PYTHON_H=1', '../src/algorithms/io/ringbufferoutput.cpp', '-c', '-o', 'src/algorithms/io/ringbufferoutput.cpp.1.o']

I am intending to update the version from 2.0.1 to 2.1, is there any comment to follow?

**Comment by dbogdanov** [comment]
This was fixed sometime ago after 2.1beta2. Build from master branch.
