### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by tcwalther** [MTG/essentia#275]
Not a real bug report; I just wanted to let you know that I built a Docker image for Essentia. Makes deploying it much easier. https://registry.hub.docker.com/u/tcwalther/essentia/

I'd be more than happy to transfer ownership of that image to you if you wish. It currently runs the latest 2.0.1 branch; I will update it to 2.1 as soon as that is stable.

**Comment by badc0re** [comment]
Is it possible to publish the DockerFile?

**Comment by tcwalther** [comment]
Oh, absolutely: https://github.com/tcwalther/essentia-docker

**Comment by badc0re** [comment]
Awesome, thanks a lot!

**Comment by techscientist** [comment]
Thanks a lot, @tcwalther! You're awesome

**Comment by mrVanDalo** [comment]
This ticket can be closed right?

**Comment by tcwalther** [comment]
Sure.

**Comment by dbogdanov** [comment]
Reopening this as we'll need to build the image for 2.1beta3

**Comment by dbogdanov** [comment]
Closing this as we are working on https://github.com/MTG/essentia-docker/

https://hub.docker.com/r/mtgupf/essentia/
