### ISSUE TITLE
TestAudioLoader_Streaming

### ISSUE THREAD

**Issue by npes87184** [MTG/essentia#276]
When I try to read some mp3 file, it will Segmentation fault. 

[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 475480
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 568348
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 804920
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 593904
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 609956
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 626148
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 631812
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 625896
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 644252
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 671180
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 749424
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 737152
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 719784
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 732392
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 606896
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 570904
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 648952
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 651884
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 716540
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 724848
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 775408
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 815972
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 834240
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 840880
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 810772
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 844084
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 840504
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 838284
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 829164
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 840496
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 814816
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 874172
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 860240
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 806300
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 600328
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 519804
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 539824
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 749812
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 571820
[ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
[ WARNING  ] at sample index: 0
[ WARNING  ] decoded samples: 0
[ WARNING  ] packet size: 56624
Segmentation fault (core dumped)

And then, I try to run test python...

testBitrate (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ERROR
testFlac (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ERROR
testInvalidFile (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ok
testLoadMultiple (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ERROR
testMD5 (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ERROR
testMp3 (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ERROR
testMultiChannel (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ok
testOgg (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ERROR
testPcm (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ERROR
testResetStandard (io.test_audioloader_streaming.TestAudioLoader_Streaming) ... ERROR

My os is RHEL 7 (redhat)

**Comment by dbogdanov** [comment]
Which version of ffmpeg are you using?

**Comment by npes87184** [comment]
2.3.4-2

**Comment by dbogdanov** [comment]
Can you still reproduce this error with the latest version of Essentia (master branch)?
