### ISSUE TITLE
some problem  build essentia by MSVC

### ISSUE THREAD

**Issue by huolingfeng210** [MTG/essentia#282]
I reconstruct a VC project, but I get some trouble  when the library is called.
Details are as follows:
"standard_pitchyinfft.cpp" file is tested but  the line " Algorithm* audioload = factory.create" is crashed and my log shows that  "Identifier 'MonoLoader" not found in registry...". what is more,
I  can't  debug code  into function  "essentia::init()", which AlgorithmFactory::init() and  registerAlgorithm() are called, so I don't know how to deal with it. looking forward  to your answers.
 
In addition, my building steps are  as  follows:
Firstly, I get "version.h" and "register_algorithms.cpp" by  "algorithms_info.py".  so registerAlgorithm() function should be defined。
Then add all of files "in src" and "win32_3rdparty" directory except "examples", "3rdparty" and "python" directory. fftw and libsamplerate library are chose and Gaia, FFTA, FFTK modules are skipped.
Lastly, shared library of essentia is built  successfully.

**Comment by dbogdanov** [comment]
Libav was not detected, therefore, MonoLoader was not compiled and it is not in algorithms' registry. You can check if this is the case in the configuration log file: ```build/config.log```

Are you building the master branch?

**Comment by huolingfeng210** [comment]
@dbogdanov, thanks.
I didn't use waf file and construct a new VC project by manual without  using existing VC project in the root folder. In addition, MonoLoader file is complied because monoloader.obj file can be seen, but as you said, it is not in algorithms's registry.

**Comment by dbogdanov** [comment]
Just in case, I guess you've already checked that  "register_algorithms.cpp" contains MonoLoader
