### ISSUE TITLE
leak memory problem

### ISSUE THREAD

**Issue by lazumbra** [MTG/essentia#283]
I found a problem of memory leak when I used valgrind to test. The problem is found even when the example code(http://essentia.upf.edu/documentation/_downloads/streaming_mfcc.cpp) is used.
When I try to extract many features(more than 30 features) of many music(more then 50) in the same code(using for int = 0, i < 130; i++), the essentia stops. Sending a problem of memory leak. 
Anyone knows how can I fix this problem?

**Comment by dbogdanov** [comment]
This was fixed fixed recently (#297).
