### ISSUE TITLE
FFmpeg version

### ISSUE THREAD

**Issue by lazumbra** [MTG/essentia#285]
Which one of the FFmpeg version is suitable to install essentia master? I want to download from this website https://www.ffmpeg.org/download.html
I can't find any suitable version. I can't install essentia master here. How can I stall it?

**Comment by dbogdanov** [comment]
LibAv 10.1 or higher will work. There is no need to compile LibAv yourself - if you are installing on Ubuntu/Debian or Mac, there are apt and brew packages ready.
