### ISSUE TITLE
./waf build fail (essentia-2.1_beta2 on 10.10.4 OSX Yosemite)

### ISSUE THREAD

**Issue by yyf** [MTG/essentia#288]
I had a ./waf build fail on a new OSX machine, wondering how to resolve this? wasn't sure if this is similar to this previous issue #237 

I was able to configure (without gaia) but failed when I tried to compile essentia. Here is the log:

Waf: Leaving directory `/Users/.../.../.../essentia-2.1_beta2/build'
Build failed
 -> task in 'essentia' failed (exit status 1): 
	{task 4379792848: cxx jsonconvert.cpp -> jsonconvert.cpp.1.o}
['/usr/bin/g++', '-pipe', '-Wall', '-msse', '-msse2', '-mfpmath=sse', '-O2', '-fPIC', '-I/Users/.../.../.../essentia-2.1_beta2/build/src', '-I/Users/.../.../.../essentia-2.1_beta2/src', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia/scheduler', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia/scheduler', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia/streaming', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia/streaming', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia/streaming/algorithms', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia/streaming/algorithms', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia/utils', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia/utils', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/3rdparty', '-I/Users/.../.../.../essentia-2.1_beta2/src/3rdparty', '-I/usr/local/Cellar/fftw/3.3.4_1/include', '-I/usr/local/Cellar/ffmpeg/2.7.2_1/include', '-I/usr/local/Cellar/libsamplerate/0.1.8/include', '-I/usr/local/Cellar/taglib/1.9.1/include/taglib', '-DGTEST_HAS_TR1_TUPLE=0', '-DHAVE_AVCODEC=1', '-DHAVE_AVFORMAT=1', '-DHAVE_AVUTIL=1', '-DHAVE_SWRESAMPLE=1', '-DHAVE_FFTW=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_TAGLIB=1', '-D__STDC_CONSTANT_MACROS', '-DHAVE_YAML=1', '-DPYTHONDIR="/usr/local/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/site-packages"', '-DHAVE_PYTHON_H=1', '../src/essentia/utils/jsonconvert.cpp', '-c', '-o', 'src/essentia/utils/jsonconvert.cpp.1.o']
 -> task in 'essentia' failed (exit status 1): 
	{task 4379791504: cxx yamlast.cpp -> yamlast.cpp.1.o}
['/usr/bin/g++', '-pipe', '-Wall', '-msse', '-msse2', '-mfpmath=sse', '-O2', '-fPIC', '-I/Users/.../.../.../essentia-2.1_beta2/build/src', '-I/Users/.../.../.../essentia-2.1_beta2/src', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia/scheduler', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia/scheduler', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia/streaming', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia/streaming', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia/streaming/algorithms', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia/streaming/algorithms', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia/utils', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia/utils', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/3rdparty', '-I/Users/.../.../.../essentia-2.1_beta2/src/3rdparty', '-I/usr/local/Cellar/fftw/3.3.4_1/include', '-I/usr/local/Cellar/ffmpeg/2.7.2_1/include', '-I/usr/local/Cellar/libsamplerate/0.1.8/include', '-I/usr/local/Cellar/taglib/1.9.1/include/taglib', '-DGTEST_HAS_TR1_TUPLE=0', '-DHAVE_AVCODEC=1', '-DHAVE_AVFORMAT=1', '-DHAVE_AVUTIL=1', '-DHAVE_SWRESAMPLE=1', '-DHAVE_FFTW=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_TAGLIB=1', '-D__STDC_CONSTANT_MACROS', '-DHAVE_YAML=1', '-DPYTHONDIR="/usr/local/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/site-packages"', '-DHAVE_PYTHON_H=1', '../src/essentia/utils/yamlast.cpp', '-c', '-o', 'src/essentia/utils/yamlast.cpp.1.o']

**Comment by dbogdanov** [comment]
I can't see the error messages in this output, only that it fails in yamlast.cpp and jsonconvert.cpp. Can you provide more details? (use ```./waf -vvv```)

**Comment by dbogdanov** [comment]
Btw, now there is an easier way to install Essentia using a brew formula
https://github.com/MTG/homebrew-essentia

**Comment by yyf** [comment]
Thanks @dbogdanov Just in case, is there anything I should do/clean up before trying to compile using the brew formula? 

Here is the log after ./waf -vvv

1 error generated.
Waf: Leaving directory `/Users/.../.../.../essentia-2.1_beta2/build'
  File "./waf", line 163, in <module>
    Scripting.waf_entry_point(cwd, VERSION, wafdir)
  File "/Users/.../.../.../essentia-2.1_beta2/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 97, in waf_entry_point
    run_commands()
  File "/Users/.../.../.../essentia-2.1_beta2/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 153, in run_commands
    ctx=run_command(cmd_name)
  File "/Users/.../.../.../essentia-2.1_beta2/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 146, in run_command
    ctx.execute()
  File "/Users/.../.../.../essentia-2.1_beta2/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 351, in execute
    return execute_method(self)
  File "/Users/.../.../.../essentia-2.1_beta2/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Build.py", line 106, in execute
    self.execute_build()
  File "/Users/.../.../.../essentia-2.1_beta2/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Build.py", line 115, in execute_build
    self.compile()
  File "/Users/.../.../.../essentia-2.1_beta2/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Tools/errcheck.py", line 124, in check_compile
    ret=self.orig_compile()
  File "/Users/.../.../.../essentia-2.1_beta2/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Build.py", line 198, in compile
    raise Errors.BuildError(self.producer.error)
  File "/Users/.../.../.../essentia-2.1_beta2/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Errors.py", line 25, in __init__
    WafError.__init__(self,self.format_error())
 
Build failed
 -> task in 'essentia' failed (exit status 1): 
	{task 4522338192: cxx jsonconvert.cpp -> jsonconvert.cpp.1.o}
['/usr/bin/g++', '-pipe', '-Wall', '-msse', '-msse2', '-mfpmath=sse', '-O2', '-fPIC', '-I/Users/.../.../.../essentia-2.1_beta2/build/src', '-I/Users/.../.../.../essentia-2.1_beta2/src', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia/scheduler', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia/scheduler', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia/streaming', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia/streaming', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia/streaming/algorithms', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia/streaming/algorithms', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia/utils', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia/utils', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/3rdparty', '-I/Users/.../.../.../essentia-2.1_beta2/src/3rdparty', '-I/usr/local/Cellar/fftw/3.3.4_1/include', '-I/usr/local/Cellar/ffmpeg/2.7.2_1/include', '-I/usr/local/Cellar/libsamplerate/0.1.8/include', '-I/usr/local/Cellar/taglib/1.9.1/include/taglib', '-DGTEST_HAS_TR1_TUPLE=0', '-DHAVE_AVCODEC=1', '-DHAVE_AVFORMAT=1', '-DHAVE_AVUTIL=1', '-DHAVE_SWRESAMPLE=1', '-DHAVE_FFTW=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_TAGLIB=1', '-D__STDC_CONSTANT_MACROS', '-DHAVE_YAML=1', '-DPYTHONDIR="/usr/local/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/site-packages"', '-DHAVE_PYTHON_H=1', '../src/essentia/utils/jsonconvert.cpp', '-c', '-o', 'src/essentia/utils/jsonconvert.cpp.1.o']
 -> task in 'essentia' failed (exit status 1): 
	{task 4522339728: cxx yamlast.cpp -> yamlast.cpp.1.o}
['/usr/bin/g++', '-pipe', '-Wall', '-msse', '-msse2', '-mfpmath=sse', '-O2', '-fPIC', '-I/Users/.../.../.../essentia-2.1_beta2/build/src', '-I/Users/.../.../.../essentia-2.1_beta2/src', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia/scheduler', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia/scheduler', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia/streaming', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia/streaming', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia/streaming/algorithms', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia/streaming/algorithms', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/essentia/utils', '-I/Users/.../.../.../essentia-2.1_beta2/src/essentia/utils', '-I/Users/.../.../.../essentia-2.1_beta2/build/src/3rdparty', '-I/Users/.../.../.../essentia-2.1_beta2/src/3rdparty', '-I/usr/local/Cellar/fftw/3.3.4_1/include', '-I/usr/local/Cellar/ffmpeg/2.7.2_1/include', '-I/usr/local/Cellar/libsamplerate/0.1.8/include', '-I/usr/local/Cellar/taglib/1.9.1/include/taglib', '-DGTEST_HAS_TR1_TUPLE=0', '-DHAVE_AVCODEC=1', '-DHAVE_AVFORMAT=1', '-DHAVE_AVUTIL=1', '-DHAVE_SWRESAMPLE=1', '-DHAVE_FFTW=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_TAGLIB=1', '-D__STDC_CONSTANT_MACROS', '-DHAVE_YAML=1', '-DPYTHONDIR="/usr/local/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/site-packages"', '-DHAVE_PYTHON_H=1', '../src/essentia/utils/yamlast.cpp', '-c', '-o', 'src/essentia/utils/yamlast.cpp.1.o']
  File "./waf", line 163, in <module>
	Scripting.waf_entry_point(cwd, VERSION, wafdir)
  File "/Users/.../.../.../essentia-2.1_beta2/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 101, in waf_entry_point
	Logs.error(e.msg)

**Comment by dbogdanov** [comment]
@yyf Just follow the instructions in the link and run brew install.

**Comment by yyf** [comment]
Thank you @dbogdanov 

My steps:
(1) brew tap MTG/essentia
(2) brew install essentia --HEAD

Results: 
I was able to do ./waf run_python_tests, and here is the log:
----------------------------------------------------------------------
Ran 1014 tests in 532.615s
FAILED (failures=11, errors=25)
'run_python_tests' finished successfully (14m18.038s)

When I tried to do ./waf run_tests, it gave me this:
sh: build/basetest: No such file or directory
'run_tests' finished successfully (0.002s)

Is there a way to run the C++ base unit tests (only test basic library behavior) if one uses homebrew formula to install essentia?

**Comment by dbogdanov** [comment]
You do not need to use waf if you are using the brew install nor you probably need tests. This installation does not include test.  Probably, test [can be included](https://github.com/MTG/homebrew-essentia/blob/master/essentia.rb#L54) in the homebrew formula but it is not done for now.

If you want to run tests, you will have to build the source on your own.

**Comment by yyf** [comment]
I haven't got a chance to test ./waf run_tests, but the brew formula worked for me. 
I was able to get my old projects running on 10.10.4 now. Thanks!!!

**Comment by marwa1013** [comment]
I had a ./waf build fail on ubuntu 14.04, wondering how to resolve this?
I was able to configure (without gaia) but failed when I tried to compile essentia. Here is the log:

marwa@marwa-PC:~/Desktop/essentia-master$ ./waf
Waf: Entering directory /home/marwa/Desktop/essentia-master/build' → building from /home/marwa/Desktop/essentia-master → building from /home/marwa/Desktop/essentia-master/src Building all the algorithms Ignoring the following algorithms: GaiaTransform, MultiPitchKlapuri → building from /home/marwa/Desktop/essentia-master/src/examples → building from /home/marwa/Desktop/essentia-master/src/python [306/326] cxxshlib: build/src/examples/vampplugins.cpp.34.o build/src/examples/vamppluginsextra.cpp.34.o build/src/examples/vampwrapper.cpp.34.o build/src/3rdparty/vamp-plugin-sdk-2.4/src/vamp-sdk/FFT.cpp.34.o build/src/3rdparty/vamp-plugin-sdk-2.4/src/vamp-sdk/PluginAdapter.cpp.34.o build/src/3rdparty/vamp-plugin-sdk-2.4/src/vamp-sdk/RealTime.cpp.34.o -> build/src/examples/libvamp_essentia.so [326/326] cxxshlib: build/src/python/essentia.cpp.1.o build/src/python/parsing.cpp.1.o build/src/python/pytypes/boolean.cpp.1.o build/src/python/pytypes/integer.cpp.1.o build/src/python/pytypes/mapvectorstring.cpp.1.o build/src/python/pytypes/matrixreal.cpp.1.o build/src/python/pytypes/pypool.cpp.1.o build/src/python/pytypes/pyreal.cpp.1.o build/src/python/pytypes/pystereosample.cpp.1.o build/src/python/pytypes/string.cpp.1.o build/src/python/pytypes/vectorcomplex.cpp.1.o build/src/python/pytypes/vectorinteger.cpp.1.o build/src/python/pytypes/vectormatrixreal.cpp.1.o build/src/python/pytypes/vectorreal.cpp.1.o build/src/python/pytypes/vectorstereosample.cpp.1.o build/src/python/pytypes/vectorstring.cpp.1.o build/src/python/pytypes/vectorvectorreal.cpp.1.o build/src/python/pytypes/vectorvectorstereosample.cpp.1.o build/src/python/pytypes/vectorvectorstring.cpp.1.o -> build/src/python/_essentia.so /usr/bin/ld.bfd.real: /usr/local/lib/libavformat.a(allformats.o): relocation R_X86_64_32 againstff_a64_muxer' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libavformat.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld.bfd.real: /usr/local/lib/libavformat.a(allformats.o): relocation R_X86_64_32 against ff_a64_muxer' can not be used when making a shared object; recompile with -fPIC /usr/local/lib/libavformat.a: error adding symbols: Bad value collect2: error: ld returned 1 exit status Waf: Leaving directory/home/marwa/Desktop/essentia-master/build'
Build failed
-> task in 'vamp_essentia' failed (exit status 1): 
{task 140498184996688: cxxshlib vampplugins.cpp.34.o,vamppluginsextra.cpp.34.o,vampwrapper.cpp.34.o,FFT.cpp.34.o,PluginAdapter.cpp.34.o,RealTime.cpp.34.o -> libvamp_essentia.so}
['/usr/bin/g++', '-shared', '-pthread', '-pthread', 'src/examples/vampplugins.cpp.34.o', 'src/examples/vamppluginsextra.cpp.34.o', 'src/examples/vampwrapper.cpp.34.o', 'src/3rdparty/vamp-plugin-sdk-2.4/src/vamp-sdk/FFT.cpp.34.o', 'src/3rdparty/vamp-plugin-sdk-2.4/src/vamp-sdk/PluginAdapter.cpp.34.o', 'src/3rdparty/vamp-plugin-sdk-2.4/src/vamp-sdk/RealTime.cpp.34.o', '-o', '/home/marwa/Desktop/essentia-master/build/src/examples/libvamp_essentia.so', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-lfftw3f', '-lavformat', '-lavcodec', '-lswresample', '-lavutil', '-lm', '-lavcodec', '-lswresample', '-lavutil', '-lm', '-lavutil', '-lm', '-lavresample', '-lavutil', '-lm', '-lsamplerate', '-ltag', '-lyaml']
-> task in '_essentia' failed (exit status 1): 
{task 140498184810768: cxxshlib essentia.cpp.1.o,parsing.cpp.1.o,boolean.cpp.1.o,integer.cpp.1.o,mapvectorstring.cpp.1.o,matrixreal.cpp.1.o,pypool.cpp.1.o,pyreal.cpp.1.o,pystereosample.cpp.1.o,string.cpp.1.o,vectorcomplex.cpp.1.o,vectorinteger.cpp.1.o,vectormatrixreal.cpp.1.o,vectorreal.cpp.1.o,vectorstereosample.cpp.1.o,vectorstring.cpp.1.o,vectorvectorreal.cpp.1.o,vectorvectorstereosample.cpp.1.o,vectorvectorstring.cpp.1.o -> _essentia.so}
['/usr/bin/g++', '-shared', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-pthread', '-Wl,-O1', '-Wl,-Bsymbolic-functions', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-pthread', '-pthread', 'src/python/essentia.cpp.1.o', 'src/python/parsing.cpp.1.o', 'src/python/pytypes/boolean.cpp.1.o', 'src/python/pytypes/integer.cpp.1.o', 'src/python/pytypes/mapvectorstring.cpp.1.o', 'src/python/pytypes/matrixreal.cpp.1.o', 'src/python/pytypes/pypool.cpp.1.o', 'src/python/pytypes/pyreal.cpp.1.o', 'src/python/pytypes/pystereosample.cpp.1.o', 'src/python/pytypes/string.cpp.1.o', 'src/python/pytypes/vectorcomplex.cpp.1.o', 'src/python/pytypes/vectorinteger.cpp.1.o', 'src/python/pytypes/vectormatrixreal.cpp.1.o', 'src/python/pytypes/vectorreal.cpp.1.o', 'src/python/pytypes/vectorstereosample.cpp.1.o', 'src/python/pytypes/vectorstring.cpp.1.o', 'src/python/pytypes/vectorvectorreal.cpp.1.o', 'src/python/pytypes/vectorvectorstereosample.cpp.1.o', 'src/python/pytypes/vectorvectorstring.cpp.1.o', '-o', '/home/marwa/Desktop/essentia-master/build/src/python/_essentia.so', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L/usr/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-lpython2.7', '-lfftw3f', '-lavformat', '-lavcodec', '-lswresample', '-lavutil', '-lm', '-lavcodec', '-lswresample', '-lavutil', '-lm', '-lavutil', '-lm', '-lavresample', '-lavutil', '-lm', '-lsamplerate', '-ltag', '-lyaml']

**Comment by dbogdanov** [comment]
@marwa1013 answered in another issue
