### ISSUE TITLE
Melodia algorithm names and documentation are confusing

### ISSUE THREAD

**Issue by alastair** [MTG/essentia#291]
We have many melodia algorithms, `PredominantPitchMelodia` (the original, which used to be called  `PredominantMelody`, `PitchMelodia`, which was originally called `MelodiaMonophonic` (https://github.com/MTG/essentia/commit/34512255), and also `MultiPitchMelodia` (https://github.com/MTG/essentia/commit/3c9283f2)

The documentation for these three algorithms is very similar, and it can be difficult to work out which one to use:

> While the algorithm is originally designed to extract melody in polyphonic music, this implementation is adapted for monophonic signals.
> 
> The algorithm is specifically suited to extract melody in polyphonic music, but also works for monophonic signals.
> 
> While the algorithm is originally designed to extract melody in polyphonic music, this implementation is adapted for multiple sources.

If we are going to keep all of the algorithms their purpose needs to be made much more explicit in the documentation

**Comment by dbogdanov** [comment]
The was a specific reasoning for naming the algorithms this way:
- ```Pitch*``` algorithms estimate a single pitch in monophonic signals.
- ```MultiPitch*``` algorithms estimate multiple pitches found in polyphonic signals.
- ```PredominantPitch*``` algorithms estimate a single predominant pitch in polyphonic signals.
 
@NadineKroher should know more details. There is also a [tutorial](https://github.com/MTG/essentia/blob/master/src/examples/python/melody-workshop/melody-analysis.ipynb) that we should reuse to improve the documentation. (@jjaner current version in our master branch is not complete, it should be updated. Where is the tutorial hosted?)

**Comment by jjaner** [comment]
We are preparing tutorial examples in the essentia-musicbricks fork. It 
includes the updated file for melody analysis.
It can be found here:

https://github.com/jjaner/essentia-musicbricks/blob/master/src/examples/python/musicbricks-tutorials/melody-analysis.ipynb

Shall I do pull request of this file, or can Dmitry update it directly 
to the essentia master?

**Comment by dbogdanov** [comment]
@jjaner Pull request will be better ;)

**Comment by dbogdanov** [comment]
Updated documentation for ```Pitch*``` algorithms, still missing tutorials.

**Comment by genepoo** [comment]
I think the zip file linked to at the tutorial is missing files in its osx folder.

**Comment by dbogdanov** [comment]
The melody analysis tutorial is located at https://github.com/MTG/essentia/blob/master/src/examples/python/musicbricks-tutorials/5-melody_analysis.ipynb
