### ISSUE TITLE
confidence values for yin and yinfft

### ISSUE THREAD

**Issue by alastair** [MTG/essentia#292]
@sertansenturk believes that the confidence value of the output of the yin algorithms is `(0, 1]`, not `[0, 1]` as listed in the documentation. We need to verify that this is correct in our implementations and correct the documentation if needed.

**Comment by dbogdanov** [comment]
Confidence value can actually get the value of 0, when the pitch is not possible to detect: 
https://github.com/MTG/essentia/blob/master/src/algorithms/tonal/pitchyinfft.cpp#L202

**Comment by alastair** [comment]
OK, no problem
