### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by user424242** [MTG/essentia#294]
Hi, 
I'm trying to built essentia on Mint 17.1.  I followed the documentation as much as possible, though i had to manually install ffmpeg and gaia (they were missing after sudo apt-get install build-essential libyaml-dev libfftw3-dev libavcodec-dev libavformat-dev libavutil-dev libavresample-dev python-dev libsamplerate0-dev libtag1-dev). 

Now when i try to built with ./waf i get the following error

In file included from ../src/algorithms/essentia_algorithms_reg.cpp:116:0:
/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/src/algorithms/highlevel/gaiatransform.h:23:34: fatal error: gaia2/transformation.h: No such file or directory
 #include <gaia2/transformation.h>
                                  ^
compilation terminated.
Waf: Leaving directory `/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/build'
Build failed
 -> task in 'essentia' failed (exit status 1): 
	{task 139760767727184: cxx essentia_algorithms_reg.cpp -> essentia_algorithms_reg.cpp.1.o}
['/usr/bin/g++', '-pipe', '-Wall', '-msse', '-msse2', '-mfpmath=sse', '-O2', '-fPIC', '-pthread', '-pthread', '-I/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/build/src', '-I/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/src', '-I/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/build/src/essentia', '-I/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/src/essentia', '-I/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/build/src/essentia/scheduler', '-I/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/src/essentia/scheduler', '-I/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/build/src/essentia/streaming', '-I/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/src/essentia/streaming', '-I/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/build/src/essentia/streaming/algorithms', '-I/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/src/essentia/streaming/algorithms', '-I/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/build/src/essentia/utils', '-I/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/src/essentia/utils', '-I/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/build/src/3rdparty', '-I/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/src/3rdparty', '-I/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/build/src/3rdparty/vamp-plugin-sdk-2.4', '-I/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/src/3rdparty/vamp-plugin-sdk-2.4', '-I/opt/ffmpeg/include', '-I/usr/include/taglib', '-I/usr/local/include/gaia2', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-DHAVE_AVCODEC=1', '-DHAVE_AVFORMAT=1', '-DHAVE_AVUTIL=1', '-DHAVE_SWRESAMPLE=1', '-DHAVE_FFTW=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_TAGLIB=1', '-DHAVE_GAIA2=1', '-D__STDC_CONSTANT_MACROS', '-DHAVE_YAML=1', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYTHON_H=1', '../src/algorithms/essentia_algorithms_reg.cpp', '-c', '-o', 'src/algorithms/essentia_algorithms_reg.cpp.1.o']

Any Ideas ? Thanks :)

**Comment by dbogdanov** [comment]
You are building with gaia support, and the compilation for GaiaTransform algorithm fails because it was impossible to find the gaia library installed. How did you configure your project? Do not use the flag ```--with-gaia``` in ```./waf configure```.

**Comment by dbogdanov** [comment]
Is gaia2 library detected when doing configuration? You can check that in ```build/config.log```

**Comment by user424242** [comment]
First of thx for the answers :).
The gaia2 library is detected when doing configuration, though only if i use: 
export PKG_CONFIG_PATH=/opt/ffmpeg/lib/pkgconfig:/home/sliqz/Dokumente/Essentia/gaia2/gaia-master/build (got that from a different issue you answered ;)

When i configure it without gaia there is a different error (same when i dont take other parts always errors):

Build failed
 -> task in 'standard_pitchyinfft' failed (exit status 1): 
	{task 140076447813584: cxxprogram standard_pitchyinfft.cpp.4.o -> standard_pitchyinfft}
['/usr/bin/g++', '-pthread', '-pthread', 'src/examples/standard_pitchyinfft.cpp.4.o', '-o', '/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/build/src/examples/standard_pitchyinfft', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L/opt/ffmpeg/lib', '-L/build/ffmpeg-HDepCh/ffmpeg-2.7.2+git4~trusty/build_libs/lib', '-L/opt/ffmpeg/lib', '-L/build/ffmpeg-HDepCh/ffmpeg-2.7.2+git4~trusty/build_libs/lib', '-L/opt/ffmpeg/lib', '-L/opt/ffmpeg/lib', '-lfftw3f', '-lyaml', '-lavformat', '-lavcodec', '-lXv', '-lXext', '-lva-x11', '-lva', '-lxcb-shm', '-lxcb-xfixes', '-lxcb-render', '-lxcb-shape', '-lxcb', '-lX11', '-lasound', '-lSDL', '-lxvidcore', '-lx265', '-lx264', '-lpthread', '-lvpx', '-lvorbisenc', '-lvorbis', '-logg', '-lvo-aacenc', '-lvidstab', '-lspeex', '-lsoxr', '-lpulse', '-lopus', '-lopencore-amrwb', '-lopencore-amrnb', '-lmp3lame', '-lfreetype', '-lfdk-aac', '-ldcadec', '-lass', '-lbz2', '-lz', '-ldl', '-lswresample', '-lavutil', '-lm', '-lavcodec', '-lXv', '-lXext', '-lva-x11', '-lva', '-lxcb-shm', '-lxcb-xfixes', '-lxcb-render', '-lxcb-shape', '-lxcb', '-lX11', '-lasound', '-lSDL', '-lxvidcore', '-lx265', '-lx264', '-lpthread', '-lvpx', '-lvorbisenc', '-lvorbis', '-logg', '-lvo-aacenc', '-lvidstab', '-lspeex', '-lsoxr', '-lpulse', '-lopus', '-lopencore-amrwb', '-lopencore-amrnb', '-lmp3lame', '-lfreetype', '-lfdk-aac', '-ldcadec', '-lass', '-lbz2', '-lz', '-ldl', '-lswresample', '-lavutil', '-lm', '-lavutil', '-lm', '-lswresample', '-lavutil', '-lm', '-lsamplerate', '-ltag']
 -> task in 'standard_beatsmarker' failed (exit status 1): 
	{task 140076447812560: cxxprogram standard_beatsmarker.cpp.1.o -> standard_beatsmarker}
['/usr/bin/g++', '-pthread', '-pthread', 'src/examples/standard_beatsmarker.cpp.1.o', '-o', '/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/build/src/examples/standard_beatsmarker', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L/opt/ffmpeg/lib', '-L/build/ffmpeg-HDepCh/ffmpeg-2.7.2+git4~trusty/build_libs/lib', '-L/opt/ffmpeg/lib', '-L/build/ffmpeg-HDepCh/ffmpeg-2.7.2+git4~trusty/build_libs/lib', '-L/opt/ffmpeg/lib', '-L/opt/ffmpeg/lib', '-lfftw3f', '-lyaml', '-lavformat', '-lavcodec', '-lXv', '-lXext', '-lva-x11', '-lva', '-lxcb-shm', '-lxcb-xfixes', '-lxcb-render', '-lxcb-shape', '-lxcb', '-lX11', '-lasound', '-lSDL', '-lxvidcore', '-lx265', '-lx264', '-lpthread', '-lvpx', '-lvorbisenc', '-lvorbis', '-logg', '-lvo-aacenc', '-lvidstab', '-lspeex', '-lsoxr', '-lpulse', '-lopus', '-lopencore-amrwb', '-lopencore-amrnb', '-lmp3lame', '-lfreetype', '-lfdk-aac', '-ldcadec', '-lass', '-lbz2', '-lz', '-ldl', '-lswresample', '-lavutil', '-lm', '-lavcodec', '-lXv', '-lXext', '-lva-x11', '-lva', '-lxcb-shm', '-lxcb-xfixes', '-lxcb-render', '-lxcb-shape', '-lxcb', '-lX11', '-lasound', '-lSDL', '-lxvidcore', '-lx265', '-lx264', '-lpthread', '-lvpx', '-lvorbisenc', '-lvorbis', '-logg', '-lvo-aacenc', '-lvidstab', '-lspeex', '-lsoxr', '-lpulse', '-lopus', '-lopencore-amrwb', '-lopencore-amrnb', '-lmp3lame', '-lfreetype', '-lfdk-aac', '-ldcadec', '-lass', '-lbz2', '-lz', '-ldl', '-lswresample', '-lavutil', '-lm', '-lavutil', '-lm', '-lswresample', '-lavutil', '-lm', '-lsamplerate', '-ltag']
 -> task in 'standard_onsetrate' failed (exit status 1): 
	{task 140076447813264: cxxprogram standard_onsetrate.cpp.3.o -> standard_onsetrate}
['/usr/bin/g++', '-pthread', '-pthread', 'src/examples/standard_onsetrate.cpp.3.o', '-o', '/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/build/src/examples/standard_onsetrate', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L/opt/ffmpeg/lib', '-L/build/ffmpeg-HDepCh/ffmpeg-2.7.2+git4~trusty/build_libs/lib', '-L/opt/ffmpeg/lib', '-L/build/ffmpeg-HDepCh/ffmpeg-2.7.2+git4~trusty/build_libs/lib', '-L/opt/ffmpeg/lib', '-L/opt/ffmpeg/lib', '-lfftw3f', '-lyaml', '-lavformat', '-lavcodec', '-lXv', '-lXext', '-lva-x11', '-lva', '-lxcb-shm', '-lxcb-xfixes', '-lxcb-render', '-lxcb-shape', '-lxcb', '-lX11', '-lasound', '-lSDL', '-lxvidcore', '-lx265', '-lx264', '-lpthread', '-lvpx', '-lvorbisenc', '-lvorbis', '-logg', '-lvo-aacenc', '-lvidstab', '-lspeex', '-lsoxr', '-lpulse', '-lopus', '-lopencore-amrwb', '-lopencore-amrnb', '-lmp3lame', '-lfreetype', '-lfdk-aac', '-ldcadec', '-lass', '-lbz2', '-lz', '-ldl', '-lswresample', '-lavutil', '-lm', '-lavcodec', '-lXv', '-lXext', '-lva-x11', '-lva', '-lxcb-shm', '-lxcb-xfixes', '-lxcb-render', '-lxcb-shape', '-lxcb', '-lX11', '-lasound', '-lSDL', '-lxvidcore', '-lx265', '-lx264', '-lpthread', '-lvpx', '-lvorbisenc', '-lvorbis', '-logg', '-lvo-aacenc', '-lvidstab', '-lspeex', '-lsoxr', '-lpulse', '-lopus', '-lopencore-amrwb', '-lopencore-amrnb', '-lmp3lame', '-lfreetype', '-lfdk-aac', '-ldcadec', '-lass', '-lbz2', '-lz', '-ldl', '-lswresample', '-lavutil', '-lm', '-lavutil', '-lm', '-lswresample', '-lavutil', '-lm', '-lsamplerate', '-ltag']
 -> task in 'standard_mfcc' failed (exit status 1): 
	{task 140076447813008: cxxprogram standard_mfcc.cpp.2.o -> standard_mfcc}
['/usr/bin/g++', '-pthread', '-pthread', 'src/examples/standard_mfcc.cpp.2.o', '-o', '/home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/build/src/examples/standard_mfcc', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L/opt/ffmpeg/lib', '-L/build/ffmpeg-HDepCh/ffmpeg-2.7.2+git4~trusty/build_libs/lib', '-L/opt/ffmpeg/lib', '-L/build/ffmpeg-HDepCh/ffmpeg-2.7.2+git4~trusty/build_libs/lib', '-L/opt/ffmpeg/lib', '-L/opt/ffmpeg/lib', '-lfftw3f', '-lyaml', '-lavformat', '-lavcodec', '-lXv', '-lXext', '-lva-x11', '-lva', '-lxcb-shm', '-lxcb-xfixes', '-lxcb-render', '-lxcb-shape', '-lxcb', '-lX11', '-lasound', '-lSDL', '-lxvidcore', '-lx265', '-lx264', '-lpthread', '-lvpx', '-lvorbisenc', '-lvorbis', '-logg', '-lvo-aacenc', '-lvidstab', '-lspeex', '-lsoxr', '-lpulse', '-lopus', '-lopencore-amrwb', '-lopencore-amrnb', '-lmp3lame', '-lfreetype', '-lfdk-aac', '-ldcadec', '-lass', '-lbz2', '-lz', '-ldl', '-lswresample', '-lavutil', '-lm', '-lavcodec', '-lXv', '-lXext', '-lva-x11', '-lva', '-lxcb-shm', '-lxcb-xfixes', '-lxcb-render', '-lxcb-shape', '-lxcb', '-lX11', '-lasound', '-lSDL', '-lxvidcore', '-lx265', '-lx264', '-lpthread', '-lvpx', '-lvorbisenc', '-lvorbis', '-logg', '-lvo-aacenc', '-lvidstab', '-lspeex', '-lsoxr', '-lpulse', '-lopus', '-lopencore-amrwb', '-lopencore-amrnb', '-lmp3lame', '-lfreetype', '-lfdk-aac', '-ldcadec', '-lass', '-lbz2', '-lz', '-ldl', '-lswresample', '-lavutil', '-lm', '-lavutil', '-lm', '-lswresample', '-lavutil', '-lm', '-lsamplerate', '-ltag']

**Comment by dbogdanov** [comment]
I can't see what is the error from this output. If you run the command 
```
/usr/bin/g++ -pthread -pthread src/examples/standard_pitchyinfft.cpp.4.o -o /home/sliqz/Dokumente/Essentia/essentia-2.1_beta2/build/src/examples/standard_pitchyinfft -Wl,-Bstatic -Lsrc -lessentia -Wl,-Bdynamic -L/opt/ffmpeg/lib -L/build/ffmpeg-HDepCh/ffmpeg-2.7.2+git4~trusty/build_libs/lib -L/opt/ffmpeg/lib -L/build/ffmpeg-HDepCh/ffmpeg-2.7.2+git4~trusty/build_libs/lib -L/opt/ffmpeg/lib -L/opt/ffmpeg/lib -lfftw3f -lyaml -lavformat -lavcodec -lXv -lXext -lva-x11 -lva -lxcb-shm -lxcb-xfixes -lxcb-render -lxcb-shape -lxcb -lX11 -lasound -lSDL -lxvidcore -lx265 -lx264 -lpthread -lvpx -lvorbisenc -lvorbis -logg -lvo-aacenc -lvidstab -lspeex -lsoxr -lpulse -lopus -lopencore-amrwb -lopencore-amrnb -lmp3lame -lfreetype -lfdk-aac -ldcadec -lass -lbz2 -lz -ldl -lswresample -lavutil -lm -lavcodec -lXv -lXext -lva-x11 -lva -lxcb-shm -lxcb-xfixes -lxcb-render -lxcb-shape -lxcb -lX11 -lasound -lSDL -lxvidcore -lx265 -lx264 -lpthread -lvpx -lvorbisenc -lvorbis -logg -lvo-aacenc -lvidstab -lspeex -lsoxr -lpulse -lopus -lopencore-amrwb -lopencore-amrnb -lmp3lame -lfreetype -lfdk-aac -ldcadec -lass -lbz2 -lz -ldl -lswresample -lavutil -lm -lavutil -lm -lswresample -lavutil -lm -lsamplerate -ltag
```
from the build folder, you will have more details.

**Comment by user424242** [comment]
Ok the result:

/usr/bin/ld: cannot find -lXv
/usr/bin/ld: cannot find -lXext
/usr/bin/ld: cannot find -lva-x11
/usr/bin/ld: cannot find -lva
/usr/bin/ld: cannot find -lxcb-shm
/usr/bin/ld: cannot find -lxcb-xfixes
/usr/bin/ld: cannot find -lxcb-render
/usr/bin/ld: cannot find -lxcb-shape
/usr/bin/ld: cannot find -lxcb
/usr/bin/ld: cannot find -lX11
/usr/bin/ld: cannot find -lasound
/usr/bin/ld: cannot find -lSDL
/usr/bin/ld: cannot find -lxvidcore
/usr/bin/ld: cannot find -lx265
/usr/bin/ld: cannot find -lx264
collect2: error: ld returned 1 exit status

**Comment by dbogdanov** [comment]
It looks like you installation of ffmpeg requires all that libraries, and they are missing. Why not installing libav* packages from the repository? Although, you told it was not possible for you to install them, it seems [they are available for Mint](http://community.linuxmint.com/software/view/libavcodec-dev) (the version for Quiana should work)

**Comment by user424242** [comment]
I installed ffmpeg because i didnt habe the libswresample package and it was the only place i found it. I couldn't find libswresample http://community.linuxmint.com/software/view/libavcodec-dev here.
I can indeed get alle the libav* packages, what would be the best way to get libswresample. Should i reinstall ffmpeg from a different source ? (if yes from where). THX for the answers again :)

**Comment by user424242** [comment]
I reinstalled from here https://www.ffmpeg.org/download.html and i still get the same error. I'm going to try to hunt down all the librarie that are missing.

**Comment by user424242** [comment]
Right now when running your command i am still missing:
/usr/bin/ld: cannot find -lXv
/usr/bin/ld: cannot find -lva-x11
/usr/bin/ld: cannot find -lva
/usr/bin/ld: cannot find -lSDL
/usr/bin/ld: cannot find -lx265
/usr/bin/ld: cannot find -lx264

I installed most of them but they aren't found during the build

Furthermore i noticed that when compiling without gaia the build fails after:

/usr/bin/ld: /usr/local/lib/libavformat.a(allformats.o): relocation R_X86_64_32 against `ff_a64_muxer' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libavformat.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

In a different issue (https://github.com/MTG/essentia/issues/232) someone seems to have already found a solution for that, though i don't know how to implement it.

**Comment by dbogdanov** [comment]
The libswresample library is not an obligatory dependency. It is an alternative to libavresample library. 
In the case libavresample is not found, Essentia will be built using it. You can ignore installation of this library if you have libavresample installed.

After configuring, if everything went correct you will see the message
```
'configure' finished successfully
```

Although some libraries may be missing, if you see this message, Essentia can be still compiled without errors.

**Comment by user424242** [comment]
I can actually configure it succesfully with every package. 

Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for 'libavcodec' >= 53.25.0     : yes 
Checking for 'libavformat'               : yes 
Checking for 'libavutil'                 : yes 
Checking for 'libswresample'             : yes 
Checking for 'fftw3f'                    : yes 
Checking for 'samplerate'                : yes 
Checking for 'taglib' >= 1.9             : yes 
Checking for 'yaml-0.1'                  : yes 
Checking for program python              : /usr/bin/python 
Checking for python version              : (2, 7, 6, 'final', 0) 
Checking for library python2.7 in LIBDIR : yes 
Checking for program /usr/bin/python-config,python2.7-config,python-config-2.7,python2.7m-config : /usr/bin/python-config 
Checking for header Python.h                                                                     : yes 
(some other text inbetween)
'configure' finished successfully (1.130s)

The problems appear when i try to build it. Before i installed all the packages i could find, that were missing for ffmpeg, there was the problem we talked about before.

Now however when i try to install it i get: 
usr/bin/ld: /usr/local/lib/libavformat.a(allformats.o): relocation R_X86_64_32 against `ff_a64_muxer' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libavformat.a: error adding symbols: Bad value

probably because i found most of the packages that were missing for ffmpeg. 
In a different issue (#232) someone seems to have already found a solution for that, though i don't know how to implement it. I apreciate any help :). Should i try to uninstall the libswresample library so that the still missing packages are ignored or is my new error related to the libswresample library at all.

**Comment by dbogdanov** [comment]
To avoid any mess, try removing your ffmpeg installation and install it from the repository.

**Comment by srviest** [comment]
hi @user424242 , 
The same issue happens to me when I compiled the C++ examples,
To be clear, when I ./waf , I got 
/usr/bin/ld: cannot find -lXv
/usr/bin/ld: cannot find -lva-drm
/usr/bin/ld: cannot find -lva-x11
/usr/bin/ld: cannot find -lva
/usr/bin/ld: cannot find -lxcb-shm
/usr/bin/ld: cannot find -lasound
/usr/bin/ld: cannot find -lSDL
/usr/bin/ld: cannot find -lxvidcore
/usr/bin/ld: cannot find -lx265 

how did you finally figure this out?
Thanks a lot!
