### ISSUE TITLE
Improve documentation for the Key algorithm and add more profiles

### ISSUE THREAD

**Issue by dbogdanov** [MTG/essentia#302]
Improve documentation for the Key algorithm:
- Explain for which type of music each profile is expected to be suited for (on which type of music it works good or bad)
- Provide recommended setting for HPCP calculation for different types of music using these profiles
- Add references for each profile

Add new profile suited for electronic music (@angelfaraldo).

**Comment by dbogdanov** [comment]
@angelfaraldo any updates on this?

**Comment by angelfaraldo** [comment]
Added the profiles on my fork of essentia.... Will work on the
documentation very soon! I have just received an email that our paper with
the key profiles has been accepted!

cheers!

----------------------
Tordera 36 - Ppal. 3
08012 Barcelona
+34 617456373
www.angelfaraldo.info
angelfaraldo@gmail.com
----------------------

**Comment by dbogdanov** [comment]
The documentation is added in 2.1-beta3
