### ISSUE TITLE
libavcodec version check does not handle current version 56

### ISSUE THREAD

**Issue by colbec** [MTG/essentia#304]
My current up to date libavcodec is now major version 56.
Compilation stops:
===============
Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for 'libavcodec' >= 55.34.1     : not found 
Checking for 'libavformat'               : not found 
Checking for 'libavutil'                 : not found 
Checking for 'libavresample'             : not found 
Checking for 'libswresample'             : not found 
Checking for 'samplerate'                : yes 
Checking for 'taglib' >= 1.9             : not found 
Checking for 'yaml-0.1'                  : not found 
Checking for 'fftw3f'                    : yes 
Checking for 'gaia2'                     : not found

**Comment by dbogdanov** [comment]
Check ```build/config.log``` for more details
