### ISSUE TITLE
Installation from source fails on Ubuntu

### ISSUE THREAD

**Issue by Midafi** [MTG/essentia#308]
I have not been able to compile Essentia on Ubuntu 14.04, using the current git version of Essentia.

The error, on `./waf install`, is:

    Could not find '../essentia.pc' in /home/michael/build/essentia/src

This missing file does not exist anywhere in the folder heirarchy, although I've seen it is mentioned in a couple of the waf build files.

The full output from configuring and attempted install is:

    michael@biryani:~/build/essentia$ ./waf configure --mode=release --with-python --with-cpptests --with-examples --with-vamp
    Setting top to                           : /home/michael/build/essentia 
    Setting out to                           : /home/michael/build/essentia/build 
    → configuring the project in /home/michael/build/essentia
    → Building in release mode
    Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
    Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
    Checking for program pkg-config          : /usr/bin/pkg-config 
    Checking for 'libavcodec' >= 53.25.0     : yes 
    Checking for 'libavformat'               : yes 
    Checking for 'libavutil'                 : yes 
    Checking for 'libswresample'             : yes 
    Checking for 'fftw3f'                    : yes 
    Checking for 'samplerate'                : yes 
    Checking for 'taglib' >= 1.9             : yes 
    Checking for 'yaml-0.1'                  : yes 
    Checking for program python              : /home/michael/anaconda/bin/python 
    Checking for python version              : (2, 7, 10, 'final', 0) 
    Checking for library python2.7 in LIBPATH_PYEMBED : yes 
    Checking for program /home/michael/anaconda/bin/python-config,python2.7-config,python-config-2.7,python2.7m-config : /home/michael/anaconda/bin/python-config 
    Checking for header Python.h                                                                                       : yes 

    ================================ CONFIGURATION SUMMARY ================================
    - FFmpeg / libav detected!
      The following algorithms will be included: ['AudioLoader', 'MonoLoader', 'EqloudLoader', 'EasyLoader', 'MonoWriter', 'AudioWriter']

    - libsamplerate (SRC) detected!
      The following algorithms will be included: ['Resample']

    - TagLib detected!
      The following algorithms will be included: ['MetadataReader']

    - Essentia is configured without Gaia2.
      The following algorithms will be ignored: ['GaiaTransform']
      Examples requiring Gaia2 will be ignored

    - Compiling 23 examples
      standard_beatsmarker, standard_mfcc, standard_onsetrate, standard_pitchyinfft, standard_fadedetection, standard_spectralcontrast, standard_rhythmtransform, streaming_extractor, streaming_extractor_short_sounds, streaming_extractor_music, streaming_beatsmarker, streaming_mfcc, streaming_gfcc, streaming_rhythmextractor_multifeature, streaming_beattracker_multifeature_mirex2013, streaming_onsetrate, streaming_panning, streaming_tuningfrequency, streaming_key, streaming_pitchyinfft, streaming_predominantmelody, streaming_md5, streaming_extractor_freesound
    =======================================================================================
    'configure' finished successfully (0.390s)

    michael@biryani:~/build/essentia$ ./waf install
    Waf: Entering directory `/home/michael/build/essentia/build'
    → building from /home/michael/build/essentia
    → building from /home/michael/build/essentia/src
    Building all the algorithms
    Ignoring the following algorithms: GaiaTransform
    Could not find '../essentia.pc' in /home/michael/build/essentia/src

**Comment by alastair** [comment]
After `./waf configure` you must run `./waf` before running `./waf install`
