### ISSUE TITLE
Could not find '../essentia.pc'

### ISSUE THREAD

**Issue by pawellll** [MTG/essentia#311]
In 2.01 version and current master after configuring with:

./waf configure --mode=release --with-python --with-cpptests --with-examples --with-vamp --with-gaia 

and

./waf install 

I get:
Waf: Entering directory `/home/pawel/Desktop/inz/essentia/essentia-2.1_beta2/build'
→ building from /home/pawel/Desktop/inz/essentia/essentia-2.1_beta2
→ building from /home/pawel/Desktop/inz/essentia/essentia-2.1_beta2/src
Building all the algorithms
Could not find '../essentia.pc' in /home/pawel/Desktop/inz/essentia/essentia-2.1_beta2/src

OS:
3.13.0-65-generic #106-Ubuntu 

x86_64 GNU/Linux

**Comment by dbogdanov** [comment]
Do ```./waf```before ```./waf install```
