### ISSUE TITLE
/waf build fail (essentia-master on ubuntu 14.04)

### ISSUE THREAD

**Issue by marwa1013** [MTG/essentia#312]
I had a ./waf build fail on ubuntu 14.04, wondering how to resolve this?
I was able to configure (without gaia) but failed when I tried to compile essentia. Here is the log:

marwa@marwa-PC:~/Desktop/essentia-master$ ./waf
Waf: Entering directory `/home/marwa/Desktop/essentia-master/build'
→ building from /home/marwa/Desktop/essentia-master
→ building from /home/marwa/Desktop/essentia-master/src
Building all the algorithms
Ignoring the following algorithms: GaiaTransform, MultiPitchKlapuri
→ building from /home/marwa/Desktop/essentia-master/src/examples
→ building from /home/marwa/Desktop/essentia-master/src/python
[306/326] cxxshlib: build/src/examples/vampplugins.cpp.34.o build/src/examples/vamppluginsextra.cpp.34.o build/src/examples/vampwrapper.cpp.34.o build/src/3rdparty/vamp-plugin-sdk-2.4/src/vamp-sdk/FFT.cpp.34.o build/src/3rdparty/vamp-plugin-sdk-2.4/src/vamp-sdk/PluginAdapter.cpp.34.o build/src/3rdparty/vamp-plugin-sdk-2.4/src/vamp-sdk/RealTime.cpp.34.o -> build/src/examples/libvamp_essentia.so
[326/326] cxxshlib: build/src/python/essentia.cpp.1.o build/src/python/parsing.cpp.1.o build/src/python/pytypes/boolean.cpp.1.o build/src/python/pytypes/integer.cpp.1.o build/src/python/pytypes/mapvectorstring.cpp.1.o build/src/python/pytypes/matrixreal.cpp.1.o build/src/python/pytypes/pypool.cpp.1.o build/src/python/pytypes/pyreal.cpp.1.o build/src/python/pytypes/pystereosample.cpp.1.o build/src/python/pytypes/string.cpp.1.o build/src/python/pytypes/vectorcomplex.cpp.1.o build/src/python/pytypes/vectorinteger.cpp.1.o build/src/python/pytypes/vectormatrixreal.cpp.1.o build/src/python/pytypes/vectorreal.cpp.1.o build/src/python/pytypes/vectorstereosample.cpp.1.o build/src/python/pytypes/vectorstring.cpp.1.o build/src/python/pytypes/vectorvectorreal.cpp.1.o build/src/python/pytypes/vectorvectorstereosample.cpp.1.o build/src/python/pytypes/vectorvectorstring.cpp.1.o -> build/src/python/_essentia.so
/usr/bin/ld.bfd.real: /usr/local/lib/libavformat.a(allformats.o): relocation R_X86_64_32 against `ff_a64_muxer' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libavformat.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld.bfd.real: /usr/local/lib/libavformat.a(allformats.o): relocation R_X86_64_32 against `ff_a64_muxer' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libavformat.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Waf: Leaving directory `/home/marwa/Desktop/essentia-master/build'
Build failed
 -> task in 'vamp_essentia' failed (exit status 1): 
	{task 140498184996688: cxxshlib vampplugins.cpp.34.o,vamppluginsextra.cpp.34.o,vampwrapper.cpp.34.o,FFT.cpp.34.o,PluginAdapter.cpp.34.o,RealTime.cpp.34.o -> libvamp_essentia.so}
['/usr/bin/g++', '-shared', '-pthread', '-pthread', 'src/examples/vampplugins.cpp.34.o', 'src/examples/vamppluginsextra.cpp.34.o', 'src/examples/vampwrapper.cpp.34.o', 'src/3rdparty/vamp-plugin-sdk-2.4/src/vamp-sdk/FFT.cpp.34.o', 'src/3rdparty/vamp-plugin-sdk-2.4/src/vamp-sdk/PluginAdapter.cpp.34.o', 'src/3rdparty/vamp-plugin-sdk-2.4/src/vamp-sdk/RealTime.cpp.34.o', '-o', '/home/marwa/Desktop/essentia-master/build/src/examples/libvamp_essentia.so', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-lfftw3f', '-lavformat', '-lavcodec', '-lswresample', '-lavutil', '-lm', '-lavcodec', '-lswresample', '-lavutil', '-lm', '-lavutil', '-lm', '-lavresample', '-lavutil', '-lm', '-lsamplerate', '-ltag', '-lyaml']
 -> task in '_essentia' failed (exit status 1): 
	{task 140498184810768: cxxshlib essentia.cpp.1.o,parsing.cpp.1.o,boolean.cpp.1.o,integer.cpp.1.o,mapvectorstring.cpp.1.o,matrixreal.cpp.1.o,pypool.cpp.1.o,pyreal.cpp.1.o,pystereosample.cpp.1.o,string.cpp.1.o,vectorcomplex.cpp.1.o,vectorinteger.cpp.1.o,vectormatrixreal.cpp.1.o,vectorreal.cpp.1.o,vectorstereosample.cpp.1.o,vectorstring.cpp.1.o,vectorvectorreal.cpp.1.o,vectorvectorstereosample.cpp.1.o,vectorvectorstring.cpp.1.o -> _essentia.so}
['/usr/bin/g++', '-shared', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-pthread', '-Wl,-O1', '-Wl,-Bsymbolic-functions', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-pthread', '-pthread', 'src/python/essentia.cpp.1.o', 'src/python/parsing.cpp.1.o', 'src/python/pytypes/boolean.cpp.1.o', 'src/python/pytypes/integer.cpp.1.o', 'src/python/pytypes/mapvectorstring.cpp.1.o', 'src/python/pytypes/matrixreal.cpp.1.o', 'src/python/pytypes/pypool.cpp.1.o', 'src/python/pytypes/pyreal.cpp.1.o', 'src/python/pytypes/pystereosample.cpp.1.o', 'src/python/pytypes/string.cpp.1.o', 'src/python/pytypes/vectorcomplex.cpp.1.o', 'src/python/pytypes/vectorinteger.cpp.1.o', 'src/python/pytypes/vectormatrixreal.cpp.1.o', 'src/python/pytypes/vectorreal.cpp.1.o', 'src/python/pytypes/vectorstereosample.cpp.1.o', 'src/python/pytypes/vectorstring.cpp.1.o', 'src/python/pytypes/vectorvectorreal.cpp.1.o', 'src/python/pytypes/vectorvectorstereosample.cpp.1.o', 'src/python/pytypes/vectorvectorstring.cpp.1.o', '-o', '/home/marwa/Desktop/essentia-master/build/src/python/_essentia.so', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L/usr/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-lpython2.7', '-lfftw3f', '-lavformat', '-lavcodec', '-lswresample', '-lavutil', '-lm', '-lavcodec', '-lswresample', '-lavutil', '-lm', '-lavutil', '-lm', '-lavresample', '-lavutil', '-lm', '-lsamplerate', '-ltag', '-lyaml']

**Comment by dbogdanov** [comment]
You have a local static build of libav (```/usr/local/lib/libavformat.a```) you should use dynamic libraries  instead. Install libav libraries from ubuntu repository, as suggested by installation instructions. [You should be fine installing 2.1beta2 version on 14.04.](https://github.com/MTG/essentia/issues/295#issuecomment-138924656)

**Comment by marwa1013** [comment]
I had a ./waf build fail


marwa@marwa-PC:~/Desktop/essentia-2.1_beta2$ ./waf configure --mode=release --with-python --with-examples
Setting top to                           : /home/marwa/Desktop/essentia-2.1_beta2 
Setting out to                           : /home/marwa/Desktop/essentia-2.1_beta2/build 
→ configuring the project in /home/marwa/Desktop/essentia-2.1_beta2
→ Building in release mode
Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for 'libavcodec' >= 53.25.0     : yes 
Checking for 'libavformat'               : yes 
Checking for 'libavutil'                 : yes 
Checking for 'libswresample'             : yes 
Checking for 'fftw3f'                    : yes 
Checking for 'samplerate'                : yes 
Checking for 'taglib' >= 1.9             : yes 
Checking for 'yaml-0.1'                  : yes 
Checking for program python              : /usr/bin/python 
Checking for python version              : (2, 7, 6, 'final', 0) 
Checking for library python2.7 in LIBDIR : yes 
Checking for program /usr/bin/python-config,python2.7-config,python-config-2.7,python2.7m-config : /usr/bin/python-config 
Checking for header Python.h                                                                     : yes 

================================ CONFIGURATION SUMMARY ================================
- FFmpeg / libav detected!
  The following algorithms will be included: ['AudioLoader', 'MonoLoader', 'EqloudLoader', 'EasyLoader', 'MonoWriter', 'AudioWriter']

- libsamplerate (SRC) detected!
  The following algorithms will be included: ['Resample']

- TagLib detected!
  The following algorithms will be included: ['MetadataReader']

- Essentia is configured without Gaia2.
  The following algorithms will be ignored: ['GaiaTransform']
  Examples requiring Gaia2 will be ignored

- Compiling 23 examples
  standard_beatsmarker, standard_mfcc, standard_onsetrate, standard_pitchyinfft, standard_fadedetection, standard_spectralcontrast, standard_rhythmtransform, streaming_extractor, streaming_extractor_short_sounds, streaming_extractor_music, streaming_beatsmarker, streaming_mfcc, streaming_gfcc, streaming_rhythmextractor_multifeature, streaming_beattracker_multifeature_mirex2013, streaming_onsetrate, streaming_panning, streaming_tuningfrequency, streaming_key, streaming_pitchyinfft, streaming_predominantmelody, streaming_md5, streaming_extractor_freesound
=======================================================================================
'configure' finished successfully (0.519s)
marwa@marwa-PC:~/Desktop/essentia-2.1_beta2$ sudo ./waf 
[sudo] password for marwa: 
Waf: Entering directory `/home/marwa/Desktop/essentia-2.1_beta2/build'
→ building from /home/marwa/Desktop/essentia-2.1_beta2
→ building from /home/marwa/Desktop/essentia-2.1_beta2/src
Building all the algorithms
Ignoring the following algorithms: GaiaTransform
→ building from /home/marwa/Desktop/essentia-2.1_beta2/src/examples
→ building from /home/marwa/Desktop/essentia-2.1_beta2/src/python
[205/290] cxxprogram: build/src/examples/standard_beatsmarker.cpp.1.o -> build/src/examples/standard_beatsmarker
[208/290] cxxprogram: build/src/examples/standard_mfcc.cpp.2.o -> build/src/examples/standard_mfcc
[209/290] cxxprogram: build/src/examples/standard_onsetrate.cpp.3.o -> build/src/examples/standard_onsetrate
[211/290] cxxprogram: build/src/examples/standard_pitchyinfft.cpp.4.o -> build/src/examples/standard_pitchyinfft
/usr/local/lib/libswresample.a(rematrix.o): In function `swri_rematrix_init':
/home/marwa/Downloads/ffmpeg-2.7.2/libswresample/rematrix.c:365: undefined reference to `av_calloc'
/home/marwa/Downloads/ffmpeg-2.7.2/libswresample/rematrix.c:377: undefined reference to `av_calloc'
/home/marwa/Downloads/ffmpeg-2.7.2/libswresample/rematrix.c:389: undefined reference to `av_calloc'
/usr/local/lib/libswresample.a(resample.o): In function `resample_init':
/home/marwa/Downloads/ffmpeg-2.7.2/libswresample/resample.c:220: undefined reference to `av_calloc'
collect2: error: ld returned 1 exit status
/usr/local/lib/libswresample.a(rematrix.o): In function `swri_rematrix_init':
/home/marwa/Downloads/ffmpeg-2.7.2/libswresample/rematrix.c:365: undefined reference to `av_calloc'
/home/marwa/Downloads/ffmpeg-2.7.2/libswresample/rematrix.c:377: undefined reference to `av_calloc'
/home/marwa/Downloads/ffmpeg-2.7.2/libswresample/rematrix.c:389: undefined reference to `av_calloc'
/usr/local/lib/libswresample.a(resample.o): In function `resample_init':
/home/marwa/Downloads/ffmpeg-2.7.2/libswresample/resample.c:220: undefined reference to `av_calloc'
collect2: error: ld returned 1 exit status
/usr/local/lib/libswresample.a(rematrix.o): In function `swri_rematrix_init':
/home/marwa/Downloads/ffmpeg-2.7.2/libswresample/rematrix.c:365: undefined reference to `av_calloc'
/home/marwa/Downloads/ffmpeg-2.7.2/libswresample/rematrix.c:377: undefined reference to `av_calloc'
/home/marwa/Downloads/ffmpeg-2.7.2/libswresample/rematrix.c:389: undefined reference to `av_calloc'
/usr/local/lib/libswresample.a(resample.o): In function `resample_init':
/home/marwa/Downloads/ffmpeg-2.7.2/libswresample/resample.c:220: undefined reference to `av_calloc'
collect2: error: ld returned 1 exit status
/usr/local/lib/libswresample.a(rematrix.o): In function `swri_rematrix_init':
/home/marwa/Downloads/ffmpeg-2.7.2/libswresample/rematrix.c:365: undefined reference to `av_calloc'
/home/marwa/Downloads/ffmpeg-2.7.2/libswresample/rematrix.c:377: undefined reference to `av_calloc'
/home/marwa/Downloads/ffmpeg-2.7.2/libswresample/rematrix.c:389: undefined reference to `av_calloc'
/usr/local/lib/libswresample.a(resample.o): In function `resample_init':
/home/marwa/Downloads/ffmpeg-2.7.2/libswresample/resample.c:220: undefined reference to `av_calloc'
collect2: error: ld returned 1 exit status
Waf: Leaving directory `/home/marwa/Desktop/essentia-2.1_beta2/build'
Build failed
 -> task in 'standard_mfcc' failed (exit status 1): 
	{task 140471199307152: cxxprogram standard_mfcc.cpp.2.o -> standard_mfcc}
['/usr/bin/g++', '-pthread', '-pthread', 'src/examples/standard_mfcc.cpp.2.o', '-o', '/home/marwa/Desktop/essentia-2.1_beta2/build/src/examples/standard_mfcc', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L../../../../../usr/lib/x86_64-linux-gnu', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-lpthread', '-lfftw3f', '-lyaml', '-lavformat', '-lavcodec', '-lswresample', '-lavutil', '-lm', '-lavcodec', '-lswresample', '-lavutil', '-lm', '-lavutil', '-lm', '-lswresample', '-lavutil', '-lm', '-lsamplerate', '-ltag']
 -> task in 'standard_beatsmarker' failed (exit status 1): 
	{task 140471199480912: cxxprogram standard_beatsmarker.cpp.1.o -> standard_beatsmarker}
['/usr/bin/g++', '-pthread', '-pthread', 'src/examples/standard_beatsmarker.cpp.1.o', '-o', '/home/marwa/Desktop/essentia-2.1_beta2/build/src/examples/standard_beatsmarker', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L../../../../../usr/lib/x86_64-linux-gnu', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-lpthread', '-lfftw3f', '-lyaml', '-lavformat', '-lavcodec', '-lswresample', '-lavutil', '-lm', '-lavcodec', '-lswresample', '-lavutil', '-lm', '-lavutil', '-lm', '-lswresample', '-lavutil', '-lm', '-lsamplerate', '-ltag']
 -> task in 'standard_pitchyinfft' failed (exit status 1): 
	{task 140471199307728: cxxprogram standard_pitchyinfft.cpp.4.o -> standard_pitchyinfft}
['/usr/bin/g++', '-pthread', '-pthread', 'src/examples/standard_pitchyinfft.cpp.4.o', '-o', '/home/marwa/Desktop/essentia-2.1_beta2/build/src/examples/standard_pitchyinfft', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L../../../../../usr/lib/x86_64-linux-gnu', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-lpthread', '-lfftw3f', '-lyaml', '-lavformat', '-lavcodec', '-lswresample', '-lavutil', '-lm', '-lavcodec', '-lswresample', '-lavutil', '-lm', '-lavutil', '-lm', '-lswresample', '-lavutil', '-lm', '-lsamplerate', '-ltag']
 -> task in 'standard_onsetrate' failed (exit status 1): 
	{task 140471199307408: cxxprogram standard_onsetrate.cpp.3.o -> standard_onsetrate}
['/usr/bin/g++', '-pthread', '-pthread', 'src/examples/standard_onsetrate.cpp.3.o', '-o', '/home/marwa/Desktop/essentia-2.1_beta2/build/src/examples/standard_onsetrate', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L../../../../../usr/lib/x86_64-linux-gnu', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-lpthread', '-lfftw3f', '-lyaml', '-lavformat', '-lavcodec', '-lswresample', '-lavutil', '-lm', '-lavcodec', '-lswresample', '-lavutil', '-lm', '-lavutil', '-lm', '-lswresample', '-lavutil', '-lm', '-lsamplerate', '-ltag']

**Comment by dbogdanov** [comment]
Again, some part of manual installation of  FFMpeg is still in local (libswresample). Probably, there is an error when compiling with libswresample, that I will haave to check or we will disable its use in general. Remove that library from your ```/usr/local/lib```
