### ISSUE TITLE
missing dependencies on Linux(centos 6.3)

### ISSUE THREAD

**Issue by agangzz** [MTG/essentia#313]
Hi,

I followed the instructions for building the library on Linux, as shown in 
https://github.com/MTG/essentia/blob/master/FAQ.md#cross-compiling-for-windows-on-linux

but I still miss some dependencies.
this command should have installed all the missing libraries, but the waf can't find them.

Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for 'libavcodec' >= 53.25.0     : not found 
Checking for 'libavformat'               : not found 
Checking for 'libavutil'                 : not found 
Checking for 'libswresample'             : not found 
Checking for 'fftw3f'                    : not found 
The configuration failed
(complete log in /home/www/Software/sonic/essentia-2.1_beta2/build/config.log)

could you help me to solve this problem?
thank you

**Comment by dbogdanov** [comment]
Still relevant?

**Comment by alastair** [comment]
No response, closing
