### ISSUE TITLE
Cross compilation for Windows fails.

### ISSUE THREAD

**Issue by orgue** [MTG/essentia#318]
I'm trying cross compilation of essentia-2.1_beta2 for Windows on Ubuntu 14.04, but it fails. I have no idea what is wrong.
Here is a part of the log:

[203/270] write_pcfile:  -> build/essentia.pc
[204/270] cxx: src/examples/standard_beatsmarker.cpp -> build/src/examples/standard_beatsmarker.cpp.1.o
In file included from /home/a-ueda/Downloads/essentia-2.1_beta2/src/essentia/types.h:30:0,
                 from /home/a-ueda/Downloads/essentia-2.1_beta2/src/essentia/algorithmfactory.h:26,
                 from ../src/examples/standard_beatsmarker.cpp:22:
/home/a-ueda/Downloads/essentia-2.1_beta2/src/essentia/config.h:137:0: warning: "NOMINMAX" redefined [enabled by default]
   #define NOMINMAX
 ^
In file included from /usr/include/c++/4.8/i686-w64-mingw32/bits/c++config.h:426:0,
                 from /usr/include/c++/4.8/iostream:38,
                 from ../src/examples/standard_beatsmarker.cpp:20:
/usr/include/c++/4.8/i686-w64-mingw32/bits/os_defines.h:45:0: note: this is the location of the previous definition
 #define NOMINMAX 1
 ^
[205/270] cxxprogram: build/src/examples/standard_beatsmarker.cpp.1.o -> build/src/examples/standard_beatsmarker.exe
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0xc9b): undefined reference to `_imp___ZNK6TagLib6String8isLatin1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0xcf0): undefined reference to `_imp___ZN6TagLib6StringC1EPKcNS0_4TypeE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0xd13): undefined reference to `_imp___ZNK6TagLib10StringList8toStringERKNS_6StringE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0xd29): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0xd3c): undefined reference to `_imp___ZNK6TagLib6String7isEmptyEv'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0xd9a): undefined reference to `_imp___ZNK6TagLib6String6to8BitEb'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0xdd8): undefined reference to `_imp___ZNK6TagLib6String6to8BitEb'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0xe3b): undefined reference to `_imp___ZNK6TagLib6String6to8BitEb'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0xee2): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0xefd): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0xf1b): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0xfd1): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x17d9): undefined reference to `_imp___ZN6TagLib8FileNameC1EPKw'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1804): undefined reference to `_imp___ZN6TagLib7FileRefC1ENS_8FileNameEbNS_15AudioProperties9ReadStyleE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1859): undefined reference to `_imp___ZNK6TagLib7FileRef6isNullEv'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1a6e): undefined reference to `_imp___ZNK6TagLib7FileRef4fileEv'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1a8a): undefined reference to `_imp___ZNK6TagLib4File10propertiesEv'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1aab): undefined reference to `_imp___ZN6TagLib6StringC1EPKcNS0_4TypeE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1ad0): undefined reference to `_imp___ZN6TagLib11PropertyMapixERKNS_6StringE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1b44): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1b6c): undefined reference to `_imp___ZN6TagLib6StringC1EPKcNS0_4TypeE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1b87): undefined reference to `_imp___ZN6TagLib11PropertyMapixERKNS_6StringE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1bfb): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1c23): undefined reference to `_imp___ZN6TagLib6StringC1EPKcNS0_4TypeE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1c3e): undefined reference to `_imp___ZN6TagLib11PropertyMapixERKNS_6StringE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1cb2): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1cd7): undefined reference to `_imp___ZN6TagLib6StringC1EPKcNS0_4TypeE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1cef): undefined reference to `_imp___ZN6TagLib11PropertyMapixERKNS_6StringE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1d57): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1d7c): undefined reference to `_imp___ZN6TagLib6StringC1EPKcNS0_4TypeE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1d94): undefined reference to `_imp___ZN6TagLib11PropertyMapixERKNS_6StringE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1dfc): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1e21): undefined reference to `_imp___ZN6TagLib6StringC1EPKcNS0_4TypeE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1e39): undefined reference to `_imp___ZN6TagLib11PropertyMapixERKNS_6StringE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1ea1): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1ec6): undefined reference to `_imp___ZN6TagLib6StringC1EPKcNS0_4TypeE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1ede): undefined reference to `_imp___ZN6TagLib11PropertyMapixERKNS_6StringE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1f46): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x1fb8): undefined reference to `_imp___ZNK6TagLib6String6to8BitEb'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x2232): undefined reference to `_imp___ZNK6TagLib6String6to8BitEb'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x238f): undefined reference to `_imp___ZNK6TagLib7FileRef15audioPropertiesEv'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x23cb): undefined reference to `_imp___ZNK6TagLib7FileRef15audioPropertiesEv'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x2407): undefined reference to `_imp___ZNK6TagLib7FileRef15audioPropertiesEv'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x2443): undefined reference to `_imp___ZNK6TagLib7FileRef15audioPropertiesEv'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x2560): undefined reference to `_imp___ZN6TagLib11PropertyMapD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x25ba): undefined reference to `_imp___ZN6TagLib7FileRefD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x26aa): undefined reference to `_imp___ZN6TagLib7FileRefD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x28be): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x2919): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x2974): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x29c9): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x2a1e): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x2a73): more undefined references to `_imp___ZN6TagLib6StringD1Ev' follow
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x2c3e): undefined reference to `_imp___ZN6TagLib11PropertyMapD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x2c96): undefined reference to `_imp___ZN6TagLib7FileRefD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x2f1a): undefined reference to `_imp___ZN6TagLib8FileNameC1EPKc'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x2f45): undefined reference to `_imp___ZN6TagLib7FileRefC1ENS_8FileNameEbNS_15AudioProperties9ReadStyleE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x2f78): undefined reference to `_imp___ZNK6TagLib7FileRef6isNullEv'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x31d1): undefined reference to `_imp___ZNK6TagLib7FileRef4fileEv'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x31ed): undefined reference to `_imp___ZNK6TagLib4File10propertiesEv'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x320e): undefined reference to `_imp___ZN6TagLib6StringC1EPKcNS0_4TypeE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x3233): undefined reference to `_imp___ZN6TagLib11PropertyMapixERKNS_6StringE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x32a1): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x32c6): undefined reference to `_imp___ZN6TagLib6StringC1EPKcNS0_4TypeE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x32de): undefined reference to `_imp___ZN6TagLib11PropertyMapixERKNS_6StringE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x3340): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x3365): undefined reference to `_imp___ZN6TagLib6StringC1EPKcNS0_4TypeE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x337d): undefined reference to `_imp___ZN6TagLib11PropertyMapixERKNS_6StringE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x33df): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x3404): undefined reference to `_imp___ZN6TagLib6StringC1EPKcNS0_4TypeE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x341c): undefined reference to `_imp___ZN6TagLib11PropertyMapixERKNS_6StringE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x347e): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x34a3): undefined reference to `_imp___ZN6TagLib6StringC1EPKcNS0_4TypeE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x34bb): undefined reference to `_imp___ZN6TagLib11PropertyMapixERKNS_6StringE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x351d): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x3542): undefined reference to `_imp___ZN6TagLib6StringC1EPKcNS0_4TypeE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x355a): undefined reference to `_imp___ZN6TagLib11PropertyMapixERKNS_6StringE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x35bc): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x35e1): undefined reference to `_imp___ZN6TagLib6StringC1EPKcNS0_4TypeE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x35f9): undefined reference to `_imp___ZN6TagLib11PropertyMapixERKNS_6StringE'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x365b): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x3674): undefined reference to `_imp___ZNK6TagLib7FileRef15audioPropertiesEv'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x36b7): undefined reference to `_imp___ZNK6TagLib7FileRef15audioPropertiesEv'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x37be): undefined reference to `_imp___ZNK6TagLib7FileRef15audioPropertiesEv'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x380b): undefined reference to `_imp___ZNK6TagLib7FileRef15audioPropertiesEv'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x386f): undefined reference to `_imp___ZN6TagLib11PropertyMapD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x38ca): undefined reference to `_imp___ZN6TagLib7FileRefD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x3922): undefined reference to `_imp___ZN6TagLib7FileRefD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x3b7c): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x3bd1): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x3c26): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x3c7b): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x3cd0): undefined reference to `_imp___ZN6TagLib6StringD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x3d25): more undefined references to `_imp___ZN6TagLib6StringD1Ev' follow
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x3e4b): undefined reference to `_imp___ZN6TagLib11PropertyMapD1Ev'
src/libessentia.a(metadatareader.cpp.1.o):metadatareader.cpp:(.text+0x3e78): undefined reference to `_imp___ZN6TagLib7FileRefD1Ev'
/usr/bin/i686-w64-mingw32-ld: src/libessentia.a(metadatareader.cpp.1.o): bad reloc address 0x0 in section `.data'
collect2: error: ld returned 1 exit status
Waf: Leaving directory `/home/a-ueda/Downloads/essentia-2.1_beta2/build'
Build failed
 -> task in 'standard_beatsmarker' failed (exit status 1): 
	{task 3067012332L: cxxprogram standard_beatsmarker.cpp.1.o -> standard_beatsmarker.exe}
['/usr/bin/i686-w64-mingw32-g++', '-Wl,--enable-auto-import', '-Wl,--enable-auto-import', 'src/examples/standard_beatsmarker.cpp.1.o', '-o', '/home/a-ueda/Downloads/essentia-2.1_beta2/build/src/examples/standard_beatsmarker.exe', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L../../../../../usr/lib/i386-linux-gnu', '-L/home/a-ueda/Downloads/essentia-2.1_beta2/packaging/win32_3rdparty/lib', '-L/home/a-ueda/Downloads/essentia-2.1_beta2/packaging/win32_3rdparty/lib', '-L/home/a-ueda/Downloads/essentia-2.1_beta2/packaging/win32_3rdparty/lib', '-L/home/a-ueda/Downloads/essentia-2.1_beta2/packaging/win32_3rdparty/lib', '-L/home/a-ueda/Downloads/essentia-2.1_beta2/packaging/win32_3rdparty/lib', '-L/home/a-ueda/Downloads/essentia-2.1_beta2/packaging/win32_3rdparty/lib', '-L/home/a-ueda/Downloads/essentia-2.1_beta2/packaging/win32_3rdparty/lib', '-lpthread', '-lfftw3f', '-lm', '-lyaml', '-lavformat', '-lavcodec', '-lpsapi', '-lavutil', '-lm', '-lavcodec', '-lpsapi', '-lavutil', '-lm', '-lavutil', '-lm', '-lsamplerate', '-ltag']

**Comment by dbogdanov** [comment]
You got some problems linking to taglib. Did you build taglib with the script ``build_taglib.sh``?

**Comment by orgue** [comment]
Yes, I used the build_taglib.sh script. 
Here is the entire log.
https://drive.google.com/file/d/0B_PUCvyCDo4ZMUUxd0pfUE8ydUk/view?usp=sharing

BTW I could not find gcc-mingw32 in the package list of ubuntu 14.04, so I installed the g++-mingw-w64-i686 package before compilation. Is this correct?

**Comment by dbogdanov** [comment]
Try [v2.1_beta2_fixe](https://github.com/MTG/essentia/tree/v2.1_beta2_fixes) branch, there were some fixes recently. Then, share the ```build/config.log``` if it does not work for you.

**Comment by orgue** [comment]
I tried the fixes beanch. It still reports errors.
(config.log)
https://drive.google.com/file/d/0B_PUCvyCDo4ZZmFqeFEwZDRld00/view?usp=sharing
(all of the terminal output)
https://drive.google.com/file/d/0B_PUCvyCDo4ZVTRTcnhfeVBEVG8/view?usp=sharing
Thanks.
