### ISSUE TITLE
OS X 10.6.8 - can't import essentia

### ISSUE THREAD

**Issue by drlids** [MTG/essentia#319]
Hi, I think I successfully built essentia-2.1_beta2 - at least, it passed the C and Python tests. But where do import the essentia module from? I'm getting an error in iPython.

Thanks.

**Comment by carthach** [comment]
Did you install essentia then set your python path appropriately like:
export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

**Comment by drlids** [comment]
Thanks. I've set the python path as advised. Now from ipython I get this message:

------------------

In [1]: import essentia
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-88e1c733dfcb> in <module>()
----> 1 import essentia

/usr/local/lib/python2.7/site-packages/essentia/__init__.py in <module>()

ImportError: dlopen(/usr/local/lib/python2.7/site-packages/essentia/_essentia.so, 2): Library not loaded: /usr/local/opt/essentia/lib/libessentia.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/essentia/_essentia.so
  Reason: image not found

------------------

I seem not to have an essentia folder in /usr/local/opt.

**Comment by dbogdanov** [comment]
Try installing from [brew formula](http://essentia.upf.edu/documentation/installing.html#osx)

**Comment by yurci** [comment]
@carthach Thank you that solved the issue!

**Comment by brennon** [comment]
Installing through Homebrew does not resolve this issue for me. In particular, this is what is happening for me:

```
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import essentia
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/essentia/__init__.py", line 1, in <module>
    import _essentia
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/essentia/_essentia.so, 2): Library not loaded: /private/tmp/essentia-20160909-12874-3qliph/build/src/libessentia.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/essentia/_essentia.so
  Reason: image not found
```

**Comment by dbogdanov** [comment]
@brennon Make sure that brew install completed successfully.

**Comment by carthach** [comment]
Also make sure there is actually something in

/usr/local/lib/python2.7/site-packages/essentia/

That it installed the Python stuff properly...

**Comment by brennon** [comment]
Well, the package contents seem to be there, but it certainly doesn’t seem
to be installed properly…


On September 15, 2016 at 4:29:13 PM, Cárthach Ó Nuanáin (
notifications@github.com) wrote:

Also make sure there is actually something in

/usr/local/lib/python2.7/site-packages/essentia/

That it installed the Python stuff properly...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MTG/essentia/issues/319#issuecomment-247445288>, or mute
the thread
