### ISSUE TITLE
Failed python test and cannot import essentia

### ISSUE THREAD

**Issue by FredomLuo** [MTG/essentia#322]
`brew doctor` is clear.
`./waf configure --mode=release --with-python --with-cpptests --with-examples --with-vamp` shows one of the possible problem:
<img width="825" alt="2015-11-23 04 28 08" src="https://cloud.githubusercontent.com/assets/5856202/11326119/6793c792-919b-11e5-8976-77ce86b0e853.png">
`which python` is /usr/local/bin/python.
There is no problem with `./waf` and `./waf install`.
`./waf run_python_tests` shows:
<img width="1272" alt="2015-11-23 04 25 42" src="https://cloud.githubusercontent.com/assets/5856202/11326108/2ad6d42a-919b-11e5-9174-a9855fd06330.png">
It is the same message when importing essentia in python. 
How can I solve this? Please help me.

**Comment by srviest** [comment]
Hi Mr. Luo, please try adding the path essentia installed in your PYTHONPATH :)

**Comment by alastair** [comment]
runtime path issues, closing
