### ISSUE TITLE
Cannot filter metadata in MetadataReader

### ISSUE THREAD

**Issue by julianterzyk** [MTG/essentia#323]
When trying to filter the metadata output from the standard MetadataReader method I still get all output data returned and not just the one I'm filtering for. 

Here is a tiny code snippet:

import essentia.standard as estd

estd.MetadataReader(filename='../../datasets/example.mp3', filterMetadata=True, filterMetadataTags=['duration'])()

Anything wrong with my implementation, maybe with the filterMetadataTags argument? 

Cheers,
Julian

**Comment by dbogdanov** [comment]
MetadataReader reads all metadata tags found in audio and stores them in the pool *tagPool*. Standard metadata tags found in audio files include [these strings](https://taglib.github.io/api/classTagLib_1_1PropertyMap.html#details). Tag strings are case-sensitive and they are converted to lower-case when stored to the pool. It is possible to filter these tags by using ```filterMetadataTags```. This parameter should specify a white-list of tag strings as they are found in the audio file (e.g., "ARTIST"). 

Typically, there is no tag string "duration" among tags, therefore, your tag pool should be empty after filtering:

```
In [1]: import essentia.standard as es
In [2]: _,_,_,_,_,_,_, p, _,_,_,_ = es.MetadataReader(filename=test.mp3", filterMetadata=True, filterMetadataTags=['duration'])()
In [3]: p.descriptorNames()
Out[3]: []
```

```
In [1]: import essentia.standard as es
In [2]: _,_,_,_,_,_,_, p, _,_,_,_ = es.MetadataReader(filename="test.mp3", filterMetadata=True, filterMetadataTags=['ALBUM', 'ARTIST'])()
In [3]: p.descriptorNames()
Out[3]: ['metadata.tags.album', 'metadata.tags.artist']
```

```
In [1]: import essentia.standard as es
In [2]: _,_,_,_,_,_,_, p, _,_,_,_ = es.MetadataReader(filename="test.mp3")()
In [3]: p.descriptorNames()
Out[3]: 
['metadata.tags.album',
 'metadata.tags.albumartist',
 'metadata.tags.albumartistsort',
 'metadata.tags.artist',
 'metadata.tags.artistsort',
 'metadata.tags.asin',
 'metadata.tags.comment:songs-db_custom1',
 'metadata.tags.comment:songs-db_custom2',
 'metadata.tags.comment:songs-db_custom3',
 'metadata.tags.contentgroup',
 'metadata.tags.date',
 'metadata.tags.genre',
 'metadata.tags.mood',
 'metadata.tags.musicbrainz album release country',
 'metadata.tags.musicbrainz album status',
 'metadata.tags.musicbrainz album type',
 'metadata.tags.musicbrainz_albumartistid',
 'metadata.tags.musicbrainz_albumid',
 'metadata.tags.musicbrainz_artistid',
 'metadata.tags.musicbrainz_trackid',
 'metadata.tags.originaldate',
 'metadata.tags.title',
 'metadata.tags.tracknumber']
```
