### ISSUE TITLE
Different results for ubuntu 15.10 

### ISSUE THREAD

**Issue by andrebola** [MTG/essentia#324]
I'm getting different results when using a mp3 than a wav file (converted from the same mp3).
I'm using:
        ubuntu version 15.10, 
        essentia version: 2.1beta1

I'm loading the file with MonoLoader, then running PitchContours with the following parameters:
        hopSize=128
        binResolution=7.5
        peakDistributionThreshold = 1.4

This is the output if I plot both results:
![ing2](https://cloud.githubusercontent.com/assets/991305/11404192/0012dc72-93a1-11e5-969b-bc5abb1bb67b.png)

**Comment by dbogdanov** [comment]
Closing this because 2.1beta1 version is outdated.
