### ISSUE TITLE
Error compiling standard_mfcc.cpp on Ubuntu 14.10 undefined reference to `swr_alloc_set_opts'

### ISSUE THREAD

**Issue by ramonsanabria** [MTG/essentia#326]
When compiling the standard_mfcc.cpp file as suggested on the FAQ.md: 

g++ -pipe -Wall -O2 -fPIC -I/usr/local/include/essentia/ -I/usr/local/include/essentia/scheduler/ -I/usr/local/include/essentia/streaming/  -I/usr/local/include/essentia/utils -I/usr/include/taglib -I/usr/local/include/gaia2 -I/usr/include/qt4 -I/usr/include/qt4/QtCore -D__STDC_CONSTANT_MACROS standard_mfcc.cpp -o standard_mfcc -L/usr/local/lib -lessentia -lfftw3 -lyaml -lavcodec -lavformat -lavutil -lsamplerate -ltag -lfftw3f -lQtCore -lgaia2

The following errors appear:
/usr/local/lib/libessentia.a(audioloader.cpp.1.o): In function `essentia::streaming::AudioLoader::openAudioFile(std::string const&)':
audioloader.cpp:(.text+0x5ce): undefined reference to `swr_alloc_set_opts'
audioloader.cpp:(.text+0x5e1): undefined reference to `swr_init'
/usr/local/lib/libessentia.a(audioloader.cpp.1.o): In function `essentia::streaming::AudioLoader::closeAudioFile()':
audioloader.cpp:(.text+0xcd0): undefined reference to `swr_free'
/usr/local/lib/libessentia.a(audioloader.cpp.1.o): In function `essentia::streaming::AudioLoader::decode_audio_frame(AVCodecContext*, short*, int*, AVPacket*)':
audioloader.cpp:(.text+0xf38): undefined reference to `swr_convert'
collect2: error: ld returned 1 exit status

I have been able to successfully compile the example by rearranging the compilation flags as shown on the waf output in verbose mode (-vvv). As a result, the following command successfully compiles the example:

g++ -pipe -Wall -O2 -fPIC -I/usr/local/include/essentia/ -I/usr/local/include/essentia/scheduler/ -I/usr/local/include/essentia/streaming/  -I/usr/local/include/essentia/utils -I/usr/include/taglib -I/usr/local/include/gaia2 -I/usr/include/qt4 -I/usr/include/qt4/QtCore -D__STDC_CONSTANT_MACROS standard_mfcc.cpp -o standard_mfcc -lessentia -L/usr/local/lib -LQtCore -lpthread -lfftw3f -lyaml -lavformat -lavcodec -lavutil -lswresample -lsamplerate -ltag -lgaia2 -lQtCore -lyaml

**Comment by dbogdanov** [comment]
Closing, as these errors are related to libswresample, which is not supported anymore (see #321).
