### ISSUE TITLE
framercutter size 0, missing bark and mfcc bands?

### ISSUE THREAD

**Issue by q-depot** [MTG/essentia#332]
Hi,

I'm running essentia on windows, most of the bits seem working fine, the Spectrum(KissFft) looks good and so the other scales, however I'm still having some issues:

**1) framecutter size is always 0**
I had the same problem a while ago on OSX too, I never figured it out, I think I'm doing everything correctly, the only difference is the PCM buffer that doesn't come from essentia but rather from my app(ie no audio loader).
The same pcm buffer is passed to KissFft which seems to compute correctly so I'm not sure where the problem is, this is my initialisation, mFrameCutter is the first thing I try to compute, size is always 0

```
essentia::init();
mFactory        = &AlgorithmFactory::instance();
mWindow         = mFactory->create("Windowing", "type", "blackmanharris62");
mFrameCutter    = mFactory->create("FrameCutter", "frameSize", EssentiaDevice::FrameSize, "hopSize", EssentiaDevice::HopSize, "startFromZero", true );

mPcmData.resize( EssentiaDevice::PcmSize );

mFrameCutter->input("signal").set( mPcmData );
mFrameCutter->output("frame").set( mFrameData );
```

**2) barkbands and mfcc bands have some gaps in the bands**
I'm not sure why most of the bands are computed except a few, you can see a screenshot below, the 1st band of mfcc is always 0, same for 2nd and 4th of the barks. any idea?
![screenshot_00004 crop](https://cloud.githubusercontent.com/assets/32179/11866908/c798fc3a-a4a5-11e5-86c3-b59f8976ba81.png)

EDIT: the problem with the "missing" bands seems to be related to the PCM buffer size, if the buffer is 512 samples than the bands are missing, with 1024/2048 everything seems fine.
Framecutter still not working.

**Comment by dbogdanov** [comment]
What is your PCM buffer size, and FrameCutter frame/hop sizes? 

FrameCutter returns empty frames in the case the input buffer is empty.

**Comment by q-depot** [comment]
FrameSize is 2048, hopsize is 1024, I also tried with 1024/512.
Can you confirm that the frame size should be the size of my pcm buffer(mono)? the hopsize is still a bit of a mystery to me, I usually go with half of the pcm size.

thanks.

**Comment by dbogdanov** [comment]
How do you manage / refill the "mPcmData" vector? FrameCutter cuts the input vector into frames, so maybe there is no need to use it in your case, your buffer is your input frame in the case you have equal pcm size and frame sizes

**Comment by q-depot** [comment]
the pcm buffer is a FIFO buffer with fixed size

**Comment by dbogdanov** [comment]
What you feed to FrameCutter is an std vector, over which it iterates each time compute() is called. If the mPcmData size is equal to framesize, there should be one frame output.

**Comment by q-depot** [comment]
I will double check but I'm confident the pcm size is always equal to framesize, the raw pcm is a FIFO buffer which I copy on each iteration to a std vector of Real

**Comment by dbogdanov** [comment]
Btw, you can use the streaming mode and [RingBufferInput](https://github.com/MTG/essentia/blob/9e13431443f77b1b574f15ebd1824b709040ccbd/src/essentia/streaming/algorithms/ringbufferinput.h#L37).

**Comment by q-depot** [comment]
thanks, I'll try it soon.
