### ISSUE TITLE
Problem while installing essentia

### ISSUE THREAD

**Issue by kartikgupta0909** [MTG/essentia#337]
I was getting the following error while installing essentia.

/usr/bin/ld: /usr/local/lib/libavformat.a(allformats.o): relocation R_X86_64_32 against `ff_a64_muxer' can not be used when making a shared object; recompile with -fPIC

Using ubuntu 13.04

**Comment by dbogdanov** [comment]
Provide more details from your ```build/config.log```
You are compiling a shared library, and there is a conflict while the build script intends to link to static ```/usr/local/lib/libavformat.a```. It seems you have manually buit LibAv. You can remove it and install required packages from Ubuntu repositories. However, to do so, your Ubuntu version is too old if you are installing Essentia 2.1_beta2.
