### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by nils-werner** [MTG/essentia#349]
FYI, I have managed to create a Conda recipe for essentia: https://github.com/nils-werner/conda-essentia

I had to patch two things:
- WAF was too old to work with Conda, so I am bundling version 1.8.18 with the recipe
- `src/wscript` had a definition of `ctx.env.INCLUDES` that
  1. was overwriting what was there (`INCLUDES = [...]` instead of `INCLUDES += [...]`)
  2. was not including stuff from `$PREFIX/include`.
     
     This prevented the compiler from linking against packages that are in the Conda environment, especially failing at `#include <yaml.h>`.

**Comment by nils-werner** [comment]
Actually, I could not get it to compile with `--with-python`, so the python bindings will not work.

**Comment by dbogdanov** [comment]
Closing this, as you can ```pip install essentia``` inside a conda environment.
