### ISSUE TITLE
run_python_tests fails on Xubuntu 13.10

### ISSUE THREAD

**Issue by surgesg** [MTG/essentia#36]
I am unable to run the python tests:

The installed GLIBC is 2.17

ptnx@ptnx-TA970:~/Documents/Code/essentia-master$ ./waf run_python_testsTraceback (most recent call last):
  File "test/src/unittest/all_tests.py", line 27, in <module>
    import essentia
  File "/home/ptnx/anaconda/lib/python2.7/site-packages/essentia/__init__.py", line 1, in <module>
    import _essentia
ImportError: /home/ptnx/anaconda/bin/../lib/libm.so.6: version `GLIBC_2.15' not found (required by /usr/lib/x86_64-linux-gnu/libvorbis.so.0)

**Comment by faroit** [comment]
Update: managed to install d8fa87 with anaconda. Looks like the updated waf and wafscripts helped here. 

To install to the correct anaconda site-package you have to set the anaconda base dir:

```./waf configure --with-python --prefix=anaconda_basedir```

however python finds the package but quits with segfault 11 when importing essentia. 

Any ideas?

**Comment by jfraj** [comment]
I also had trouble installing it with anaconda so I decided to install it in a separate environment with virtualenv where I reinstalled everything

```
virtualenv env
source env/bin/activate
pip install ipython numpy
pip install matplotlib
##... other missing lib if necessary
./waf configure --mode=release --with-python --prefix=/path_to_my/env --with-cpptests --with-examples --with-vamp
./waf
./waf install
```

It worked for me.

**Comment by Jose-Coursera** [comment]
I had this problem on ubuntu the solution was:

Add a .pth file to the directory $HOME/path/to/anaconda/lib/pythonX.X/site-packages. This can be named anything (it just must end with .pth). A .pth file is just a newline-separated listing of the full path-names of directories that will be added to your path on Python startup.

in the .ph file i wrote this:
/usr/local/lib/python2.7/site-packages/

and it works on linux ubuntu 14.04
