### ISSUE TITLE
Audioloader fails to read correctly

### ISSUE THREAD

**Issue by fkraemer** [MTG/essentia#367]
Encountered in version 2.1_beta2 (so might be fixed by now) when reading .flac files shorter than 1s.

The data read through python function:

```
loader = essentia.standard.AudioLoader(filename=filename)
audio, sampleRate, numberChannels, md5, bit_rate, codec = loader()
```
produces too much data (about >6times of samples actually in the file), while sampleRate/numberChannels is set correctly. Same function works flawless for files >1s.
Warnings are issued:
> [ WARNING  ] AudioLoader: more than 1 frame in packet, decoding remaining bytes...
> [ WARNING  ] at sample index: 47568
>[ WARNING  ] decoded samples: 4698
>[ WARNING  ] packet size: 28118

I am attaching an example file producing the error:
[1453978595912224054.flac.zip](https://github.com/MTG/essentia/files/108076/1453978595912224054.flac.zip)

**Comment by dbogdanov** [comment]
No issues with the latest master tested on my Linux machine.
