### ISSUE TITLE
Training classifier models in Gaia

### ISSUE THREAD

**Issue by purushottamekande** [MTG/essentia#368]
Hello,

I installed Essentia, Gaia, pre-trained models and could get the Essentia Genre classification output by using the streaming_extractors as in the manual.  Further I want to train classifier model using my own data.  For this I created descriptor yaml files from the music files; created groundtruth file and filelist.yaml and ran the following python script in Gaia.

python scripts/classification/train_model.py groundtruth.yaml result_filelist.yaml testsvm.prj testsvmdir testsvm.history

This seems to create the classification result and cross-verification result.  But the model output file (which I mentioned as the last argument in the python command above) hasn't come out to be text file but a binary file.  Anything wrong in the the sequence of training classifier model?  Please suggest.  

Thanks,

**Comment by purushottamekande** [comment]
Request for any inputs or suggestions.  Thanks in advance!

**Comment by purushottamekande** [comment]
[cla000.json.txt](https://github.com/MTG/essentia/files/109872/cla000.json.txt)
[cla000.sig.txt](https://github.com/MTG/essentia/files/109873/cla000.sig.txt)
[groundtruth.yaml.txt](https://github.com/MTG/essentia/files/109874/groundtruth.yaml.txt)
[result_filelist.yaml.txt](https://github.com/MTG/essentia/files/109875/result_filelist.yaml.txt)

python scripts/classification/train_model.py groundtruth.yaml result_filelist.yaml testsvm.prj testsvmdir testsvm.history

Attached files if it helps suggest if anything wrong. Thanks

**Comment by alastair** [comment]
Please note that we only give best effort support in this channel, and don't have time to respond to all tickets immediately. Asking for an update less than 1 day after you post the question isn't going to result in a faster response.

You are correct that the output file is a binary file. There is some further documentation of the format of this file here: http://essentia.upf.edu/documentation/streaming_extractor_music.html#high-level-classifier-models

> Each model (a *.history file) is basically a transformation history that maps a pool (a feature vector) of such lower-level descriptors produced by extractor into probability values of classes on which the model was trained.

You can use the `streaming_extractor_music_svm` example included in essentia to evaluate a json input document using a model file.

**Comment by purushottamekande** [comment]
Hi Alastair, thanks for the reply!  Yes, I understand the constraints. Thanks again.

**Comment by rajusinghd99** [comment]
Hi purushottamekande,
I have the same problem...Could you please help me to understand which file actually you used for streaming_extractor_music_svm. Even the binary file is also missing in outputs.
