### ISSUE TITLE
beat aligned summarization

### ISSUE THREAD

**Issue by echo66** [MTG/essentia#370]
Greetings!

Is there any example with beat aligned summarization? I'm following the normal and streaming tutorials in python but, the closest thing seems to be: 
(1) create a pool aggregator per beat interval.
(2) add the feature vectors to the corresponding aggregators.
Right now, AFAIK, this is done "manually" (i.e.: there are no Essentia classes to take care of this).

**Comment by dbogdanov** [comment]
This can be done manually in a few lines of code in python. You create pools for each beat interval and feed them the frames.

In standard mode this is a question of extracting beats from audio and then iterating through audio (FrameGenerator) to compute frames and populate the corresponding pools. You can also use [Slicer](http://essentia.upf.edu/documentation/reference/std_Slicer.html) to cut audio into segments first, and then compute frames on each segment.

**Comment by echo66** [comment]
Thanks for the clarification, Dmitry. :+1:
