### ISSUE TITLE
'./waf configure --with-gaia' failed. Checking for 'gaia2'   : not found.

### ISSUE THREAD

**Issue by penguin-penpen** [MTG/essentia#378]
I've complete all the dependencies and the rest of configurations.
`/usr/local/Cellar/libyaml/0.1.6_1/include
Checking for 'fftw3f'                    : yes
Checking for 'gaia2'                     : not found
The configuration failed
(complete log in /Users/yangyy/GitHub/VM/essentia-master/build/config.log)`

What should I do to complete the installation?

In the config.log:
Checking for 'gaia2'
['/usr/local/bin/pkg-config', '--cflags', '--libs', '--modversion', 'gaia2']
err: Ignoring incompatible output option "--modversion"
Package gaia2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gaia2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gaia2' found

not found
from /Users/yangyy/GitHub/VM/essentia-master/src: The configuration failed

**Comment by dbogdanov** [comment]
You should [install Gaia](https://github.com/MTG/gaia/blob/master/README.md) first.

**Comment by dbogdanov** [comment]
Btw, there is a temporal problem with installation of Gaia on OSX: [use Swig 3.0.4](https://github.com/MTG/gaia/issues/35) instead of the newest 3.0.8. In brew you can specify a version of package to install.

**Comment by penguin-penpen** [comment]
```brew tap MTG/essentia
Warning: Already tapped!```

```
brew install essentia --HEAD
Error: undefined method `desc' for Formulary::Formulae::Essentia:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/mtg/homebrew-essentia/essentia.rb:4:in `<class:Essentia>'
/usr/local/Library/Taps/mtg/homebrew-essentia/essentia.rb:3:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:140:in `<main>'
```

After that, I built from command line and it seemed installed successfully.
However, when I tried to configure and compile essentia, still get the same error.
`brew list` didn't show gaia.

**Comment by dbogdanov** [comment]
```
brew install gaia --HEAD
```

**Comment by penguin-penpen** [comment]
Tried again and I've installed essentia successfully, but in terminal it echoes
```
Python 2.7.9 (default, Feb 21 2016, 23:53:20)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import essentia
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named essentia
```

**Comment by dbogdanov** [comment]
First of all, did you solve you original problem or ```./waf configure --with-gaia``` still fails?
Once Essentia is installed, make sure you run a correct version of python installed from homebrew:
http://stackoverflow.com/a/26588821/603642

**Comment by penguin-penpen** [comment]
Let me specify the situation. I build the source code following the instruction and there's no error message, so I thought it was installed successfully. After that, I run `./waf configure --with-gaia` and there's 
```
Setting top to                           : /Users/yangyy/GitHub/VM/essentia-master
Setting out to                           : /Users/yangyy/GitHub/VM/essentia-master/build
→ configuring the project in /Users/yangyy/GitHub/VM/essentia-master
→ Building in release mode
Checking for 'g++' (c++ compiler)        : /usr/bin/g++
Checking for 'gcc' (c compiler)          : /usr/bin/gcc
Checking for program pkg-config          : /usr/local/bin/pkg-config
Checking for 'libavcodec' >= 55.34.1     : yes
Checking for 'libavformat'               : yes
Checking for 'libavutil'                 : yes
Checking for 'libavresample'             : yes
Checking for 'samplerate'                : yes
Checking for 'taglib' >= 1.9             : yes
Checking for 'yaml-0.1'                  : yes
/usr/local/Cellar/libyaml/0.1.6_1/include
Checking for 'fftw3f'                    : yes
Checking for 'gaia2'                     : yes

================================ CONFIGURATION SUMMARY ================================
- using FFTW for FFT

- fftw detected!
- FFmpeg / libav detected!
- libsamplerate (SRC) detected!
  The following algorithms will be included: ['MonoLoader', 'Resample', 'AudioWriter', 'EasyLoader', 'MonoWriter', 'EqloudLoader', 'AudioLoader']

- TagLib detected!
  The following algorithms will be included: ['MetadataReader']

- libyaml detected!
  The following algorithms will be included: ['YamlInput', 'YamlOutput']

- Gaia2 detected!
  The following algorithms will be included: ['GaiaTransform']

Building all the algorithms
Ignoring the following algorithms: IFFTA, IFFTK, FFTA, FFTK
Created algorithms registration file
=======================================================================================
'configure' finished successfully (0.748s)
```

It seemed to me that every thing's fine.
Then I run `./waf`
```
...
Waf: Leaving directory `/Users/yangyy/GitHub/VoiceMagician/essentia-master/build'
'build' finished successfully (2m40.919s)
```
No error message all the way.
Finally run `./waf install`
```
Waf: Leaving directory `/Users/yangyy/GitHub/VoiceMagician/essentia-master/build'
'install' finished successfully (0.541s)
```

Does that mean it is installed successfully? I'm sorry I didn't specify it clearly. Thanks for your patience!

**Comment by penguin-penpen** [comment]
OK. Finally I've successfully installed essentia. Thanks.

**Comment by dbogdanov** [comment]
You need to use ```--with-python``` flag when configuring the project to enable Python bindings. Installing then writes all required files to your ```/usr/local/``` folder so that Python can find them.
