### ISSUE TITLE
update official version from 2.1 beta2

### ISSUE THREAD

**Issue by fedorareis** [MTG/essentia#381]
I learned today while trying to get essentia set up on my computer that there are a number of issues with version 2.1 beta2. I figured I would use the official release since that is normally a good idea and all it brought me was sadness. As noted in some of the other bug reports such as #274 there are files that are missing in beta2. Also if someone is going through the whole setup now and installing dependencies they will most likely install ffmpeg 3.0 which beta2 does not support. For these reasons I believe that you should either update to a new official release that solves these issues (the current master doesn't have either issue) or put a note in the install instructions about known errors.

**Comment by dbogdanov** [comment]
We are about to release beta3 after few unit tests will be fixed. There is a [note to install the master branch](http://essentia.upf.edu/documentation/installing.html#compiling-essentia) in documentation as well.
