### ISSUE TITLE
Error compiling for Android

### ISSUE THREAD

**Issue by verkin** [MTG/essentia#384]
Hello Dmitry!

I would use 'essentia' for the development of a mobile application for Android.

I followed your instructions (I use Ubuntu 15.04):
https://github.com/MTG/essentia/blob/master/FAQ.md#cross-compiling-for-android
OR
I tried using the script _build_android.sh_

Nothing happens.

Execution result for
./waf configure --cross-compile-android --lightweight = --fft = KISS --ignore-algos = LPC --prefix = / Users / carthach / Dev / android / modules / essentia;

green @ green-ubuntu: ~ / essentia-master $ ./waf configure --cross-compile-android --lightweight = --fft = KISS --ignore-algos = LPC --prefix = / Users / carthach / Dev / android / modules / essentia;
Setting top to: / home / green / essentia-master
Setting out to: / home / green / essentia-master / build
→ configuring the project in / home / green / essentia-master
→ Building in release mode
→ Cross-compiling for Android ARM
Checking for program arm-linux-androideabi-gcc: / usr / bin / arm-linux-androideabi-gcc
Checking for program arm-linux-androideabi-g ++: / usr / bin / arm-linux-androideabi-g ++
Checking for program arm-linux-androideabi-ar: / usr / bin / arm-linux-androideabi-ar
Checking for 'g ++' (c ++ compiler): / usr / bin / arm-linux-androideabi-g ++
Checking for 'gcc' (c compiler): / usr / bin / arm-linux-androideabi-gcc

======================= Lightweight Mode: Ignoring ALL libraries except [ ''] ================ =======

================================ CONFIGURATION SUMMARY ================ ================
- Using KISS for FFT

- FFmpeg (or LibAv on debian / ubuntu) seems to be missing.
The following algorithms will be ignored: [ 'AudioLoader', 'MonoLoader', 'EqloudLoader', 'EasyLoader', 'MonoWriter', 'AudioWriter']

- Libsamplerate seems to be missing.
The following algorithms will be ignored: [ 'Resample', 'MonoLoader', 'EqloudLoader', 'EasyLoader']

Examples requiring FFmpeg / libav and libsamplerate will be ignored

- TagLib seems to be missing.
The following algorithms will be ignored: [ 'MetadataReader']

- Libyaml seems to be missing.
The following algorithms will be ignored: [ 'YamlInput', 'YamlOutput']

- Essentia is configured without Gaia2.
The following algorithms will be ignored: [ 'GaiaTransform']
Examples requiring Gaia2 will be ignored

Building all the algorithms
Ignoring the following algorithms: EasyLoader, Resample, YamlInput, MonoLoader, IFFTW, AudioWriter, FFTW, AudioLoader, IFFTA, MonoWriter, YamlOutput, MetadataReader, EqloudLoader, GaiaTransform, LPC, FFTA
Created algorithms registration file
================================================== =====================================
'Configure' finished successfully (0.183s)

**Execution result for:
./waf;**

green @ green-ubuntu: ~ / essentia-master $ ./waf
Waf: Entering directory `/ home / green / essentia-master / build '
→ building from / home / green / essentia-master
→ building from / home / green / essentia-master / src
Building all the algorithms
Ignoring the following algorithms: LPC, YamlInput, MonoLoader, IFFTW, Resample, FFTW, AudioWriter, EasyLoader, MonoWriter, MetadataReader, EqloudLoader, AudioLoader, GaiaTransform, YamlOutput, FFTA, IFFTA
Created algorithms registration file
[2/211] cxx: src / essentia / algorithm.cpp -> build / src / essentia / algorithm.cpp.1.o
[3/211] cxx: src / essentia / configurable.cpp -> build / src / essentia / configurable.cpp.1.o
In file included from ../src/essentia/algorithm.h:23:0,
from ../src/essentia/algorithm.cpp:20:
../src/essentia/types.h:23:15: fatal error: map: No such file or directory
compilation terminated.
../src/essentia/configurable.cpp:20:18: fatal error: memory: No such file or directory
compilation terminated.
Waf: Leaving directory `/ home / green / essentia-master / build '
Build failed
-> Task in 'essentia' failed (exit status 1):
{Task 3065949804L: cxx algorithm.cpp -> algorithm.cpp.1.o}
[ '/ Usr / bin / arm-linux-androideabi-g ++', '-pipe', '-Wall', '-O2', '-fPIC', '-pthread', '-w', '-fPIC' , '-fPIC', '-I / home / green / essentia-master / build / src', '-I / home / green / essentia-master / src', '-I / home / green / essentia-master / build / src / essentia ',' -I / home / green / essentia-master / src / essentia ',' -I / home / green / essentia-master / build / src / essentia / scheduler ',' -I / home / green / essentia-master / src / essentia / scheduler ',' -I / home / green / essentia-master / build / src / essentia / streaming ',' -I / home / green / essentia-master / src / essentia / streaming ',' -I / home / green / essentia-master / build / src / essentia / streaming / algorithms ',' -I / home / green / essentia-master / src / essentia / streaming / algorithms ',' - I / home / green / essentia-master / build / src / essentia / utils ',' -I / home / green / essentia-master / src / essentia / utils ',' -I / home / green / essentia-master / build / src / 3rdparty ',' -I / home / green / essentia-master / src / 3rdparty ',' -I / home / green / essentia-master / build / src / 3rdparty / spline ',' -I / home / green / essentia-master / src / 3rdparty / spline ',' -I / home / green / essentia-master / build / src / 3rdparty / kiss_fft130 ',' -I / home / green / essentia-master / src / 3rdparty / kiss_fft130 ',' -D__STDC_CONSTANT_MACROS ',' ../src/essentia/algorithm.cpp ',' -c ',' -o ',' src / essentia / algorithm.cpp.1.o ']
-> Task in 'essentia' failed (exit status 1):
{Task 3065949708L: cxx configurable.cpp -> configurable.cpp.1.o}
[ '/ Usr / bin / arm-linux-androideabi-g ++', '-pipe', '-Wall', '-O2', '-fPIC', '-pthread', '-w', '-fPIC' , '-fPIC', '-I / home / green / essentia-master / build / src', '-I / home / green / essentia-master / src', '-I / home / green / essentia-master / build / src / essentia ',' -I / home / green / essentia-master / src / essentia ',' -I / home / green / essentia-master / build / src / essentia / scheduler ',' -I / home / green / essentia-master / src / essentia / scheduler ',' -I / home / green / essentia-master / build / src / essentia / streaming ',' -I / home / green / essentia-master / src / essentia / streaming ',' -I / home / green / essentia-master / build / src / essentia / streaming / algorithms ',' -I / home / green / essentia-master / src / essentia / streaming / algorithms ',' - I / home / green / essentia-master / build / src / essentia / utils ',' -I / home / green / essentia-master / src / essentia / utils ',' -I / home / green / essentia-master / build / src / 3rdparty ',' -I / home / green / essentia-master / src / 3rdparty ',' -I / home / green / essentia-master / build / src / 3rdparty / spline ',' -I / home / green / essentia-master / src / 3rdparty / spline ',' -I / home / green / essentia-master / build / src / 3rdparty / kiss_fft130 ',' -I / home / green / essentia-master / src / 3rdparty / kiss_fft130 ',' -D__STDC_CONSTANT_MACROS ',' ../src/essentia/configurable.cpp ',' -c ',' -o ',' src / essentia / configurable.cpp.1.o ']

How to overcome this error?
What to do?
Maybe there are already compiled library for Android?

**Comment by dbogdanov** [comment]
@carthach

**Comment by carthach** [comment]
First things first, did you make yourself a toolchain:
http://developer.android.com/ndk/guides/standalone_toolchain.html
