### ISSUE TITLE
svm_models: v2.1-beta2 streaming_extractor_music_svm core dump / git version fine

### ISSUE THREAD

**Issue by Spiritdude** [MTG/essentia#388]
v2.1 beta2 on Ubuntu 15.10, I managed to `./waf install` but I don't know where the actual examples/streaming* reside after that, so I run them from build/src/examples/streaming_extractor_... direct. 

## v2.1-beta2
There is no svm_models in http://essentia.upf.edu/documentation/extractors/essentia-extractors-v2.1_beta2-linux-x86_64.tar.gz - and none is created with `./waf` or `./waf install` as stated in a previous (closed) issue.

I downloaded `svm_models` from http://essentia.upf.edu/documentation/svm_models/ which covers v2.1 beta1 (not beta2) and extracted in the source tree, but when I run 
```
% build/src/examples/streaming_extractor_music_svm ~/ownCloud2/Datasets/Semantics::Audio/piano-phase-music.txt piano-phase-music-svm.txt
adding SVM model: svm_models/genre_tzanetakis.history
adding SVM model: svm_models/genre_dortmund.history
adding SVM model: svm_models/genre_electronica.history
terminate called after throwing an instance of 'gaia2::GaiaException'
  what():  Could not open file: svm_models/genre_electronica.history
Abort (core dumped)
```

Solutions:
a) best provide svm_models_v2.1_beta2 download
b) include svm_models in the distribution (.tar.gz) you release

## git version (2016/03/27)
1) `./waf install` creates binaries in `/usr/local/bin/essentia_...`
2) `essentia_streaming_extractor_music` works
3) `essentia_streaming_extractor_music_svm` works too with svm_models-v2.1_beta1.tar.gz extracted and `svm_models` in the same dir where I ran the command.

Solution:
a)  include svm_models in the distribution

Very impressive results of the final `svm.txt` I've got with the git-version, will test it with a large sample set.

**Comment by Spiritdude** [comment]
I found the link for the svm_models-v2.1-beta1.tar.gz download but it's rather hidden in the documentation (http://essentia.upf.edu/documentation/streaming_extractor_music.html), it would be better to provide it in the Download page at http://essentia.upf.edu/download otherwise it's confusing if someone compiles and can't get essentia_extractor_music_svm to work and misses svm_models.

**Comment by dbogdanov** [comment]
Added the link to download page.

**Comment by wxy656** [comment]
then where is svm_models_v2.1_beta2 download-link,I encounter the same promble as you

**Comment by yyf** [comment]
Having similar issue: 
I had svm_models in the essentia-2.1_beta3 folder, and when I did 

`./essentia_streaming_extractor_music_svm /Users/someFolder/audio_samples/myMusic.mp3 /Users/someFolder/audio_samples\myMusic_svm_out.txt
`

I got this:
`adding SVM model: svm_models/danceability.history
libc++abi.dylib: terminating with uncaught exception of type gaia2::GaiaException: Could not open file: svm_models/danceability.history
Abort trap: 6`

Any suggestion or instruction to follow along?

Thanks
