### ISSUE TITLE
What to do after including the compiled code (libessentia.so) in Android

### ISSUE THREAD

**Issue by s1155030742** [MTG/essentia#393]
I follow instructions in FAQ, and the step as this post [](http://stackoverflow.com/questions/33882060/local-path-not-returning-the-path-to-current-directory-correctly)

I compiled the source code and put it in my android project,
now I have a in app/src/main/jni/arm64-v8a/libessentia.so.

And then I have no idea what to do next. Should I write a single function 
according to this [](http://essentia.upf.edu/documentation/howto_standard_extractor.html)
and compile it by ndk. 
And use it with my java code by providing JNI for that function?

**Comment by carthach** [comment]
Example project here in JUCE:
https://github.com/GiantSteps/eear/tree/master/eear-Mobile

**Comment by s1155030742** [comment]
Finally I have successfully build the project,
here is the reference: 
[](https://github.com/s1155030742/IndieLink_2.0)
