### ISSUE TITLE
Cross compile for Android fails

### ISSUE THREAD

**Issue by boggledekoog** [MTG/essentia#397]
Hi there,

I am currently running Linux Mint 17.3 (64bit) and I am trying to cross compile for Android.

I set up a standalone toolchain by using this script:
#!/bin/sh
export NDK='/home/jjj/dev/android-ndk'
./make-standalone-toolchain.sh --ndk-dir=$NDK --arch=arm --platform=android-15 --install-dir=/home/jjj/dev/toolchainin

Then I created the build script:

#!/usr/bin/env bash
export PATH=/home/jjj/dev/toolchainin/bin:$PATH;
./waf clean;
./waf configure --cross-compile-android --lightweight= --fft=KISS --prefix=/Users/jjj/dev/builds/essentia;
./waf;
./waf install;

**`./waf configure ...` finishes correctly:**

→ building from /home/jjj/dev/essentia-master
→ building from /home/jjj/dev/essentia-master/src
Building all the algorithms
Ignoring the following algorithms: YamlInput, MonoLoader, IFFTW, Resample, FFTW, AudioWriter, EasyLoader, MonoWriter, MetadataReader, EqloudLoader, AudioLoader, GaiaTransform, YamlOutput, FFTA, IFFTA
Created algorithms registration file
'clean' finished successfully (0.095s)
Setting top to                           : /home/jjj/dev/essentia-master 
Setting out to                           : /home/jjj/dev/essentia-master/build 
→ configuring the project in /home/jjj/dev/essentia-master
→ Building in release mode
→ Cross-compiling for Android ARM
Checking for program arm-linux-androideabi-gcc : /home/jjj/dev/toolchainin/bin/arm-linux-androideabi-gcc 
Checking for program arm-linux-androideabi-g++ : /home/jjj/dev/toolchainin/bin/arm-linux-androideabi-g++ 
Checking for program arm-linux-androideabi-ar  : /home/jjj/dev/toolchainin/bin/arm-linux-androideabi-ar 
Checking for 'g++' (c++ compiler)              : /home/jjj/dev/toolchainin/bin/arm-linux-androideabi-g++ 
Checking for 'gcc' (c compiler)                : /home/jjj/dev/toolchainin/bin/arm-linux-androideabi-gcc 

=======================Lightweight Mode : Ignoring ALL libraries except [''] =======================

================================ CONFIGURATION SUMMARY ================================
- using KISS for FFT

- FFmpeg (or LibAv on debian/ubuntu) seems to be missing.
  The following algorithms will be ignored: ['AudioLoader', 'MonoLoader', 'EqloudLoader', 'EasyLoader', 'MonoWriter', 'AudioWriter']

- libsamplerate seems to be missing.
  The following algorithms will be ignored: ['Resample', 'MonoLoader', 'EqloudLoader', 'EasyLoader']

  Examples requiring FFmpeg / libav and libsamplerate will be ignored

- TagLib seems to be missing.
  The following algorithms will be ignored: ['MetadataReader']

- libyaml seems to be missing.
  The following algorithms will be ignored: ['YamlInput', 'YamlOutput']

- Essentia is configured without Gaia2.
  The following algorithms will be ignored: ['GaiaTransform']
  Examples requiring Gaia2 will be ignored

Building all the algorithms
Ignoring the following algorithms: EasyLoader, Resample, YamlInput, MonoLoader, IFFTW, AudioWriter, FFTW, AudioLoader, IFFTA, MonoWriter, MetadataReader, EqloudLoader, GaiaTransform, YamlOutput, FFTA

Created algorithms registration file

'configure' finished successfully (0.158s)

**But then `./waf` fails:**

Waf: Entering directory `/home/jjj/dev/essentia-master/build'
→ building from /home/jjj/dev/essentia-master
→ building from /home/jjj/dev/essentia-master/src
Building all the algorithms
Ignoring the following algorithms: YamlInput, MonoLoader, IFFTW, Resample, FFTW, AudioWriter, EasyLoader, MonoWriter, MetadataReader, EqloudLoader, AudioLoader, GaiaTransform, YamlOutput, FFTA, IFFTA
Created algorithms registration file
[  1/224] cxx: src/essentia/algorithm.cpp -> build/src/essentia/algorithm.cpp.1.o
[  2/224] cxx: src/essentia/configurable.cpp -> build/src/essentia/configurable.cpp.1.o
Assembler messages:
Fatal error: invalid -march= option: `armv5te'
../src/essentia/algorithm.cpp:90:1: fatal error: error writing to -: Broken pipe
 } // namespace essentia
 ^
compilation terminated.
Assembler messages:
Fatal error: invalid -march= option: `armv5te'
../src/essentia/configurable.cpp:128:1: fatal error: error writing to -: Broken pipe
 } // namespace essentia
 ^
compilation terminated.
Waf: Leaving directory `/home/jjj/dev/essentia-master/build'
Build failed
 -> task in 'essentia' failed (exit status 1): 
	{task 140676881486864: cxx algorithm.cpp -> algorithm.cpp.1.o}
['/home/jjj/dev/toolchainin/bin/arm-linux-androideabi-g++', '-pipe', '-Wall', '-O2', '-fPIC', '-pthread', '-w', '-fPIC', '-fPIC', '-I/home/jjj/dev/essentia-master/build/src', '-I/home/jjj/dev/essentia-master/src', '-I/home/jjj/dev/essentia-master/build/src/essentia', '-I/home/jjj/dev/essentia-master/src/essentia', '-I/home/jjj/dev/essentia-master/build/src/essentia/scheduler', '-I/home/jjj/dev/essentia-master/src/essentia/scheduler', '-I/home/jjj/dev/essentia-master/build/src/essentia/streaming', '-I/home/jjj/dev/essentia-master/src/essentia/streaming', '-I/home/jjj/dev/essentia-master/build/src/essentia/streaming/algorithms', '-I/home/jjj/dev/essentia-master/src/essentia/streaming/algorithms', '-I/home/jjj/dev/essentia-master/build/src/essentia/utils', '-I/home/jjj/dev/essentia-master/src/essentia/utils', '-I/home/jjj/dev/essentia-master/build/src/3rdparty', '-I/home/jjj/dev/essentia-master/src/3rdparty', '-I/home/jjj/dev/essentia-master/build/src/3rdparty/spline', '-I/home/jjj/dev/essentia-master/src/3rdparty/spline', '-I/home/jjj/dev/essentia-master/build/src/3rdparty/kiss_fft130', '-I/home/jjj/dev/essentia-master/src/3rdparty/kiss_fft130', '-D__STDC_CONSTANT_MACROS', '../src/essentia/algorithm.cpp', '-c', '-o', 'src/essentia/algorithm.cpp.1.o']
 -> task in 'essentia' failed (exit status 1): 
	{task 140676881486736: cxx configurable.cpp -> configurable.cpp.1.o}
['/home/jjj/dev/toolchainin/bin/arm-linux-androideabi-g++', '-pipe', '-Wall', '-O2', '-fPIC', '-pthread', '-w', '-fPIC', '-fPIC', '-I/home/jjj/dev/essentia-master/build/src', '-I/home/jjj/dev/essentia-master/src', '-I/home/jjj/dev/essentia-master/build/src/essentia', '-I/home/jjj/dev/essentia-master/src/essentia', '-I/home/jjj/dev/essentia-master/build/src/essentia/scheduler', '-I/home/jjj/dev/essentia-master/src/essentia/scheduler', '-I/home/jjj/dev/essentia-master/build/src/essentia/streaming', '-I/home/jjj/dev/essentia-master/src/essentia/streaming', '-I/home/jjj/dev/essentia-master/build/src/essentia/streaming/algorithms', '-I/home/jjj/dev/essentia-master/src/essentia/streaming/algorithms', '-I/home/jjj/dev/essentia-master/build/src/essentia/utils', '-I/home/jjj/dev/essentia-master/src/essentia/utils', '-I/home/jjj/dev/essentia-master/build/src/3rdparty', '-I/home/jjj/dev/essentia-master/src/3rdparty', '-I/home/jjj/dev/essentia-master/build/src/3rdparty/spline', '-I/home/jjj/dev/essentia-master/src/3rdparty/spline', '-I/home/jjj/dev/essentia-master/build/src/3rdparty/kiss_fft130', '-I/home/jjj/dev/essentia-master/src/3rdparty/kiss_fft130', '-D__STDC_CONSTANT_MACROS', '../src/essentia/configurable.cpp', '-c', '-o', 'src/essentia/configurable.cpp.1.o']
Waf: Entering directory `/home/jjj/dev/essentia-master/build'
→ building from /home/jjj/dev/essentia-master
→ building from /home/jjj/dev/essentia-master/src
Building all the algorithms
Ignoring the following algorithms: YamlInput, MonoLoader, IFFTW, Resample, FFTW, AudioWriter, EasyLoader, MonoWriter, MetadataReader, EqloudLoader, AudioLoader, GaiaTransform, YamlOutput, FFTA, IFFTA
Created algorithms registration file
Could not find '../build/essentia.pc' in /home/jjj/dev/essentia-master/src

I am quite new to cross-compiling, so I'd be glad if you could help me out here.

Thanks

**Comment by dbogdanov** [comment]
@carthach

**Comment by boggledekoog** [comment]
Okay, I was able to solve it, someone on stackoverflow had the same problem:
http://stackoverflow.com/questions/10770296/error-while-compiling-android-jni-sample-invalid-march-option-armv5te
I just created that link with 
`ln -s path-to-toolchain/bin/arm-linux-androideabi-as path-to-toolchain/bin/as`
 and then it worked.
