### ISSUE TITLE
Problem in compiling essentia with python binding.

### ISSUE THREAD

**Issue by prashant2018** [MTG/essentia#409]
Please help. After configuring essentia when i am trying to compile usi ./waf it gives this error 

[ 50/283] cxx: src/algorithms/standard/noiseadder.cpp -> build/src/algorithms/standard/noiseadder.cpp.1.o
In file included from /usr/local/include/gaia2/parser/filter.h:24:0,
                 from /usr/local/include/gaia2/searchspace.h:26,
                 from /usr/local/include/gaia2/searchspacepool.h:24,
                 from /usr/local/include/gaia2/view.h:27,
                 from /usr/local/include/gaia2/convert.h:27,
                 from ../src/algorithms/highlevel/gaiatransform.cpp:23:
/usr/local/include/gaia2/parser/parsertypes.h:24:19: fatal error: point.h: No such file or directory
 #include "point.h"
                   ^
compilation terminated.
Waf: Leaving directory `/home/prashant/Documents/essentia-master/build'
Build failed
 -> task in 'essentia' failed (exit status 1): 
	{task 139624129974032: cxx gaiatransform.cpp -> gaiatransform.cpp.1.o}
['/usr/bin/g++', '-pipe', '-Wall', '-msse', '-msse2', '-mfpmath=sse', '-O2', '-fPIC', '-pthread', '-fPIC', '-I/home/prashant/Documents/essentia-master/build/src', '-I/home/prashant/Documents/essentia-master/src', '-I/home/prashant/Documents/essentia-master/build/src/essentia', '-I/home/prashant/Documents/essentia-master/src/essentia', '-I/home/prashant/Documents/essentia-master/build/src/essentia/scheduler', '-I/home/prashant/Documents/essentia-master/src/essentia/scheduler', '-I/home/prashant/Documents/essentia-master/build/src/essentia/streaming', '-I/home/prashant/Documents/essentia-master/src/essentia/streaming', '-I/home/prashant/Documents/essentia-master/build/src/essentia/streaming/algorithms', '-I/home/prashant/Documents/essentia-master/src/essentia/streaming/algorithms', '-I/home/prashant/Documents/essentia-master/build/src/essentia/utils', '-I/home/prashant/Documents/essentia-master/src/essentia/utils', '-I/home/prashant/Documents/essentia-master/build/src/3rdparty', '-I/home/prashant/Documents/essentia-master/src/3rdparty', '-I/home/prashant/Documents/essentia-master/build/src/3rdparty/spline', '-I/home/prashant/Documents/essentia-master/src/3rdparty/spline', '-I/home/prashant/Documents/essentia-master/build/src/3rdparty/vamp-plugin-sdk-2.4', '-I/home/prashant/Documents/essentia-master/src/3rdparty/vamp-plugin-sdk-2.4', '-I/usr/include/taglib', '-I/usr/local/include', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-DHAVE_AVFORMAT=1', '-DHAVE_AVUTIL=1', '-DHAVE_AVRESAMPLE=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_TAGLIB=1', '-DHAVE_YAML=1', '-DHAVE_FFTW=1', '-DHAVE_GAIA2=1', '-D__STDC_CONSTANT_MACROS', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYTHON_H=1', '../src/algorithms/highlevel/gaiatransform.cpp', '-c', '-o', 'src/algorithms/highlevel/gaiatransform.cpp.1.o']

**Comment by trostli** [comment]
+1 Getting the same error

**Comment by dbogdanov** [comment]
Build with the latest gaia from master branch.

**Comment by prashant2018** [comment]
Thanks already did. Working now
