### ISSUE TITLE
Two different warnings

### ISSUE THREAD

**Issue by ESchae** [MTG/essentia#410]
Hello,

trying to build my own feature extractor 
[feature_extractor.txt](https://github.com/MTG/essentia/files/276251/feature_extractor.txt)

I get two warnings which I can not handle:

1.) [ WARNING  ] ARGLLLLLL
I get this as soon as I try to import anything from essentia.streaming, e.g. 
`from essentia.streaming import *` 
but also for any Algorithm instead of *. It seems to stem from SourceBase::attachProxy in sourcebase.cpp (https://github.com/MTG/essentia/blob/51793a357d5fa4a18a4b487591532ee737c0aad6/src/essentia/streaming/sourcebase.cpp)

2.) [ WARNING  ] AudioLoader: using depricated audioconvert and manually converting planar format to interleaved
I get this for every .mp3 audiofile

Using essentia-2.1_beta2_fixes, streaming mode in python, Ubuntu 14.04

**Comment by dbogdanov** [comment]
Closing this as this issues are fixed in master branch
