### ISSUE TITLE
Example program - memory leak found by Valgrind

### ISSUE THREAD

**Issue by vasicek58** [MTG/essentia#418]
Hello, 

I have just installed the Essentia 2.1 beta2 and when I compiled and ran the sample program _standard_mfcc.cpp_ with Valgrind it showed that over 44 MB memory was lost, which is quite similar to the size of the wave file I analyzed, although no errors were found. Do you know what might be the problem?

Many thanks!

This is the output I got from Valgrind (the size of the wav file is 44,190,464 B):

==12533== Memcheck, a memory error detector
==12533== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==12533== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==12533== Command: ./std_mfcc song.wav output.txt
==12533== 
-------- connecting algos ---------
-------- start processing song.wav --------
-------- writing results to file output.txt ---------
==12533== 
==12533== HEAP SUMMARY:
==12533==     in use at exit: 44,276,152 bytes in 10,790 blocks
==12533==   total heap usage: 267,775 allocs, 256,985 frees, 280,702,381 bytes allocated
==12533== 
==12533== LEAK SUMMARY:
==12533==    definitely lost: 44,251,528 bytes in 10,784 blocks
==12533==    indirectly lost: 0 bytes in 0 blocks
==12533==      possibly lost: 24,624 bytes in 6 blocks
==12533==    still reachable: 0 bytes in 0 blocks
==12533==         suppressed: 0 bytes in 0 blocks
==12533== Rerun with --leak-check=full to see details of leaked memory
==12533== 
==12533== For counts of detected and suppressed errors, rerun with: -v
==12533== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by dbogdanov** [comment]
Install from master branch, there was a memory leak that is fixed in master.
