### ISSUE TITLE
test failed，how can i solve it

### ISSUE THREAD

**Issue by wxy656** [MTG/essentia#419]
[  FAILED  ] 7 tests, listed below:
[  FAILED  ] AudioLoader.SimpleLoad
[  FAILED  ] AudioLoader.SampleFormatConversion
[  FAILED  ] Network.SimpleVisibleNetwork
[  FAILED  ] Network.ExecutionNetworkWithComposite
[  FAILED  ] Scheduler.SourceProxyFork
[  FAILED  ] TreeTraversal.DepthFirstMap
[  FAILED  ] TreeTraversal.DepthFirstSearch

**Comment by alastair** [comment]
Duplicate of #413
