### ISSUE TITLE
error installing essentia on ubuntu 14.04

### ISSUE THREAD

**Issue by great-thoughts** [MTG/essentia#420]
I was trying to install essential on ubuntu 14.04 However I get this error:
```
./waf configure --mode=release --build-static --with-python --with-cpptests --with-examples --with-vamp --with-gaia
waf: error: no such option: --build-static
```

**Comment by alastair** [comment]
Which version of essentia are you compiling? The latest master from git has the `--build-static` option, but 2.1beta2 does not. Remove this option for older versions of essentia

**Comment by alastair** [comment]
no response, closing
