### ISSUE TITLE
 remove humming noise

### ISSUE THREAD

**Issue by great-thoughts** [MTG/essentia#423]
Can you please advise on which command to use to remove humming noise from audio recordings of speech?

**Comment by dbogdanov** [comment]
Essentia does not provide this functionality, but you can do some basic [high-pass](http://essentia.upf.edu/documentation/reference/std_HighPass.html)/[low-pass](http://essentia.upf.edu/documentation/reference/std_LowPass.html) filtering or suppress some of the magnitudes in the computed spectrum to reduce some noise . You can check for other libraries for noise reduction / speech enhancement too.

http://cmusphinx.sourceforge.net/wiki/faq
http://dsp.stackexchange.com/questions/17317/what-is-best-practice-to-remove-static-noise
http://superuser.com/questions/733061/reduce-background-noise-and-optimize-the-speech-from-an-audio-clip-using-ffmpeg

Let us know if you find out useful algorithms that could be implemented in Essentia.
