### ISSUE TITLE
Error when running streaming_extractor_music

### ISSUE THREAD

**Issue by bd117** [MTG/essentia#428]
Hello,

I appreciate if somebody can give me some clues on my problem. 

I hope to extract mood/emotion infomation from a mp3 file and I typed  ./streaming_extractor_music input output profile on Linux command line. profile.yml is the example profile file provided by http://essentia.upf.edu/documentation/streaming_extractor_music.html.
It displays as below:
processing step: compute aggregation
processing step: SVM models
adding SVM model: svm_models/genre_tzanetakis.history
Identifier GaiaTransform not found in registry...

Anybody can provide any clues? Thanks.

**Comment by dbogdanov** [comment]
Have you compiled streaming_extractor_music with gaia?

**Comment by bd117** [comment]
Streaming_extractor_music  works now. But I still have problems
just configuring gaia...

2016-06-28 6:15 GMT-04:00 Dmitry Bogdanov <notifications@github.com>:

**Comment by techscientist** [comment]
I'm getting the same issue. Any updates?

**Comment by alastair** [comment]
Closing because original author said that it was now working. If anyone else has specific problems please open a new issue.
