### ISSUE TITLE
Error when compiling streaming_extractor_music_svm.cpp

### ISSUE THREAD

**Issue by bd117** [MTG/essentia#429]
Hello,
I have some problems on compiling streaming_extractor_music_svm.cpp as below:
g++ -pipe -Wall -O2 -fPIC -I/usr/local/include/essentia/ -I/usr/local/include/essentia/scheduler/ -I/usr/local/include/essentia/streaming/ -I/usr/local/include/essentia/utils -I/usr/include/taglib -I/usr/local/include/gaia2 -I/usr/include/qt4 -I/usr/include/qt4/QtCore -D_STDC_CONSTANT_MACROS streaming_extractor_music_svm.cpp -o streaming_extractor_music_svm -L/usr/local/lib -lessentia -lfftw3 -lyaml -lavcodec -lavformat -lavutil -lsamplerate -ltag -lfftw3f -lQtCore -lgaia2  
/usr/bin/ld: /usr/local/lib/libgaia2.a(yamlcpp.cpp.1.o): undefined reference to symbol 'yaml_sequence_end_event_initialize'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libyaml.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
I guess I need to modify some dependencies..? Does anybody have some ideas?

**Comment by alastair** [comment]
Do you still have a problem here? I don't recognise the error message, but from searching, it seems that perhaps `-lyaml` has to be after `-lgaia2` in the compile line (http://stackoverflow.com/questions/19901934/strange-linking-error-dso-missing-from-command-line)

However, I'm not sure of the specific conditions which may cause this to be a problem. For example, in acousticbrainz we automatically perform this exact compilation and don't have problems with it:
https://github.com/metabrainz/acousticbrainz-server/blob/3b9f087f5e3945cc11c790b25cef73fdf78576c3/admin/install_hl_extractor.sh
