### ISSUE TITLE
compare fft between noise and speech

### ISSUE THREAD

**Issue by great-thoughts** [MTG/essentia#432]
I want to compare between the fft of two waveforms. one that belongs to noise and the other belongs to speech. I think I need some kind of normalization so that I can compare the two fft. I am not sure how to do this?

**Comment by dbogdanov** [comment]
The question is too broad. The most suitable way to classify speech from noise is to use MFCC because it captures structure of spectrum and speech has a clear structure unlike noise. You can try other spectral features  too.
