### ISSUE TITLE
ImportError: No module named essentia

### ISSUE THREAD

**Issue by yyf** [MTG/essentia#44]
$ python
Python 2.7.5 |Anaconda 1.8.0 (x86_64)| (default, Oct 24 2013, 07:02:20) 
[GCC 4.0.1 (Apple Inc. build 5493)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import essentia
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named essentia

I had essentia compiled but in python I still got importError, how to check if essentia is in my pythonpath (Python 2.7.5)? (I on 10.8 and have python 2.6 and 2.7)

**Comment by sannawag** [comment]
If you installed essentia using [homebrew ](http://essentia.upf.edu/documentation/installing.html), and then type in the Terminal:

brew info essentia 

you will find the following instructions, which fixed the problem for me:

Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/apple/.local/lib/python2.7/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/apple/.local/lib/python2.7/site-packages/homebrew.pth
