### ISSUE TITLE
Unable to update PKG_CONFIG_PATH to allow configure to find libavcodec/libavformat/libavutil/libswresample/fftw3f

### ISSUE THREAD

**Issue by afriendcalledben** [MTG/essentia#443]
Hi, 

I'm trying to compile the streaming_extractor_music for Windows with Gaia support. 

I've been trying the last few days but have hit a wall.
I did a fresh install of Ubuntu 16.04 and carefully added all the required packages as per the instructions.
I've managed to compile Gaia but when trying to configure the build of Essentia, I hit a snag.
I've installed all the required dependencies and I can see them all sitting in /usr/local/lib/pkgconfig.
I've attempted to set PKG_CONFIG_PATH to point at these and have confirmed that it appears to do so by using pkg-config --variable pc_path pkg-config.
However, this build log reveals that it appears to be looking in the incorrect places despite this. This build log is below:

Checking for program pkg-config
/usr/bin/pkg-config
find program=['pkg-config'] paths=[**'/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/usr/games', '/usr/local/games', '/snap/bin'**] var='PKGCONFIG' -> '/usr/bin/pkg-config'
----------------------------------------
Checking for 'libavcodec' >= 53.25.0
['/usr/bin/pkg-config', 'libavcodec >= 53.25.0', '--cflags', '--libs', '--modversion', 'libavcodec']
err: Ignoring incompatible output option "--modversion"
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found

not found
from /home/afriendcalledben/Desktop/essentia-2.1_beta2/src: The configuration failed
----------------------------------------
Checking for 'libavformat'
['/usr/bin/pkg-config', '--cflags', '--libs', '--modversion', 'libavformat']
err: Ignoring incompatible output option "--modversion"
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found

not found
from /home/afriendcalledben/Desktop/essentia-2.1_beta2/src: The configuration failed
----------------------------------------
Checking for 'libavutil'
['/usr/bin/pkg-config', '--cflags', '--libs', '--modversion', 'libavutil']
err: Ignoring incompatible output option "--modversion"
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found

not found
from /home/afriendcalledben/Desktop/essentia-2.1_beta2/src: The configuration failed
----------------------------------------
Checking for 'libswresample'
['/usr/bin/pkg-config', '--cflags', '--libs', '--modversion', 'libswresample']
err: Ignoring incompatible output option "--modversion"
Package libswresample was not found in the pkg-config search path.
Perhaps you should add the directory containing `libswresample.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswresample' found

not found
from /home/afriendcalledben/Desktop/essentia-2.1_beta2/src: The configuration failed
----------------------------------------
Checking for 'fftw3f'
['/usr/bin/pkg-config', '--cflags', '--libs', '--modversion', 'fftw3f']
err: Ignoring incompatible output option "--modversion"
Package fftw3f was not found in the pkg-config search path.
Perhaps you should add the directory containing `fftw3f.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fftw3f' found

not found
from /home/afriendcalledben/Desktop/essentia-2.1_beta2/src: The configuration failed

Do I need to alter the waf script somehow to change that paths array to include /usr/bin/local/pkg-config?

Any help would be really appreciated.

Thanks,

Ben

**Comment by dbogdanov** [comment]
Make sure you have actually updated the variable.
You can use export command before runing waf configure: 
```
export PKG_CONFIG_PATH=... ```
```

**Comment by afriendcalledben** [comment]
Hi, 

I did that just prior.

In Terminal:
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
echo $PKG_CONFIG_PATH _(Returns /usr/local/lib/pkgconfig)_
./waf configure --with-gaia --with-static-examples

Get the same log saying:
Checking for program pkg-config
/usr/bin/pkg-config
find program=['pkg-config'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/usr/games', '/usr/local/games', '/snap/bin'] var='PKGCONFIG' -> '/usr/bin/pkg-config'

Apologies, I'm fairly new to dealing with packages. Is it possible there are two pkg-config instances and Terminal is pointing at one but the ./waf configure utilises another? Sorry if that's a silly question.

Thanks for your response.

Ben

**Comment by dbogdanov** [comment]
Do not use ```--with-static-examples``` flag unless you need static builds. If you are having this flag, the build  script searches for packages in [another place](https://github.com/MTG/essentia/blob/master/FAQ.md#linuxosx-static-builds) (```packaging/debian_3rdparty/```) and you are supposed to build static dependencies in that folder.

**Comment by afriendcalledben** [comment]
Hi Dmitry, 

Sorry I'm trying to create the static builds for Windows with Gaia support - specifically streaming_extractor_music.exe. Is that something that is definitely currently achievable? I've followed your link above and got as far as building the dependencies for win32 when I noticed it doesn't have build_gaia.sh and build_qt.sh like the debian_3rdparty does. 

Is there a way to add those dependencies to the win32_3rd party so that I can configure and build Essentia for Windows specifically for the static builds? 

Thanks again for your help. It's really appreciated.

Ben

**Comment by dbogdanov** [comment]
Static builds can be easily done without gaia. However, building with Gaia was complicated due to dependency on Qt , therefore gaia is not included when using ```--with-static-examples``` option. You can try to make such a build yourself and let us know. Getting rid of dependency on Qt is in our wish-list and will be the best solution in the future.

**Comment by afriendcalledben** [comment]
Hi Dmitry,

Thanks again for your response. 

When you say "building with Gaia was complicated due to dependency on Qt , therefore gaia is not included when using --with-static-examples option", are you only talking about cross compiling static builds for Windows?

Or do you mean that building with Gaia for static builds was complicated across all platforms - Windows, Linux and OSX and therefore has not been done yet? If it's more easily achievable to compile a static build of Essentia for Linux with Gaia, I'll go down that route.

**Comment by afriendcalledben** [comment]
Hi Dmitry,

I've gone a different route and have successfully compiled Essentia with Gaia support for my needs. Thank you for your help.

Ben
