### ISSUE TITLE
import essentia fail

### ISSUE THREAD

**Issue by MingAnLin** [MTG/essentia#456]
Hi,i had install Essentia (with ffmpeg 3.1.2,ubuntu 14.04).But when i import essentia,i got a error. Here is the error:
`Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/usr/local/lib/python2.7/dist-packages/essentia/__init__.py", line 1, in <module>

    import _essentia

ImportError: /usr/local/lib/libessentia.so: undefined symbol: av_frame_free

`
Please help me. Thanks!
MingAn

**Comment by dbogdanov** [comment]
Install Essentia from master branch.
