### ISSUE TITLE
Essentia Installation for Mac

### ISSUE THREAD

**Issue by nimahamidi** [MTG/essentia#465]
I'm trying to install Essentia and I'm getting the following error: 
Error: You must `brew link python` before mtg/essentia/essentia can be installed
I do that but still nothing. I was wondering if Essentia is just supported by specific Mac OS X. (I'm using OS X EL Capitan, Python 2.7)
Thanks

**Comment by dbogdanov** [comment]
What's your exact error? Try ```brew doctor```. A typical error would be that you are using system python instead the one installed by brew. You can solve that by adding homebrew directory [on the top of the PATH](http://docs.python-guide.org/en/latest/starting/install/osx/) environmental variable.
