### ISSUE TITLE
"_avcodec_alloc_frame" issue after installing ffmpeg

### ISSUE THREAD

**Issue by yyf** [MTG/essentia#467]
I had essentia library (v2.1 beta 2) working fine in my Xcode C++ project until installing ffmpeg (3.1.2). Did a quick search in previous posts but didn't find similar issues. Would recompiling the latest essentia resolve this issue? Here is the log. Thanks. 

Undefined symbols for architecture x86_64:
  "_avcodec_alloc_frame", referenced from:
      essentia::streaming::AudioLoader::openAudioFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libessentia.a(audioloader.cpp.1.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dbogdanov** [comment]
Use master branch instead of beta2.

**Comment by yyf** [comment]
Tried install the master branch, but got the numpy issue again (ImportError: No module named numpy). Noticed this warning when I ran ./waf configure: 

python executable '/usr/local/bin/python' differs from system '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python'

Any suggestion how to proceed? Thanks.

**Comment by dbogdanov** [comment]
```export PATH=/usr/local/bin:/usr/local/sbin:$PATH```
http://docs.python-guide.org/en/latest/starting/install/osx/
