### ISSUE TITLE
libc++abi.dylib: terminate called throwing an exception?

### ISSUE THREAD

**Issue by yyf** [MTG/essentia#47]
>>> MonoWriter(filename = 'onsets_complex.mp3', format = 'mp3')(marker(audio))
libc++abi.dylib: terminate called throwing an exception
Abort trap: 6

I was following this example under python 2.7.6:
http://essentia.upf.edu/documentation/_downloads/onsetdetection_example.py

any idea what might be the cause? thx

**Comment by dbogdanov** [comment]
Cannot reproduce this issue with the latest master.
