### ISSUE TITLE
Implement Chromaprint and Echoprint fingerprinting algorithm

### ISSUE THREAD

**Issue by dbogdanov** [MTG/essentia#474]
Re-use [Chromaprint](https://acoustid.org/chromaprint) library.
https://oxygene.sk/2011/01/how-does-chromaprint-work/

**Comment by alastair** [comment]
It might be interesting to implement echoprint, too

**Comment by dbogdanov** [comment]
Correct, we should have both.

**Comment by dbogdanov** [comment]
@alastair Is echoprint still relevant? In this case let's open a separate issue.
