### ISSUE TITLE
Implement 'htk' approach for MelBands and MFCC

### ISSUE THREAD

**Issue by georgid** [MTG/essentia#476]
In literature there are two common MFCCs  'standards' differring in some parameters and the mel-scale computation itself:  the slaney way (currently in `https://github.com/MTG/essentia/blob/efce862f6c12870277542c665c7af29fcbc75a09/src/algorithms/spectral/mfcc.cpp`)  and the htk way ( chapter 5.4 from [htk book](http://www.dsic.upv.es/docs/posgrado/20/RES/materialesDocentes/alejandroViewgraphs/htkbook.pdf)).    

see
http://www.ee.columbia.edu/ln/rosa/matlab/rastamat/mfccs.html
and 
http://artax.karlin.mff.cuni.cz/r-help/library/tuneR/html/melfcc.html

**Comment by georgid** [comment]
One can divide the extraction in two steps: 
1) filterbank bins = log( mel scale (magn spectrum)) 
2) dct(filterbank) 
To reproduce the first step one can do in htk's config file 
TARGETKIND = FBANK

**Comment by georgid** [comment]
NOTE also that 2) step in htk can be done:
.FBANK file as input and change config to  
SOURCEKIND = ANON
TARGETKIND = MFCC

**Comment by georgid** [comment]
add parameter to support DCT type III (used by htk) 
and a paramter to add optional liftering after DCT.

**Comment by dbogdanov** [comment]
This requires implementing DCT type III in [DCT algorithm](https://github.com/MTG/essentia/blob/master/src/algorithms/standard/dct.cpp). We can create a separate issue for that. 

What is the optional filtering?

**Comment by georgid** [comment]
I created a new issue for the DCT https://github.com/MTG/essentia/issues/507

**Comment by georgid** [comment]
To reproduce the htk type of mfcc extraction see: 
https://github.com/georgid/mfcc-htk-an-librosa/blob/master/extract_mfcc_the_htk_way.ipynb

**Comment by dbogdanov** [comment]
@georgid Add this python code to tutorials (src/examples/tutorial).
