### ISSUE TITLE
GaiaTransfrom not found in registry

### ISSUE THREAD

**Issue by knockyouout** [MTG/essentia#478]
Hello,

I have compiled and installed first Gaia then Essentia library to my Ubuntu 16.04. I want to use the out of box streaming_extractor_music executable. When I run streaming_extractor_music without any profile I get no problem and a nice output. 

However, when I create a profile file that includes:
highlevel:
    compute: 1
    svm_models: ['svm_models/genre_tzanetakis.history', 'svm_models/mood_sad.history']

I get GaiaTransform not found in the registry error when it processes the high level svm models. 

Any help will be appreciated.

**Comment by alastair** [comment]
This happens when you do not configure essentia to use gaia. Did you use the `--with-gaia` option when configuring essentia?

**Comment by knockyouout** [comment]
I actually did configured essentia to use gaia before installation. 

To be on the safe side, how can I configure essentia again to use gaia?

**Comment by alastair** [comment]
Please tell us what command you used to configure essentia, and also attach the `build/config.log` file after you have run `./waf configure`

**Comment by knockyouout** [comment]
I executed the command: 

./waf configure --mode=release --build-static --with-python --with-cpptests --with-examples --with-vamp --with-gaia


[config.log.zip](https://github.com/MTG/essentia/files/505732/config.log.zip)

**Comment by alastair** [comment]
We don't support building static builds which include gaia, sorry.
Remove the `--build-static` flag and it should work.

Do you have a specific need to require a static build?

**Comment by knockyouout** [comment]
No, I build it static because it is stated that way in the installation instructions.

**Comment by alastair** [comment]
OK, thanks. We'll update the instructions to make this more clear.

**Comment by knockyouout** [comment]
I installed essentia again with new configurations. It did not work. I guess it because I have to delete essentia first?

**Comment by alastair** [comment]
Yes, you may have to uninstall and reinstall essentia. Are you getting the same error (GaiaTransform not found in the registry) when you try and run it?

What is the output of 
`ldd streaming_extractor_music`
and
`ldd /usr/local/lib/essentia.so`

**Comment by knockyouout** [comment]
I will post my output when I reinstall essentia. Thanks a lot for your help.

**Comment by knockyouout** [comment]
I reinstalled gaia and after essentia after uninstalling both of them. However, I get the same error. GaiaTransform not found in the registry. 

Any suggestions?

**Comment by alastair** [comment]
What are the outputs of the two commands I said?

**Comment by knockyouout** [comment]
I didnt find ldd essentia.so but there is libessentia.so . I tried with libessentia.so. Did mean libessentia.so? I am sharing the outputs
Thank you

baturay@ubuntu:~/Downloads$ ldd streaming_extractor_music
    not a dynamic executable

baturay@ubuntu:/usr/local/lib$ ldd libessentia.so
    linux-vdso.so.1 =>  (0x00007ffd6e3ce000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7085366000)
    libfftw3f.so.3 => /usr/lib/x86_64-linux-gnu/libfftw3f.so.3 (0x00007f7084f5b000)
    libavformat-ffmpeg.so.56 => /usr/lib/x86_64-linux-gnu/libavformat-ffmpeg.so.56 (0x00007f7084b5d000)
    libavcodec-ffmpeg.so.56 => /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56 (0x00007f7083733000)
    libavutil-ffmpeg.so.54 => /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54 (0x00007f70834c4000)
    libavresample-ffmpeg.so.2 => /usr/lib/x86_64-linux-gnu/libavresample-ffmpeg.so.2 (0x00007f70832a1000)
    libsamplerate.so.0 => /usr/lib/x86_64-linux-gnu/libsamplerate.so.0 (0x00007f7082f35000)
    libtag.so.1 => /usr/lib/x86_64-linux-gnu/libtag.so.1 (0x00007f7082c62000)
    libyaml-0.so.2 => /usr/lib/x86_64-linux-gnu/libyaml-0.so.2 (0x00007f7082a42000)
    libQtCore.so.4 => /usr/lib/x86_64-linux-gnu/libQtCore.so.4 (0x00007f708254f000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f70821cd000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7081ec3000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7081cad000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f70818e4000)
    /lib64/ld-linux-x86-64.so.2 (0x00005555ac526000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f70816df000)
    libssh-gcrypt.so.4 => /usr/lib/x86_64-linux-gnu/libssh-gcrypt.so.4 (0x00007f7081496000)
    librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f708127a000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f708105f000)
    libmodplug.so.1 => /usr/lib/x86_64-linux-gnu/libmodplug.so.1 (0x00007f7080cd4000)
    libgme.so.0 => /usr/lib/x86_64-linux-gnu/libgme.so.0 (0x00007f7080a86000)
    libbluray.so.1 => /usr/lib/x86_64-linux-gnu/libbluray.so.1 (0x00007f708083c000)
    libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f708050c000)
    libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f70802fc000)
    libswresample-ffmpeg.so.1 => /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1 (0x00007f70800df000)
    libva.so.1 => /usr/lib/x86_64-linux-gnu/libva.so.1 (0x00007f707fec3000)
    libzvbi.so.0 => /usr/lib/x86_64-linux-gnu/libzvbi.so.0 (0x00007f707fc38000)
    libxvidcore.so.4 => /usr/lib/x86_64-linux-gnu/libxvidcore.so.4 (0x00007f707f923000)
    libx265.so.79 => /usr/lib/x86_64-linux-gnu/libx265.so.79 (0x00007f707ed04000)
    libx264.so.148 => /usr/lib/x86_64-linux-gnu/libx264.so.148 (0x00007f707e960000)
    libwebp.so.5 => /usr/lib/x86_64-linux-gnu/libwebp.so.5 (0x00007f707e703000)
    libwavpack.so.1 => /usr/lib/x86_64-linux-gnu/libwavpack.so.1 (0x00007f707e4da000)
    libvpx.so.3 => /usr/lib/x86_64-linux-gnu/libvpx.so.3 (0x00007f707e0b6000)
    libvorbisenc.so.2 => /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007f707de0c000)
    libvorbis.so.0 => /usr/lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007f707dbe0000)
    libtwolame.so.0 => /usr/lib/x86_64-linux-gnu/libtwolame.so.0 (0x00007f707d9bd000)
    libtheoraenc.so.1 => /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1 (0x00007f707d77d000)
    libtheoradec.so.1 => /usr/lib/x86_64-linux-gnu/libtheoradec.so.1 (0x00007f707d563000)
    libspeex.so.1 => /usr/lib/x86_64-linux-gnu/libspeex.so.1 (0x00007f707d34a000)
    libsnappy.so.1 => /usr/lib/x86_64-linux-gnu/libsnappy.so.1 (0x00007f707d141000)
    libshine.so.3 => /usr/lib/x86_64-linux-gnu/libshine.so.3 (0x00007f707cf34000)
    libschroedinger-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0 (0x00007f707cc5f000)
    libopus.so.0 => /usr/lib/x86_64-linux-gnu/libopus.so.0 (0x00007f707ca14000)
    libopenjpeg.so.5 => /usr/lib/x86_64-linux-gnu/libopenjpeg.so.5 (0x00007f707c7f1000)
    libmp3lame.so.0 => /usr/lib/x86_64-linux-gnu/libmp3lame.so.0 (0x00007f707c57c000)
    libgsm.so.1 => /usr/lib/x86_64-linux-gnu/libgsm.so.1 (0x00007f707c36d000)
    libcrystalhd.so.3 => /usr/lib/x86_64-linux-gnu/libcrystalhd.so.3 (0x00007f707c152000)
    liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f707bf30000)
    libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f707bc1e000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f707ba16000)
    libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f707b734000)
    libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f707b4ea000)
    libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f707b2b7000)
    libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f707b080000)
    libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f707ae00000)
    libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f707aa46000)
    libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f707a802000)
    libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f707a558000)
    libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f707a2f3000)
    libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f707a0bf000)
    libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f7079eac000)
    libsoxr.so.0 => /usr/lib/x86_64-linux-gnu/libsoxr.so.0 (0x00007f7079c47000)
    libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f7079a21000)
    libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f7079816000)
    libogg.so.0 => /usr/lib/x86_64-linux-gnu/libogg.so.0 (0x00007f707960c000)
    liborc-0.4.so.0 => /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0 (0x00007f707938c000)
    libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f707911b000)
    libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f7078f07000)
    libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f7078c35000)
    libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f7078a05000)
    libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f7078801000)
    libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f70785f6000)
    libicuuc.so.55 => /usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007f7078261000)
    libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f7078038000)
    libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f7077e30000)
    libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f7077c0d000)
    libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f7077a09000)
    libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f70777ed000)
    libicudata.so.55 => /usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007f7075d36000)

**Comment by alastair** [comment]
Yes, I meant libessentia.so, sorry.

Where did you get the `streaming_extractor_music` file from? I thought you compiled it, but now going back to what you said, I think you may have downloaded our static file, based on the output of ldd.
This file doesn't have support for gaia. You can compile it yourself when you compile essentia by adding `--with-example=streaming_extractor_music` to the compile flags, and running the binary in `build/src/examples`. e.g., this is what I get when I run ldd:
```
alastair@mahler:~/code/essentia/build/src/examples$ ldd essentia_streaming_extractor_music 
	linux-vdso.so.1 =>  (0x00007ffe2dbf6000)
	libessentia.so => /usr/local/lib/libessentia.so (0x00007f60154ba000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6015132000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6014e29000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6014c12000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f601484b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f601462b000)
	libfftw3f.so.3 => /usr/lib/x86_64-linux-gnu/libfftw3f.so.3 (0x00007f6014220000)
	libavformat.so.57 => /usr/lib/x86_64-linux-gnu/libavformat.so.57 (0x00007f6013e08000)
	libavcodec.so.57 => /usr/lib/x86_64-linux-gnu/libavcodec.so.57 (0x00007f601275a000)
	libavutil.so.55 => /usr/lib/x86_64-linux-gnu/libavutil.so.55 (0x00007f60124dc000)
	libavresample.so.3 => /usr/lib/x86_64-linux-gnu/libavresample.so.3 (0x00007f60122b5000)
	libsamplerate.so.0 => /usr/lib/x86_64-linux-gnu/libsamplerate.so.0 (0x00007f6011f47000)
	libtag.so.1 => /usr/lib/x86_64-linux-gnu/libtag.so.1 (0x00007f6011c74000)
	libyaml-0.so.2 => /usr/lib/x86_64-linux-gnu/libyaml-0.so.2 (0x00007f6011a55000)
	/lib64/ld-linux-x86-64.so.2 (0x000055f27416e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6011851000)
	libssh-gcrypt.so.4 => /usr/lib/x86_64-linux-gnu/libssh-gcrypt.so.4 (0x00007f60115e3000)
	librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f60113c7000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f60111ab000)
	libmodplug.so.1 => /usr/lib/x86_64-linux-gnu/libmodplug.so.1 (0x00007f6010e20000)
	libgme.so.0 => /usr/lib/x86_64-linux-gnu/libgme.so.0 (0x00007f6010bd2000)
	libbluray.so.1 => /usr/lib/x86_64-linux-gnu/libbluray.so.1 (0x00007f6010989000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f601062f000)
	libchromaprint.so.0 => /usr/lib/x86_64-linux-gnu/libchromaprint.so.0 (0x00007f601041e000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f601020c000)
	libswresample.so.2 => /usr/lib/x86_64-linux-gnu/libswresample.so.2 (0x00007f600ffee000)
	libva.so.1 => /usr/lib/x86_64-linux-gnu/libva.so.1 (0x00007f600fdcf000)
	libzvbi.so.0 => /usr/lib/x86_64-linux-gnu/libzvbi.so.0 (0x00007f600fb44000)
	libxvidcore.so.4 => /usr/lib/x86_64-linux-gnu/libxvidcore.so.4 (0x00007f600f830000)
	libx265.so.79 => /usr/lib/x86_64-linux-gnu/libx265.so.79 (0x00007f600ec11000)
	libx264.so.148 => /usr/lib/x86_64-linux-gnu/libx264.so.148 (0x00007f600e86c000)
	libwebpmux.so.2 => /usr/lib/x86_64-linux-gnu/libwebpmux.so.2 (0x00007f600e662000)
	libwebp.so.6 => /usr/lib/x86_64-linux-gnu/libwebp.so.6 (0x00007f600e401000)
	libwavpack.so.1 => /usr/lib/x86_64-linux-gnu/libwavpack.so.1 (0x00007f600e1d7000)
	libvpx.so.3 => /usr/lib/x86_64-linux-gnu/libvpx.so.3 (0x00007f600ddb1000)
	libvorbisenc.so.2 => /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007f600db08000)
	libvorbis.so.0 => /usr/lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007f600d8da000)
	libtwolame.so.0 => /usr/lib/x86_64-linux-gnu/libtwolame.so.0 (0x00007f600d6b7000)
	libtheoraenc.so.1 => /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1 (0x00007f600d478000)
	libtheoradec.so.1 => /usr/lib/x86_64-linux-gnu/libtheoradec.so.1 (0x00007f600d25a000)
	libspeex.so.1 => /usr/lib/x86_64-linux-gnu/libspeex.so.1 (0x00007f600d041000)
	libsnappy.so.1 => /usr/lib/x86_64-linux-gnu/libsnappy.so.1 (0x00007f600ce39000)
	libshine.so.3 => /usr/lib/x86_64-linux-gnu/libshine.so.3 (0x00007f600cc2a000)
	libschroedinger-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0 (0x00007f600c955000)
	libopus.so.0 => /usr/lib/x86_64-linux-gnu/libopus.so.0 (0x00007f600c70b000)
	libopenjpeg.so.5 => /usr/lib/x86_64-linux-gnu/libopenjpeg.so.5 (0x00007f600c4e8000)
	libmp3lame.so.0 => /usr/lib/x86_64-linux-gnu/libmp3lame.so.0 (0x00007f600c273000)
	libgsm.so.1 => /usr/lib/x86_64-linux-gnu/libgsm.so.1 (0x00007f600c065000)
	libcrystalhd.so.3 => /usr/lib/x86_64-linux-gnu/libcrystalhd.so.3 (0x00007f600be48000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f600bc25000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f600ba1d000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f600b70e000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f600b4c4000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f600b28f000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f600b059000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f600add9000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f600aa1f000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f600a7dc000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f600a52f000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f600a2c9000)
	libidn.so.11 => /lib/x86_64-linux-gnu/libidn.so.11 (0x00007f600a096000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f6009e83000)
	libsoxr.so.0 => /usr/lib/x86_64-linux-gnu/libsoxr.so.0 (0x00007f6009c1e000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f60099ec000)
	libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f60097df000)
	libogg.so.0 => /usr/lib/x86_64-linux-gnu/libogg.so.0 (0x00007f60095d6000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f60092c3000)
	liborc-0.4.so.0 => /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0 (0x00007f6009045000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f6008e31000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f6008b5e000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f600892d000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f6008729000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f600851e000)
	libicuuc.so.57 => /usr/lib/x86_64-linux-gnu/libicuuc.so.57 (0x00007f6008176000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f6007f4c000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f6007d44000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f6007b14000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f600786c000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f6007668000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f600745e000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f600723c000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f6007032000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f6006cf7000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f6006ae5000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f60068e1000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f60066c6000)
	libicudata.so.57 => /usr/lib/x86_64-linux-gnu/libicudata.so.57 (0x00007f6004c49000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f6004a43000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f600483d000)

```

**Comment by knockyouout** [comment]
Yes, I was using the static executable streaming_extractor_music. I did not completely understand how can I compile streaming_extractor_music. Can you explain how can I compile streaming_extractor_music in detail?

**Comment by alastair** [comment]
If you run the waf configure command as you did:
```
./waf configure --mode=release --with-python  --with-examples --with-gaia
```
Then there will be a file `build/src/examples/essentia_streaming_extractor_music` which will do what you want

**Comment by knockyouout** [comment]
Thanks a lot for your interest! I will try and post the result.

**Comment by knockyouout** [comment]
I got the file `essentia_streaming_extractor_music`. However when I run it I get the error `error while loading shared libraries: libessentia.so: cannot open shared object file: No such file or directory`
Any Idea why It cannot access the library

**Comment by alastair** [comment]
You will need to install essentia (`sudo ./waf install`) and then update the shared library cache (`sudo ldconfig`)

**Comment by knockyouout** [comment]
It is done. Thanks a lot!
