### ISSUE TITLE
Analysis in SingleBeatLoudness fails

### ISSUE THREAD

**Issue by nagisa** [MTG/essentia#482]
Not sure if the right place to report this.

Using the abzsubmit downloaded from [here](https://acousticbrainz.org/download), I got

```
[:( extract] $PATH_TO_SOME_VALID_FLAC
b'Process step: Read metadata\nProcess step: Compute md5 audio hash and codec\nProcess step: Replay gain\nProcess step: Compute audio features\nSingleBeatLoudness: size of input beat cannot be smaller than beatWindowSize + beatDuration\n'
```

The track is very long, which may be a cause for the failure. Suggest extra steps to help reproduce.

**Comment by dbogdanov** [comment]
This issue was fixed today in ef7c8a5ea3ff61bcaceb4f6bb052fad07b26aaf6

Build and use ```essentia_streaming_extractor_music``` from master instead of using the one provided on the AB web-page. Otherwise, ignore very long files for now.
