### ISSUE TITLE
Danceability outputs negative values

### ISSUE THREAD

**Issue by dbogdanov** [MTG/essentia#483]
Reported in #402. There should be no negative values.

Test audio: https://github.com/MTG/essentia/files/288363/004077.mp3.zip

```
import essentia.standard as es
audio = es.MonoLoader(filename="/tmp/004077.mp3")()
print es.Danceability()(audio)
```

Output:  -6.91133165359

**Comment by dbogdanov** [comment]
@alastair Any examples of negative values in AcousticBrainz database?

**Comment by alastair** [comment]
http://acousticbrainz.org/083831dc-cd35-4594-88a9-4a1ff3e5ade5/low-level?n=0
http://acousticbrainz.org/0c4b7ec1-7686-44d3-8ab5-1cb0aab069d5/low-level?n=0
http://acousticbrainz.org/191eb544-5975-48ba-a0d0-f4b2e22a0b4b/low-level?n=0
http://acousticbrainz.org/1a605b0e-eca2-4d4d-8ff0-d60e3307aec1/low-level?n=0
http://acousticbrainz.org/1b902e71-f50c-4b01-9cad-fac557de7719/low-level?n=0
http://acousticbrainz.org/2690030a-7753-4b1f-8ea1-cc1ffa38de77/low-level?n=0
http://acousticbrainz.org/4a924781-be29-4cf4-83e6-f1d4bbc43016/low-level?n=2
http://acousticbrainz.org/4b5f677f-eb2c-4dab-8799-920969be738e/low-level?n=0
http://acousticbrainz.org/59f759d3-b901-428c-8a3a-495982f0e5f0/low-level?n=0
http://acousticbrainz.org/67611f7e-6c0d-436e-a685-bec28b49ae51/low-level?n=0
http://acousticbrainz.org/6a6005dc-ff63-4884-a37d-936110ca5d27/low-level?n=0
http://acousticbrainz.org/6d6e1dfd-e571-4ae5-9071-c1110e4856ab/low-level?n=0
http://acousticbrainz.org/6d6e1dfd-e571-4ae5-9071-c1110e4856ab/low-level?n=1
http://acousticbrainz.org/6d6e1dfd-e571-4ae5-9071-c1110e4856ab/low-level?n=2
http://acousticbrainz.org/7ae02402-f8ba-4b08-9705-1a5a9d281a0f/low-level?n=0
http://acousticbrainz.org/9785a694-c7cd-4d4a-94b4-06ffbfda159a/low-level?n=0
http://acousticbrainz.org/a93a1b14-d2d5-4ce5-bb24-d3253beb0847/low-level?n=0
http://acousticbrainz.org/c53efb7c-bdfa-4b1c-82bd-7ccfc2d1b075/low-level?n=0
http://acousticbrainz.org/cb4d210d-fdf5-4b97-b5d6-4cdd2ceccf51/low-level?n=0
http://acousticbrainz.org/f2c07b15-be55-411e-b37f-a4fcd17ba434/low-level?n=0
