### ISSUE TITLE
implement inverse 12 MFCCs for visualisation 

### ISSUE THREAD

**Issue by georgid** [MTG/essentia#487]
The first MFCCs are standard for describing singing voice timbre. The MFCC feature vector however does not represent visually well the singing voice. Instead, a common practice is to use for visualisation the inverted first some (12-15) MFCC coefficients to mel-bands domain.
Port from the invmelfcc.m  as explained here http://labrosa.ee.columbia.edu/matlab/rastamat/
or from python: 
https://github.com/avaitla/HenryVsRudolph/blob/master/Python/MFCC.py

**Comment by dbogdanov** [comment]
The algorithm should have a parameter to specify how many coefficients to take from the MFCC vector.

**Comment by georgid** [comment]
implementation plan: 
1) output the _dctTable from the DCT in essentia
https://github.com/MTG/essentia/blob/528c57494ae3322ffed4442f44082ef0608c0ee8/src/algorithms/standard/dct.cpp
2) invert it, use MEL_BANDS  and a parame: MFCC_COEFS: how many coefficients to take from the MFCC
invD = numpy.inv(_dctTable)
3) multiply MFCC * invD

**Comment by georgid** [comment]
@pabloEntropia 
Once you are done, may you add in both in the documentation of InverseDCT and MFCC that inverseDCT can be used to compute smoothedMelBands in the following way: 
1) compute MFCC 
2) smoothedMelBands = inverseDCT(computed MFCC)
