### ISSUE TITLE
Error while configuring MonoLoader

### ISSUE THREAD

**Issue by YichiHuang** [MTG/essentia#490]
Hi, 
there is a runtimeError when I run the code:
`loader = MonoLoader(filename=wav_fp, sampleRate=16000`
where `wav_fp="/home/data/TIMIT/train/dr1/mmrp0/sx54.wav"`
and a RuntimeError raised:
`RuntimeError: Error while configuring MonoLoader : AudioLoader : Could not open file "/home/data/TIMIT/train/dr1/mmrp0/sx54.wav" , error = Invalid data found when processing input`

**Comment by dbogdanov** [comment]
Make sure that you can access this file, and it is not broken and you can read it. You can do it using ffprobe in command line:

```ffprobe /home/data/TIMIT/train/dr1/mmrp0/sx54.wav```

**Comment by YichiHuang** [comment]
The command line tells:
`/home/data/TIMIT/train/dr1/mmrp0/sx54.wav : Invalid data found when processing input`

**Comment by dbogdanov** [comment]
This wav file seems to be broken according to ffmpeg and Essentia relies on ffmpeg for loading audio.
