### ISSUE TITLE
add option for using magnitude spectrum in MelBands, MFCC, TriangularBands, and GFCC

### ISSUE THREAD

**Issue by edufonseca** [MTG/essentia#501]
To compute mfcc, we make use of [MelBands](https://github.com/MTG/essentia/blob/master/src/algorithms/spectral/melbands.cpp) algorithm, where power spectrum is currently being used.

In Essentia documentation we are citing (MFCC FB-40, [1]), based on Slaney’s Auditory Toolbox. However, both in [1] and in Auditory Toolbox, the magnitude spectrum is used.

In the literature, several implementations of MFCC can be found (with slightly different parameters or procedures). One of those issues is the spectrum type:

- Some of them use power spectrum (Rabiner and Schafer, Introduction to Digital Speech Processing,see 5.25a) or also [here](http://practicalcryptography.com/miscellaneous/machine-learning/guide-mel-frequency-cepstral-coefficients-mfccs/#eqn2)

- Others use magnitude spectrum, as those described in [1].

Perhaps we could allow both options (magnitude and power spectrum) for computation, according to an input parameter. Something like this is already done in the [ERBBands](https://github.com/MTG/essentia/blob/master/src/algorithms/spectral/erbbands.cpp) algorithm (see very bottom). In the [ERBBands documentation](http://essentia.upf.edu/documentation/reference/std_ERBBands.html), the parameter 'type' is defined. IMHO, perhaps the explanation of the parameter is not very clear? Maybe, a more intuitive way would be to define two options: _magnitude_ and _power_, where the explanation may be something like: 'use magnitude or power spectrum' . In any case, I'd like someone else with more background in this topic to give an opinion on this before changing anything :D @dbogdanov 

[1] T. Ganchev, N. Fakotakis, and G. Kokkinakis, "Comparative evaluation of various MFCC implementations on the speaker verification task," in International Conference on Speach and Computer (SPECOM’05), 2005, vol. 1, pp. 191–194.

**Comment by dbogdanov** [comment]
Agreed, we can have a parameter "type" = {magnitude, power} in MelBands, MFCC, and  GFCC (it is only implemented in ERBBands currently). @georgid

@pabloEntropia, can you include this new parameter to MelBands as you are reviewing it right now?

**Comment by dbogdanov** [comment]
@pabloEntropia this will actually mean adding this parameter to TriangularBands too.

**Comment by dbogdanov** [comment]
@pabloEntropia For consistency, we would like to add ```type``` parameter to GFCC too (it is already implemented in ERBBands).

**Comment by pabloEntropia** [comment]
@dbogdanov  Great, btw do you think I should also add 'dctType' ?

**Comment by dbogdanov** [comment]
Great, I'll close this issue after a pull request.

**Comment by dbogdanov** [comment]
Done
