### ISSUE TITLE
Log type as a parameter in MFCC, GFCC, and *Bands algorithms

### ISSUE THREAD

**Issue by dbogdanov** [MTG/essentia#510]
Till now for consistency all our *Bands algorithms (MelBands, ERBBands, BarkBands, FrequencyBands) output energies while MFCC and GFCC output log-energies. In addition TriangularBands has an option to output log-energies (although it is not specifically used by any algorithm).

We should either support log-energies output in all *Bands algorithms (**if we can really justify it to be very very useful**) or in none of them keeping code simpler. In the latter case, if users want log computation, it can be done apart using [UnaryOperator](http://essentia.upf.edu/documentation/reference/std_UnaryOperator.html) or we can implement a new LogCompress algorithm.

In addition MFCC and GFCC provide log-energy outputs. There are (at least) three ways to compute log energies for MFCCs: 
- [20log10(energy)](https://github.com/MTG/essentia/blob/master/src/algorithms/spectral/mfcc.cpp#L71) (as used now in Essentia)
- 10log10(energy) (used in librosa)
- [log2(1+energy)](https://github.com/MTG/essentia/blob/master/src/algorithms/spectral/triangularbands.cpp#L105) (not sure if it can be used for MFCCs, but we have it for TriangularBands)
- Any other variants known?

We should implement these variants as an option in MFCC and GFCC.

@georgid @edufonseca

**Comment by dbogdanov** [comment]
@georgid There are two version of 'db' as mentioned in #510. I propose we implement both: 
- "db": 10 log10(x) - used in librosa. This is a formula to compute dB for measurements of power quantities. It is appropriate for energy. 
- "2db": 20 log10(x) - used in Essentia. This formula is appropriate for magnitudes. However, it was (probably mistakenly) used with energy, which is conceptually incorrect although won't lead to any significant differences.

**Comment by dbogdanov** [comment]
We need to add ```logType``` to GFCC too.

**Comment by dbogdanov** [comment]
Remove debug output (printing array) in testRegression in SpectrumToCent

**Comment by pabloEntropia** [comment]
I've implemented log type for the GFCC but I've found that there isn't any unit test for it. Should I create it? If so, do you have any suggestion for another reliable implementation to create a regression test?

**Comment by dbogdanov** [comment]
Yes, let's implement the test (you can use test for MFCC for inspiration). We can fake regression test using our own output now as correct (add a comment to code that it is fake).

**Comment by dbogdanov** [comment]
We can do a pull request to close this issue meanwhile. There is another issue related to unit tests for GFCC (#503).

**Comment by dbogdanov** [comment]
Done.
