### ISSUE TITLE
real-time classification. 

### ISSUE THREAD

**Issue by JoshMarler** [MTG/essentia#512]
Hi all, 

Apologies if it is inappropriate to ask a question on the issues list. It looks like general question are being asked so hopefully this is not an big annoyance! 

I have recently been working on an audio plugin that implements real-time extraction and classification. Essentially it is a beat-box to MIDI/Synthesis plugin. The plugin has been developed for the purposes of my masters (Msc) final project. It works, I can (poorly) "beatbox" kick, snare and hi-hat sounds and they are classified in real-time which results in the corresponding drum synth sounds firing off with minimal latency (such is the topic of my research project). 

I am an avid JUCE user (using it for my project) and have just noticed Essentia mentioned in a talk regarding the rapid-mix API for interactive machine learning etc. I THINK I came across Essential at one point during my early research and did not see the ability to classify short term audio frames in real-time. 

Could someone who knows more about the library clarify for me whether or not their are learning/classification algorithms contained suitable for real-time usage ? i.e. non-blocking and without memory allocations internally. So I could call Essential::foo.classify() or similar on a real-time thread ? Am I right in thinking Gaia SVM's are the only classification features included ? 

I'm asking out of interest to see whether I have re-inveted a far better made wheel and also to check whether it might be worth me referencing Essentia in my work as a comparison! 

Any clarification would be much appreciated. Finding it hard to workout from the DOCs and the code base is a bit of a beast to go climbing through. Not sure how TNT allocated memory internally for its vector / matrix representations etc. (i.e. does it use expression templates to avoid temporaries / not malloc etc)

Thanks a lot in advance for any responses. 

Josh

**Comment by dbogdanov** [comment]
Currently, the only way to use classification is to use Gaia separately to train SVM models and then use them in Essentia via GaiaTransform algorithm. I would expect the classification to be fast enough for real time (although I did not experiment with that).

**Comment by JoshMarler** [comment]
Thanks a lot for the response/taking the time. That sort of confirms things for me in a way.

Cheers

Josh
