### ISSUE TITLE
'Spectrum' with parameter 'sampleRate' 

### ISSUE THREAD

**Issue by lazumbra** [MTG/essentia#514]
When I try to change the frameSize and the hopsize I get an info. What does it mean? How can I change these parameters?
[0;32m[   INFO   ] [0mMelBands: input spectrum size (1001) does not correspond to the "inputSize" parameter (1025). Recomputing the filter bank.

**Comment by dbogdanov** [comment]
This warning means that the MelBands algorithm had to reconfigure itself as it was expecting spectrum of size 1025.  You can either ignore this warning or specify  a correct expected inputSize = 1001.
