### ISSUE TITLE
TonalExtractor issue- RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by yyf** [MTG/essentia#516]
Tried to use Tonal Extractor but ran into runtime error, any idea? 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-349-69d83ed97035> in <module>()
----> 1 tonalExtractorCalculator(bg_track)

<ipython-input-348-378afb859aff> in tonalExtractorCalculator(audioInput)
      1 def tonalExtractorCalculator(audioInput):
      2     tonalExtractor = essentia.standard.TonalExtractor()
----> 3     tonal = tonalExtractorCalculator(audioInput)
      4     return tonal

... last 1 frames repeated, from the frame below ...

<ipython-input-348-378afb859aff> in tonalExtractorCalculator(audioInput)
      1 def tonalExtractorCalculator(audioInput):
      2     tonalExtractor = essentia.standard.TonalExtractor()
----> 3     tonal = tonalExtractorCalculator(audioInput)
      4     return tonal

RuntimeError: maximum recursion depth exceeded while calling a Python object

**Comment by dbogdanov** [comment]
This is not related to Essentia. You have an infinite recursion in your tonalExtractorCalculator() python code.
