### ISSUE TITLE
Finalize work on TriangularBands, MelBands, and MFCCs

### ISSUE THREAD

**Issue by dbogdanov** [MTG/essentia#518]
@pabloEntropia  
- Now I see there are various new branches in your repository. Please merge them all together into one and make a new pull request (or merge them all into one existing pull request) otherwise it is difficult to track things.
- Update unit tests for TriangularBands testing new parameters 
- Add a few "real-case" regression tests in MelBands unit test (use a few of different spectrum inputs and default parameters. Use the output from older version of MelBands as a reference ground truth). This is to make sure that results of MelBands are identical after code updates. 
- Add another "real-case" regression test (or few of them) comparing htk MelBands using results from htk as a reference.

@georgid

**Comment by pabloEntropia** [comment]
I have created a branch merging all my work here in order to make it possible to track all my commits. 
I will create the pull request when I am satisfied with the results of all the tests.
[TriangularBands-tools](https://github.com/pabloEntropia/essentia/tree/TriangularBands-tools)

**Comment by dbogdanov** [comment]
You've also got some work in faster-TriangularBands. Is that to be merged too?

**Comment by pabloEntropia** [comment]
Yes it is!
