### ISSUE TITLE
Iterating through "Slicer" frames question

### ISSUE THREAD

**Issue by FRD93** [MTG/essentia#519]
Hello everybody,

I'm facing a problem and I cannot find any reference about this. 
I'm trying to make a simple extractor in the streaming mode, and the problem is:

I'm slicing the signal in more parts using "Slicer" algorithm. After that, I need to pass each resulting signal to an fft chain (such as framecutter->windowing->fft->hfc) and store the results for each sliced signal, but I can't realize how to accomplish this. 

Is there a way to iterate through each vector output of the "Slicer" algorithm and perform extraction in each of them?

Thanks in advance,
FD

**Comment by dbogdanov** [comment]
You can't connect multiple framecutters to a slicer in the same network. What you can do is to compute slices first and then stream them (using [VectorInput](http://essentia.upf.edu/documentation/reference/streaming_VectorInput.html)) into your chains.
