### ISSUE TITLE
problem occurs when executing import essentia on my python intepreter. It cannot find .so files or something

### ISSUE THREAD

**Issue by nimeshmora** [MTG/essentia#521]
I have downloaded and installed essentia on ubuntu 16.04 lts. all the configuration, compilation and installation parts were successfull. But when i'm going to execute "import essentia" in my python intepreter it says an error called , .so file is not found in shared path or something. Can somone help me with this please. I'm new to Ubuntu too

**Comment by dbogdanov** [comment]
Make sure you are using python2, not python3. 
```python --version```

Make sure you've configured with ```--with-python```. After you did ```./waf install``` you should have the file ```_essentia.so``` in the ```/usr/local/lib/python2.7/dist-packages/essentia/``` folder.

**Comment by nimeshmora** [comment]
Thank you. I will check.

**Comment by nimeshmora** [comment]
All the configuration , compilation , installation done correctly. but when i type import essentia on python 2.7 intepreter , it gives this error. what is the solution for this?

Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.

>>> import essentia
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/essentia/__init__.py", line 1, in <module>
    import _essentia
ImportError: libessentia.so: cannot open shared object file: No such file or directory

**Comment by nimeshmora** [comment]
FInally it worked .

**Comment by lakshdkt** [comment]
How it worked?

**Comment by georgid** [comment]
> Make sure you are using python2, not python3.
> `python --version`
> 
> Make sure you've configured with `--with-python`. After you did `./waf install` you should have the file `_essentia.so` in the `/usr/local/lib/python2.7/dist-packages/essentia/` folder.

One can check if _essentia.so points to the correct libraries on which it depends by using `ldd` on linux-based OS and `otool` on mac os x. e.g in my case the libessentia was not linked correclty:  
ldd /usr/lib/python2.7/site-packages/essentia/_essentia.so
	linux-vdso.so.1 =>  (0x00007ffed2df2000)
	libessentia.so => not found
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fac3c10e000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fac3be0c000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fac3bbf6000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fac3b9da000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fac3b60d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fac3c6b5000)
