### ISSUE TITLE
when buildin essentia with gaia gives an error?

### ISSUE THREAD

**Issue by nimeshmora** [MTG/essentia#524]
I was installed gaia2 successfully on my ubuntu 16.04. after that i configured my essentia source code using --with-gaia . configuratoin was successfull and it said that gaia transform is detected. After i build the essentia. then it gives this error.

[ 41/246] Compiling src/algorithms/standard/maxfilter.cpp
In file included from ../src/algorithms/essentia_algorithms_reg.cpp:143:0:
../src/algorithms/highlevel/gaiatransform.h:37:10: error: ‘TransfoChain’ in namespace ‘gaia2’ does not name a type
   gaia2::TransfoChain _history;
          ^
../src/algorithms/highlevel/gaiatransform.h: In constructor ‘essentia::standard::GaiaTransform::GaiaTransform()’:
../src/algorithms/highlevel/gaiatransform.h:47:5: error: ‘init’ is not a member of ‘gaia2’
     gaia2::init();
     ^
../src/algorithms/highlevel/gaiatransform.h:47:5: note: suggested alternative:
In file included from ../src/essentia/algorithmfactory.h:27:0,
                 from ../src/algorithms/essentia_algorithms_reg.cpp:1:
../src/essentia/essentia.h:46:6: note:   ‘essentia::init’
 void init();
      ^

Waf: Leaving directory `/home/nimesha/Documents/essentia-master/build'
Build failed
 -> task in 'essentia' failed with exit status 1 (run with -v to display more information)

can someone please help with this

**Comment by dbogdanov** [comment]
Try ```./waf clean```, and  ```./waf configure``` and ```./waf``` again

**Comment by HamidiMassinissa** [comment]
I am getting the same error as the one aforementioned by @nimeshmora even after trying the solution provided by @dbogdanov.

**Comment by HamidiMassinissa** [comment]
It is finally an error that occurred while configuring `Gaia` that caused my problem. Actually, rather than using merely the following options for configuration:

`./waf configure --with-python-bindings --with-asserts --with-cyclops`

the option `--with-stlfacade ` was added by inadvertence and as you know, this option is not compatible when using `Gaia` in conjunction with `Essentia`.
