### ISSUE TITLE
how to import essentia in a virtual env

### ISSUE THREAD

**Issue by yyf** [MTG/essentia#526]
Had essentia globally installed in my environment, but want to import it in a new virtual env for a different project. Tried to import but got ImportError: No module named essentia.

Tried to install essentia again under the virtual env by following
- brew tap MTG/essentia
- brew install essentia
and had this error:
Error: You must `brew link yasm lame` before mtg/essentia/essentia can be installed

then "brew link yasm lame" gave this error: 
Linking /usr/local/Cellar/yasm/1.3.0... 
Error: Could not symlink include/libyasm/arch.h
Target /usr/local/include/libyasm/arch.h
already exists. You may want to remove it:
rm '/usr/local/include/libyasm/arch.h

To force the link and overwrite all conflicting files:
  brew link --overwrite yasm

To list all files that would be deleted:
  brew link --overwrite --dry-run yasm`

And "brew link --overwrite yasm" gave this error: 
Error: Could not symlink include/libyasm/arch.h
/usr/local/include/libyasm is not writable.

Wondering what's a proper way to import essentia in a virtual env? or is it necessary to install essentia again under the virtual env? possible to install essentia via pip? thanks

**Comment by yyf** [comment]
"virtualenv venv --system-site-packages" this resolves my issue.

**Comment by scherroman** [comment]
See my comment in #553
