### ISSUE TITLE
Getting error while importing "essentia.standard" in python

### ISSUE THREAD

**Issue by anil-tiwari** [MTG/essentia#527]
Hi , 
I have installed Essentia on Ubuntu 16.04 machine by following below steps:

### Step 1 : Install Ruby 
- sudo apt-get install build-essential curl git python-setuptools ruby

### Step 2 : Install BREW
- ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"

Configure Brew , Add to your .bashrc or .zshrc:
	export PATH="$HOME/.linuxbrew/bin:$PATH"
	export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
	export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"

### Step 3 : Add Essentia Repo to brew
	brew tap mtg/essentia

### Step 4: Re-Install openBLas
	brew reinstall openblas -s

### Step 5 : Install Essentia
	brew insall essentia --HEAD 

It install successfully on my machine. 
*************************************************
When i am going to **import essentia.standard** getting below error 

> ubuntu@ip-172-31-13-197:~$ python
Python 2.7.12 (default, Dec  7 2016, 05:41:46) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> import essentia.standard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/essentia/__init__.py", line 1, in <module>
    import _essentia
ImportError: /home/ubuntu/.linuxbrew/lib/libessentia.so: undefined symbol: _ZNK6TagLib6String6to8BitB5cxx11Eb
>>>

**Comment by anil-tiwari** [comment]
@dbogdanov Any idea?? Am I doing any wrong step.
This error comes with every version the latest "**.beta3" and the oldest one 2.0.0

**Comment by anil-tiwari** [comment]
it's working on OsX but for linux distribution

**Comment by dbogdanov** [comment]
You should not use brew on Linux. Install from source as explained here: 
http://essentia.upf.edu/documentation/installing.html#installing-dependencies-on-linux
http://essentia.upf.edu/documentation/installing.html#compiling-essentia

**Comment by anil-tiwari** [comment]
@dbogdanov  : thanks for your valuable reply but it really not worked for me.
I just disable the taglib("#depends_on "libtag" => :recommended") installation on brew perl script and then it's works fantastically.
