### ISSUE TITLE
Specifying the Libav version for Ubuntu < 16.04

### ISSUE THREAD

**Issue by sertansenturk** [MTG/essentia#536]
I have just installed Essentia to Ubuntu 14.04. In the [documentation](https://github.com/MTG/essentia/blob/master/FAQ.md#build-essentia-on-ubuntu-1404-or-earlier) for this specific compilation, the Libav version is not specified (the text reads "Download and unpack Libav source code").

libav 11+ does not provide __libav*.so.52__. On the other hand, libav 9- does not meet the dependency requirements checked by ["./waf configure"](http://essentia.upf.edu/documentation/installing.html#compiling-essentia). Basically, the only useful version is [libav 10](https://libav.org/download/#release_10). 

@dbogdanov can you confirm this on different Linux versions we support? If this holds, we should refer to this specific version, to better explain the compilation step.

**Comment by dbogdanov** [comment]
Which Essentia version do you install? You should be able to build the latest LibAv from source for 2.1-beta3.

**Comment by sertansenturk** [comment]
I have installed 2.1-dev. 

I have tried the same procedure again and libav12 (latest) seems to work. Don't know what the problem was earlier, I cannot reproduce. I think we can close the issue.

**Comment by dbogdanov** [comment]
Thanks!
