### ISSUE TITLE
Essentia in Windows 10 via bash

### ISSUE THREAD

**Issue by sertansenturk** [MTG/essentia#537]
A recent update makes it possible to [install bash to Windows 10](https://msdn.microsoft.com/commandline/wsl/install_guide). This means that Essentia support in Windows might be greatly improved without many effort.

As a matter of fact, I have already installed Essentia to my machine. The process so far is identical to how you would install in Ubuntu 14.04 (which the bash in Windows is built upon).

I am currently testing some scenarios I have been using Essentia as part of my workflow. I will write a short report/tutorial with possibilities and/or issues as soon as I am done.

**Comment by dbogdanov** [comment]
:clap::sparkles::balloon::christmas_tree::clap:

**Comment by sertansenturk** [comment]
OK, I have run the [tests](http://essentia.upf.edu/documentation/installing.html#running-tests-optional) and most of the things seem to work. (I'm also happy that my audio analysis code involving Essentia also works without any problems :satisfied:) The test outputs are below.

[c_tests.txt.txt](https://github.com/MTG/essentia/files/656054/c_tests.txt.txt)
[python_tests.txt.txt](https://github.com/MTG/essentia/files/656053/python_tests.txt.txt)

We can check the results in my machine, if you'd like. If you think these results are fine, I can start writing the short report/tutorial.

**Comment by dbogdanov** [comment]
Some tests are failing because you are missing audio from the [test/audio submodule](https://github.com/MTG/essentia-audio/tree/33ded4f7932cd22bf97e8ef57cdedc3dbe4ad798). The rest is fine. 

You can add installation instructions to https://github.com/MTG/essentia/blob/master/doc/sphinxdoc/installing.rst or post them here in the comments.

**Comment by dbogdanov** [comment]
Addressed in the pull request
