### ISSUE TITLE
Ubuntu: wav compilation failure

### ISSUE THREAD

**Issue by aagnone3** [MTG/essentia#548]
Your conditional for line 262 of the root wscript file fails for Ubuntu 16.04. This is due to the fact that platform.dist()[0] is 'debian', and the conditional only checks for 'Ubuntu'.

The following quick fix works:
    platform.dist()[0] in ['Ubuntu', 'debian'] and ....

**Comment by dbogdanov** [comment]
platform.dist() should return "Ubuntu" (checked on Ubuntu 16.04) This could be a [bug in python](http://bugs.python.org/issue9514).

**Comment by aagnone3** [comment]
Confirmed, but seems to not be a python bug.

- The basic python installation on Ubuntu 16.04 returns "Ubuntu" from platform.dist()[0].
- A python installation with [anaconda](https://www.continuum.io/) returns "debian" from platform.dist()[0].

I haven't done further digging, but this is likely a library difference that comes with the installation of anaconda. Seems like it won't hurt to include this check to support anaconda users?

**Comment by dbogdanov** [comment]
There's now anaconda support through pypi packages.
