### ISSUE TITLE
AudioLoader: add support for audio sources with multiple audio streams

### ISSUE THREAD

**Issue by louis49** [MTG/essentia#552]
I got these error when loading an audio file containing multiple audio streams :
AudioLoader ERROR: found 4 streams in the file, expecting only one audio stream

Do you know how to get only first/nth/last stream ?

**Comment by dbogdanov** [comment]
Currently there is no way to specify the audio stream. You can manually extract the streams using ffmpeg. However this would be a very useful option to have.

**Comment by dbogdanov** [comment]
Add new parameter ```audioStream``` (audio stream index) to AudioLoader. Default value = 1 corresponds to the first audio stream among the streams in the source.

https://github.com/MTG/essentia/blob/master/src/algorithms/io/audioloader.cpp#L104

**Comment by dbogdanov** [comment]
Throw exception if there is no audio streams.

**Comment by dbogdanov** [comment]
@pabloEntropia

**Comment by dbogdanov** [comment]
Fixed in #557
