### ISSUE TITLE
Python instalation Segmentation Fault

### ISSUE THREAD

**Issue by fnbns** [MTG/essentia#553]
Dear essentia users,

I mananged to install essentia through brew. I have anaconda installed also and I ran the following commands:

1. mkdir -p /Users/atnm1/.local/lib/python2.7/site-packages
2. echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/atnm1/.local/lib/python2.7/site-packages/homebrew.pth

However, when I import essentia I get:

Segmentation fault 11

Can you help me with this?
Thank you,
Alex.

**Comment by dbogdanov** [comment]
Have you resolved this problem?

**Comment by fnbns** [comment]
No, I've tried several environments (os Siera & OSX Capitan) but I get the same error.

**Comment by scherroman** [comment]
I use Miniconda 3.5 on Mac OS X Sierra, and this is how I do it:

**Install Essentia via Homebrew**
`brew tap MTG/essentia`
`brew install essentia`

**Move Essentia package from Homebrew to your Conda virtual environment**
`cp -r /usr/local/lib/python2.7/site-packages/essentia ~/miniconda/envs/my_project_env/lib/python2.7/site-packages/essentia`

Would be nice to be able to install the python bindings directly via pip though!

**Comment by jpauwels** [comment]
I'm trying to fix these kind of problems in #597.

**Comment by georgid** [comment]
I am facing the segmentation fault on mac os x 10.12.  I did add the path of @jpauwels, then compiled using the python installed with homebrew like that: 

```
/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/bin/python ./waf configure --with-python
/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/bin/python ./waf
```
here I get a bunch of warnings like these ones:
ld: warning: ignoring file /usr/local/Cellar/taglib/1.9.1/lib/libtag.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/Cellar/taglib/1.9.1/lib/libtag.dylib
ld: warning: ignoring file /usr/local/Cellar/libyaml/0.1.6/lib/libyaml.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/Cellar/libyaml/0.1.6/lib/libyaml.dylib

I ignore them and proceed with
```
/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/bin/python ./waf install
```
The python extension gets installed in both places: 
/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/essentia/_essentia.so
..and 
/usr/local/lib/python2.7/site-packages/essentia/_essentia.so 


When I run 
`otool -L /usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/essentia/_essentia.so`
...the first lines are:

```
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1349.8.0)
	/Users/joro/workspace/essentia/build/src/libessentia.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.10)
```
...this last line shows that it is being linked against the system's python, not the one from brew.

Any idea? 
Also, I was wondering if one can use the flags
--python or --python-path of waf?

**Comment by dbogdanov** [comment]
@georgid Include ```FileOutputProxy``` to your list of algorithms to include (the ```--include-algos``` flag)

**Comment by georgid** [comment]
Thanks @dbogdanov, that solved my particular problem. 
Further, I realized the right way to avoid the segmentation fault is to explicitly tell essentia which python version to use with the `-python` flag

**Comment by georgid** [comment]
@dbogdanov  you can close the issue. Thanks for your help

**Comment by seffka** [comment]
Have had Segmentation Fault problem when "import essentia" on macOS 10.13 and pyenv.
#597 patch didn't help. It appears, that my python installation has no "[Framework](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/WhatAreFrameworks.html)".

 After reinstalling with:
`env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.5.1`
everything works!
