### ISSUE TITLE
Help - Python : Create my own streaming::Algorithm

### ISSUE THREAD

**Issue by louis49** [MTG/essentia#554]
Hi! 
Do you know how can i write my own streaming::Algorithm in Python?

Example : 
I extract MFCC from an audio source, then I want use these result with an other python code and then write result on file.

**Comment by dbogdanov** [comment]
Not possible in Python, you'll have to write your streaming algorithm in C++.

**Comment by louis49** [comment]
Hi @dbogdanov !

Where I can find an example to do that in C++ ?

**Comment by dbogdanov** [comment]
http://essentia.upf.edu/documentation/extending_essentia_streaming.html
