### ISSUE TITLE
unit in loudness algorithms 

### ISSUE THREAD

**Issue by yyf** [MTG/essentia#556]
Been trying to get some loudness estimation using 
- essentia.standard.Loudness()
- essentia.standard.LoudnessEBUR128()
- essentia.standard.Leq()
- essentia.standard.LevelExtractor()
Wondering if there is a doc to look up/confirm unit for outputs from these loudness algorithms? could be useful if the unit is included in the reference documentation page. 

Thanks

**Comment by dbogdanov** [comment]
This is documented for [LoudnessEBU128](http://essentia.upf.edu/documentation/reference/std_LoudnessEBUR128.html). The units are [LUFS](https://en.wikipedia.org/wiki/LKFS).

Leq units are dB.

**Comment by dbogdanov** [comment]
There is no specific unit for Loudness and LevelExtractor, which are based on [Stevens' power law](https://en.wikipedia.org/wiki/Stevens'_power_law).
