### ISSUE TITLE
[python] SpectralContrast crash

### ISSUE THREAD

**Issue by louis49** [MTG/essentia#568]
loader = EasyLoader(filename='test.wav', sampleRate=48000)
    signal = loader()
    pool = essentia.Pool()
    fg = FrameGenerator(signal,
                        frameSize=1024,
                        hopSize=512,
                        startFromZero=True,
                        validFrameThresholdRatio=0,
                        lastFrameToEndOfFile=True)
    window = Windowing(type="hamming",
                       size=1024,
                       zeroPadding=0,
                       normalized=False,
                       zeroPhase=False)
    spectrum = Spectrum(size=2048)
    scAlgo = SpectralContrast(
        lowFrequencyBound=0,
        highFrequencyBound=11000,
        numberBands=6,
        sampleRate=48000,
        frameSize=int(2048/2+1)
    )

    for frame in fg:
        w = window(frame)
        s = spectrum(w)
        spectralContrast,spectralValley = scAlgo(s)       => Crash

        print(spectralContrast)

**Comment by dbogdanov** [comment]
The problem occurs when lowFrequencyBound is set to zero.

**Comment by louis49** [comment]
Thank you
