### ISSUE TITLE
Support for Wavpack files

### ISSUE THREAD

**Issue by bearcatsandor** [MTG/essentia#569]
Would you consider support for wavpack files? While not as popular as Flac, it's an accepted format in the Linux world and supported by the major audio libraries.  The tag format is APE.

More info here: http://www.wavpack.com/

Thanks

**Comment by dbogdanov** [comment]
Wavpack files are actually supported. Literally, any format that ffmpeg supports is supported as it is mentioned in the [documentation for AudioLoader](http://essentia.upf.edu/documentation/reference/std_AudioLoader.html).
