### ISSUE TITLE
PoolAggregator standard deviation not working (Python)

### ISSUE THREAD

**Issue by savovs** [MTG/essentia#570]
Hi guys,

I'm doing some aggregation like this:
`PoolAggregator(defaultStats = ["mean", "std"])(pool)`

But I get this error saying standard deviation is not supported:
```
Traceback (most recent call last):
  File "/Users/vlady/code/SoundFXAnalysis/src/featureExtractor.py", line 33, in <module>
    dataPoolsAggregated.append(PoolAggregator(defaultStats = ["mean", "stdev"])(pool))
  File "/usr/local/lib/python2.7/site-packages/essentia/standard.py", line 43, in __init__
    self.configure(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/essentia/standard.py", line 58, in configure
    self.__configure__(**kwargs)
RuntimeError: Error while configuring PoolAggregator: PoolAggregator: unsupported aggregation statistic: 'stdev'
```
It works for anything else but standard deviation. The docs mention [support](http://essentia.upf.edu/documentation/reference/std_PoolAggregator.html) for it so I'm wondering what am I doing wrong?

**Comment by dbogdanov** [comment]
Use "stdev", not "std"

**Comment by savovs** [comment]
I'm on 2.1 beta3 installed from homebrew, but still getting the same error after using "stdev".

**Comment by dbogdanov** [comment]
You need to install master
```
brew install essentia --HEAD
```
