### ISSUE TITLE
import Essentia Error, Library not loaded: /usr/local/lib/libswresample.1.dylib

### ISSUE THREAD

**Issue by ronggong** [MTG/essentia#573]
I need to use command line tool avconv in macOS, so I did `brew install libav`. I think brew install by default the newest version of libav 12. After installation of brew libav, I got essentia import error: 
`ImportError: dlopen(/usr/local/lib/python2.7/site-packages/essentia/_essentia.so, 2): Library not loaded: /usr/local/lib/libswresample.1.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/essentia/_essentia.so
  Reason: image not found`
I checked /usr/local/lib folder, only libswresample.2.dylib is found. So I am confused which version of libav should I install?

**Comment by alastair** [comment]
It's possible that installing avconv installed a new version of libav, and now the version that essentia is linked against no longer exists. Try and recompile essentia.

**Comment by ronggong** [comment]
great I recompiled using this http://essentia.upf.edu/documentation/installing.html#compiling-essentia, not by brew install essentia. It works, thanks!
