### ISSUE TITLE
cant find python version of streaming_extractor_archivemusicextractor

### ISSUE THREAD

**Issue by snape6666** [MTG/essentia#575]
Hi,

is there a python Version of the streaming_extractor_archivemusicextractor ? I would love to use this extractor in my python code, but iam not a programmer so i dont know how to use the cpp version in my py code.

OR is there a other way to get the mood, genre, danceability, timbre, genre_electronic, mood_aggressive etc... ?^^

Thx for helping me =)

**Comment by dbogdanov** [comment]
You can call command-line extractors from your python script using [os.system](https://docs.python.org/2/library/os.html#os.system).

You can also use a new algorithm MusicExtractor that you can call directly in Python, if you install essentia from [music_extractor_refactor branch](https://github.com/MTG/essentia/tree/music_extractor_refactor).

**Comment by snape6666** [comment]
I try to programm a real-time application that uses pyaudio to input the microphone. Is that also possible? I have to say that iam a novice in python programming :")

**Comment by snape6666** [comment]
nice the installation worked! Ill see if iam able to include the musicextractor into my code =)

**Comment by snape6666** [comment]
ok shit... the musicExtractor is for musicfiles... how can i use it with windowed audio from my microphone?

I use pyaudio to get the microphone signal:

########################################################################

p=pyaudio.PyAudio()
stream=p.open(format=pyaudio.paFloat32,channels=1,rate=RATE,input=True,
              frames_per_buffer=WINDOWSIZE)

frameBuffer = np.fromstring(stream.read(WINDOWSIZE),dtype=np.float32)

########################################################################

now i want to use this frameBuffer as a input for your musicExtractor... is there a way to do this?

**Comment by snape6666** [comment]
ok i tried musicextractor but it is very slow, has a "filename" input and doesnt extract timbre, mood and genre...

I want to write a applikation which is able to get the timbre, mood and genre out of the microphone input in "realtime". I would buffer some seconds of record to get a precise result but i want to be able to detect the mood like this applikation based on marsyas:

https://www.youtube.com/watch?v=NDLhrc_WR5Q

**Comment by snape6666** [comment]
when i change the cpp file do i have to recompile essentia? my idea was to change the Musicextractor.cpp input from "filename" to pool so i can input the audiostream from my microphone.

or do you have a easier solution?
