### ISSUE TITLE
How to run the examples in MacOS XCode

### ISSUE THREAD

**Issue by KonstantinosTro** [MTG/essentia#58]
Hello,

I am interested in using essentia library in MacOS XCode. I have succesfully installed the library. I am trying to compile the examples in the src/examples directory. 
- I include Essentia's headers properly (from /usr/local/include/essentia)
- I link against libessentia.a 

But I run into some errors. Below are the error and some screen shot which shows the settings of the projects.
Any help would be appreciated

Thanks,
Costas

Undefined symbols for architecture x86_64:
  "essentia::nameOfType(std::type_info const&)", referenced from:
      essentia::TypeProxy::checkType(std::type_info const&, std::type_info const&) const in main.o
  "essentia::ParameterMap::add(std::string const&, essentia::Parameter const&)", referenced from:
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&, std::string const&, essentia::Parameter const&) const in main.o
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&, std::string const&, essentia::Parameter const&, std::string const&, essentia::Parameter const&) const in main.o
  "essentia::loggerInstance", referenced from:
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&) const in main.o
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&, std::string const&, essentia::Parameter const&) const in main.o
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&, std::string const&, essentia::Parameter const&, std::string const&, essentia::Parameter const&) const in main.o
  "essentia::EssentiaFactoryessentia::standard::Algorithm::_instance", referenced from:
      essentia::EssentiaFactoryessentia::standard::Algorithm::instance() in main.o
  "essentia::debugIndentLevel", referenced from:
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&) const in main.o
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&, std::string const&, essentia::Parameter const&) const in main.o
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&, std::string const&, essentia::Parameter const&, std::string const&, essentia::Parameter const&) const in main.o
  "essentia::activatedDebugLevels", referenced from:
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&) const in main.o
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&, std::string const&, essentia::Parameter const&) const in main.o
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&, std::string const&, essentia::Parameter const&, std::string const&, essentia::Parameter const&) const in main.o
  "essentia::Pool::add(std::string const&, std::vector<float, std::allocator<float> > const&, bool)", referenced from:
      _main in main.o
  "essentia::init()", referenced from:
      _main in main.o
  "essentia::Logger::debug(essentia::DebuggingModule, std::string const&, bool)", referenced from:
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&) const in main.o
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&, std::string const&, essentia::Parameter const&) const in main.o
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&, std::string const&, essentia::Parameter const&, std::string const&, essentia::Parameter const&) const in main.o
  "essentia::shutdown()", referenced from:
      _main in main.o
  "essentia::standard::Algorithm::processingMode", referenced from:
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&) const in main.o
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&, std::string const&, essentia::Parameter const&) const in main.o
      essentia::EssentiaFactoryessentia::standard::Algorithm::create_i(std::string const&, std::string const&, essentia::Parameter const&, std::string const&, essentia::Parameter const&) const in main.o
  "essentia::standard::Algorithm::input(std::string const&)", referenced from:
      _main in main.o
  "essentia::standard::Algorithm::output(std::string const&)", referenced from:
      _main in main.o
  "essentia::Parameter::~Parameter()", referenced from:
      _main in main.o
      std::pair<std::string const, essentia::Parameter>::~pair() in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

![screen shot 2014-02-12 at 5 25 13 pm](https://f.cloud.github.com/assets/6659595/2146837/3947747e-93c8-11e3-803e-3c34d22ea5f1.png)

**Comment by jumeca** [comment]
I have installed essentia with homebrew but it is not making a static build so in the lib folder I don't have libessentia.a

Could you please guide me on how to install essentia and get a static library so I can follow these steps? Thank you
