### ISSUE TITLE
Metadata.py attribute error

### ISSUE THREAD

**Issue by kyorch** [MTG/essentia#583]
When i try to use Metadata.py i get this error:
   metadata.track >> (pool, 'metadata.tags.track')
AttributeError: 'StreamingAlgo' object has no attribute 'track'

**Comment by dbogdanov** [comment]
This is some outdated code (as folder name ```outdated``` suggest) that we'll cleanup. Just follow the [documentation for MetadataReader algorithm](http://essentia.upf.edu/documentation/reference/std_MetadataReader.html) and ```src/examples/python/extractor_metadata.py``` as an example of its use.
