### ISSUE TITLE
YamlInput: error during parsing: Error parsing json dictionary: expected '}' when using essentia_streaming_extractor_music_svm

### ISSUE THREAD

**Issue by yyf** [MTG/essentia#594]
Tried to use essentia_streaming_extractor_music_svm to get high-level features, but ran into some YamlInput error, any suggestion how to resolve this? Thanks 

users-MacBook-Pro:essentia-2.1_beta3 user$ ./build/src/examples/essentia_streaming_extractor_music_svm /Users/user/Code/test/2017/audio_samples/test.mp3 /Users/user/Code/test/2017/audio_samples\test_svm_out.txt

`adding SVM model: svm_models/danceability.history
adding SVM model: svm_models/gender.history
adding SVM model: svm_models/genre_dortmund.history
adding SVM model: svm_models/genre_electronic.history
adding SVM model: svm_models/genre_rosamerica.history
adding SVM model: svm_models/genre_tzanetakis.history
adding SVM model: svm_models/ismir04_rhythm.history
adding SVM model: svm_models/mood_acoustic.history
adding SVM model: svm_models/mood_aggressive.history
adding SVM model: svm_models/mood_electronic.history
adding SVM model: svm_models/mood_happy.history
adding SVM model: svm_models/mood_party.history
adding SVM model: svm_models/mood_relaxed.history
adding SVM model: svm_models/mood_sad.history
adding SVM model: svm_models/moods_mirex.history
adding SVM model: svm_models/timbre.history
adding SVM model: svm_models/tonal_atonal.history
adding SVM model: svm_models/voice_instrumental.history
skipping /Users/user/Code/test/2017/audio_samples/test.mp3 due to error: YamlInput: error during parsing: Error parsing json dictionary: expected '}'`

**Comment by YEL-Bazinga** [comment]
Using the streaming_extractor_music_svm tools , the input file should be .json/.yaml produced by streaming_extractor_music instead of the audio file.

**Comment by yyf** [comment]
Thanks @YEL-Bazinga
