### ISSUE TITLE
Difference between tonal.key_key and tonal.chords_key?

### ISSUE THREAD

**Issue by TheSaturn** [MTG/essentia#596]
Hello! 
What is the difference  between tonal.key_key and tonal.chords_key?
Also I wonder the same thing about tonal.hpcp and tonal.thpcp.
It's hard to find description of all features from MusicExtractor.

**Comment by alastair** [comment]
There is a list of algorithms used for each feature in the essentia documentation here: http://essentia.upf.edu/documentation/streaming_extractor_music.html

Specifically, `key_key` comes from http://essentia.upf.edu/documentation/reference/streaming_Key.html
and `chords_key` from http://essentia.upf.edu/documentation/reference/streaming_ChordsDescriptors.html

**Comment by TheSaturn** [comment]
So, What is the difference between tonal.hpcp and tonal.thpcp?
Also I don't undestand what is key_key.

**Comment by alastair** [comment]
`key_key` is the `key` output from the Key algorithm. `key_scale` is the `scale` output from the Key algorithm.

**Comment by TheSaturn** [comment]
I don't say anything about `key_scale`. I asked about `key_key` and `chords_key`. `chords_key` is mean of chords progression. But what is `key_key`?

**Comment by dbogdanov** [comment]
The ```key_key``` and ```key_scale``` are overall key/scale estimations using the average HPCP  of the whole audio input.  The ```chords_key``` and  ```chords_scale``` are overall key/scale estimations done by first extracting chords on segments of the input audio, and then summarizing them.

If you have to select between them,  the ```key_key``` and ```key_scale``` are more robust. We plan to improve the ```chords_key``` and  ```chords_scale``` estimations.
