### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by ghost** [MTG/essentia#599]
<p><h1>please add a class to this repository that does the following:</h1><br/><br/></p>
<body><p>- <i>grabs each one of the feature parameters;</i><br/>
- <i>has a root frequency for bandpass filtering</i><br/>
- <i>calculates periodicity regularity and activity over that, plus raw values</i><br/>
- <i>creates a dataset with that info;</i><br/>
- <i>runs that throughout tensorflow</i><br/></p></body>

**Comment by dbogdanov** [comment]
It is not clear what you are referring to. You should provide more details: which features, type of periodicity, what activity?
