### ISSUE TITLE
Index out of range while configuring Gaia --with-python-bindings on macOS Sierra

### ISSUE THREAD

**Issue by petrovrus** [MTG/essentia#602]
[Disclaimer] I know, that that's essentia issues section, but in both MTG/gaia (date of last comment is 13 Oct 2016) and MTG/homebrew-essentia (last comment - more than month ago) sections I had no comments for half a month, so I decided to ask here.
Here's the problem: 
After "brew install gaia --HEAD" command I get this error.
![c14d5a0e-2f8e-11e7-93e4-247465ea3455](https://cloud.githubusercontent.com/assets/16647771/26032352/0c9cf6ea-389a-11e7-8eef-1bf6a62dabd4.png)
I've seen that this issue was resolved, but didn't find a solution in gaia documentation.
Could you send me direct link to solution of my problem in gaia documentation (if you know where), or give an advise, how to deal with it? I would really appreciate any ideas!

**Comment by dbogdanov** [comment]
I have updated the formula for gaia, please try installing again. It should work now.

**Comment by petrovrus** [comment]
Yes, problem solved, thanks a lot!
