### ISSUE TITLE
Question: Building Essentia on Raspberry

### ISSUE THREAD

**Issue by snape6666** [MTG/essentia#603]
Hi, does anybody has any experience in building essentia on a Raspberry 3?

I tried to build it, but had many problems with Gaia and some other libraries...

First: ist it possible to get it running on the raspi?

second: What do i have to do to get it running?

thx!! =)

**Comment by alastair** [comment]
We have a long-open pull request that we haven't been able to verify because of lack of hardware to test on. You might have some success with it: https://github.com/MTG/essentia/pull/258

**Comment by wanda-happi** [comment]
Hi, does anybody managed to install (build) essentia on a Raspberry pi? if yes which steps you followed?
Thks

**Comment by dbogdanov** [comment]
PR #807 addresses this, closing.

**Comment by jivido** [comment]
In case anyone gets here, just like me, looking for more Raspberry Pi install info:
I managed to install Essentia 2.1 beta5 on Raspberry Pi 3B with the normal install-instructions, but I needed to configure like this:
./waf configure --no-msse
