### ISSUE TITLE
Documentation out of sync (streaming vs standard)

### ISSUE THREAD

**Issue by brodin** [MTG/essentia#605]
The documentation for ReplayGain for streaming (http://essentia.upf.edu/documentation/reference/streaming_ReplayGain.html) and standard (http://essentia.upf.edu/documentation/reference/std_ReplayGain.html) differs. Is this by design?

**Comment by brodin** [comment]
@dbogdanov who is best suited to answer this? I guess that the logic should be same; and then the documentation should be the same? But which one is more up-to-date?

**Comment by dbogdanov** [comment]
Yes, there is a difference by design. I've improved the doc in a8eabcbcfdf6c829d51adead012a561dc46b9be6 and it is available online now. We should think to make ``applyEqloud`` option also available in the standard mode.
