### ISSUE TITLE
Essentia in ubuntuserver not compiling examples

### ISSUE THREAD

**Issue by FRD93** [MTG/essentia#610]
Hello everybody,

I've just "installed" Essentia in an ubuntu server (version 14.04.5). Building works fine, but if I try to configure the build with examples (e.g.: "./waf configure --with-examples"), no ./build/src/examples/ folder is created, and so no example is currently being built.
Does anyone had the same issue? 

Thanks,
FD

**Comment by alastair** [comment]
What version of essentia are you trying to install? What is the output of `waf configure` ?
If you're running ubuntu 14.04 and a recent version of essentia (or git HEAD) then my guess is that you have an incompatible version of libav/ffmpeg and therefore you are not building the `AudioLoader` algorithm, which all examples need to open audio files. The output of waf configure should tell you this.

**Comment by FRD93** [comment]
Thank you very much, that was exactly the problem: libavcodec was not up to date! Updated and everything worked.
