### ISSUE TITLE
Problem with essentia_streaming_extractor_music

### ISSUE THREAD

**Issue by sslee70** [MTG/essentia#611]
Hi,
 
I’m so lucky that I found this amazing research and development results, and I so appreciate all your works.
 
I have been using the Essentia example extractors on Ubuntu 16.04 for a while.  Recently, I tried again to compile Gaia and Essentia on Ubuntu 16.04 with Intel i7 processor, 16 GB RAM, etc.  I guess everything went well.  However, this time I became to get the following unknown execution result.
 
> essentia_streaming_extractor_music sample.wav - essentia.profile
Descriptor name 'highlevel.svm_models' of type std::vector<std::string> not found
 
where ‘the essentia.profile’ looks like the following:
 
> analysisSampleRate: 44100
startTime: 0
endTime: 10
highlevel:
    compute: 1
 
I do have the svm_model directory in the same directory where I’m running the above command.  Would you please tell me why I get the above error message?
 
To help you help me, here’s the list of what I did for the installation.

- I installed ‘swig’ of version 3.0.12 under /usr/local/{bin, lib} by compiling it from the source.
- I installed Gaia with the following steps:
    - ./waf configure --with-python-bindings --with-asserts --with-cyclops
    - ./waf
    - ./waf install
- Then, I installed Essentia with the following steps:
    - ./waf configure --mode=release --build-static --with-python --with-cpptests --with-examples --with-vamp --with-gaia
    - ./waf
    - ./waf install

Throughout the above steps, I couldn’t find any suspicious clues.  Please help me with this.
 
Thanks,
Scott

**Comment by dbogdanov** [comment]
As you have specified to compute highlevel models (```compute: 1```) it is expected that you also provide a list of models to run in the profile file. Follow [an example in the documentation](http://essentia.upf.edu/documentation/streaming_extractor_music.html#configuration). You have to specify ```svm_models``` in the profile.
