### ISSUE TITLE
The problem when compiling the Essentia and Gaia in  QT 5.9.0

### ISSUE THREAD

**Issue by alyfreym** [MTG/essentia#613]
Hi guys!.  I configured essentia using: `./waf configure --lightweight= --fft=KISS --build-static --with-gaia`, and install. Configured gaia using: `./waf configure`  and install. Next i add libessentia.a and libgaia2.a in my project. When I start compiling, I get such an error: 

> Undefined symbols for architecture x86_64:
>   "QVariant::canConvert(QVariant::Type) const", referenced from:
      gaia2::Parameter::toArrayReal() const in libgaia2.a(parameter.cpp.1.o)
      gaia2::Parameter::toRealDescriptor() const in libgaia2.a(parameter.cpp.1.o)
      gaia2::Parameter::toStringDescriptor() const in libgaia2.a(parameter.cpp.1.o)
  "typeinfo for QtConcurrent::ThreadEngineBase", referenced from:
      typeinfo for QtConcurrent::ThreadEngine<gaia2::Point*> in libgaia2.a(dataset.cpp.1.o)
  "_yaml_document_end_event_initialize", referenced from:
      gaia2::yaml::dump(gaia2::yaml::Node const&) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_document_start_event_initialize", referenced from:
      gaia2::yaml::dump(gaia2::yaml::Node const&) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_emitter_delete", referenced from:
      gaia2::yaml::dump(gaia2::yaml::Node const&) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_emitter_emit", referenced from:
      gaia2::yaml::dumpObject(yaml_emitter_s*, gaia2::yaml::Node const&) in libgaia2.a(yamlcpp.cpp.1.o)
      gaia2::yaml::dump(gaia2::yaml::Node const&) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_emitter_initialize", referenced from:
      gaia2::yaml::dump(gaia2::yaml::Node const&) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_emitter_set_output", referenced from:
      gaia2::yaml::dump(gaia2::yaml::Node const&) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_event_delete", referenced from:
      gaia2::yaml::load(char const*, unsigned int, bool) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_mapping_end_event_initialize", referenced from:
      gaia2::yaml::dumpObject(yaml_emitter_s*, gaia2::yaml::Node const&) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_mapping_start_event_initialize", referenced from:
      gaia2::yaml::dumpObject(yaml_emitter_s*, gaia2::yaml::Node const&) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_parser_delete", referenced from:
      gaia2::yaml::load(char const*, unsigned int, bool) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_parser_initialize", referenced from:
      gaia2::yaml::load(char const*, unsigned int, bool) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_parser_parse", referenced from:
      gaia2::yaml::load(char const*, unsigned int, bool) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_parser_set_input_string", referenced from:
      gaia2::yaml::load(char const*, unsigned int, bool) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_scalar_event_initialize", referenced from:
      gaia2::yaml::dumpObject(yaml_emitter_s*, gaia2::yaml::Node const&) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_sequence_end_event_initialize", referenced from:
      gaia2::yaml::dumpObject(yaml_emitter_s*, gaia2::yaml::Node const&) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_sequence_start_event_initialize", referenced from:
      gaia2::yaml::dumpObject(yaml_emitter_s*, gaia2::yaml::Node const&) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_stream_end_event_initialize", referenced from:
      gaia2::yaml::dump(gaia2::yaml::Node const&) in libgaia2.a(yamlcpp.cpp.1.o)
  "_yaml_stream_start_event_initialize", referenced from:
      gaia2::yaml::dump(gaia2::yaml::Node const&) in libgaia2.a(yamlcpp.cpp.1.o)

> "qt_message_output(QtMsgType, char const*)", referenced from:
      QDebug::~QDebug() in libgaia2.a(dataset.cpp.1.o)
  "qHash(QString const&)", referenced from:
      QHash<QString, QHashDummyValue>::insert(QString const&, QHashDummyValue const&) in libgaia2.a(pointlayout.cpp.1.o)
      QSet<QString>::subtract(QSet<QString> const&) in libgaia2.a(pointlayout.cpp.1.o)
      QHash<QString, QHashDummyValue>::remove(QString const&) in libgaia2.a(pointlayout.cpp.1.o)
      QSet<QString>::intersect(QSet<QString> const&) in libgaia2.a(pointlayout.cpp.1.o)
      QSet<QString>::intersect(QSet<QString> const&) in libgaia2.a(utils.cpp.1.o)
      QHash<QString, QHashDummyValue>::insert(QString const&, QHashDummyValue const&) in libgaia2.a(utils.cpp.1.o)
      QHash<QString, QHashDummyValue>::remove(QString const&) in libgaia2.a(utils.cpp.1.o)
      ...
  "QByteArray::shared_null", referenced from:
      gaia2::SVMPredict::SVMPredict(gaia2::Transformation const&) in libgaia2.a(svmpredict.cpp.1.o)
      gaia2::DataSet::toBase64() const in libgaia2.a(dataset.cpp.1.o)
      gaia2::Parameter::Parameter(gaia2::PointLayout const&) in libgaia2.a(parameter.cpp.1.o)
      gaia2::yaml::dump(gaia2::yaml::Node const&) in libgaia2.a(yamlcpp.cpp.1.o)
      gaia2::Point::toBase64() const in libgaia2.a(point.cpp.1.o)
  "QByteArray::realloc(int)", referenced from:
      gaia2::GaiaException::what() const in libgaia2.a(distancefunction.cpp.1.o)
      operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, QString const&) in libgaia2.a(applier.cpp.1.o)
      gaia2::GaiaException::what() const in libgaia2.a(applier.cpp.1.o)
      gaia2::GaiaException::what() const in libgaia2.a(analyzer.cpp.1.o)
      gaia2::GaiaException::what() const in libgaia2.a(frozendistance.cpp.1.o)
      gaia2::parser::FilterParser::parseFilter(QString const&) const in libgaia2.a(filter.cpp.1.o)
      gaia2::GaiaException::what() const in libgaia2.a(filter.cpp.1.o)
      ...
  "QByteArray::QByteArray(char const*)", referenced from:
      QTextCodec::codecForName(char const*) in libgaia2.a(gaia.cpp.1.o)
  "QVectorData::reallocate(QVectorData*, int, int, int)", referenced from:
      QVector<gaia2::Point*>::realloc(int, int) in libgaia2.a(applier.cpp.1.o)
      QVector<float>::realloc(int, int) in libgaia2.a(frozendistance.cpp.1.o)
      QVector<int>::realloc(int, int) in libgaia2.a(filter.cpp.1.o)
      QVector<gaia2::Point*>::realloc(int, int) in libgaia2.a(svmpredict.cpp.1.o)
      QVector<gaia2::Point*>::realloc(int, int) in libgaia2.a(addfieldapplier.cpp.1.o)
      QVector<gaia2::Point*>::realloc(int, int) in libgaia2.a(enumerateapplier.cpp.1.o)
      QVector<int>::realloc(int, int) in libgaia2.a(utils.cpp.1.o)
      ...
  "QVectorData::shared_null", referenced from:
      gaia2::FrozenCosineAngleDistance::FrozenCosineAngleDistance(gaia2::FrozenDataSet const&, gaia2::ParameterMap const&) in libgaia2.a(frozendistance.cpp.1.o)
      gaia2::createIndexMappings(gaia2::PointLayout const&, gaia2::PointLayout&, gaia2::Region const&, QList<QPair<gaia2::Segment, gaia2::Segment> >&, QList<QPair<gaia2::Segment, gaia2::Segment> >&, QList<QPair<gaia2::Segment, gaia2::Segment> >&) in libgaia2.a(utils.cpp.1.o)
      gaia2::LinearCombinationDistance::LinearCombinationDistance(gaia2::PointLayout const&, gaia2::ParameterMap const&) in libgaia2.a(linearcombinationdistance.cpp.1.o)
      gaia2::RCA::analyze(gaia2::DataSet const*, gaia2::Region const&) const in libgaia2.a(rca.cpp.1.o)
      gaia2::RCA::getChunkletsFromMap(QMap<QString, QString> const&, gaia2::DataSet const*) in libgaia2.a(rca.cpp.1.o)
      QVector<gaia2::Point*>::clear() in libgaia2.a(dataset.cpp.1.o)
      gaia2::DataSet::addPoints(QVector<gaia2::Point*> const&, bool, bool, bool, bool, bool) in libgaia2.a(dataset.cpp.1.o)
      ...
  "QVectorData::free(QVectorData*, int)", referenced from:
      gaia2::Applier::mapDataSet(gaia2::DataSet const*) const in libgaia2.a(applier.cpp.1.o)
      QVector<gaia2::Point*>::realloc(int, int) in libgaia2.a(applier.cpp.1.o)
      gaia2::FrozenCosineAngleDistance::FrozenCosineAngleDistance(gaia2::FrozenDataSet const&, gaia2::ParameterMap const&) in libgaia2.a(frozendistance.cpp.1.o)
      QVector<float>::realloc(int, int) in libgaia2.a(frozendistance.cpp.1.o)
      gaia2::FrozenCosineAngleDistance::~FrozenCosineAngleDistance() in libgaia2.a(frozendistance.cpp.1.o)
      gaia2::parser::ValueVariable::bind(gaia2::PointLayout const&, gaia2::Point const**) in libgaia2.a(filter.cpp.1.o)
      QVector<int>::realloc(int, int) in libgaia2.a(filter.cpp.1.o)
      ...
  "QVectorData::grow(int, int, int, bool)", referenced from:
      gaia2::FrozenCosineAngleDistance::init(int, int) in libgaia2.a(frozendistance.cpp.1.o)
      gaia2::LinearCombinationDistance::LinearCombinationDistance(gaia2::PointLayout const&, gaia2::ParameterMap const&) in libgaia2.a(linearcombinationdistance.cpp.1.o)
      gaia2::LinearCombinationDistance::addDistance(gaia2::DistanceFunction*, float) in libgaia2.a(linearcombinationdistance.cpp.1.o)
      gaia2::RCA::getChunkletsFromMap(QMap<QString, QString> const&, gaia2::DataSet const*) in libgaia2.a(rca.cpp.1.o)
      gaia2::DataSet::copy() const in libgaia2.a(dataset.cpp.1.o)
      gaia2::DataSet::load(QDataStream&, int, int, bool) in libgaia2.a(dataset.cpp.1.o)
      gaia2::DataSet::addPoints(QVector<gaia2::Point*> const&, bool, bool, bool, bool, bool) in libgaia2.a(dataset.cpp.1.o)
      ...
  "QVectorData::allocate(int, int)", referenced from:
      gaia2::Applier::mapDataSet(gaia2::DataSet const*) const in libgaia2.a(applier.cpp.1.o)
      QVector<gaia2::Point*>::realloc(int, int) in libgaia2.a(applier.cpp.1.o)
      QVector<float>::realloc(int, int) in libgaia2.a(frozendistance.cpp.1.o)
      QVector<int>::realloc(int, int) in libgaia2.a(filter.cpp.1.o)
      gaia2::SVMPredict::mapDataSet(gaia2::DataSet const*) const in libgaia2.a(svmpredict.cpp.1.o)
      QVector<gaia2::Point*>::realloc(int, int) in libgaia2.a(svmpredict.cpp.1.o)
      gaia2::AddFieldApplier::mapDataSet(gaia2::DataSet const*) const in libgaia2.a(addfieldapplier.cpp.1.o)
      ...
  "QtConcurrent::ResultStoreBase::addResults(int, void const*, int, int)", referenced from:
      QtConcurrent::ResultStore<gaia2::Point*>::addResults(int, QVector<gaia2::Point*> const*, int) in libgaia2.a(dataset.cpp.1.o)

And more... If you need all the errors, tell me, I'll give them to you.
Of course I followed the descriptions of the installation.

If I compile essentia without using gala: `./waf configure --lightweight= --fft=KISS --build-static
./waf install`
 everything works fine

I assume that I did not correctly compile gaya, but I can not understand what I'm doing wrong, if someone has encountered such a problem, please let me know. If you need any additional information, tell me. Thank you. Sorry for my English

**Comment by alastair** [comment]
Hi,
From the description your issue I think you have compiled essentia and now you want to link libessentia.a and libgaia.a into another C/C++ program which you have written.

It looks like you have a linking issue - that is, the essenta and gaia libraries also need other dependencies to run, libyaml, libqt, libavcodec, etc. When you compile your own program you will need to include these, for example

    gcc myprogram.cpp libessentia.a libgaia.a -o myprogram -lyaml -lavcodec -lfftw3 -lqtcore

Look at the files `build/essentia.pc` (for essentia) and `build/gaia2.pc` (for gaia) to see a list of the libraries that you need to link with.

**Comment by alyfreym** [comment]
Hi  **alastair**, Thank you for your comment, I had a error related to libyaml, after connecting the static library to my project `LIBS += /usr/local/Cellar/libyaml/0.1.7/lib/libyaml.a`,  this solved the problem associated with this error. Next I proceeded to solve the problems with QtCore. All my remaining errors are associated with QtCore. Having opened `build/gaia2.pc`, I hired that this: `qtlibdir=-F/usr/local/Cellar/qt@4/4.8.7_1/lib -framework QtCore`.  Hence, gaya2 uses very old Qt version, but my version is `5.9.0`.  QtCore automatically linked in my project, should be gaia2 does not work with the new version Qt `5.9.0` ? Of course I may be wrong. If you have any comments, please write. Thank you. Again  sorry for my English).

**Comment by dbogdanov** [comment]
Hey, @alyfreym. QT5 is not supported by gaia, try building with QT4.

**Comment by alyfreym** [comment]
**dbogdanov** Ok. Thank you.
