### ISSUE TITLE
Building static-examples fails on ubuntu

### ISSUE THREAD

**Issue by FRD93** [MTG/essentia#615]
Hello everyone,

I'm trying to build static examples on Ubuntu 14.04 (normal build --with-examples works fine). I've done all the steps suggested in FAQ, as:
1) apt-get install yasm cmake
2) packaging/build_3rdparty_static_debian.sh
3) ./waf configure  --with-static-examples
When running "./waf" (both with or without "sudo"), the output is as follows:

Waf: Entering directory `/home/arcslab/Documents/Dependencies/APR/essentia-master/build'
→ building from /home/arcslab/Documents/Dependencies/APR/essentia-master
→ building from /home/arcslab/Documents/Dependencies/APR/essentia-master/src
Building all the algorithms
Ignoring the following algorithms: IFFTK, MusicExtractorSVM, IFFTA, FFTK, GaiaTransform, FFTA
Created algorithms registration file
→ building from /home/arcslab/Documents/Dependencies/APR/essentia-master/src/examples
[259/331] Linking build/src/examples/essentia_standard_beatsmarker
[261/331] Linking build/src/examples/essentia_standard_fadedetection
[263/331] Linking build/src/examples/essentia_standard_mfcc
[267/331] Linking build/src/examples/essentia_standard_onsetrate
/usr/bin/ld: cannot find -ltag
/usr/bin/ld: cannot find -ltag
/usr/local/lib/libavformat.a(rtpproto.o): In function `rtp_resolve_host':
/home/arcslab/Documents/Dependencies/APR/libav/libavformat/rtpproto.c:136: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status

/usr/bin/ld: cannot find -ltag
/usr/bin/ld: cannot find -ltag
/usr/local/lib/libavformat.a(rtpproto.o): In function `rtp_resolve_host':
/home/arcslab/Documents/Dependencies/APR/libav/libavformat/rtpproto.c:136: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status

/usr/bin/ld: cannot find -ltag
/usr/bin/ld: cannot find -ltag
/usr/local/lib/libavformat.a(rtpproto.o): In function `rtp_resolve_host':
/home/arcslab/Documents/Dependencies/APR/libav/libavformat/rtpproto.c:136: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status

/usr/bin/ld: cannot find -ltag
/usr/bin/ld: cannot find -ltag
/usr/local/lib/libavformat.a(rtpproto.o): In function `rtp_resolve_host':
/home/arcslab/Documents/Dependencies/APR/libav/libavformat/rtpproto.c:136: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/arcslab/Documents/Dependencies/APR/essentia-master/build'
Build failed
 -> task in 'essentia_standard_beatsmarker' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_standard_mfcc' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_standard_onsetrate' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_standard_fadedetection' failed with exit status 1 (run with -v to display more information)

so, if I run it with verbose option, I get:

Waf: Entering directory `/home/arcslab/Documents/Dependencies/APR/essentia-master/build'
→ building from /home/arcslab/Documents/Dependencies/APR/essentia-master
→ building from /home/arcslab/Documents/Dependencies/APR/essentia-master/src
Building all the algorithms
Ignoring the following algorithms: IFFTK, MusicExtractorSVM, IFFTA, FFTK, GaiaTransform, FFTA
Created algorithms registration file
→ building from /home/arcslab/Documents/Dependencies/APR/essentia-master/src/examples
[259/331] Linking build/src/examples/essentia_standard_beatsmarker
20:30:55 runner ['/usr/bin/g++', '-static', 'src/examples/standard_beatsmarker.cpp.1.o', '-o/home/arcslab/Documents/Dependencies/APR/essentia-master/build/src/examples/essentia_standard_beatsmarker', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bstatic', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-lavformat', '-lavcodec', '-lavutil', '-ltag', '-lfftw3f', '-lavformat', '-lavcodec', '-lavutil', '-lavresample', '-lsamplerate', '-ltag', '-lyaml']
[261/331] Linking build/src/examples/essentia_standard_fadedetection
20:30:55 runner ['/usr/bin/g++', '-static', 'src/examples/standard_fadedetection.cpp.2.o', '-o/home/arcslab/Documents/Dependencies/APR/essentia-master/build/src/examples/essentia_standard_fadedetection', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bstatic', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-lavformat', '-lavcodec', '-lavutil', '-ltag', '-lfftw3f', '-lavformat', '-lavcodec', '-lavutil', '-lavresample', '-lsamplerate', '-ltag', '-lyaml']
[263/331] Linking build/src/examples/essentia_standard_mfcc
20:30:55 runner ['/usr/bin/g++', '-static', 'src/examples/standard_mfcc.cpp.3.o', '-o/home/arcslab/Documents/Dependencies/APR/essentia-master/build/src/examples/essentia_standard_mfcc', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bstatic', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-lavformat', '-lavcodec', '-lavutil', '-ltag', '-lfftw3f', '-lavformat', '-lavcodec', '-lavutil', '-lavresample', '-lsamplerate', '-ltag', '-lyaml']
[270/331] Linking build/src/examples/essentia_standard_onsetrate
20:30:55 runner ['/usr/bin/g++', '-static', 'src/examples/standard_onsetrate.cpp.4.o', '-o/home/arcslab/Documents/Dependencies/APR/essentia-master/build/src/examples/essentia_standard_onsetrate', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bstatic', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-lavformat', '-lavcodec', '-lavutil', '-ltag', '-lfftw3f', '-lavformat', '-lavcodec', '-lavutil', '-lavresample', '-lsamplerate', '-ltag', '-lyaml']
/usr/bin/ld: cannot find -ltag
/usr/bin/ld: cannot find -ltag
/usr/local/lib/libavformat.a(rtpproto.o): In function `rtp_resolve_host':
/home/arcslab/Documents/Dependencies/APR/libav/libavformat/rtpproto.c:136: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status

/usr/bin/ld: cannot find -ltag
/usr/bin/ld: cannot find -ltag
/usr/local/lib/libavformat.a(rtpproto.o): In function `rtp_resolve_host':
/home/arcslab/Documents/Dependencies/APR/libav/libavformat/rtpproto.c:136: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status

/usr/bin/ld: cannot find -ltag
/usr/bin/ld: cannot find -ltag
/usr/local/lib/libavformat.a(rtpproto.o): In function `rtp_resolve_host':
/home/arcslab/Documents/Dependencies/APR/libav/libavformat/rtpproto.c:136: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status

/usr/bin/ld: cannot find -ltag
/usr/bin/ld: cannot find -ltag
/usr/local/lib/libavformat.a(rtpproto.o): In function `rtp_resolve_host':
/home/arcslab/Documents/Dependencies/APR/libav/libavformat/rtpproto.c:136: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/arcslab/Documents/Dependencies/APR/essentia-master/build'
Build failed
 -> task in 'essentia_standard_fadedetection' failed with exit status 1: 
	{task 140337417116400: cxxprogram standard_fadedetection.cpp.2.o -> essentia_standard_fadedetection}
['/usr/bin/g++', '-static', 'src/examples/standard_fadedetection.cpp.2.o', '-o/home/arcslab/Documents/Dependencies/APR/essentia-master/build/src/examples/essentia_standard_fadedetection', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bstatic', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-lavformat', '-lavcodec', '-lavutil', '-ltag', '-lfftw3f', '-lavformat', '-lavcodec', '-lavutil', '-lavresample', '-lsamplerate', '-ltag', '-lyaml']
 -> task in 'essentia_standard_beatsmarker' failed with exit status 1: 
	{task 140337417116320: cxxprogram standard_beatsmarker.cpp.1.o -> essentia_standard_beatsmarker}
['/usr/bin/g++', '-static', 'src/examples/standard_beatsmarker.cpp.1.o', '-o/home/arcslab/Documents/Dependencies/APR/essentia-master/build/src/examples/essentia_standard_beatsmarker', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bstatic', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-lavformat', '-lavcodec', '-lavutil', '-ltag', '-lfftw3f', '-lavformat', '-lavcodec', '-lavutil', '-lavresample', '-lsamplerate', '-ltag', '-lyaml']
 -> task in 'essentia_standard_mfcc' failed with exit status 1: 
	{task 140337417116560: cxxprogram standard_mfcc.cpp.3.o -> essentia_standard_mfcc}
['/usr/bin/g++', '-static', 'src/examples/standard_mfcc.cpp.3.o', '-o/home/arcslab/Documents/Dependencies/APR/essentia-master/build/src/examples/essentia_standard_mfcc', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bstatic', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-lavformat', '-lavcodec', '-lavutil', '-ltag', '-lfftw3f', '-lavformat', '-lavcodec', '-lavutil', '-lavresample', '-lsamplerate', '-ltag', '-lyaml']
 -> task in 'essentia_standard_onsetrate' failed with exit status 1: 
	{task 140337417116800: cxxprogram standard_onsetrate.cpp.4.o -> essentia_standard_onsetrate}
['/usr/bin/g++', '-static', 'src/examples/standard_onsetrate.cpp.4.o', '-o/home/arcslab/Documents/Dependencies/APR/essentia-master/build/src/examples/essentia_standard_onsetrate', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bstatic', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-L/usr/local/lib', '-lavformat', '-lavcodec', '-lavutil', '-ltag', '-lfftw3f', '-lavformat', '-lavcodec', '-lavutil', '-lavresample', '-lsamplerate', '-ltag', '-lyaml']

Since I wasn't able to find an answer to this problem googling on the web, I'm trying here. 

Thanks in advance, best,
FD

**Comment by dbogdanov** [comment]
Taglib cannot be found when linking. How does your build/config.log file look like?

**Comment by dbogdanov** [comment]
No reply. Closing.
