### ISSUE TITLE
./waf build fail - TagLib

### ISSUE THREAD

**Issue by katpi** [MTG/essentia#619]
Hello,
I'm trying to run the script ./waf and when I use flags `--mode=release --build-static --with-python --with-cpptests --with-examples --with-vamp`, I always get stuck at the file metadatareader.cpp. Stacktrace:

`[338/374] Linking build/src/examples/essentia_standard_beatsmarker
	[339/374] Linking build/src/examples/essentia_standard_onsetrate
	src/libessentia.a(metadatareader.cpp.1.o): In function `formatString(TagLib::StringList const&)':
	metadatareader.cpp:(.text+0x14f1): undefined reference to `TagLib::String::to8Bit(bool) const'
	metadatareader.cpp:(.text+0x157d): undefined reference to `TagLib::String::to8Bit(bool) const'
	metadatareader.cpp:(.text+0x15b4): undefined reference to `TagLib::String::to8Bit(bool) const'
	src/libessentia.a(metadatareader.cpp.1.o): In function `essentia::standard::MetadataReader::compute()':
	metadatareader.cpp:(.text+0x2a85): undefined reference to `TagLib::String::to8Bit(bool) const'
	metadatareader.cpp:(.text+0x2c67): undefined reference to `TagLib::String::to8Bit(bool) const'
	collect2: error: ld returned 1 exit status

	src/libessentia.a(metadatareader.cpp.1.o): In function `formatString(TagLib::StringList const&)':
	metadatareader.cpp:(.text+0x14f1): undefined reference to `TagLib::String::to8Bit(bool) const'
	metadatareader.cpp:(.text+0x157d): undefined reference to `TagLib::String::to8Bit(bool) const'
	metadatareader.cpp:(.text+0x15b4): undefined reference to `TagLib::String::to8Bit(bool) const'
	src/libessentia.a(metadatareader.cpp.1.o): In function `essentia::standard::MetadataReader::compute()':
	metadatareader.cpp:(.text+0x2a85): undefined reference to `TagLib::String::to8Bit(bool) const'
	metadatareader.cpp:(.text+0x2c67): undefined reference to `TagLib::String::to8Bit(bool) const'
	collect2: error: ld returned 1 exit status

	Waf: Leaving directory `/home/kapi/essentia/build'
	Build failed
	 -> task in 'essentia_standard_beatsmarker' failed with exit status 1 (run with -v to display more information)
	 -> task in 'essentia_standard_onsetrate' failed with exit status 1 (run with -v to display more information)
`
I tried installing both the newest (1.11.1) and one of the older (1.9) versions of the TagLib. What can I do to make it work? My operating system is Ubuntu 16.04 LTS.

**Comment by dbogdanov** [comment]
What version of Essentia are you building? Building from the master branch works perfectly fine for me on Ubuntu 16.04 using the same configuration flags. My libtag1-dev package version is ```1.9.1-2.4ubuntu1```

**Comment by katpi** [comment]
I try to build current top version cloned by git today:

`git clone https://github.com/MTG/essentia.git`

so I think that current master should build.
When I run 

> sudo apt-get install libtag1-dev

 I receive information that:

> libtag1-dev is already the newest version (1.9.1-2.4ubuntu1).

Is there any possibility that there is other reason that I receive error:

> undefined reference to `TagLib::String::to8Bit(bool) const'

like cmake version or gcc version problem? My current gcc is `gcc (Ubuntu 4.9.3-13ubuntu2) 4.9.3`, my current cmake is `cmake version 3.5.2`.

**Comment by laloutre12** [comment]
Hi there,

I think i have a related problem.

I'm on Ubuntu 16.04,
> libtag1-dev is already the newest version (1.9.1-2.4ubuntu1).

compilation was giving me the error mentionned by  @katpi. I installed the newest taglib from sources (TagLib 1.11.1) and the error has changed but still related.

`./waf configure --mode=release --build-static --with-python --with-cpptests --with-examples --with-vamp`

>...
 [321/376] Compiling src/3rdparty/vamp-plugin-sdk-2.4/src/vamp-sdk/RealTime.cpp
[322/376] Linking build/src/python/_essentia.so
/usr/bin/ld: /usr/local/lib/libtag.a(tstring.cpp.o): réadressage de R_X86_64_32S en vertu de « _ZTVN6TagLib6StringE » ne peut être utilisé lors de la création d'un objet partagé; recompilez avec -fPIC
/usr/local/lib/libtag.a : erreur lors de l'ajout de symboles : Mauvaise valeur
collect2: error: ld returned 1 exit status

> Waf: Leaving directory `/home/sebastien/Dropbox/projects/essentia/build'
Build failed task in '_essentia' failed with exit status 1 (run with -v to display more information)


My system is in french so i should translate a bit : 

> /usr/bin/ld: /usr/local/lib/libtag.a(tstring.cpp.o): readress of R_X86_64_32S in virtue of « _ZTVN6TagLib6StringE » can't be used during the creation of a shared object; recompile with -fPIC
/usr/local/lib/libtag.a : error adding symbols : Bad value

**Comment by dbogdanov** [comment]
Try without ```--build-static```, does it work?

**Comment by laloutre12** [comment]
no,
same thing : 

> ./waf configure --mode=release --with-python --with-cpptests --with-examples --with-vamp


> [259/259] Linking build/src/libessentia.so
/usr/bin/ld: /usr/local/lib/libtag.a(tstring.cpp.o): réadressage de R_X86_64_32S en vertu de « _ZTVN6TagLib6StringE » ne peut être utilisé lors de la création d'un objet partagé; recompilez avec -fPIC
/usr/local/lib/libtag.a : erreur lors de l'ajout de symboles : Mauvaise valeur
collect2: error: ld returned 1 exit status

**Comment by dbogdanov** [comment]
@laloutre12  Now, it is still trying to link to the static library file for taglib found in your ```/usr/local/lib```. The ```/usr/local/lib``` has a priority over the standard installation path (for apt-get) ```/usr/lib```.

To link agains the taglib installed with apt-get, remove the taglib installed from source from ```/usr/local```and try again.

**Comment by laloutre12** [comment]
Yep, you were right, so i'm back to the first problem now :/

> ./waf configure --mode=release --with-cpptests --with-examples --with-vamp --with-python

> ...
[339/376] Compiling test/src/basetest/test_vectoroutput.cpp
[340/376] Linking build/src/examples/essentia_standard_onsetrate
[341/376] Linking build/src/examples/essentia_standard_mfcc
src/libessentia.so : référence indéfinie vers « TagLib::String::to8Bit(bool) const »
collect2: error: ld returned 1 exit status
src/libessentia.so : référence indéfinie vers « TagLib::String::to8Bit(bool) const »
collect2: error: ld returned 1 exit status

**Comment by dbogdanov** [comment]
Just in case, how does your ```config.log``` look like?

You should have the same lines:
``
Checking for 'taglib' >= 1.9
['/usr/bin/pkg-config', 'taglib >= 1.9', '--cflags', '--libs', 'taglib']
out: -I/usr/include/taglib -ltag
```

**Comment by laloutre12** [comment]
here it is yes.
> Checking for 'taglib' >= 1.9
['/usr/bin/pkg-config', 'taglib >= 1.9', '--cflags', '--libs', 'taglib']
out: -I/usr/include/taglib -ltag

would the whole config.log help you in any way ?

**Comment by dbogdanov** [comment]
Yes, please! @laloutre12

**Comment by laloutre12** [comment]
Ok [there](https://pastebin.com/W5F5gB2U) it is.

**Comment by katpi** [comment]
And for me it was exactly the same.  [Here](https://pastebin.com/XAA2bnM6) you have my full config.log file.

**Comment by nagamanojk** [comment]
Hi dbogdanov, 
Even I'm facing the same issue as mentioned by @katpi.
Please help!!!

Thanks,
Nagamanoj

**Comment by nagamanojk** [comment]
Hi @dbogdanov,
Even I'm facing the same issue as mentioned by @katpi.
Please help!!!

Thanks,
Nagamanoj

**Comment by nagamanojk** [comment]
I guess the issue in my case was with "anaconda2" as it had old version of gcc different from the gcc in the system.
I tried to uninstall anaconda2. I cloned the essentia again. And followed the instructions in WEEK-1 lecture of coursera and WEEK-9 lecture coursera for installation of essentia.
Now its working fine.
tested with $ pyton 
>>> import essentia

**Comment by laloutre12** [comment]
@nagamanojk : 
I don't understand how anaconda is involved in the problem ? 
My gcc version is :
> gcc version 4.9.3 (Ubuntu 4.9.3-13ubuntu2)

Also what is the coursera your're refering to ? Do you have a link ?

**Comment by dbogdanov** [comment]
Closing this issue for now. For reference, here is a [build script for static Taglib](https://github.com/MTG/essentia/blob/master/packaging/debian_3rdparty/build_taglib.sh) that we use.
