### ISSUE TITLE
question: Cross-compiling for Android 

### ISSUE THREAD

**Issue by chubaiyi** [MTG/essentia#622]
There's a error when i cross-compiling for Android , I compiled it as the document, from http://essentia.upf.edu/documentation/FAQ.html#cross-compiling-for-android
the log is:
1. first,configure,that's ok;

[root@ubuntu:~/essentia-2.1# export PATH=/opt/my_ndk_toolchain/bin:$PATH;
[root@ubuntu:~/essentia-2.1# ./waf configure --cross-compile-android --lightweight= --fft=KISS 
Setting top to                           : /root/essentia-2.1 
Setting out to                           : /root/essentia-2.1/build 
→ configuring the project in /root/essentia-2.1
→ Building in release mode
→ Cross-compiling for Android ARM
Checking for program arm-linux-androideabi-gcc : /opt/my_ndk_toolchain/bin/arm-linux-androideabi-gcc 
Checking for program arm-linux-androideabi-g++ : /opt/my_ndk_toolchain/bin/arm-linux-androideabi-g++ 
Checking for program arm-linux-androideabi-ar  : /opt/my_ndk_toolchain/bin/arm-linux-androideabi-ar 
Checking for 'g++' (c++ compiler)              : /opt/my_ndk_toolchain/bin/arm-linux-androideabi-g++ 
Checking for 'gcc' (c compiler)                : /opt/my_ndk_toolchain/bin/arm-linux-androideabi-gcc 

=======================Lightweight Mode : Ignoring ALL libraries except [''] =======================

================================ CONFIGURATION SUMMARY ================================
- using KISS for FFT

- FFmpeg (or LibAv on debian/ubuntu) seems to be missing.
  The following algorithms will be ignored: ['AudioLoader', 'MonoLoader', 'EqloudLoader', 'EasyLoader', 'MonoWriter', 'AudioWriter']

- libsamplerate seems to be missing.
  The following algorithms will be ignored: ['Resample', 'MonoLoader', 'EqloudLoader', 'EasyLoader']

  Examples requiring FFmpeg / libav and libsamplerate will be ignored

- TagLib seems to be missing.
  The following algorithms will be ignored: ['MetadataReader']

- libyaml seems to be missing.
  The following algorithms will be ignored: ['YamlInput', 'YamlOutput']

- Essentia is configured without Gaia2.
  The following algorithms will be ignored: ['GaiaTransform']
  Examples requiring Gaia2 will be ignored

Building all the algorithms
Ignoring the following algorithms: EasyLoader, Resample, YamlInput, MonoLoader, IFFTW, AudioWriter, FFTW, AudioLoader, IFFTA, MonoWriter, YamlOutput, MetadataReader, EqloudLoader, Chromagram, GaiaTransform, ConstantQ, FFTA, FFTWComplex
Created algorithms registration file
=======================================================================================
'configure' finished successfully (0.122s)

2. compiling,but error.
[root@ubuntu:~/essentia-2.1# ./waf 
Waf: Entering directory `/root/essentia-2.1/build'
→ building from /root/essentia-2.1
→ building from /root/essentia-2.1/src
Building all the algorithms
Ignoring the following algorithms: ConstantQ, YamlInput, MonoLoader, IFFTW, Resample, FFTW, AudioWriter, EasyLoader, MonoWriter, FFTWComplex, MetadataReader, EqloudLoader, Chromagram, AudioLoader, GaiaTransform, YamlOutput, FFTA, IFFTA
Created algorithms registration file
[  1/229] cxx: src/essentia/algorithm.cpp -> build/src/essentia/algorithm.cpp.1.o
[  2/229] cxx: src/essentia/configurable.cpp -> build/src/essentia/configurable.cpp.1.o
[  3/229] cxx: src/essentia/connector.cpp -> build/src/essentia/connector.cpp.1.o
[  4/229] cxx: src/essentia/debugging.cpp -> build/src/essentia/debugging.cpp.1.o
[  5/229] cxx: src/essentia/essentia.cpp -> build/src/essentia/essentia.cpp.1.o
[  6/229] cxx: src/essentia/essentiautil.cpp -> build/src/essentia/essentiautil.cpp.1.o
[  7/229] cxx: src/essentia/parameter.cpp -> build/src/essentia/parameter.cpp.1.o
../src/essentia/essentia.cpp: In function 'std::string essentia::demangle(const char*)':
../src/essentia/essentia.cpp:85:15: error: '__cxa_demangle' is not a member of 'abi'
   char* res = abi::__cxa_demangle(name,
               ^
Waf: Leaving directory `/root/essentia-2.1/build'
Build failed
 -> task in 'essentia' failed (exit status 1): 
	{task 40290960: cxx essentia.cpp -> essentia.cpp.1.o}
['/opt/my_ndk_toolchain/bin/arm-linux-androideabi-g++', '-pipe', '-Wall', '-O2', '-fPIC', '-pthread', '-fPIC', '-I/root/essentia-2.1/build/src', '-I/root/essentia-2.1/src', '-I/root/essentia-2.1/build/src/essentia', '-I/root/essentia-2.1/src/essentia', '-I/root/essentia-2.1/build/src/essentia/scheduler', '-I/root/essentia-2.1/src/essentia/scheduler', '-I/root/essentia-2.1/build/src/essentia/streaming', '-I/root/essentia-2.1/src/essentia/streaming', '-I/root/essentia-2.1/build/src/essentia/streaming/algorithms', '-I/root/essentia-2.1/src/essentia/streaming/algorithms', '-I/root/essentia-2.1/build/src/essentia/utils', '-I/root/essentia-2.1/src/essentia/utils', '-I/root/essentia-2.1/build/src/3rdparty', '-I/root/essentia-2.1/src/3rdparty', '-I/root/essentia-2.1/build/src/3rdparty/spline', '-I/root/essentia-2.1/src/3rdparty/spline', '-I/root/essentia-2.1/build/src/3rdparty/kiss_fft130', '-I/root/essentia-2.1/src/3rdparty/kiss_fft130', '-D__STDC_CONSTANT_MACROS', '../src/essentia/essentia.cpp', '-c', '-o', 'src/essentia/essentia.cpp.1.o']

So,can someone give me some suggest,thx.

**Comment by alexsivris** [comment]
Got the same issue, still not managed to solve it?

**Comment by alexsivris** [comment]
OK, I managed to fix my issue by using the gnustl in my toolchain as the standard library instead of libc++. Pay attention, because on the official android standalone toolchain website the example in the very bottom uses `--stl=libc++` which creates a wrong standard library. Instead, use `--stl=gnustl`.
The versions I used are the following:
Android Standalone Toolchain (NDK): r17b
Essentia: 2.1-beta5-dev (master branch as of today)

**Comment by dbogdanov** [comment]
@alexsivris Hmm, the Android NDK documentation [here](https://developer.android.com/ndk/guides/cpp-support) suggests to use  libc++ instead of gnustl since NDK r16. Any idea why this does not work?

**Comment by alexsivris** [comment]
@dbogdanov I don't know why, but it seems that when libc++ is used, there are some header files missing, which are required by essentia. For instance, the header "ext/atomicity.h" is missing in the libc++ version.

**Comment by dbogdanov** [comment]
@alexsivris Please, test the fix in the android_fix branch. This uses clang with libc++.

**Comment by alexsivris** [comment]
@dbogdanov Thank you, it compiled perfectly now with libc++! This also solved my other issue #770

**Comment by ChenJunHero** [comment]
@chubaiyi 
First,  with the **./waf configure --cross-compile-android --lightweight= --fft=KISS --prefix=/home/chenjun/essentia-master**，I got the same result as you.
Second, with the **./waf**, I got the following:
> [244/244] Linking build/src/libessentia.so
> Waf: Leaving directory `/home/chenjun/essentia-master/build'
> 'build' finished successfully (1m56.941s)

And ran **file libessentia.so**, I got the following:
> libessentia.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, not stripped

**Comment by ihassantariq** [comment]
> @alexsivris Please, test the fix in the android_fix branch. This uses clang with libc++.

Thank you @dbogdanov for fixing it. I have tried anrdoid_fix branch it is currently able to build the required file for me.
