### ISSUE TITLE
Precomplied binaries (Linux) failing on VPS

### ISSUE THREAD

**Issue by ariba932** [MTG/essentia#627]
Good day.. 
Complied and used the precomplied binaries on my laptop. It work successful.
Now am trying to do a demo with more users using my AWS -Lightsail. I keep getting this error

AudioLoader: Could not find stream information, error =operation not permitted.

Pls help

**Comment by dbogdanov** [comment]
Do you have access rights to the file you analyze?

**Comment by ariba932** [comment]
Thank you very much...... the problem was the access...
