### ISSUE TITLE
MonoLoader memory issues

### ISSUE THREAD

**Issue by sankalpg** [MTG/essentia#63]
MonoLoader seems to have memory leaks (atleast on my machine). To pinpoint it I wrote a function with a single loop like this:

import essentia.standard as es
.
.
.
for audiofile in audiofiles:
        print audiofile
        audio_in=es.MonoLoader(filename=audiofile)()
        print gc.collect() 

Memory keeps on increasing as it process more and more (.wav) files. Just for a sanity check I also included garbage collector. In all iterations it shows 0 as output.

I am using Essentia 2.0-dev

**Comment by julj** [comment]
Memory leaks still here with latest version.

**Comment by dbogdanov** [comment]
Can't reproduce it with master branch.
