### ISSUE TITLE
vamp plugin "segmentation fault"

### ISSUE THREAD

**Issue by sildeag** [MTG/essentia#635]
On Ubuntu 17.04  64-bit, Essentia 2.1, with clean build from source code --with-vamp:

 `libvamp_essentia.so` is excluded from vamp plugins used by "sonic-visualiser 3.0."  vamp plugin test fails indicating "segmentation fault."  The same problem affects "audacity" except it just crashes and "sonic-annotator."

Essentia uses vamp sdk version 2.4 and latest version of vamp sdk is 2.7.  Would changes made to `wscript` in `src/examples` folder be the correct place to upgrade the build so that vamp sdk 2.7 is used rather than 2.4?    I would like to use something like this. 

`VAMP_SDK_DIR = /home/<user name>/vamp-plugin-sdk` and

`# Libraries required for the plugins.`
`#`
`PLUGIN_LIBS     = -L../vamp-plugin-sdk/vamp-sdk -Wl,-Bstatic -lvamp-sdk -Wl,-Bdynamic -lpthread`

`# Flags required to tell the compiler to make a dynamically loadable object`
`#`
`PLUGIN_LDFLAGS  = -shared -Wl,-Bdynamic -Wl,-soname=$(PLUGIN) $(VAMP_SDK_DIR)/libvamp-sdk.a -Wl,--version-script=vamp-plugin.map`

`# File extension for a dynamically loadable object`
`#`
`PLUGIN_EXT      = .so`

Are there any special flags that should be used in "essentia 2.1"?

**Comment by dbogdanov** [comment]
No problems running the newest Sonic Visualizer v3.0.3 and sonic-annotator v1.5 on Mac OSX with the Essentia's vamp plugin built with the old SDK. Also, sonic-annotator v1.5 works fine with it on my Ubuntu 16.04 too.

**Comment by dbogdanov** [comment]
@sildeag Correct, you can modify [src/examples/wscript](https://github.com/MTG/essentia/blob/master/src/examples/wscript#L142) if you want to.

**Comment by dbogdanov** [comment]
I get setfault in sonic-annotator on Ubuntu, when using the ```--build-static``` flag in ```waf configure``` to build the Vamp plugin. Will look into this now...

**Comment by dbogdanov** [comment]
Fixes are to be merged in master.

**Comment by sildeag** [comment]
I take it that you aren't going to use the latest version of Vamp.

**Comment by dbogdanov** [comment]
We'll update to Vamp 2.7 in future, but the issue was not related to that.

**Comment by sildeag** [comment]
Thanks.  Yes, with the revisions you made vamp plugin works.
