### ISSUE TITLE
SineModelSynth, synthesizing sinusoids

### ISSUE THREAD

**Issue by grz0zrg** [MTG/essentia#637]
Hello,

i would like to synthesize one or more sinusoid at a specific frequency with SineModelSynth, however the output is very loud and contain more frequency components than what was defined.

My question is, how can you synthesize specific sinusoids with SineModelSynth ? Is there something wrong with the defined mag/frq/phases parameters or is it something else related to the model ?

I am actually using the sample code from the examples
```
AlgorithmFactory& factory = AlgorithmFactory::instance();

sinemodelsynth = factory.create("SineModelSynth", "sampleRate", sr, "fftSize", framesize, "hopSize", hopsize);
ifft = factory.create("IFFT", "size", framesize);

overlapAdd = factory.create("OverlapAdd", "frameSize", framesize, "hopSize", hopsize, "gain", 0.00001);

sinemodelsynth->input("magnitudes").set(magnitudes);
sinemodelsynth->input("frequencies").set(frequencies);
sinemodelsynth->input("phases").set(phases);
sinemodelsynth->output("fft").set(sfftframe);

ifft->input("fft").set(sfftframe);
ifft->output("frame").set(ifftframe);

overlapAdd->input("signal").set(ifftframe);
overlapAdd->output("signal").set(audioOutput);

magnitudes.push_back(0.5);
frequencies.push_back(440.0);
phases.push_back(randf(0.0, 1.0));

```

Then i call this code in a real-time audio callback for each samples

```
for (i = 0; i < samples; i += 1) {
  unsigned int smp_s = i % hopsize;

  if (smp_s == 0) {
    sinemodelsynth->compute();

    ifft->compute();
    overlapAdd->compute();`
  }

  *out++ = audioOutput[i];
}
```

**Comment by dbogdanov** [comment]
@jjaner perhaps can help

**Comment by jjaner** [comment]
From the code above it seems you are just initializing the values for a single frame. If you want to synthesize a pure sinusoid you should give the right phase for all audio frames (considering an incremental phase shift depending on the frequency, 440Hz in your case). 
You can check the analysis/synthesis example [here](https://github.com/MTG/essentia/blob/master/src/examples/standard_sinemodel.cpp).

**Comment by grz0zrg** [comment]
Thank, i tried to do something like this :

`for (i = 0; i < samples; i += 1) {
  unsigned int smp_s = i % hopsize;

  if (smp_s == 0) {
    phases.clear();
    phases.push_back(sin((double)i * 3.141592 * 2. * 440. / 96000.));

    sinemodelsynth->compute();

    ifft->compute();
    overlapAdd->compute();`
  }

  *out++ = audioOutput[i];
}`

But there is still many frequency components other than the 440hz frequency.

**Comment by grz0zrg** [comment]
Thank you, this work as expected with the phase, there was an issue with my code related to sample index which was the source of incorrect frequencies.
