### ISSUE TITLE
Problems with generated docs (including 3 attachments to fix issues)

### ISSUE THREAD

**Issue by sildeag** [MTG/essentia#639]
In generating documentation using `./waf doc`:

Besides the output following this paragraph, `../essentia/doc/sphinxdoc/_build/html/FAQ.html` has references to `.rst` files that don't exist, eg. `premade extracts out-of-box` and `python tutorial`, while `.html` file for the first does exist and `python_tutorial.html` can be copied from the `MTG/essentia` documentation website.

After reading sources... [100%] streaming_extractor_music                             
`../essentia/doc/sphinxdoc/contents.rst:9: WARNING: toctree contains reference to nonexisting document u'essentia_python_tutorial'`

**This might mean** `../essentia/doc/sphinxdoc/_build/html/python_tutorial.html` is missing from github repo.

`WARNING: ../essentia/doc/sphinxdoc/extending_essentia.rst:106: (WARNING/2) Title underline too short.`

`The ``configure()`` method
^^^^^^^^^^^^^^^^^^^^^^`
`WARNING: ../essentia/doc/sphinxdoc/extending_essentia.rst:106: (WARNING/2) Title underline too short.`

`The ``configure()`` method
^^^^^^^^^^^^^^^^^^^^^^`
`../essentia/doc/sphinxdoc/installing.rst:49: WARNING: Definition list ends without a blank line; unexpected unindent.`
`../essentia/doc/sphinxdoc/streaming_extractor_music.rst:11: WARNING: Literal block expected; none found.`
`../essentia/doc/sphinxdoc/streaming_extractor_music.rst:2: WARNING: Duplicate explicit target name: "the code of extractor".`
`../essentia/doc/sphinxdoc/streaming_extractor_music.rst:2: WARNING: Duplicate explicit target name: "the code of extractor".`

**Comment by sildeag** [comment]
Suggested fixes for these issues are attached.
[FAQ.txt](https://github.com/MTG/essentia/files/1278879/FAQ.txt)  this needs to be renamed from FAQ.txt to FAQ.md in `../essentia` folder.

[essentia_python_tutorial.txt](https://github.com/MTG/essentia/files/1278885/essentia_python_tutorial.txt)
[python_tutorial.txt](https://github.com/MTG/essentia/files/1278884/python_tutorial.txt) these two files need to be rename from `.txt` to `.rst` in the `../essentia/doc/sphinxdoc` folder.   

`.png` and `.svg` images need to be obtained to complete the suggested fix.

**Comment by dbogdanov** [comment]
```essentia_python_tutorial``` should be automatically generated from ```src/examples/tutorial/essentia_python_tutorial.ipynb```
