### ISSUE TITLE
Missing audio file in MusicBricks python tutorials

### ISSUE THREAD

**Issue by dbogdanov** [MTG/essentia#645]
In *5-melody_analysis.ipynb*, *6-harmonic_mask.ipynb* and *6-harmonic_mask.py*

``RuntimeError: Error while configuring MonoLoader: AudioLoader: Could not open file "predom.wav", error = No such file or directory``

@jjaner

**Comment by jjaner** [comment]
Hi,

you can change the audio filename “predom.wav” to “flamenco.wav”, which is the actual audio file found in the repository.

Best,
jordi
