### ISSUE TITLE
Confidence is always zero for PitchYinFFT()

### ISSUE THREAD

**Issue by jamiebullock** [MTG/essentia#647]
Whilst pitch results seem fairly accurate, I'm unable to obtain anything other than 0 for pitch confidence using PitchYinFFT. Even when using a pure sine tone as input.

**Comment by pabloEntropia** [comment]
I tried to replicate this issue with the following lines,
``` Python
from essentia.standard import *
import numpy as np

# Generates one second of 300Hz tone sampled at 44.1kHz.
PitchYinFFT()(Spectrum()(Windowing()(np.sin(np.pi*2*np.linspace(0, 1, 44100) * 300).astype('float32'))))
```

Which return the following `pitch`, `pitchConfidence` pair:
`(300.0031433105469, 0.9999268651008606)`

If this is still a problem please feel free to reopen the issue with some details on your particuar setup.
