### ISSUE TITLE
Question: Load Audio File Without ffmpeg Libraries

### ISSUE THREAD

**Issue by pizzicatomania** [MTG/essentia#649]
Hello,

I have tried to use Essentia on my Android application so I cross-complied it for reduced Android version.
After that, however, I couldn't find the way to load audio file and put it into some algorithms as an input.
On the Linux environment, I've been using MonoLoader, EasyLoader, etc., but the reduced version of library doesn't include those 'Loader' functions because it was complied without ffmpeg libraries. 
Is there any Android function instead of those loader functions? 
The Essentia loader functions load audio file and produce' Vector\<Real\>' type of audio signal, but I couldn't find any other method to do the same task.

Thanks.

**Comment by carthach** [comment]
None in Essentia if you don't use ffmpeg. Try and find a framework that can load audio and convert it to a stream of floats, then pass it to Essentia. I have used openFrameworks and JUCE in the past.
