### ISSUE TITLE
Can I use Essentia for KTV Score System?

### ISSUE THREAD

**Issue by evehal** [MTG/essentia#653]
i want to implement a KTV system,after finish singing,KTV should give a score to player.
Im a newbie in audio,Can i use Essentia to finish this job?and how?
please give me a direction,thank you very much

**Comment by dbogdanov** [comment]
It is definitely suitable for this task, however it depends on [what kind of score do you want](https://www.quora.com/How-do-karaoke-machines-score-your-singing) and may require significant trial-and-error work. 

It is possible to estimate onsets and pitch for singing voice using Essentia's algorithms. @georgid can probably give you some suggestions as he is working with singing voice.

**Comment by evehal** [comment]
cool,you are my lighthouse!!!i will do some research on Essentia,thank you
