### ISSUE TITLE
errors while trying to run pythontests

### ISSUE THREAD

**Issue by artha72** [MTG/essentia#654]
Hi. I'm trying to run python tests from 
essentia/test/src/pythontests$ python tests.py
First I got the following error:
+ test_essentia_import
.
+ test_essentia_music
Traceback (most recent call last):
  File "tests.py", line 34, in <module>
    return_value = module.test()
  File "/home/essentia/test/src/pythontests/test_essentia_music.py", line 29, in test
    essentia_extractor.compute('music', "../../audio/jazz-guitar.wav","jazz-guitar.sig")
  File "/usr/local/lib/python2.7/dist-packages/essentia/essentia_extractor.py", line 324, in compute
    config = open(profile, 'r').read()
IOError: [Errno 2] No such file or directory: 'music'

I traced back and found out that for whatever reason, when I built and installed essentia, profiles directory did not get copied to /usr/local/lib/python2.7/dist-packages/  and therefore it couldn't find the music_config.yaml and threw an error.
So I manually copied the profiles directory and ran it again.

Now got a new error :
+ test_essentia_import
.
+ test_essentia_music
Traceback (most recent call last):
  File "tests.py", line 34, in <module>
    return_value = module.test()
  File "/home/essentia/test/src/pythontests/test_essentia_music.py", line 29, in test
    essentia_extractor.compute('music', "../../audio/jazz-guitar.wav","jazz-guitar.sig")
  File "/usr/local/lib/python2.7/dist-packages/essentia/essentia_extractor.py", line 349, in compute
    audio = loadAudioFile(inputFilename, pool, options)
  File "/usr/local/lib/python2.7/dist-packages/essentia/essentia_extractor.py", line 64, in loadAudioFile
    audio = essentia.MonoLoader(filename = inputFilename,
AttributeError: 'module' object has no attribute 'MonoLoader'

I traced it back again and found out that for all essentia algorithms, python is recognizing them only if I import them as "essentia.standard" instead of "essentia".

So my question is that could there have been any problem with my installation that is causing these problems? Or is it just that the pythontests are not updated to run with latest essentia import mechanics?

P.S. I'm testing on Ubuntu 17.10. Essentia source is from the master-branch

**Comment by dbogdanov** [comment]
Those are some outdated tests to be reviewed. Just run python tests with ./waf run_python_tests if you want to execute all python tests. Note however, that not all of them pass successfully in the master branch and there is a number of issues filed to fix.
