### ISSUE TITLE
waf doesn't find installed libraries even if PKG_CONFIG_PATH is set

### ISSUE THREAD

**Issue by jamiebullock** [MTG/essentia#657]
```
$ ls /usr/local/lib/pkgconfig | grep yaml
yaml-0.1.pc
$ export | grep PKG_CONFIG
declare -x PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/lib/pkgconfig"
```

But...

```
$ ./waf configure --build-static --with-vamp --mode=release --lightweight= --fft=KISS
- libyaml seems to be missing.
```

This also applies to TagLib and libsamplerate which are not found.

Platform macOS 10.13

**Comment by dbogdanov** [comment]
Just in case, can you make sure the PKG_CONGIG_PATH is correctly read like here https://github.com/MTG/essentia/commit/1591b4c0ce996c99af3d534b9a3abde791276c36?
