### ISSUE TITLE
--with-gaia Essentia compilation issue

### ISSUE THREAD

**Issue by colonder** [MTG/essentia#664]
I'm using Kubuntu 17.10 64-bit. Firstly, I followed instructions [here](https://github.com/MTG/gaia) to compile Gaia, it compiled and installed successfully. Then I typed following command to configure Essentia
`./waf configure --mode=release --build-static --with-python --with-cpptests --with-examples --with-vamp --with-gaia --build-static --download`

and while compilation I'm receiving following error:

`Build failed
 -> task in 'essentia' failed (exit status 1): 
        {task 140574783372944: cxx essentia_algorithms_reg.cpp -> essentia_algorithms_reg.cpp.1.o}
['/usr/bin/g++', '-pipe', '-Wall', '-msse', '-msse2', '-mfpmath=sse', '-O2', '-fPIC', '-pthread', '-fPIC', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/build/src', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/src', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/build/src/essentia', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/src/essentia', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/build/src/essentia/scheduler', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/src/essentia/scheduler', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/build/src/essentia/streaming', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/src/essentia/streaming', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/build/src/essentia/streaming/algorithms', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/src/essentia/streaming/algorithms', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/build/src/essentia/utils', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/src/essentia/utils', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/build/src/3rdparty', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/src/3rdparty', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/build/src/3rdparty/spline', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/src/3rdparty/spline', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/build/src/3rdparty/vamp-plugin-sdk-2.4', '-I/home/kuba/Aplikacje/essentia-2.1_beta3/src/3rdparty/vamp-plugin-sdk-2.4', '-I/usr/include/x86_64-linux-gnu', '-I/usr/include/taglib', '-I/usr/local/include', '-I/usr/include/qt4', '-I/usr/include/qt4/QtCore', '-DHAVE_AVCODEC=1', '-DHAVE_AVFORMAT=1', '-DHAVE_AVUTIL=1', '-DHAVE_AVRESAMPLE=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_TAGLIB=1', '-DHAVE_YAML=1', '-DHAVE_FFTW=1', '-DHAVE_GAIA2=1', '-D__STDC_CONSTANT_MACROS', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYTHON_H=1', '../src/algorithms/essentia_algorithms_reg.cpp', '-c', '-o', 'src/algorithms/essentia_algorithms_reg.cpp.1.o']`

As I understood from the documentation the gaia is required to use SVM classification models. What using other models? Is gaia still needed?

**Comment by dbogdanov** [comment]
What's the compilation error message?

**Comment by colonder** [comment]
```
[ 31/373] cxx: src/algorithms/essentia_algorithms_reg.cpp -> build/src/algorithms/essentia_algorithms_reg.cpp.1.o
In file included from ../src/algorithms/essentia_algorithms_reg.cpp:140:0:
/home/kuba/Aplikacje/essentia-2.1_beta3/src/algorithms/highlevel/gaiatransform.h:23:10: fatal error: gaia2/transformation.h: No file or directory
 #include <gaia2/transformation.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Commands I used:
```
/waf configure --with-python-bindings --with-asserts --with-cyclops --want-rpath --prefix="/home/kuba/anaconda2/" --bindir="/home/kuba/anaconda2/bin/" --libdir="/home/kuba/anaconda2/lib/"
sudo ./waf
./waf install
./waf configure --mode=release --build-static --with-python --with-cpptests --with-examples --with-vamp --with-gaia --build-static --download --prefix="/home/kuba/anaconda2/"
sudo ./waf
```

**Comment by alastair** [comment]
I assume that the first three commands that you show are from when you installed gaia. If this is the case then essentia won't find the gaia headers because you are installing them into your custom prefix instead of `/usr/local`.
You should tell pkg-config where your gaia configuration files are when you configure essentia:

    PKG_CONFIG_PATH=/home/kuba/anaconda2/lib/pkgconfig ./waf configure --with-gaia [other examples]

The version of essentia that you have downloaded, 2.1beta3 is an old release and does not correctly warn you if it cannot find gaia. We recommend that you download 2.1beta4 (https://github.com/MTG/essentia/releases/tag/v2.1_beta4) or use the current master (https://github.com/MTG/essentia/archive/master.zip)

Can you tell us where you got the command line to configure essentia from? This is not the line that we suggest in our install document (i.e., we don't suggest the `--download` flag. Why did you add this?)

As another unrelated point, you shouldn't need `sudo` to compile using waf.

**Comment by colonder** [comment]
When I click on releases tab at Essentia's github, the beta4 release is completely invisible compared to the big bold bet3 header. Moreover there is written that beta3 is current preliminary version and is recommended to install, so I did as it says. I composed the command myself based on `./waf --help`. I added any option that seemed reasonable for successfully building Essentia.

**Comment by sildeag** [comment]
You might want to look at `MTG/gaia` issues.  I have migrated `Gaia` from using `Qt4` to `Qt5` and built `essentia` with `Gaia` built using `Qt5` on Ubuntu 17.10.  The final comment is about building `essentia`.

I did not use `--build-static` when successfully building with `Qt4` or `Qt5`.
