### ISSUE TITLE
Constant Q Cepstral Coefficient (CQCC) algorithm request

### ISSUE THREAD

**Issue by colonder** [MTG/essentia#665]
Just like in the title. Could you make that?

**Comment by dbogdanov** [comment]
We'll put this into our wishlist for the future. 

Adding a reference for this feature: https://www.researchgate.net/publication/301199823_A_New_Feature_for_Automatic_Speaker_Verification_Anti-Spoofing_Constant_Q_Cepstral_Coefficients
