### ISSUE TITLE
Intercept streaming process and modify data

### ISSUE THREAD

**Issue by arthurtofani** [MTG/essentia#668]
Hi,

I'm wondering how I could use the streaming algorithms with some piece of code in the middle such that I could modify data but keeping the stream flowing.

```
----------      ------------      -----------      --------------      --------------      --------------
MonoLoader      FrameCutter       Windowing        Spectrum            HERE                MFCC
     audio ---> signal frame ---> frame frame ---> frame spectrum ---> some mods --->      spectrum bands ---> NOWHERE
                                                                                           mfcc  ---> Pool: lowlevel.mfcc
----------      ------------      -----------      --------------      --------------      --------------
```
I'm using the python wrappers. 

My question is how would be the best way to implement it. Would it be a new extractor or just a new Algorithm? Also, is it possible to process this intermediary block using python? 

regards,

**Comment by dbogdanov** [comment]
You can implement a new steaming algorithm in C++, no way to do that in Python. Or use the standard mode if you want to have your own intermediary processing.

**Comment by arthurtofani** [comment]
thank you!
