### ISSUE TITLE
Spectral Contrast hard coded

### ISSUE THREAD

**Issue by MichaelSound** [MTG/essentia#669]
Hello!

FreesoundLowlevelDescriptors.cpp has a hardcoded value of for highFrequencyBound of 11000 Hz.

I was trying to use Essentia on some low sample rate files, which produces an error (highFrequencyBound cannot be higher than Nyquist)

It seems your couldn't set this value using a config.yaml file so I had to change the value IN THE CODE and then rebuild.

Another option would be to make this bound a fraction of the Nyquist frequency.

Also ...

I am new to Essentia. I appreciate the all the effort !

I have used Freesound streaming extractor to process one of my files. What is the best way to view the frame features on the JSON file? It didn't seem easy to find tools for viewing and understanding the results of Essentia processing.

I am new so I would appreciate your help. This could also be a good topic for the FAQ.

Thank you,

Michael.
p.s. I did see  code for converting JSON to CSV but this seems to be an old processing philosophy. I hoped JSON tools would be available.

**Comment by dbogdanov** [comment]
You may want to try using Essentia's [vamp plugin](http://essentia.upf.edu/documentation/vamp_plugins/) to be able to visualize frames for particular descriptors in mind. You can build it yourself following Essentia's installation instructions.

**Comment by dbogdanov** [comment]
Are you modifying the default analysisSampleRate for 44100. to a lower sample rate? This the sample rate to be used for analysis, that is, any input audio will be resampled to this sample rate first. Perhaps, it is not clear enough from the documentation and we'll improve that.

**Comment by MichaelSound** [comment]
Hi Dmitry,

Thank you for your help.

1. VAMP
I'd appreciate a little more help please. I have searched for an example of using Essentia and VAMP without success.
I believe I built VAMP when I installed Essentia.

Is there a simple example that will get me started?
Will it allow me to visualise the frame-based features in my JSON file?
Is there a c++ option and a python option?

In your 2013 paper you mentioned VAMP and Sonic Visualiser, but this is a separate option isn't it?

2. analysisSampleRate
I did change the analysisSampleRate to a lower value in my config.yaml file. I have unusual data recorded at a low sample rate.
I, in turn, needed to change highFrequencyBound in the code to process the file. Setting the value in the config.yaml file didn't seem possible. An automatic value with respect to Nyquist could be an other option.

3. Audio files
I don't believe cloning the audio files was mentioned in the Essentia installation instructions.
The installation documentation could mention that they are required for the "Running tests" section.

Overall I am trying to go from:
  a. raw data files -> frame features (can these be visualised?)
  b. frame features -> important features 
  c. important features and unsupervised clusters

Thanks again,

Michael.

**Comment by dbogdanov** [comment]
@MichaelSound Having a values for frequencies relative to Nyquist frequency might not be a good idea. To work properly, some of our descriptors rely on hardcoded values that make acoustical/musical sense. For example, for HPCP a frequency range of between 100 and 5000 Hz is used. For that reason, for consistency, all audio is being resampled up to 44100. 

What is the samplerate you are using?

**Comment by dbogdanov** [comment]
@MichaelSound  Essentia Vamp plugin will allow you to use [SonicVisualizer software](http://www.sonicvisualiser.org/). Using it you can go through available algorithms one by one and run them on an audio files and then inspect frame value plotted together with the waveform in a graphical interface. 

If you want something more automated, to be used on top of MusicExtractor algorithm, you can use pythons' matplotlib library and write your own code to visualize frame values of each feature. 

Not all of the features from MusicExtractor are present in the vamp plugin, but some of the most important ones are.

**Comment by dbogdanov** [comment]
Added instructions to clone Essentia github repository with its submodules for tests 988afd4bf310e7e155a7969439d46a380fbb1f7c.

**Comment by MichaelSound** [comment]
Thanks Dmitry!
