### ISSUE TITLE
Cannot import MusicExtractor in Python

### ISSUE THREAD

**Issue by eadward** [MTG/essentia#675]
Dear Team,

thanks for this excellent library. It is a much needed development.

I am particularly interested in the set of features extracted by the Music Extractor. I have the pre-compiled binaries, but ideally I would like to use Python because I want to be more flexible on the way I export the data (and also compute some functionals using sliding windows).

I downloaded your tutorial example [example_musicextractor.py](https://github.com/MTG/essentia/blob/master/src/examples/tutorial/example_musicextractor.py), compiled Essentia on Ubuntu 16.04 with Python bindings, and copied the folder `essentia-master/build/python/essentia` and its contents to the folder where the tutorial example is (this is the step that  I am sure about).

When I run the script I get an error:
```
 Traceback (most recent call last):
  File "example_musicextractor.py", line 8, in <module>
    from essentia.standard import MusicExtractor, YamlOutput
ImportError: cannot import name MusicExtractor
```

I could not find instruction on the documentation that could help me understand the way that Essentia works with Python and solve this problem. I would be grateful if you could provide some help with this. 

thanks in advance.

**Comment by eadward** [comment]
It was a problem related to the installation of the different modules. Problem solved after recompiling and installing Essentia. Thanks anyway.

**Comment by simonefrancia** [comment]
@eadward I have the same issue here https://github.com/MTG/essentia/issues/758
how did you fix the install?

**Comment by eadward** [comment]
The compilation was not being done properly (the necessary extra libraries were not installed) and also I had not installed the libraries and other files to the correct location. In any case I stopped using Python with Essentia and focused on C++. Try to follow the steps in the tutorial and make sure that you read the outputs on the terminal to make sure that nothing is missing.

**Comment by dbogdanov** [comment]
@simonefrancia For Python on Linux, you can now ```pip install essentia```.
