### ISSUE TITLE
I would like to use MTG/gaia with essentia without Qt4.  Hoping someone can point me in the right direction.

### ISSUE THREAD

**Issue by sildeag** [MTG/essentia#679]
Gaia compiles, with the modifications I've made to wscript and source code, until this link then a bunch of things seem to be missing - OS is Ubuntu 17.10 c++11 gnu version 7.2.  Qt 5.9.1

These messages come immediately after linking but I hoped to get some pointers rather than bore people with the details.  I suspect it may be `swig` related.

`could not find 'cstddef'`
`could not find 'std_string.i'`
`could not find 'std_pair.i'`
`could not find 'std_iostream.i'`
`could not find 'std_vector.i'`
`could not find 'std_pair.i'`
`could not find 'std_map.i'`
`...`
`src/libgaia2.a(convert.cpp.1.o):(.bss+0x0): multiple definition of `gaia2::scope'` `
`src/bindings/gaia2.swigwrap_1.cxx.1.o:(.bss+0x10): first defined here`
`src/libgaia2.a(dataset.cpp.1.o):(.bss+0x0): multiple definition of `gaia2::scope'` `
`src/bindings/gaia2.swigwrap_1.cxx.1.o:(.bss+0x10): first defined here`
`src/libgaia2.a(descriptortree.cpp.1.o):(.bss+0x0): multiple definition of `gaia2::scope'` `
`src/bindings/gaia2.swigwrap_1.cxx.1.o:(.bss+0x10): first defined here`
`src/libgaia2.a(frozendataset.cpp.1.o):(.bss+0x0): multiple definition of `gaia2::scope'` `
`...`

`[84/92] Linking build/src/libgaia2.a
19:06:03 runner ['/usr/bin/ar', 'rcs', 'src/libgaia2.a', 'src/convert.cpp.1.o', 'src/dataset.cpp.1.o', 'src/debugging.cpp.1.o', 'src/descriptortree.cpp.1.o', 'src/frozendataset.cpp.1.o', 'src/gaia.cpp.1.o', 'src/gaiamath.cpp.1.o', 'src/linalg.cpp.1.o', 'src/parameter.cpp.1.o', 'src/point.cpp.1.o', 'src/pointlayout.cpp.1.o', 'src/region.cpp.1.o', 'src/searchspace.cpp.1.o', 'src/searchspacepool.cpp.1.o', 'src/timer.cpp.1.o', 'src/transformation.cpp.1.o', 'src/utils.cpp.1.o', 'src/yamlcpp.cpp.1.o', 'src/algorithms/addfield.cpp.1.o', 'src/algorithms/addfieldapplier.cpp.1.o', 'src/algorithms/algoutils.cpp.1.o', 'src/algorithms/analyzer.cpp.1.o', 'src/algorithms/applier.cpp.1.o', 'src/algorithms/center.cpp.1.o', 'src/algorithms/cleaner.cpp.1.o', 'src/algorithms/distribute.cpp.1.o', 'src/algorithms/dotproduct.cpp.1.o', 'src/algorithms/enumerate.cpp.1.o', 'src/algorithms/enumerateapplier.cpp.1.o', 'src/algorithms/extract.cpp.1.o', 'src/algorithms/extractapplier.cpp.1.o', 'src/algorithms/fixlength.cpp.1.o', 'src/algorithms/fixlengthapplier.cpp.1.o', 'src/algorithms/gaussianize.cpp.1.o', 'src/algorithms/inverseprojection.cpp.1.o', 'src/algorithms/matmult.cpp.1.o', 'src/algorithms/merge.cpp.1.o', 'src/algorithms/mergeregion.cpp.1.o', 'src/algorithms/mergeregionapplier.cpp.1.o', 'src/algorithms/normalize.cpp.1.o', 'src/algorithms/pca.cpp.1.o', 'src/algorithms/rca.cpp.1.o', 'src/algorithms/remove.cpp.1.o', 'src/algorithms/removedesc.cpp.1.o', 'src/algorithms/removevl.cpp.1.o', 'src/algorithms/rename.cpp.1.o', 'src/algorithms/renameapplier.cpp.1.o', 'src/algorithms/select.cpp.1.o', 'src/algorithms/selectdesc.cpp.1.o', 'src/algorithms/svmpredict.cpp.1.o', 'src/algorithms/svmtrain.cpp.1.o', 'src/metrics/bpfdistance.cpp.1.o', 'src/metrics/cosineangledistance.cpp.1.o', 'src/metrics/cosinesimilarity.cpp.1.o', 'src/metrics/crosssegmentdistance.cpp.1.o', 'src/metrics/distancefunction.cpp.1.o', 'src/metrics/euclideandistance.cpp.1.o', 'src/metrics/exponentialcompressdistance.cpp.1.o', 'src/metrics/forceidentitydistance.cpp.1.o', 'src/metrics/frozendistance.cpp.1.o', 'src/metrics/keydistance.cpp.1.o', 'src/metrics/kullbackleiblerdistance.cpp.1.o', 'src/metrics/linearcombinationdistance.cpp.1.o', 'src/metrics/manhattandistance.cpp.1.o', 'src/metrics/minkowskidistance.cpp.1.o', 'src/metrics/randomdistance.cpp.1.o', 'src/metrics/resistoraveragedistance.cpp.1.o', 'src/metrics/rhythmdistance.cpp.1.o', 'src/metrics/semanticclassifierdistance.cpp.1.o', 'src/metrics/summedsegmentdistance.cpp.1.o', 'src/metrics/weightedeuclideandistance.cpp.1.o', 'src/metrics/weightedpearsondistance.cpp.1.o', 'src/3rdparty/alglib/ap.cpp.1.o', 'src/3rdparty/alglib/chisquaredistr.cpp.1.o', 'src/3rdparty/alglib/gammaf.cpp.1.o', 'src/3rdparty/alglib/igammaf.cpp.1.o', 'src/3rdparty/alglib/normaldistr.cpp.1.o', 'src/3rdparty/libsvm/gaiasvmutils.cpp.1.o', 'src/3rdparty/libsvm/svm.cpp.1.o', 'src/parser/filter.cpp.1.o', 'src/parser/filterwrapper.cpp.1.o', 'src/parser/lex.yy.cpp.1.o']
...
[85/93] Processing src/bindings/gaia.swig`

**Comment by sildeag** [comment]
Seems to be a defective swig install am removing old version and installing swig 4.0.  Also, will fix the namespace initializations.

**Comment by alastair** [comment]
Please open a bug in the gaia repository if you want further help, but please understand that compiling gaia without qt is not supported by us and we may not be able to help you further.
