### ISSUE TITLE
Cannot load any function ubuntu 17.10 with python 3.6

### ISSUE THREAD

**Issue by giamic** [MTG/essentia#685]
Whenever I try to load a function from the essentia library, say MonoLoader from essentia.standard, I obtain the error:
`TypeError: __init__() takes 1 positional argument but 2 were given`

At the same time, PyCharm says that it cannot find the reference 'MonoLoader' in standard.py. However, if I do dir(essentia.standard), I find all the names of the functions, including MonoLoader. 

(PyCharm shouldn't be the cause of the problem since the same also happens if I start an iPython console from the terminal.)

I'm running python 3.6 on ubuntu 17.10.

**Comment by dbogdanov** [comment]
Works for me on python 3.6.3 on ubuntu 17.10. 

Are you using master branch?

**Comment by giamic** [comment]
Thank for the reply. 

I actually didn't clone the git repository, I've just downloaded version 2.1 beta3 and followed the installation instructions at http://essentia.upf.edu/documentation/installing.html.

**Comment by giamic** [comment]
Thank for the reply. I actually didn't clone the git repository, I've just
downloaded version 2.1 beta3 and followed the installation instructions at
http://essentia.upf.edu/documentation/installing.html.

**Comment by dbogdanov** [comment]
Just clone the repository and use the master branch.

**Comment by giamic** [comment]
I did it and nothing changed. I still can't use the library.

**Comment by giamic** [comment]
Hi, I would really love to use the library but I still can't get it to work. 

By inspecting the source code, Pycharm tells me that the line `from . import _essentia` gives an error: unresolved reference `_essentia`. I don't know if that helps, but in the essentia source directory I have  `_essentia.cpython-36m-x86_64-linux-gnu.so` file but no `_essentia.py`.

**Comment by giamic** [comment]
Also, many of the tests that I can run with waf fail (maybe a 10% of them?)

**Comment by dbogdanov** [comment]
Try installing with ```pip install essentia```. Indeed, some of the tests fail, this should be fixed for the final release.
