### ISSUE TITLE
LoudnessEBUR128 - Warning BUFFER SIZE MISMATCH, long calculation time on 2nd call and possible memory leakage

### ISSUE THREAD

**Issue by MartinJRAT** [MTG/essentia#696]
When using the <LoudnessEBUR128> algorithm in standard mode I got a couple of warnings when computing it the first time on a stereo-signal buffer (std::vector<essentia::StereoSample>) of size about 10s (44.1kHz-Sampling): 

[0;32m[   INFO   ] [0mOn connection BinaryOperatorStream::array ÔåÆ FrameCutter::signal:
[0;32m[   INFO   ] [0mBUFFER SIZE MISMATCH: max=4096 - asked for read size 17640
[0;32m[   INFO   ] [0mresizing buffer to 155232/19404
[0;32m[   INFO   ] [0mOn connection BinaryOperatorStream::array ÔåÆ FrameCutter::signal:
[0;32m[   INFO   ] [0mBUFFER SIZE MISMATCH: max=19404 - asked for read size 132300
[0;32m[   INFO   ] [0mresizing buffer to 1164240/145530
[0;32m[   INFO   ] [0mOn connection Mean::mean ÔåÆ UnaryOperatorStream::array:
[0;32m[   INFO   ] [0mBUFFER SIZE MISMATCH: max=0 - asked for read size 4096
[0;32m[   INFO   ] [0mresizing buffer to 36040/4505
[0;32m[   INFO   ] [0mOn connection Mean::mean ÔåÆ UnaryOperatorStream::array:
[0;32m[   INFO   ] [0mBUFFER SIZE MISMATCH: max=0 - asked for read size 4096
[0;32m[   INFO   ] [0mresizing buffer to 36040/4505

Anyway, the results computed seem to be ok and are calculated quickly. But performing a second call (-mLoudnessAlg->compute()) with another buffer of audiodata takes a very long time (>1min for a 10s Buffer). Still, the calculation is correct in principle, but runtime is practically not feasible.

To overcome this, I de-initialized (shutdown) and re-initialized Essentia (and algorithms) in each iteration. This solves the calculation-speed issue, but still the warnings emerge on each call (fist call of compute). Moreover memory consumption drastically increases for each ->compute() call. It seems, there is something leaking...

Has anyone an idea about the problem(s) behind? I am not sure, if the problems/observation are related, but I hope any hint about the causes might help. The version used is Essentia V2.1 Beta 3 (latest release)...

**Comment by dbogdanov** [comment]
Can you try to reproduce using latest code from the master branch?

**Comment by MartinJRAT** [comment]
Many thanks, using the actual master-branch the warnings are no longer produced anymore and the memory is stable when de-initializing (shutdown) and re-initializing Essentia (and algorithms) in each iteration. Consecutive ->compute() calls are still much slower than performing de/re-initialization, but as the latter is not critical (very fast) it is a feasible solution for my use-case. Thanks for assistance!

**Comment by dbogdanov** [comment]
We'll keep that in mind, the consecutive calls should be just as fast, so we'll revise the code. Thanks for reporting.
