### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by ShrutiSarikaChakraborty** [MTG/essentia#705]
I have installed essentia successfully and have also compiled it in Ubuntu Bash on Windows 10.I am getting no module found error for essentia.standard and other packages.I have no idea how to handle this problem.Please help

**Comment by martmists** [comment]
configure your PYTHONPATH to include `/usr/local/lib/python3.6/site-packages`

**Comment by dbogdanov** [comment]
You should be able to install Essentia inside Bash on Ubuntu with ```pip install essentia```.
