### ISSUE TITLE
Can't run Freesound or Music Extractor.

### ISSUE THREAD

**Issue by savovs** [MTG/essentia#716]
Hi guys, when I do this:
```python
audio = MonoLoader(filename = path)()
extractor = MusicExtractor()
result = extractor(audio)
```

I get this error:
`Traceback (most recent call last):
  File "extractFeatures.py", line 60, in <module>
    current_extractor = extractor(audio)
  File "/usr/local/lib/python2.7/site-packages/essentia/standard.py", line 118, in __call__
    return self.compute(*args)
  File "/usr/local/lib/python2.7/site-packages/essentia/standard.py", line 95, in compute
    %(str(_c.determineEdt(arg)), str(goalType)))
TypeError: Error cannot convert argument VECTOR_REAL to STRING`

Not sure what's happening, I just installed Essentia from HEAD today

**Comment by alastair** [comment]
`MusicExtractor` takes the filename as an argument, not an audio stream: http://essentia.upf.edu/documentation/reference/std_MusicExtractor.html
