### ISSUE TITLE
Linux static build

### ISSUE THREAD

**Issue by eadward** [MTG/essentia#729]
I just downloaded the code updated after commit 0dda5e5727a883564c935c0f719bc666c876d673 and tried to  create static build of the library and executable example extractors. The library is being compiled, but I get an error when compiling the extractors. I am attaching the config and compilation logs. Any ideas? Thanks!

[configuration-compilation.log](https://github.com/MTG/essentia/files/2035249/configuration-compilation.log)

[config.log](https://github.com/MTG/essentia/files/2035242/config.log)

**Comment by sildeag** [comment]
See pull request #702.  Even without `gaia2`, I am sure it fixes a number of Linux issues.  I use Ubuntu 18.04.

**Comment by eadward** [comment]
Thanks for this. Do you know if these changes will be added to the main branch?

**Comment by sildeag** [comment]
No, but I hope they will.

**Comment by dbogdanov** [comment]
Closing this, at it builds fine with the latest master (we've updated scripts for static builds some time ago).
