### ISSUE TITLE
When are pull requests going to be completed?

### ISSUE THREAD

**Issue by sildeag** [MTG/essentia#738]
I made some changes to hopefully improve Gaia2 and make it more current using Qt5.  I made some changes to Essentia to accommodate the revised Gaia2.  Gaia2 could use a further overhaul - possibly using Postgresql.  I also found numerous issues with the Essentia built for Ubuntu (Linux) and fixed them.  Otherwise the package seems very comprehensive and robust.  Other people have made contributions too.  

Now, MTG is modifying the Essentia build, which certainly didn't generate the Examples and/or Vamp for Ubuntu platform, and in Travis seems to be targeting a `docker` containerized application.

Could MTG share its schedule for completing pull requests and say something about its plans rather than just waste these efforts by introducing apparent conflicts which didn't exist before.  Travis is really a non-issue as it is intended for a specific environment.  Thanks.

**Comment by dbogdanov** [comment]
Our current priority is to finalize python packaging for PyPi and release the 2.1_beta5 for people to start using those packages. We goal for manylinux1 packages which are compatible with any Linux distribution. For that reason we've setup builds usign a CentOS 5 docker environment  and those builds are run in Travis and will be automatically deployed on PyPi. We'll also add there building examples, cpptests, and possibly Vamp, too. 

After that, we'll get back to updating Gaia to Qt5 and the rest of pull requests. Thank you for your contributions!!

**Comment by sildeag** [comment]
Okay.  Sounds good.
