### ISSUE TITLE
Failed to build on arch linux

### ISSUE THREAD

**Issue by kureta** [MTG/essentia#739]
There are two errors:

    ../src/algorithms/standard/constantq.cpp: In member function ‘virtual void essentia::standard::ConstantQ::compute()’:
    ../src/algorithms/standard/constantq.cpp:64:35: error: no matching function for call to ‘std::vector<std::complex<float> >::assign(int&, std::complex<double>)’ constantQ.assign(_uK, 0.0 + 0.0i); // initialize output

    ../src/algorithms/standard/constantq.cpp: In member function ‘virtual void essentia::standard::ConstantQ::configure()’:
    ../src/algorithms/standard/constantq.cpp:104:69: error: no matching function for call to ‘std::vector<std::complex<float> >::vector(int&, std::complex<double>)’ vector<complex<Real> > transfHammingWindowR(_FFTLength, 0.0 + 0.0i);

I can provide additional information if you tell me what you need to diagnose the problem.

**Comment by dbogdanov** [comment]
Please, check if this fix solves the issue (the ```constantq_archlinux_fix``` branch).

**Comment by kureta** [comment]
Thanks. It did fix the compilation error. Everything works now.
