### ISSUE TITLE
In testing I have discovered that while many features work, link failures occur.

### ISSUE THREAD

**Issue by sildeag** [MTG/essentia#743]
1. `python3 ./waf configure --with-python --with-vamp --with-cpptests --with-examples` works  but the same build configuration plus `--with-gaia` fails.  I was hoping this would use the `Libs` and `Cflags`from pkg-config `gaia2.pc` but it doesn't seem to and is very difficult to figure out.

2. `python3 ./waf configure --mode=release --with-gaia --with-example=streaming_extractor_music_svm` fails.  The use of a `gaia` example fails to link properly.   

3.  At least on Ubuntu 18.04, `--with-python` results in `_essentia.cpython-36m-x86_64-linux-gnu.so`.  This might need to be `_essentia.so` for normal functioning.  This might be a `python3` specific issue and could be solved using `ctx.env['pyext_PATTERN'] = "%s.so" and some code to alter the ctx.env['PYTHONDIR'] for python3, whichever version is used.

4. `python3 ./waf doc` does not work.  Sphinx attempts to use python 2.7.  I believe this is some kind of unresolved Sphinx issue:
Output:
`Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/sildeag/.local/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 168, in <module>
    exec(compile(open("essentia_reference.py").read(), "essentia_reference.py", 'exec'))
IOError: [Errno 2] No such file or directory: 'essentia_reference.py'`

`essentia_reference.py` does in fact exist.

**Comment by dbogdanov** [comment]
No issues building the cases 1) and 2) with the latest master.

3) This is the correct file nameing for python 3. 

4) ```python3 waf doc``` now works (513235bf6a47f1bc5fb2a5e0722e17c9a6575a1f)
