### ISSUE TITLE
Understanding Essentia Key detection algorithm

### ISSUE THREAD

**Issue by jamiebullock** [MTG/essentia#744]
I'm a bit confused by how Essentia's Key detection algorithm works...

It takes as input a HPCP, which is in turn derived from the frequencies of the spectral peaks for a given spectral frame.

Looking at the code AFAICT neither HPCP nor Key are stateful, so it seems like the Key estimate is based on the spectral content of the current frame only. Is that correct? So if the frame size is 2048, then we only ever get a key estimate based on the current 2048 samples, the next key estimate is for the next 2048 and so on. Is that right, or have I missed something?

**Comment by dbogdanov** [comment]
The standard mode of the algorithm estimates key/scale for a given HPCP vector. The streaming mode first accumulates a stream of HPCP vectors and computes its mean to provide the estimation.

**Comment by jamiebullock** [comment]
Ah OK. I can now see this in the code, thanks.

**Comment by dbogdanov** [comment]
That is also mentioned in the documentation.

**Comment by jamiebullock** [comment]
@dbogdanov one more question: does `KeyExtractor` internally always use the streaming mode?

**Comment by dbogdanov** [comment]
@jamiebullock Yes, it does!
