### ISSUE TITLE
undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by tanjiarui** [MTG/essentia#745]
According to the official installation tutorial, all dependencies were set, and Compiling for Python3 succeed. But this error jumped out when i ran ./waf run_python_tests. What happened?
> Running python unit tests using /usr/bin/python
Traceback (most recent call last):
  File "test/src/unittests/all_tests.py", line 27, in <module>
    import essentia
  File "/usr/share/essentia/build/python/essentia/__init__.py", line 1, in <module>
    from . import _essentia
ImportError: /usr/share/essentia/build/python/essentia/_essentia.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_ZeroStruct

**Comment by tanjiarui** [comment]
BTW, /usr/bin/python is already linked to python3.6

**Comment by AnasGhrab** [comment]
I have to same problem...

**Comment by AnasGhrab** [comment]
It's gone with pip install essentia

**Comment by dbogdanov** [comment]
This is a result of python version mismatch on your particular installation. If anyone has this issue and needs to build from source, you are welcome to re-open the issue and provide more details.
