### ISSUE TITLE
Using ConstantQ

### ISSUE THREAD

**Issue by eshaan-m** [MTG/essentia#746]
The documentation says that it needs a input as : vector_complex i.e. a complex vector frame. 
I'm having trouble understanding how exactly do I get a complex vector frame. The FrameGenerator gives a frame that is a vector_real. 
Kindly help ...
error I'm getting is : TypeError: Error cannot convert argument VECTOR_REAL to VECTOR_COMPLEX

**Comment by dbogdanov** [comment]
For your purpose you can use [SpectrumCQ](http://essentia.upf.edu/documentation/reference/std_SpectrumCQ.html).

**Comment by eshaan-m** [comment]
I am getting an error : NameError: name 'SpectrumCQ' is not defined
Also it would be great if you could shed some light on the difference between ConstantQ and SpectrumCQ

**Comment by dbogdanov** [comment]
SpectrumCQ is a wrapper around ConstantQ algorithm that accepts vectors of reals. 

Note, that you can also use [NSGConstantQ](http://essentia.upf.edu/documentation/reference/std_NSGConstantQ.html).

See a tutorial here: https://github.com/MTG/essentia/blob/master/src/examples/python/NSGConstantQ-example.ipynb 

You might be using an older version of Essentia. Try ```brew install essentia --HEAD``` to build the latest master (we've just merged updates for NSGConstantQ and updated the documentation) .
