### ISSUE TITLE
Key algorithm never completes execution

### ISSUE THREAD

**Issue by NaturalFigurehead** [MTG/essentia#751]
I'm running this on a virtual Ubuntu machine. 

The `KeyExtractor` algorithm works fine, but I wanted to try out the `Key` algorithm with its customizable profile types. However when I execute the `Key` algorithm it outputs `[   INFO   ] MusicExtractorSVM: no classifier models were configured by default` and then it never finishes executing. 

My code looks like this:

`audio = es.MonoLoader(filename='samples/TakeTheFall.mp3')()`

`key = es.Key(profileType='shaath',useThreeChords=True)(audio)`

`print key`

What's going on with this algorithm?

**Comment by dbogdanov** [comment]
The input to the Key algorithm is not audio, but an HPCP vector (see [documentation](http://essentia.upf.edu/documentation/reference/std_Key.html)). You should first compute the HPCP for the audio segment on which you want to analyze the key, and then run this algorithm. See the example of how it is done in the streaming mode here: 

https://github.com/MTG/essentia/blob/master/src/examples/tutorial/example_key_by_steps_streaming.py

If you are interested to estimate key on a bunch of audio files, you can also use [MusicExtractor](http://essentia.upf.edu/documentation/reference/std_MusicExtractor.html) algorithm which computes three different profiles. 

We should update KeyExtractor algorithm to allow different key profiles.

**Comment by NaturalFigurehead** [comment]
@dbogdanov ah cool I see now. Thanks for the help.
