### ISSUE TITLE
Commented code on NSGConstantQ

### ISSUE THREAD

**Issue by pabloEntropia** [MTG/essentia#753]
`NSGConstantQ` was implemented in a way that the input is a vector of audio samples (`vector<Real>`) and the output is a time/frequency matrix of complex values (`vector<vector<Complex> >`). Although this makes perfect sense for the standard (offline) implementation, it is not suitable for the streaming case (real time) as  Essentia pools can not store streams of complex 2D matrices.

The first workaround proposed for this was to implement a wrapping class in order to store all the input audio frames until the stream is over and then compute the `NSGConstantQ` just once as in the standard mode.
The code is commented here,
https://github.com/MTG/essentia/blob/72928a8c806fe6822818861927c41336ca5f28fc/src/algorithms/standard/nsgconstantq.h#L113

However, this solution was discarded as it does not allow real real-time processing. 
The final solution was to implement a new streaming algorithm [NSGConstantQStreaming](https://github.com/MTG/essentia/blob/72928a8c806fe6822818861927c41336ca5f28fc/src/algorithms/standard/nsgconstantqstreaming.h) that for each audio frame calls the `NSGConstantQ` `StreamingAlgorithmWrapper`. Then the algorithm takes each 2D output matrix and sequentially pushes each column to the pool along with a timestamp counter in order to facilitate its posterior reconstruction. 

Note that although the `NSGConstantQ` `StreamingAlgorithmWrapper` output cannot be directly stored in a pool, it can be feed into other algorithms in an Essentia streaming network.

**Comment by dbogdanov** [comment]
@pabloEntropia Are there any relevant TODOs to follow or we can archive this issue?

**Comment by pabloEntropia** [comment]
No. Changes related to this issue were already addressed at #754
