### ISSUE TITLE
Failed compilation with KISSFFT

### ISSUE THREAD

**Issue by alexsivris** [MTG/essentia#757]
Hello!
I tried compiling essentia with the following configuration:

`./waf configure --lightweight= --fft=KISS`

Waf correctly detects, that I want to use KISSFFT instead of FFTW when running ./waf:
`Building all the algorithms
Ignoring the following algorithms: Chromaprinter, AudioLoader, EasyLoader, Chromagram, ConstantQ, FreesoundExtractor, MonoLoader, Resample, AudioWriter, MusicExtractor, MonoWriter, EqloudLoader, YamlOutput, MusicExtractorSVM, MetadataReader, GaiaTransform, YamlInput, IFFTW, FFTW, IFFTA, FFTA, FFTWComplex
Created algorithms registration file
`
 However, the compilation process aborts because the header file fftw3.h cannot be found:
`[ 34/247] Compiling src/algorithms/essentia_algorithms_reg.cpp
In file included from ../src/algorithms/essentia_algorithms_reg.cpp:109:0:
../src/algorithms/standard/ifftwcomplex.h:26:10: fatal error:fftw3.h: No such file or directory
 #include <fftw3.h>
          ^~~~~~~~~
compilation terminated.`
What am I missing?

Edit: I forgot to mention that I am facing this issue in version 2.1-beta5-dev, cloned from github. The version 2.1-beta3 compiles fine.

**Comment by sildeag** [comment]
You are probably missing the dependency.  Look at `essentia/packaging/debian_3rdparty/build_fftw3.sh`.  Hope that helps.
