### ISSUE TITLE
ERROR -> audioloader.cpp:(.text+0x3a2): undefined reference to `swr_alloc_set_opts'

### ISSUE THREAD

**Issue by lazumbra** [MTG/essentia#77]
I have this big problem here. Who knows how can I fix it?

usr/local/lib//libessentia.a(audioloader.cpp.1.o): In function `essentia::streaming::AudioLoader::openAudioFile(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':

audioloader.cpp:(.text+0x3a2): undefined reference to `swr_alloc_set_opts'

audioloader.cpp:(.text+0x3b1): undefined reference to `swr_init'

audioloader.cpp:(.text+0xaa0): undefined reference to `swr_free

/usr/local/lib//libessentia.a(audioloader.cpp.1.o): In function `essentia::streaming::AudioLoader::decode_audio_frame(AVCodecContext*, short*, int*, AVPacket*)':
audioloader.cpp:(.text+0xc03): undefined reference to `swr_convert'

**Comment by ramonsanabria** [comment]
You should compile rearranging the flags as follows:

g++ -pipe -Wall -O2 -fPIC -I/usr/local/include/essentia/ -I/usr/local/include/essentia/scheduler/ -I/usr/local/include/essentia/streaming/  -I/usr/local/include/essentia/utils -I/usr/include/taglib -I/usr/local/include/gaia2 -I/usr/include/qt4 -I/usr/include/qt4/QtCore -D__STDC_CONSTANT_MACROS standard_mfcc.cpp -o standard_mfcc -lessentia -L/usr/local/lib -LQtCore -lpthread -lfftw3f -lyaml -lavformat -lavcodec -lavutil -lswresample -lsamplerate -ltag -lgaia2 -lQtCore -lyaml

**Comment by dbogdanov** [comment]
Closing, as libswresample is not supported anymore (see #321).
