### ISSUE TITLE
[Android] Crash when creating an algorithm from factory.

### ISSUE THREAD

**Issue by alexsivris** [MTG/essentia#770]
To reproduce the issue, the following lines are written in a native C++ function of your Android project:
std::vector<float> audio_data_accum = ... ;
std::vector<float> spec_out;

essentia::init();
essentia::standard::AlgorithmFactory& factory_ = essentia::standard::AlgorithmFactory::instance();
**essentia::standard::Algorithm *spec_ = factory_.create("Spectrum");**
spec_->input("frame").set(audio_data_accum);
spec_->output("spec").set(spec_out);
spec_->compute();
delete spec_;

The problem occurs when trying to "create" the Spectrum algorithm. The exception message is `SIGSEGV (signal SIGSEGV: invalid address (fault address: 0xb410027))` and, looking at the variable explorer of the frame of the function where it is thrown (void setName(const std::string& name) { _name = name; } in the file essentia/include/essentia/configurable.h, line 53), the variable _name is empty. The strange thing is that when I go to the frame of function setNames and use LLDB to print out the variable contents (by typing `fr variable` in the LLDB console), I get the following output:
(essentia::Configurable *) this = 0x0000007f90a670c0
(const std::string &) **name = 0x0000007fc3406b88 "FFT"**: {
  _M_dataplus = (_M_p = "FFT")
}

Clearly, these two outputs do not match...

**Comment by alexsivris** [comment]
@dbogdanov Yes, it works now after compiling the library from the branch android_fix (mentioned in issue #622). I also explicitly used libc++ in my gradle file:
defaultConfig {
        ...
        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_shared', '-DANDROID_TOOLCHAIN=clang'
                cppFlags "-std=c++14 -frtti -fexceptions -stdlib=libc++"
            }
            ndk {
               ...

            }
        }
    }

The first time building the project I had the error, that Android could not find libc++_shared.so, so I added the CMake file mentioned in this stackoverflow post https://stackoverflow.com/a/39628365/4699335 (direct link to cmake file https://raw.githubusercontent.com/jomof/ndk-stl/master/ndk-stl-config.cmake) to my main CMakeLists.txt by including it in the very top:
cmake_minimum_required(VERSION 3.4.1)
set (CMAKE_CXX_STANDARD 14)
**include(ndk-stl-config.cmake)**
...

**Comment by dbogdanov** [comment]
Closing this issue as solved (see #622)

**Comment by amCap1712** [comment]
@alexsivris Can you share your CMakeLists.txt or the project if possible as a sample reference ? It will be a great help in learning how to compile and use essentia on Android.
