### ISSUE TITLE
Change Compiler error

### ISSUE THREAD

**Issue by ZhiyuLiu1993** [MTG/essentia#780]
Hi，I want to change th compiler, but the following error occurred during configuration:

./waf configure --build-static --with-cpptest --prefix=/data_400g/dev/shadowerliu/trunk/SongCompare/build --check-cxx-compiler=/data/dev/commtool/gcc-4.8.2/bin/g++ --check-c-compiler=/data/dev/commtool/gcc-4.8.2/bin/gcc
Setting top to : /data_400g/dev/shadowerliu/trunk/SongCompare/build_lib/essentia-2.1_beta4
Setting out to : /data_400g/dev/shadowerliu/trunk/SongCompare/build_lib/essentia-2.1_beta4/build
→ configuring the project in /data_400g/dev/shadowerliu/trunk/SongCompare/build_lib/essentia-2.1_beta4
→ Building in release mode
Checking for '/data/dev/commtool/gcc-4.8.2/bin/g++' (C++ compiler) : not found
could not configure a C++ compiler!
(complete log in /data_400g/dev/shadowerliu/trunk/SongCompare/build_lib/essentia-2.1_beta4/build/config.log)

Any help would be appreciated！

**Comment by dbogdanov** [comment]
You should not specify the full path to the compiler binaries with the ```--check-*-compiler``` flags ([see here](https://waf.io/apidocs/tools/compiler_cxx.html)), but you can specify ```$PATH``` variable to pick up the desired compiler (example [here](https://essentia.upf.edu/documentation/FAQ.html#cross-compiling-for-android)).
