### ISSUE TITLE
LoudnessEBUR128 - Gating for momentary and short-term loudness?

### ISSUE THREAD

**Issue by MartinJRAT** [MTG/essentia#787]
When processing audio-files using the loudness in EBU R128-mode we have observed, that the short-term loudness values as well as the momentary loudness values calculated abruptly change on abrupt sample value changes (e.g. when there is now fade-in and audio suddenly starts). 

As there is an integration window applied (0.4s and 3.0s respectively) we wonder, why there is no smooth increase for the  short-term and momentary loudness values. An possible explanation for that behaviour could be, that the measurements are gated (as e.g. required for calculating "integrated" loudness), but according to EBU Tech 3341-2016 chapter 2.2 (‘EBU Mode’ metering to supplement Loudness normalisation) the measurements should not(!) be "gated".  Do you have another explanation for that observation?

**Comment by dbogdanov** [comment]
[Here](https://github.com/MTG/essentia/blob/master/src/algorithms/temporal/loudnessebur128.cpp#L61) is the code for the processing chain for computing short-term and momentary loudness. This is simply a frame cutter > compute mean of a frame > compute log for loudness. Both aren't gated, so everything looks ok. 

Can you provide an audio example and the plot of the values with abrupt changes for inspection?

**Comment by MartinJRAT** [comment]
Thank you for your answer - in the meantime we found the error in our interpretation chain.
