### ISSUE TITLE
ns3 build error

### ISSUE THREAD

**Issue by bushra03** [MTG/essentia#789]
HI,

I have installed ns3 on Ubuntu18.4. But during building I am getting following error:

Build failed
 -> task in 'REMgenerator' failed (exit status 1): 
    {task 140398528245320: cxx REMgenerator.cc -> REMgenerator.cc.1.o}
['/usr/bin/g++', '-O3', '-g', '-Wall', '-Werror', '-march=native', '-fstrict-overflow', '-Wstrict-overflow=2', '-std=c++11', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-pthread', '-pthread', '-I.', '-I..', '-I/usr/include/gtk-2.0', '-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include', '-I/usr/include/pango-1.0', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/cairo', '-I/usr/include/pixman-1', '-I/usr/include/freetype2', '-I/usr/include/libpng16', '-I/usr/include/harfbuzz', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/gio-unix-2.0', '-I/usr/include/atk-1.0', '-I/usr/include/libxml2', '-DNS3_BUILD_PROFILE_OPTIMIZED', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_SQLITE3=1', '-DHAVE_GTK2=1', '-DHAVE_LIBXML2=1', '../scratch/REMgenerator.cc', '-c', '-o',

Can anyone help me how to fix it?

**Comment by dbogdanov** [comment]
Please, provide more context. What are you compiling?
