### ISSUE TITLE
Another build fail

### ISSUE THREAD

**Issue by NOEPG** [MTG/essentia#792]
Hello,

I just built Essentia on an Ubuntu 16.04.
Now I'm trying to build it on my Debian 9.5 but I have some issues.

I run : ./waf configure --build-static --with-python --with-cpptests --with-examples --with-vamp
And then : ./waf

And at step 271 I have this : 

[271/369] Linking build/src/examples/essentia_standard_onsetrate
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libavformat.so: undefined reference to symbol 'inflate'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libavformat.so: undefined reference to symbol 'inflate'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libavformat.so: undefined reference to symbol 'inflate'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libavformat.so: undefined reference to symbol 'inflate'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/paul-gauthier/Downloads/essentia-2.1_beta4/build'
Build failed
 -> task in 'essentia_standard_fadedetection' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_standard_beatsmarker' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_standard_mfcc' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_standard_onsetrate' failed with exit status 1 (run with -v to display more information)

When I run ./waf -v I have this :

Waf: Leaving directory `/home/paul-gauthier/Downloads/essentia-2.1_beta4/build'
Build failed
 -> task in 'essentia_standard_mfcc' failed with exit status 1: 
	{task 140707032079408: cxxprogram standard_mfcc.cpp.3.o -> essentia_standard_mfcc}
['/usr/bin/g++', 'src/examples/standard_mfcc.cpp.3.o', '-o/home/paul-gauthier/Downloads/essentia-2.1_beta4/build/src/examples/essentia_standard_mfcc', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L/usr/local/lib', '-lfftw3f', '-lavformat', '-lavcodec', '-lavutil', '-lavresample', '-lsamplerate', '-ltag', '-lyaml']
 -> task in 'essentia_standard_beatsmarker' failed with exit status 1: 
	{task 140707032078768: cxxprogram standard_beatsmarker.cpp.1.o -> essentia_standard_beatsmarker}
['/usr/bin/g++', 'src/examples/standard_beatsmarker.cpp.1.o', '-o/home/paul-gauthier/Downloads/essentia-2.1_beta4/build/src/examples/essentia_standard_beatsmarker', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L/usr/local/lib', '-lfftw3f', '-lavformat', '-lavcodec', '-lavutil', '-lavresample', '-lsamplerate', '-ltag', '-lyaml']
 -> task in 'essentia_standard_fadedetection' failed with exit status 1: 
	{task 140707032079088: cxxprogram standard_fadedetection.cpp.2.o -> essentia_standard_fadedetection}
['/usr/bin/g++', 'src/examples/standard_fadedetection.cpp.2.o', '-o/home/paul-gauthier/Downloads/essentia-2.1_beta4/build/src/examples/essentia_standard_fadedetection', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L/usr/local/lib', '-lfftw3f', '-lavformat', '-lavcodec', '-lavutil', '-lavresample', '-lsamplerate', '-ltag', '-lyaml']
 -> task in 'essentia_standard_onsetrate' failed with exit status 1: 
	{task 140707032079728: cxxprogram standard_onsetrate.cpp.4.o -> essentia_standard_onsetrate}
['/usr/bin/g++', 'src/examples/standard_onsetrate.cpp.4.o', '-o/home/paul-gauthier/Downloads/essentia-2.1_beta4/build/src/examples/essentia_standard_onsetrate', '-Wl,-Bstatic', '-Lsrc', '-lessentia', '-Wl,-Bdynamic', '-L/usr/local/lib', '-lfftw3f', '-lavformat', '-lavcodec', '-lavutil', '-lavresample', '-lsamplerate', '-ltag', '-lyaml']

I have no idea how to fix it. Does anyone have a solution ?

Thank you for your help,
Paul-Gauthier

**Comment by dbogdanov** [comment]
You are [missing some dependencies](https://stackoverflow.com/questions/27366433/linking-libavcodec-and-libavformat-undefined-references) for libav when linking. The waf configuration script uses pkg-config to get necessary flags for linking and I guess those dependencies were missing. You can double-check what pkg-config detected in the ```build/config.log``` file. 

Try building without ``--build-static`` flag.  Also, building from the master branch on Debian 9.6 with your configuration works fine for me.
