### ISSUE TITLE
Plot an extractor output using gnuplot

### ISSUE THREAD

**Issue by NOEPG** [MTG/essentia#793]
Hello,

I'm very new with RtAudio and Essentia.

I want to extract and plot speech features in real time.
How can I put the mfc coefs from the mfcc algo output in a vector in order to plot it using gnuplot ?

Thank you for your help,
Paul-Gauthier

**Comment by NOEPG** [comment]
Hi,

There is also this information message in case this is linked with my issue : 

[   INFO   ] TriangularBands: input spectrum size (513) does not correspond to the "inputSize" parameter (1025). Recomputing the filter bank.

**Comment by NOEPG** [comment]
I found a way to do that using VectorOutput. I'm now able to plot spectrum and mfcc in real time

**Comment by dbogdanov** [comment]
Correct, VectorOutput is the way to go for storing algorithm outputs in the streaming mode.
