### ISSUE TITLE
'Algo' object has no attribute 'audio'

### ISSUE THREAD

**Issue by dorienh** [MTG/essentia#794]
I'm getting two errors, the ''Algo' object has no attribute 'audio'' and name 'logNorm' is not defined

Am I perhaps forgetting to load some libraries? 

My code is on Google [collab](https://colab.research.google.com/drive/19m-PDSqyCCQSAwjxNMGibOOmLG5JbrIZ). 

The code in question is: 

> 
> from matplotlib.colors import LogNorm
> import essentia
> 
> mfccs = []
> melbands = []
> melbands_log = []
> 
> for frame in FrameGenerator(audio, frameSize=1024, hopSize=512, startFromZero=True):
>     mfcc_bands, mfcc_coeffs = mfcc(spectrum(w(frame)))
>     mfccs.append(mfcc_coeffs)
>     melbands.append(mfcc_bands)
>     melbands_log.append(logNorm(mfcc_bands))
> mfccs = essentia.array(mfccs).T
> melbands = essentia.array(melbands).T
> melbands_log = essentia.array(melbands_log).T
> 
> imshow(melbands[:,:], aspect = 'auto', origin='lower', interpolation='none')
> plt.title("Mel band spectral energies in frames")
> show()
> 
> imshow(melbands_log[:,:], aspect = 'auto', origin='lower', interpolation='none')
> plt.title("Log-normalized mel band spectral energies in frames")
> show()
> 
> imshow(mfccs[1:,:], aspect='auto', origin='lower', interpolation='none')
> plt.title("MFCCs in frames")
> show()

> NameError                                 Traceback (most recent call last)
> <ipython-input-121-efd01f39b733> in <module>()
>      10     mfccs.append(mfcc_coeffs)
>      11     melbands.append(mfcc_bands)
> ---> 12     melbands_log.append(logNorm(mfcc_bands))
>      13 
>      14 # transpose to have it in a better shape
> 
> NameError: name 'logNorm' is not defined

And:

> from pylab import *
> from essentia.streaming import *
> loader = ess.MonoLoader(filename=file)
> framecutter = ess.FrameCutter(frameSize=4096, hopSize=2048)
> windowing = ess.Windowing(type='blackmanharris62')
> spectrum = ess.Spectrum()
> spectralpeaks = ess.SpectralPeaks(orderBy='magnitude',
>                                   magnitudeThreshold=0.00001,
>                                   minFrequency=20,
>                                   maxFrequency=3500,
>                                   maxPeaks=60)
> 
> hpcp = ess.HPCP()
> hpcp_key = ess.HPCP(size=36, # we will need higher resolution for Key estimation
>                     referenceFrequency=440, # assume tuning frequency is 44100.
>                     bandPreset=False,
>                     minFrequency=20,
>                     maxFrequency=3500,
>                     weightType='cosine',
>                     nonLinear=False,
>                     windowSize=1.)
> 
> key = ess.Key(profileType='edma', # Use profile for electronic music
>               numHarmonics=4,
>               pcpSize=36,
>               slope=0.6,
>               usePolyphony=True,
>               useThreeChords=True)
> pool = essentia.Pool()
> loader.audio >> framecutter.signal
> framecutter.frame >> windowing.frame >> spectrum.frame
> spectrum.spectrum >> spectralpeaks.spectrum
> spectralpeaks.magnitudes >> hpcp.magnitudes
> spectralpeaks.frequencies >> hpcp.frequencies
> spectralpeaks.magnitudes >> hpcp_key.magnitudes
> spectralpeaks.frequencies >> hpcp_key.frequencies
> hpcp_key.hpcp >> key.pcp
> hpcp.hpcp >> (pool, 'tonal.hpcp')
> key.key >> (pool, 'tonal.key_key')
> key.scale >> (pool, 'tonal.key_scale')
> key.strength >> (pool, 'tonal.key_strength')
> essentia.run(loader)
> 
> imshow(pool['tonal.hpcp'].T, aspect='auto', origin='lower', interpolation='none')
> plt.title("HPCPs in frames (the 0-th HPCP coefficient corresponds to A)")
> show()
> 
> print("Estimated key and scale:", pool['tonal.key_key'] + " " + pool['tonal.key_scale'])
> 
> 

> 
> ----------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-117-4d573b5b882a> in <module>()
>      37 
>      38 # Connect streaming algorithms
> ---> 39 loader.audio >> framecutter.signal
>      40 framecutter.frame >> windowing.frame >> spectrum.frame
>      41 spectrum.spectrum >> spectralpeaks.spectrum
> 
> AttributeError: 'Algo' object has no attribute 'audio'

It worked earlier, I think because I ran the notebook in a different order. Somehow it doesn't work anymore now... Any thoughts? It's basically the tutorial code...

**Comment by dbogdanov** [comment]
You should take care of the order in which you run cells in the tutorial notebook.  From the code you've posted, it looks that your function is called ``LogNorm``, not ``logNorm``, but instead perhaps you were referring to Essentia's algorithm (see the line ``logNorm = UnaryOperator(type='log')'' in the tutorial).

Make sure your ``loader`` object is actually referring to MonoLoader.
