### ISSUE TITLE
Classifier models don't work with latest code

### ISSUE THREAD

**Issue by antlarr** [MTG/essentia#799]
I've built gaia2 2.4.5 and the latest essentia from github for openSUSE and found that the supplied classifier models at [documentation/svm_models/](http://essentia.upf.edu/documentation/svm_models/) don't seem to work as they were made for a previous essentia version. I've then built the git version tagged as v2.1.0beta2 (the tag is from 2014/11/19 although beta2 was released in March 2015?) and this version works fine with the supplied classifiers.

Would it be possible to put also classifier models that work with beta5 to download at the above directory? The current ones only work with 4 years old code and it would be nice to promote using the latest code to see if v2.1.0 is released soon.

In any case, thanks for this great library.

**Comment by dbogdanov** [comment]
We'll need to retrain all our classifier models for that. This is definitely on our list and should be done when the 2.1 is released. Are you interested in any specific classifier model?

**Comment by antlarr** [comment]
Nice, thanks for keeping it in mind. I guess retraining the models can take quite some resources so it wouldn't be possible to retrain them for every release or at least for the latest one, right? (I wouldn't mind helping there with cpu power if possible, but I guess you need a big dataset preprocessed manually for this, and I don't think I can help with the preprocessing). Is there somewhere some schedule as to when is 2.1.0 expected to be released?

> Are you interested in any specific classifier model?

I'm developing a music player and would like to use them to categorize music so it's possible to search for "songs similar to this one" and to perform searches beyond tags. So I would be interested in most of the models (mainly voice_instrumental, gender and all of mood_*, but that's basically most of them).

**Comment by dbogdanov** [comment]
@antlarr  We are retraining the models for the current master and will provide those in the next month. The definite models will be released together with the 2.1-beta5 release of Essentia.

**Comment by antlarr** [comment]
@dbogdanov that's great! Thanks!

**Comment by antlarr** [comment]
Hi, is there any estimation on when 2.1-beta5 will be released?

**Comment by dystq** [comment]
Hi there @dbogdanov, I'm interested to know if this is still planned. We have work project for which we're very interested in leveraging the pre-trained models. Cheers!

**Comment by dbogdanov** [comment]
@dystq We have retrained a number of models. @pabloEntropia can possibly give more details.

**Comment by dystq** [comment]
Thank you Dmitry! This is great news and we can't wait to use them! @pabloEntropia would you know when and where might I be able to access the re-trained models?

**Comment by pabloEntropia** [comment]
@dystq I have recently retrained the existing models in order to make them compatible with the current Essentia version. However, they are not publically available yet. Hopefully, I will be able to test them and make them available by the end of the next week.

**Comment by pabloEntropia** [comment]
We have recently decided to release Essentia `2.1_beta5` which includes improvements for some of the features used to train the models. This means that the models have to be retrained again in order to make them fully compatible with this version. Hopefully, this will be ready by the end of the next week. Thanks for being patient!

**Comment by ALtroberts** [comment]
Hi @pabloEntropia, has there been any strides towards publicly releasing the models? Thank you for your work on this

**Comment by dbogdanov** [comment]
Have a look at https://essentia.upf.edu/documentation/svm_models/
We have new models hosted here (beta5). Let us know if everything is OK.

**Comment by antlarr** [comment]
A couple of days ago I finally (sorry for taking so long) tested it and started the integration with my music manager ([bard](https://github.com/antlarr/bard)) and it seems to work quite well (I'm using v2.1_beta5 and the appropriate models from the url you linked above), so I'll close this issue now.

Btw, I'm also creating an essentia package including those models for openSUSE (currently at https://build.opensuse.org/package/show/home:alarrosa:branches:multimedia:libs/essentia but I'll try to make it an official package). Btw, what's the license of those models? Can you add a license file to https://essentia.upf.edu/documentation/svm_models/ ?

 Thanks a lot!
