### ISSUE TITLE
Fingerprint HTTP lookup error

### ISSUE THREAD

**Issue by munendra7777** [MTG/essentia#800]
# Fingerprint lookup gives  HTTP error?

{'commit_hash': u'033ab93c7',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/munendra/.local/lib/python2.7/site-packages/IPython',
 'ipython_version': '5.8.0',
 'os_name': 'posix',
 'platform': 'Linux-4.15.0-39-generic-x86_64-with-debian-buster-sid',
 'sys_executable': '/home/munendra/anaconda2/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.15 |Anaconda, Inc.| (default, Nov 13 2018, 23:04:45) \n[GCC 7.3.0]'}
---------------------------------------------------------------------------

[Fingerprint lookup.pdf](https://github.com/MTG/essentia/files/2608959/Fingerprint.lookup.pdf)

HTTPError: HTTP Error 502: Bad Gateway

**Comment by alastair** [comment]
It looks like this is an issue with the AcoustID API, and not any feature of Essentia. Please double-check the way you call the API and check the AcousicID documentation.
If you file an issue in the future please make sure that you give more detailed information about what you are trying to do, and the specific commands that you are running when you receive the error. Be careful about posting private data in your issues. You should reset your acoustid api key.
