### ISSUE TITLE
get git sha of essentia installation

### ISSUE THREAD

**Issue by fzalkow** [MTG/essentia#803]
I want to find out the git commit corresponding to a specific essentia installation. Since there exists the variable `__version_git_sha__`, I thought that should be easy:

```python
>>> import essentia
>>> essentia.__version_git_sha__
'v2.1_beta3-482-g4df1824'
```

However, when searching for this hash in an essentia clone, I don't find any commit:

```bash
$ git rev-list --all | grep g4df1824
```

So the questions are:
* Can I find out the git commit corresponding to an essentia installation? 
* What is `__version_git_sha__` encoding?

Thanks a lot!

**Comment by dbogdanov** [comment]
The ```__version_git_sha__``` is obtained by the build script [here](https://github.com/MTG/essentia/blob/master/wscript#L11) when you configure the project.  It corresponds to the output of the following command:
```
git describe --dirty --always
```

This outputs you the version of Essentia (2.1 beta3), a number of commits done on top of it (482), and  a hash suffix ("-g" + 7-char abbreviation for the commit). See more details in the [documenation for git describe](https://git-scm.com/docs/git-describe#_examples).

**Comment by fzalkow** [comment]
Thank you! I wasn't aware that "g" is not part of the hash... Now it works:

```bash
$ git rev-list --all | grep 4df1824
```
