### ISSUE TITLE
How to get pitches of onsets？

### ISSUE THREAD

**Issue by ucasiggcas** [MTG/essentia#805]
Dear,
How to get piano pitch for 88 keys from a wav file, using the onsets detection method,
Any advice or suggestion will be good.
Thx

**Comment by dbogdanov** [comment]
Have a look at Essentia's algorithms related to pitch ([search for Pitch category](https://essentia.upf.edu/documentation/algorithms_reference.html)). PitchContourSegmentation segments pitch contours into notes.
