### ISSUE TITLE
MacOS Mojave build error

### ISSUE THREAD

**Issue by 009deep** [MTG/essentia#810]
Getting following error:

>  ----------------------------------------------------------------
> Testing pyext configuration
> ==>
> 
> #include <Python.h>
> #ifdef __cplusplus
> extern "C" {
> #endif
> 	void Py_Initialize(void);
> 	void Py_Finalize(void);
> #ifdef __cplusplus
> }
> #endif
> int main(int argc, char **argv)
> {
>    (void)argc; (void)argv;
>    Py_Initialize();
>    Py_Finalize();
>    return 0;
> }
> 
> <==
> [1/2] Compiling [32mbuild/.conf_check_84720c029ca7765dbad7d2e94e9f4731/test.cpp[0m
> 
> ['/usr/bin/clang++', '-std=c++11', '-pipe', '-Wall', '-msse', '-msse2', '-mfpmath=sse', '-O2', '-fPIC', '-fPIC', '-g', '-fwrapv', '-O3', '-arch', 'x86_64', '-arch', 'x86_64', '-fPIC', '-I../../../../anaconda3/envs/py3/include/python3.7m', '-I../../../../anaconda3/envs/py3/include', '-DGTEST_HAS_TR1_TUPLE=0', '-DHAVE_AVCODEC=1', '-DHAVE_AVFORMAT=1', '-DHAVE_AVUTIL=1', '-DHAVE_AVRESAMPLE=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_TAGLIB=1', '-DHAVE_YAML=1', '-DHAVE_FFTW=1', '-D__STDC_CONSTANT_MACROS', '-DPYTHONDIR="/usr/local/lib/python3.7/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python3.7/site-packages"', '-DNDEBUG', '../test.cpp', '-c', '-o/Users/njain202/essentia-master/build/.conf_check_84720c029ca7765dbad7d2e94e9f4731/testbuild/test.cpp.1.o', '-fPIC']
> [2/2] Linking [33mbuild/.conf_check_84720c029ca7765dbad7d2e94e9f4731/testbuild/testprog.cpython-37m-darwin.so[0m
> 
> ['/usr/bin/clang++', '-arch', 'x86_64', '-arch', 'x86_64', '-Wl,-stack_size,1000000', '-bundle', '-undefined', 'dynamic_lookup', 'test.cpp.1.o', '-o/Users/njain202/essentia-master/build/.conf_check_84720c029ca7765dbad7d2e94e9f4731/testbuild/testprog.cpython-37m-darwin.so', '-framework', 'CoreFoundation', '-L/Users/njain202/anaconda3/envs/py3/lib/python3.7/config-3.7m-darwin', '-lpython3.7m', '-ldl', '-lpython3.7m', '-ldl']
> err: ld: -stack_size option can only be used when linking a main executable
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> from /Users/njain202/essentia-master/src/python: Test does not build: Traceback (most recent call last):
>   File "/Users/njain202/essentia-master/.waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec/waflib/Configure.py", line 324, in run_build
>     bld.compile()
>   File "/Users/njain202/essentia-master/.waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec/waflib/Build.py", line 176, in compile
>     raise Errors.BuildError(self.producer.error)
> waflib.Errors.BuildError: Build failed
>  -> task in 'testprog' failed with exit status 1 (run with -v to display more information)
> 
> Could not build python extensions
> from /Users/njain202/essentia-master/src/python: The configuration failed
> 

In which file following command gets built?
> ['/usr/bin/clang++', '-arch', 'x86_64', '-arch', 'x86_64', '-Wl,-stack_size,1000000', '-bundle', '-undefined', 'dynamic_lookup', 'test.cpp.1.o', '-o/Users/njain202/essentia-master/build/.conf_check_84720c029ca7765dbad7d2e94e9f4731/testbuild/testprog.cpython-37m-darwin.so', '-framework', 'CoreFoundation', '-L/Users/njain202/anaconda3/envs/py3/lib/python3.7/config-3.7m-darwin', '-lpython3.7m', '-ldl', '-lpython3.7m', '-ldl']

This seems to be new parameter `-Wl,-stack_size,1000000` and causing issue?

**Comment by 009deep** [comment]
The issue turned out to be conda related and not mojave or python 3.7. I build it outside conda and imported to conda installation and it's working.

**Comment by jarmitage** [comment]
@009deep hi, can you share how you addressed this issue with conda?
