### ISSUE TITLE
How to use ConstantQ Algorithm in Android?

### ISSUE THREAD

**Issue by techiespace** [MTG/essentia#832]
I created a so file for Android as mentioned here - https://github.com/MTG/essentia/blob/master/FAQ.md#cross-compiling-for-android

Constantq is ignored if I use KISS so I used fftw instead.

I'm getting a blank screen on trying to use constant q in Android using factory.create() method.
Can anyone provide an example of using constant q in Android?

**Comment by bhatia-manish** [comment]
I am also facing the same issue. Please help

**Comment by bhatia-manish** [comment]
I want to knw if its possible to constant q algorithm in android as This algorithm uses fftw dependency.
If yes how to integrate this because current FAQ for cross compiling on android suggest to use KISS which ignores constant Q algorithm.

**Comment by dbogdanov** [comment]
There's a pull request #783 that will allow support for KISS FFT. We'll work on merging that soon.

**Comment by techiespace** [comment]
> There's a pull request #783 that will allow support for KISS FFT. We'll work on merging that soon.

Will this solve the ConstantQ issue, because i see `ConstantQ` in `ctx.env.ALGOIGNORE` of the pull request.

**Comment by pabloEntropia** [comment]
There is no reason for `ConstantQ` nor `Chromagram` to remain in the `ctx.env.ALGOIGNORE` after #783 for any FFT type. For the moment I will assess the behavior of the algorithms and remove them from `ALGOIGNORE` using `Kiss`.
