### ISSUE TITLE
standard_beatsmarker sample app fails on MacOS X 10.9.2

### ISSUE THREAD

**Issue by shubho** [MTG/essentia#84]
I compiled essentia on MacOSX 10.9.2 using the steps showed on the installation page. I compiled it without python or vamp support - but shouldn't matter in this case. Then I ran the standard_beatsmarker example application and I get the following error 

./standard_beatsmarker Card.mp3 Card.wav
libc++abi.dylib: terminating with uncaught exception of type essentia::EssentiaException: In BeatTrackerMultiFeature::confidence::set(): Output not bound to concrete object
Abort trap: 6

**Comment by robaru** [comment]
also fail in Debian 7.7 with essentia 2.01

$ ./standard_beatsmarker ~/exit.wav ~/exit_marker.wav 
terminate called after throwing an instance of 'essentia::EssentiaException'
  what():  In BeatTrackerMultiFeature::confidence::set(): Output not bound to concrete object
Aborted

I tried to install libav and taglib statically also... but it still does not work... 

does someone have a solution for this? 
Thanks!

**Comment by dbogdanov** [comment]
Please try the latest version 2.1-beta2 or the latest code from master. I do not have this problem.
