### ISSUE TITLE
MacOS static build issues: src/libessentia.a(essentiautil.cpp.1.o) has no symbols

### ISSUE THREAD

**Issue by dschwertfeger** [MTG/essentia#844]
I'm following the instructions in the [FAQ](https://github.com/MTG/essentia/blob/master/FAQ.md#linuxosx-static-builds) to create a static build of Essentia.

At the very end of running `./waf`, there's a warning that `src/libessentia.a(essentiautil.cpp.1.o)` has no symbols:

```bash
[264/264] Linking build/src/libessentia.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: src/libessentia.a(essentiautil.cpp.1.o) has no symbols
```

When I link against the resulting static library (`libessentia.a`) in my project…

```cmake
add_library(essentia STATIC IMPORTED)
set_target_properties(essentia PROPERTIES
  IMPORTED_LOCATION /Users/dsc/Code/github/MTG/essentia/build/src/libessentia.a)
```

… I'm getting a whole bunch of linker errors about `Undefined symbols for architecture x86_64`. 

For example:
```
"_av_frame_alloc", referenced from:
  essentia::AudioContext::encodePacket(int) in libessentia.a(audiocontext.cpp.1.o)
  essentia::streaming::AudioLoader::openAudioFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libessentia.a(audioloader.cpp.1.o)
```

And at the very end of those, I get this:

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Moreover, when I try to build the static examples (as described in the FAQ)…

```
./waf configure  --with-static-examples
./waf
```

… the build fails with what I think is the same problem.

```
[280/347] Linking build/src/examples/essentia_standard_beatsmarker
Undefined symbols for architecture x86_64:
  "_inflate", referenced from:
      TagLib::zlib::decompress(TagLib::ByteVector const&) in libtag.a(tzlib.cpp.o)
  "_inflateEnd", referenced from:
      TagLib::zlib::decompress(TagLib::ByteVector const&) in libtag.a(tzlib.cpp.o)
  "_inflateInit_", referenced from:
      TagLib::zlib::decompress(TagLib::ByteVector const&) in libtag.a(tzlib.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Here's the verbose output:

```
 -> task in 'essentia_standard_beatsmarker' failed with exit status 1: 
	{task 4367570536: cxxprogram standard_beatsmarker.cpp.1.o -> essentia_standard_beatsmarker}
['/usr/bin/clang++', '-Wl,-framework,CoreFoundation', '-Wl,-framework,Security', '-pthread', '-Wl,-framework,CoreFoundation', '-Wl,-framework,Security', '-pthread', '-Wl,-framework,CoreFoundation', '-Wl,-framework,Security', '-pthread', 'src/examples/standard_beatsmarker.cpp.1.o', '-o/Users/dsc/Code/github/MTG/essentia/build/src/examples/essentia_standard_beatsmarker', '-framework', 'CoreFoundation', '-framework', 'VideoToolbox', '-framework', 'CoreMedia', '-framework', 'QuartzCore', '-framework', 'CoreServices', '-framework', 'VideoDecodeAcceleration', '-framework', 'CoreFoundation', '-framework', 'VideoToolbox', '-framework', 'CoreMedia', '-framework', 'QuartzCore', '-framework', 'CoreServices', '-framework', 'VideoDecodeAcceleration', '-Lsrc', '-lessentia', '-L/Users/dsc/Code/github/MTG/essentia/packaging/debian_3rdparty/lib', '-L/Users/dsc/Code/github/MTG/essentia/packaging/debian_3rdparty/lib', '-L/Users/dsc/Code/github/MTG/essentia/packaging/debian_3rdparty/lib', '-L/Users/dsc/Code/github/MTG/essentia/packaging/debian_3rdparty/lib', '-L/Users/dsc/Code/github/MTG/essentia/packaging/debian_3rdparty/lib', '-L/Users/dsc/Code/github/MTG/essentia/packaging/debian_3rdparty/lib', '-L/Users/dsc/Code/github/MTG/essentia/packaging/debian_3rdparty/lib', '-L/Users/dsc/Code/github/MTG/essentia/packaging/debian_3rdparty/lib', '-L/Users/dsc/Code/github/MTG/essentia/packaging/debian_3rdparty/lib', '-lfftw3f', '-lm', '-lavformat', '-liconv', '-lm', '-lavcodec', '-liconv', '-lm', '-lavutil', '-lm', '-lavcodec', '-liconv', '-lm', '-lavutil', '-lm', '-lavutil', '-lm', '-lavresample', '-lm', '-lavutil', '-lm', '-lsamplerate', '-ltag', '-lyaml', '-lchromaprint', '-lfftw3f']
```

What stands out to me is this command which is repeated nine times:

```
'-L/Users/dsc/Code/github/MTG/essentia/packaging/debian_3rdparty/lib'
```

The static third-party libraries are located in this folder. 

**Maybe each of those commands should link against one specific library** (`packaging/debian_3rdparty/lib/libavcodec.a` for example) rather than the `lib` folder?

A few more details:

- I'm running MacOS Sierra (10.12.6)
- I'm on branch `master`
- And here's the [`config.log`](https://github.com/MTG/essentia/files/2980074/config.log)

**Please advise how to proceed.**

**Comment by loicgithub** [comment]
I just have exactly the same. I dit not try yet to import it myself in my own test. I just try to compile with the configuration with the examples. I wonder if it may be a problem with the directory for the import, maybe the lib libessentia.a should located in a precise directory, I'm not sure...
did you solved the problem since you closed the issue ?

**Comment by stevendrewers** [comment]
Same problem here! @dschwertfeger did you eventually solve this?

**Comment by MeijisIrlnd** [comment]
Resurrecting this, any ideas?

**Comment by YangLuYang** [comment]
Guys, You need import zlib,  Build Phases -> Link Binary -> + -> search libz.tdb。
And if meet "vDSP_" then import "accelerate" in same way.

**Comment by alexeismith** [comment]
Please did anyone find a solution to this that is not linking to extra dynamic libraries? I've built statically and it's giving me undefined symbol errors...

**Comment by alexeismith** [comment]
OK I realised what my issue was: I followed the steps for [Linux/OSX static builds](https://essentia.upf.edu/FAQ.html#linux-osx-static-builds), and saw the line 'Note that you can selectively build dependencies depending on the required Essentia algorithms.' I decided not to include most of the 3rd party libs and then moved onto the next step in that list:
`./waf configure  --with-static-examples
./waf`

My lack of experience meant I didn't realise that if you don't build all the dependencies, you have to choose a different configuration. I rebuilt with the following, which did the trick:
`./waf configure --lightweight= --fft=KISS
./waf`

It might be useful to include a note **in the static builds section** that different configure flags are required if you miss out dependencies - I thought the next section didn't apply to me!

Cheers
