### ISSUE TITLE
standard_onsetrate from top-of-tree fails on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by shubho** [MTG/essentia#85]
Since the top-of-tree is the only one that compiles on Ubuntu 14.04, I tried that and standard_onsetrate fails with the following error

 ./standard_onsetrate ./ComeHome.mp3 
terminate called after throwing an instance of 'essentia::EssentiaException'
  what():  AudioLoader: Error converting  from s16p to s16
Aborted (core dumped)

I have tried it with a couple of mp3's and none of them work. The supplied .wav files in ./test directory work

Is there a platform that essentia is able to read and write audio files like mp3 and wav - so far I haven't found it. Tried MacOS X 10.9.2 and Ubuntu 14.04

**Comment by dbogdanov** [comment]
Should be fixed in the latest master as we have refactored AudioLoader.
