### ISSUE TITLE
How to extract Gammatone Filter Spectra in essentia?

### ISSUE THREAD

**Issue by SethiPawandeep** [MTG/essentia#856]
Hi all.
I wanted to know how to extract GTF (Gammatone Filter Spectra) features in essentia.
GTF features are GFCC features without the last Discrete Cosine Transform (DCT).

(MFCC:MFSC = GFCC:GTF)

Thanks in advance.

**Comment by SethiPawandeep** [comment]
Also, is it the right way if I compute GFCC and then take an IDCT over the computed GFCC features?

**Comment by dbogdanov** [comment]
The ```bands``` output of the GFCC algorithm gives raw energy band values before applying DCT, if that's what you are searching for.
