### ISSUE TITLE
JSON invalid on 'danceability' for certain audios

### ISSUE THREAD

**Issue by ewekansige** [MTG/essentia#858]
I've got 1000+ audio files and I'm trying to extract their features.
For each file I am executing this command to get the audio features in a JSON file:
```
 !./essentia-extractors-v2.1_beta2/streaming_extractor_music 3_lyn_30.wav feat.json
```
But when I try to read the JSON, I'm getting an error for some of the generated JSON files:
```
   audiofeatures = pd.read_json('feat.json')
   ValueError: Unexpected character found when decoding object value
```

I checked the affected JSON files in jsonlint.com and I found that they are not valid:
Error: Parse error on line 646: ..., "danceability": -nan, "onset_rate" ----------------------^ Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

It seems to me that even if the danceability can't be obtained, throwing a "-nan" is breaking the JSON structure, therefore the returned value should be something different.

In my code I worked around it modifying the danceability in each of the offending JSON files, however I would like to know if you have had this issue before and if there is a more elegant way to handle it.

Thanks in advance.

**Comment by dbogdanov** [comment]
The "danceability" descriptor gets a NaN value. Can you provide an example file to reproduce it?

**Comment by ewekansige** [comment]
Hi,

This is one of the audios.
[sampleaudio.zip](https://github.com/MTG/essentia/files/3203910/sampleaudio.zip)

Thank you!

**Comment by dbogdanov** [comment]
Not an issue in the latest Essentia builds. This has been fixed in f5340446286d53ac0bc69534d2f6937fe2679555.

**Comment by ewekansige** [comment]
Hi,

The download page for the extractors references this website from 2015: https://essentia.upf.edu/documentation/download.html  >>> https://mtg.github.io/essentia-labs//news/2015/12/22/static-binaries-for-extractors/

Can you please tell me if there are any pre-compiled binaries available on the site with the new bug-free version? (the files from 2015 and from 2018, both have the error)

This is the way I'm using the extractor:
    !./essentia-extractors-v2.1_beta2/streaming_extractor_music $filepath $jsonname

#or this way using the 2018th binaries:
    !./essentia-extractor-tagtraum-v2.1_beta2-linux-x86_64/streaming_extractor_music $filepath $jsonname


Thank you!

**Comment by dbogdanov** [comment]
Yes, we are working on tagging a v2.1_beta5 ASAP (expected to be this or next week). We'll build and host static binaries then.

You can also build the extractors from master branch on your own.

**Comment by ewekansige** [comment]
Okay, thank you!
