### ISSUE TITLE
Arguments for Essentia Music Extractor Command Line Program

### ISSUE THREAD

**Issue by smkm** [MTG/essentia#862]
I want to use the Essentia Library for extraction of high-level music features of a local audio file. I would like to extract high-level features of local music files like how it is done in AcousticBrainz, except that I want to analyze the results myself instead of uploading it to the AcousticBrainz server. 

The default way to use Essentia in Windows is using the precompiled binaries such as streaming_extractor_music, but according to the documentation, there is no information on how to run the program.

However, I am very puzzled about how to use the command-line options essentia_streaming_extractor_music binary. There is no help option or which arguments to use specified. (Also, how can I set where the result file should be saved?)

I have tried to use the binary to run it on Windows 10, but there are absolutely no information on the arguments to run, except some explanations related to the yaml configuration (nevertheless no instruction on how to set the arguments in the command line).

I have done `.\streaming_extractor_music.exe [path to audio file]`, but the result is `Error: wrong number of arguments`. The expected results are either a help message or an outputted json file of the audio features after analysis of the audio file.

It would be a great help for any proper instructions on how to run this program.

Thank you very much.

**Comment by alastair** [comment]
You should find that if you run the extractor without arguments that you'll get the following output:

```
Error: wrong number of arguments
Usage: streaming_extractor_music.exe input_audiofile output_textfile [profile]
```

Therefore you can save the output of the extractor by specifying the location as the second argument.
