### ISSUE TITLE
Live signal processing

### ISSUE THREAD

**Issue by uidar** [MTG/essentia#865]
How can I make essentia process constant live input signal to get the descriptions as soon as possible (like aubio in jack mode)?

**Comment by albincorreya** [comment]
Hey @uidar, you could use the streaming mode of essentia for that. Check the documentation in the following links for more info.
https://essentia.upf.edu/documentation/essentia_python_tutorial.html#using-essentia-in-streaming-mode
https://essentia.upf.edu/documentation/howto_streaming_extractor.html
https://essentia.upf.edu/documentation/extending_essentia_streaming.html

Streaming mode Audioloader can load audio from live audio streams (FFmpeg supported formats)
