### ISSUE TITLE
Invalid spectralShape in NNLSChroma

### ISSUE THREAD

**Issue by pythouille** [MTG/essentia#866]
Hello,

apparently, the spectralShape parameter  of NNLSChroma in standard mode, for both default and given value.

```
import essentia.standard as ess
nnls_all_default = ess.NNLSChroma()
```
causes
```
RuntimeError: Error while configuring NNLSChroma: Parameter spectralShape = 0.699999988079 is not within specified range: (0.5,0.9)
```
(even if 0.7 seems between 0.5 and 0.9) and
```
nnls_other_value = ess.NNLSChroma(spectralShape = 0.6)
```
causes
```
RuntimeError: Error while configuring NNLSChroma: Parameter spectralShape = 0.600000023842 is not within specified range: (0.5,0.9)
```

**Comment by pabloEntropia** [comment]
Hello,
I reproduced your code in my environment an it runs smoothly. Can you give us the following details about your system: operative system, python version, Essentia version (`essentia.__version_git_sha__`) and how was it installed (compiled by yourself, from pip...)?

Thank you!

**Comment by pythouille** [comment]
Ok, I tried again, and it works. I don't explain what was different, but I remember trying mulitple times.
I am on Ubuntu, working with Ipython 5.5.0 and python 3.6.8. I installed essentia with pip, and its version is v2.1_beta4-532-g6b584720. I don't think these parameters were very different last time. But it works now, so ...
Sorry for the inconvenience.

**Comment by pabloEntropia** [comment]
No worries. Thank you for the feedback!
