### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by svenoaks** [MTG/essentia#87]
Getting memory errors when trying to run networks in multiple threads. For example, running standard_fadedetection.cpp with each call in seperate thread for a seperate file produces instant seg fault in MonoLoader. I've seen places (like Logger.flush()) where the comments mention it's not thread-safe. Is the entire library basically not thread safe then?

**Comment by jamiebullock** [comment]
I don't think this really answers the OP's question.

Put simply: is it safe to use all classes in Essentia in a multi-threaded environment, or do some of them, for example share global state? If so, which classes cannot have concurrent instances in separate threads?

PR #91 suggests that the Logger class is an example of a non thread-safe class. Are there any others?
