### ISSUE TITLE
Compile error on iOS: function 'gamma' not available

### ISSUE THREAD

**Issue by lamtev** [MTG/essentia#870]
If you'll try to build __essentia__ for iOS with algorithms included:
```
--include-algos=FrameCutter,Windowing,FFT,Spectrum,PitchYinFFT,\
Magnitude,PeakDetection,CartesianToPolar,BPF,Resample,LowPass,IIR
```
You'll get compile errors like:
```
../src/3rdparty/cephes/bessel/iv.cpp:365:10: error: call to unavailable function 'gamma': not available on iOS
    gp = gamma(v + 1) - 1;
         ^~~~~
```
Accordingly to __man__:
```
gamma() and gamma_r() are deprecated, and should not be used.  The tgamma() function should be used instead.  Note, however, that
     on some platforms, gamma() and gamma_r() historically computed the log of the Gamma function, instead of the Gamma function itself.
     When porting code from such platforms, it will be necessary to use lgamma() or lgamma_r() instead.
```
possible solution is to replace `gamma` with `tgamma` If it is available on all other platforms or to do something like this in other case:
```
#ifdef __APPLE__
#if TARGET_OS_IPHONE || TARGET_IPHONE_SIMULATOR
    //new way
    gp = tgamma(...);
#endif
#else
    //old way
    gp = gamma(...);
#endif
```

In my case there was enough to replace `gamma` with `tgamma` in `../src/3rdparty/cephes/bessel/iv.cpp` and `../src/3rdparty/cephes/bessel/hyperg.cpp` to pass the build.

**Comment by pabloEntropia** [comment]
Thank you for reporting this bug. This problem should be fixed by #879.
Finally, we decided to use the `gamma` function implementation included in the library inside a namespace to prevent naming conflicts.
