### ISSUE TITLE
Bug: parameters in profile.yaml unused

### ISSUE THREAD

**Issue by jpauwels** [MTG/essentia#872]
The options below can be specified in a `profile.yaml` file for the MusicExtractor, and are read, but never used in the actual calculation (`void MusicLowlevelDescriptors::createNetworkLoudness` in `MusicLowlevelDescriptors.cpp`, starting line 324). So their existence is quite misleading.
```
average_loudness:
    windowType: hann
    silentFrames: noise
```
No windowing at all seems to be used for average loudness calculation.

**Comment by dbogdanov** [comment]
Thanks for spotting this!
