### ISSUE TITLE
Cross Compile using Ubuntu

### ISSUE THREAD

**Issue by MicahBrady95** [MTG/essentia#873]
I am currently trying to cross compile following the instructions posted. when I try to configure using MinGW, I get this error

→ Building in release mode
→ Cross-compiling for Windows with MinGW
Checking for program 'i686-w64-mingw32-gcc' : /usr/bin/i686-w64-mingw32-gcc 
Checking for program 'i686-w64-mingw32-g++' : not found 
Could not find the program ['i686-w64-mingw32-g++']
(complete log in /home/micah/essentia/build/config.log)

running ./war -v as another post suggested (https://github.com/MTG/essentia/issues/721) gave me the following

Waf: Entering directory `/home/micah/essentia/build'
→ building from /home/micah/essentia
→ building from /home/micah/essentia/src
Building all the algorithms
Ignoring the following algorithms: IFFTK, MusicExtractorSVM, IFFTA, FFTK, GaiaTransform, FFTA
Created algorithms registration file
→ building from /home/micah/essentia/src/examples
→ building from /home/micah/essentia/src/python
Waf: Leaving directory `/home/micah/essentia/build'
'build' finished successfully (0.576s)

Any insight on how I could fix this?

**Comment by dbogdanov** [comment]
```apt-get install  g++-mingw-w64``` solves this for me.
