### ISSUE TITLE
Unable to build due to missing libchroma

### ISSUE THREAD

**Issue by MicahBrady95** [MTG/essentia#874]
I am unable to build Essentia due to libchroma being not found. I have attempted downloading chromaprint separately, and running the cmake command and re running the build_chromaprint.sh separately along with re running the ./packaging/build_3rdparty_static_win32.sh . After that, attempting to configure once more results in a failed build.

sudo  python3  ./waf configure  --with-python --with-cpptests --with-static-examples --with-vamp  --cross-compile-mingw32
Setting top to                           : /home/micah/essentia 
Setting out to                           : /home/micah/essentia/build 
→ configuring the project in /home/micah/essentia
WARNING: Using --with-static-examples flag instead of --with-examples for cross-compilation with MinGW
→ Building in release mode
→ Cross-compiling for Windows with MinGW
Checking for program 'i686-w64-mingw32-gcc' : /usr/bin/i686-w64-mingw32-gcc 
Checking for program 'i686-w64-mingw32-g++' : /usr/bin/i686-w64-mingw32-g++ 
Checking for program 'i686-w64-mingw32-ar'  : /usr/bin/i686-w64-mingw32-ar 
Checking for 'g++' (C++ compiler)           : /usr/bin/i686-w64-mingw32-g++ 
Checking for 'gcc' (C compiler)             : /usr/bin/i686-w64-mingw32-gcc 
→ Searching *.pc pkg-config files for dependencies in packaging/win32_3rdparty/lib/pkgconfig
Checking for program 'pkg-config'           : /usr/bin/pkg-config 
Checking for 'libavcodec' >= 55.34.1        : yes 
Checking for 'libavformat'                  : yes 
Checking for 'libavutil'                    : yes 
Checking for 'libavresample'                : yes 
Checking for 'samplerate'                   : yes 
Checking for 'taglib' >= 1.9                : yes 
Checking for 'yaml-0.1'                     : yes 
Checking for 'fftw3f'                       : yes 
Checking for 'libchromaprint'               : not found 
Checking for 'gcc' (C compiler)             : /usr/bin/i686-w64-mingw32-gcc 
Checking for program 'python'               : /usr/bin/python3 
Checking for python version >= 2.7.0        : 3.7.3 
→ Configuring for python3
python-config                               : /usr/bin/python3-config 
Asking python-config for pyext '--cflags --libs --ldflags' flags : yes 
Testing pyext configuration                                      : Could not build python extensions 
Testing pyext configuration                                      : Could not build python extensions 
The configuration failed
(complete log in /home/micah/essentia/build/config.log)

I am new to essentia, python and ubuntu, so I apologize for any questions that have an easy fix. If there is any more info I can provide please let me know. Thank you

**Comment by MicahBrady95** [comment]
running the chromaprint .sh gives me this error

micah@ubuntu:~/essentia/packaging/debian_3rdparty$ ./build_chromaprint.sh
Installing to: /home/micah/essentia/packaging/debian_3rdparty
Building chromaprint 1.4.3
./build_chromaprint.sh: 10: ./build_chromaprint.sh: curl: not found
tar: chromaprint-1.4.3.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
./build_chromaprint.sh: 12: cd: can't cd to chromaprint-v1.4.3
CMake Error: The source directory "/home/micah/essentia/packaging/debian_3rdparty/tmp" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
rm: cannot remove 'tmp': No such file or directory
sed: can't read /home/micah/essentia/packaging/debian_3rdparty/lib/pkgconfig/libchromaprint.pc: No such file or directory

running the make file gives me

micah@ubuntu:~/essentia/chromaprint$ sudo make
Scanning dependencies of target chromaprint_objs
[  5%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/fft_lib_avfft.cpp.o
[ 10%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/audio_processor.cpp.o
[ 15%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/chroma.cpp.o
[ 20%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/chroma_resampler.cpp.o
[ 25%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/chroma_filter.cpp.o
[ 30%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/spectrum.cpp.o
[ 35%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/fft.cpp.o
[ 40%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/fingerprinter.cpp.o
[ 45%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/image_builder.cpp.o
[ 50%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/simhash.cpp.o
[ 55%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/silence_remover.cpp.o
[ 60%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/fingerprint_calculator.cpp.o
[ 65%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/fingerprint_compressor.cpp.o
[ 70%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/fingerprint_decompressor.cpp.o
[ 75%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/fingerprinter_configuration.cpp.o
[ 80%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/fingerprint_matcher.cpp.o
[ 85%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/utils/base64.cpp.o
[ 90%] Building C object src/CMakeFiles/chromaprint_objs.dir/avresample/resample2.c.o
[ 90%] Built target chromaprint_objs
Scanning dependencies of target chromaprint
[ 95%] Building CXX object src/CMakeFiles/chromaprint.dir/chromaprint.cpp.o
[100%] Linking CXX shared library libchromaprint.so
[100%] Built target chromaprint

the issue I think is the Chromaprint library is not being built because it is not able to find the tar file.If that is the case, how am I able to fix that?

**Comment by MicahBrady95** [comment]
I fix the missing libchroma by editing the build_chromaprint.sh file from:
 curl -SLO https://github.com/acoustid/chromaprint.git
to:
curl -SLO https://github.com/acoustid/chromaprint/releases/download/v1.4.3/chromaprint-1.4.3.tar.gz

however the error: Testing pyext configuration : Could not build python extensions, still remains

**Comment by dbogdanov** [comment]
We've added a build script for chromaprint to ```packaging/win32_3rdparty/``` (89ed16fb85939f04b2cdb49f6aa15220e89ccb0d) however it fails for now: https://github.com/acoustid/chromaprint/issues/61.
