### ISSUE TITLE
Batch Processing and Feasibility

### ISSUE THREAD

**Issue by jamesb93** [MTG/essentia#875]
Hi,

I want to use Essentia to compute many descriptors on a number of audio files (around 21000). Running this in Python works well and is highly readable but it's taking ages on my 4 core 2015 Macbook Pro. Is it possible to run Essentia in the cloud, and has anyone done so? I have $300 of compute credit on Google Cloud to run, so I was curious if anyone had tried this before. Perhaps some tips can be given for optimising batch processing?

**Comment by dbogdanov** [comment]
You should be fine running analysis in the cloud (pip install essentia works fine, or you can use the standalone streaming_extractor_music).

For batch processing, you can prepare a script that compute what you want and stores results for a given input audio file, and then parallelize it, running each file in a separate process (this also avoids any possible memory leaks). We run Essentia Music Extractor on very large audio collections this way on our cluster.

Also, have a look at https://github.com/MTG/essentia/blob/master/src/python/essentia/pytools/extractors.py#L42

**Comment by jamesb93** [comment]
Thanks, this is very helpful. I did end up translating my python code into a c++ program that ran in a single thread. It did eventually compete 39 hours later, but I think it would be good to optimise it and parallelise the process so that I can re-analyse files, or use the powerful descriptors at a later point.

Ideally, should I just build my own extractor and run it like a CLI with args passed to it (file names)? This is easy to coordinate with python or even bash. I'm just sort of vague on the details how you go from code -> instantiating multiple processes.

**Comment by dbogdanov** [comment]
We often simply run a bunch of bash scripts in parallel, each one processing files with an extractor binary one by one.

**Comment by jamesb93** [comment]
I managed to export my extractor from c++. The performance is much better to be fair so it's worth it. Can you provide an example of a parallelized bash script? I assume you just pass inputs and outputs to your binary.

**Comment by dbogdanov** [comment]
Correct, for simplicity we often  process with a bunch of scripts like 
```
./essentia_streaming_extractor_music <input-audio-file-1> <output-json-file-1>
./essentia_streaming_extractor_music <input-audio-file-2> <output-json-file-2>
...
```

manually running in parallel according to the number of cores, where ```essentia_streaming_extractor_music ``` is a precompiled C++ binary. 

Of course, you can automatize that, for example, from python running each command in a separate subprocess.

**Comment by jamesb93** [comment]
Okay.

I went the Python route as it's much more familiar to me. For the benefit of everyone else the script is really as simple as follows:

`import subprocess as sp
import multiprocessing as mp
import os
import sys 
import time
from db_vars import unique_audio_folder, unique_audio_files, tmp


num_jobs = len(unique_audio_files)

def process(idx):

    input_file = os.path.join(unique_audio_folder, unique_audio_files[idx])
    output_file = os.path.join(tmp, f'{unique_audio_files[idx]}.yaml')

    if not os.path.isfile(output_file):
        sp.call([
            'essentia_streaming_batchanal', 
            input_file,
            output_file
        ])
    

with mp.Pool() as pool:
    for i, _ in enumerate(
        pool.imap_unordered(process, range(num_jobs))
        , 1):
        sys.stderr.write('\rdone {0:%}'.format(i/num_jobs))`
