### ISSUE TITLE
Cannot load essentia.standard.{function}

### ISSUE THREAD

**Issue by hankers** [MTG/essentia#880]
Whenever I try to load a function from the essentia library, say RMS from essentia.standard, I obtain the error:
TypeError: __init__() takes 1 positional argument but 2 were given
![image](https://user-images.githubusercontent.com/1625949/61636585-810c1480-acc8-11e9-8d80-c7b7acfa5097.png)

**Comment by dbogdanov** [comment]
You should first initialize an instance of the algorithm (in the case of RMS there are no parameters) and then run it: 

```
RMS()(input_vector)
```
