### ISSUE TITLE
could I get stft/istft by using C++ ？

### ISSUE THREAD

**Issue by ucasiggcas** [MTG/essentia#910]
hi,

If I want to use C++ to get the stft and istft ,how should I do ?
Any functions for them ?
Thanks a lot.

Tychee

**Comment by pabloEntropia** [comment]
hi @ucasiggcas,
you can perform stft/istft analysis/synthesis in Essentia connecting the following algorithms:

- (Analysis) Monoloader -> FrameCutter -> Windowing -> FFT

- (Synthesis) IFFT -> OverlapAdd

have a look at this [ c++ example](https://github.com/MTG/essentia/blob/master/src/examples/standard_stft.cpp).

**Comment by ucasiggcas** [comment]
@pabloEntropia 
Thanks, will have a try .
