### ISSUE TITLE
How can I convert from Real data type to Float in C++

### ISSUE THREAD

**Issue by ARincon243** [MTG/essentia#922]
Hi I'm trying to do a GUI application in JUCE based on harmonic model example. In that application I have multiple float array to save the data and compute the FFT in JUCE. Then I wanted to use the essentia functions in my application to get the harmonics from the model but I don't know if essentia is working cause I don't see any data in the harmonic array. I think is because I have float arrays and I'm using them in parts where is required real arrays. Do any of you guys know how can I convert those float arrays into real arrays and the other way around.

**Comment by pabloEntropia** [comment]
Hi @ARincon243,
our `Real` type is just a typdef to `float` so your problem should be somewhere else,  
https://github.com/MTG/essentia/blob/d6316c7b74f486c4faad8a64478108cb006c2e32/src/essentia/types.h#L68
Can you elaborate a bit more on how are you using Essentia (i.e., standard or streaming mode, how are you configuring and feeding the algorithms, etc...)?

**Comment by ARincon243** [comment]
Hi @pabloEntropia,
I used essentia after I compute FFT in JUCE, I mean, My application is based on harmonic model example and I start to use essentia from configure spectrum where the variable fifo is the data windowed from JUCE and the variable fifocomplex is the result of FFT.

// configure spectrum:
        spectrum->input("frame").set(fifo);
        spectrum->output("spectrum").set(spec);

// Harmonic model analysis
        harmonicmodelanal->input("fft").set(fifocomplex); // input fft
        harmonicmodelanal->input("pitch").set(thisPitch); // inputs a pitch
        harmonicmodelanal->output("magnitudes").set(magnitudes);
        harmonicmodelanal->output("frequencies").set(frequencies);
        harmonicmodelanal->output("phases").set(phases);
