### ISSUE TITLE
Essentia audio fingerprints not equals fingerprints generated with pyacoustid

### ISSUE THREAD

**Issue by Ogala** [MTG/essentia#923]
My understanding of a fingerprint is that it should be unique and the same, regardless of the capture medium as long as the basic computational method is constant.  

Both Essentia and AcousticID use Chromprint for fingerprinting, however, the fingerprints generated by both are not equal - in my experience. Is this by design? 

Consider this
```
import essentia
import essentia.standard as es
import acoustid as ai
import chromaprint as ch

audio = es.MonoLoader(filename='../../Downloads/test.mp3', sampleRate=44100)()
fingerprint = es.Chromaprinter()(audio)
c = bytes(fingerprint, "utf_8")
g, v = ch.decode_fingerprint(c)

duration, fp_encoded = ai.fingerprint_file('../../Downloads/test.mp3')
f, version = ch.decode_fingerprint(fp_encoded)

print(len(f), len(g)) # f is usually less than g
print(len(f) == len(g)) # false

however,

print(g[:len(f)] == f) # true
```
Apparently, `fingerprint` by pyacoustid is a subset of Essentia's. Is this intended?

**Comment by pabloEntropia** [comment]
Hi @Ogala,
your analysis seems correct to me.
By inspecting [pyacousticid](https://github.com/beetbox/pyacoustid)'s code I found that it processes the first 120 seconds by default.
https://github.com/beetbox/pyacoustid/blob/c41e1cca129b427b7f31b853b26538b2326df0da/acoustid.py#L325

In our case, the default is to compute the chromaprint for the whole track,
https://github.com/MTG/essentia/blob/96531284a35ef6142c6e6ed80cad8b82a9751e2e/src/algorithms/highlevel/chromaprinter.h#L50

You could replicate `pyacousticid` by changing this line from your code above,
```
fingerprint = es.Chromaprinter(maxLength=120)(audio)
```

**Comment by Ogala** [comment]
Ah! that explains it. Thanks @pabloEntropia
