### ISSUE TITLE
NSGT with Mel scale

### ISSUE THREAD

**Issue by cveaux** [MTG/essentia#944]
Hi,
this is more a question than an issue. Is it possible or is there a plan to add the possibility to use the NSG transform on other scales than the octave scale (Constant Q). I would like to use it for speech analysis and the Mel scale or ERB scale would be more useful. 

A separate question, do you know if there is any algorithm that could be used to resynthesise an approximation of the signal from the magnitude of the NSG transform only. For a spectrogram there are iterative algorithms such as Griffin Lim or Phase Gradient Heap Inversion (http://ltfat.github.io/notes/043/) so I was wondering if such approaches could be applied to a NSG transform?
Thanks!

**Comment by pabloEntropia** [comment]
Hi @cveaux,
indeed, it would be great to have NSG transforms at different scales, but the Constat-Q constrain is hardcoded in the current implementation and there is no plan to support others soon. 
https://github.com/MTG/essentia/blob/ba79be6515f2fd0cde75ee3f6fa98706a66f4c36/src/algorithms/standard/nsgconstantq.cpp#L90

However, the changes required to modify the scale are quite straightforward and you are welcome to propose a PR  with implementations for those you may find useful.

To answer your second question, the algorithm was designed to allow perfect reconstruction from a compact complex representation and in my experience, it's quite sensitive to phase degradation. Thus, I wouldn't expect traditional STFT phase reconstruction algorithms to work very well on it, but I have never tried myself.

**Comment by cveaux** [comment]
Thanks for these answers. Indeed it seems quite a simple modification so I'll test it here and submit it afterwards.

**Comment by pabloEntropia** [comment]
That sounds great! Feel free to open a PR to continue the discussion on your proposed modification.
