### ISSUE TITLE
cross compile broke

### ISSUE THREAD

**Issue by mice2100** [MTG/essentia#956]
_OS: UBUNTU 19.10
Essentia ver: 2.1 Beta 5
Producing:_
1: **./packaging/build_3rdparty_static_win32.sh**
[Everything is OK.
2.**./waf configure --with-static-examples --cross-compile-mingw32
./waf**
The following errors occur during linking examples:

[288/288] Linking build/src/libessentia.a
[290/383] Linking build/src/examples/essentia_standard_beatsmarker.exe
[292/383] Linking build/src/examples/essentia_standard_fadedetection.exe
[294/383] Linking build/src/examples/essentia_standard_mfcc.exe
[296/383] Linking build/src/examples/essentia_standard_onsetrate.exe
[298/383] Linking build/src/examples/essentia_standard_pitchdemo.exe
[300/383] Linking build/src/examples/essentia_standard_rhythmtransform.exe
[304/383] Linking build/src/examples/essentia_standard_spectralcontrast.exe
[305/383] Linking build/src/examples/essentia_standard_vibrato.exe
/usr/bin/i686-w64-mingw32-ld: src/libessentia.a(chromaprinter.cpp.1.o):chromaprinter.cpp:(.text+0x488): undefined reference to `_imp__chromaprint_new'
/usr/bin/i686-w64-mingw32-ld: src/libessentia.a(chromaprinter.cpp.1.o):chromaprinter.cpp:(.text+0x4f2): undefined reference to `_imp__chromaprint_start'
/usr/bin/i686-w64-mingw32-ld: src/libessentia.a(chromaprinter.cpp.1.o):chromaprinter.cpp:(.text+0x590): undefined reference to `_imp__chromaprint_feed'
/usr/bin/i686-w64-mingw32-ld: src/libessentia.a(chromaprinter.cpp.1.o):chromaprinter.cpp:(.text+0x60b): undefined reference to `_imp__chromaprint_finish'
/usr/bin/i686-w64-mingw32-ld: src/libessentia.a(chromaprinter.cpp.1.o):chromaprinter.cpp:(.text+0x68d): undefined reference to `_imp__chromaprint_get_fingerprint'
/usr/bin/i686-w64-mingw32-ld: src/libessentia.a(chromaprinter.cpp.1.o):chromaprinter.cpp:(.text+0x71f): undefined reference to `_imp__chromaprint_dealloc'
/usr/bin/i686-w64-mingw32-ld: src/libessentia.a(chromaprinter.cpp.1.o):chromaprinter.cpp:(.text+0x732): undefined reference to `_imp__chromaprint_free'
/usr/bin/i686-w64-mingw32-ld: src/libessentia.a(chromaprinter.cpp.1.o):chromaprinter.cpp:(.text+0x19af): undefined reference to `_imp__chromaprint_new'
/usr/bin/i686-w64-mingw32-ld: src/libessentia.a(chromaprinter.cpp.1.o):chromaprinter.cpp:(.text+0x1a01): undefined reference to `_imp__chromaprint_start'
/usr/bin/i686-w64-mingw32-ld: src/libessentia.a(chromaprinter.cpp.1.o):chromaprinter.cpp:(.text+0x1b1f): undefined reference to `_imp__chromaprint_feed'
/usr/bin/i686-w64-mingw32-ld: src/libessentia.a(chromaprinter.cpp.1.o):chromaprinter.cpp:(.text+0x1ba1): undefined reference to `_imp__chromaprint_finish'
/usr/bin/i686-w64-mingw32-ld: src/libessentia.a(chromaprinter.cpp.1.o):chromaprinter.cpp:(.text+0x1c2a): undefined reference to `_imp__chromaprint_get_fingerprint'
/usr/bin/i686-w64-mingw32-ld: src/libessentia.a(chromaprinter.cpp.1.o):chromaprinter.cpp:(.text+0x1cdb): undefined reference to `_imp__chromaprint_dealloc'
/usr/bin/i686-w64-mingw32-ld: src/libessentia.a(chromaprinter.cpp.1.o):chromaprinter.cpp:(.text+0x1cf5): undefined reference to `_imp__chromaprint_free'

**nm libchromaprint.a |grep chromaprint**
chromaprint.cpp.obj:
00000560 T _chromaprint_clear_fingerprint
00000cb0 T _chromaprint_dealloc
000008b0 T _chromaprint_decode_fingerprint
00000580 T _chromaprint_encode_fingerprint
00000ed0 T _chromaprint_feed
00000190 T _chromaprint_finish
00000e70 T _chromaprint_free
000000d0 T _chromaprint_get_delay
00000100 T _chromaprint_get_delay_ms
000001b0 T _chromaprint_get_fingerprint
00000530 T _chromaprint_get_fingerprint_hash

**Comment by dbogdanov** [comment]
Fixed in 1f9eabe93287f1464068c024d1972d2b0f9000e9. Use the latest development version from the master branch.
