### ISSUE TITLE
Can not use TensorflowPredict, TensorflowPredictMusiCNN, and TensorflowPredictVGGish.

### ISSUE THREAD

**Issue by VickyChing** [MTG/essentia#977]
I executed the command 
`pip install essentia`  &
`pip install essentia-tensorflow`,
but I can't use TensorflowPredict, TensorflowPredictMusiCNN, and TensorflowPredictVGGish functions, even can not pass the unit tests, all of those three tell 
`NameError: name 'TensorflowPredictxxx' is not defined`
Thanks for helping me to solve this problem.

I have tried to install essentia with tensorflow from source, but it failed.
I built essentia with the following ways from source: 
[https://mtg.github.io/essentia-labs/news/2019/10/19/tensorflow-models-in-essentia/](url)

No step goes wrong, and test successfully with the following command:
`./waf run_tests`

But when I run the python unit test:
`./waf run_python_tests`,
it comes up with a segmentation fault.
When I debug in Pycharm, it tells the Import Error:  _pywrap_tensorflow_internal.so: undefined symbol: ZTINSt6thread6_StateE

Thanks for helping me to solve this problem.

**Comment by pabloEntropia** [comment]
Hi @VickyChing ,
sorry about the misleading information in the post, our PyPI wheels are not ready yet.  In the meanwhile, you can install `essetia-tensorflow` with 
`pip install -f https://essentia.upf.edu/python-wheels/ essentia-tensorflow` 
(requires pip version ≥19.3).

If you are still interested in building `essentia-tensorflow` we will need more details about your installation: python, pip and tensorflow versions and the OS used.

Thanks!

**Comment by dbogdanov** [comment]
The package on PyPI is a dummy package. We've just got our upload limits raised on PyPI and we will update the package there soon with the new Essentia pre-release.

**Comment by VickyChing** [comment]
> If you are still interested in building `essentia-tensorflow` we will need more details about your installation: python, pip and tensorflow versions and the OS used.
> 
Thanks for your reply. These are my installation details:
python: 3.5.2
pip: 20.1
tensorflow: 1.15.0
OS: ubuntu 16.04

**Comment by pabloEntropia** [comment]
Closing this issue since essentia-tensorflow is already available in PyPI (pip install essentia-tensorflow)
