### ISSUE TITLE
Documentation: "news" URLs are broken throughout 

### ISSUE THREAD

**Issue by drscotthawley** [MTG/essentia#980]
It seems that the file structure for many pages at https://mtg.github.io/essentia-labs/ has been changed, but the links referring to these pages have not, resulting in many "Page not found" 404 errors when trying to read and follow the links. 

For example, the instructions for Tensorflow are listed in many places throughout the essentia documentation as being at
https://mtg.github.io/essentia-labs/news/2019/10/19/tensorflow-models-in-essentia/

Perhaps that once worked, but the page now lives at 
https://mtg.github.io/essentia-labs/news/tensorflow/2019/10/19/tensorflow-models-in-essentia/

And anything that reads "In our <ins>last post</ins>", or "<ins>next post</ins>" the link provided will give 404. 

Such 'news' URLs are referred to by non-news pages, such as in instructions contained in https://essentia.upf.edu/machine_learning.html and https://essentia.upf.edu/documentation.html, so trying to follow the docs is a lot of 404's right now. 

(I suspect that someone added category tags to the Jekyll blog system, not realizing that tags in Jekyll are implemented by it changing the URL.  I too have had this happen to me and it's inconvenient!)

**Comment by dbogdanov** [comment]
Thanks for noticing! We've updated the documentation online.

**Comment by dbogdanov** [comment]
Also in https://github.com/MTG/essentia-labs/commit/2742d0841ceb7e50dbc98ed6a92c594cdf4a9a44
