### ISSUE TITLE
 RuntimeError: In AudioWriter.compute: AudioWriter: Trying to call compute() on an AudioWriter algo which hasn't been correctly configured...

### ISSUE THREAD

**Issue by Maggie-Jing** [MTG/essentia#982]
hi:
     i just run the essentia_python_examples of Onset detection get this problem, my configured peocess is work well. please help me, thanks!

**Comment by Maggie-Jing** [comment]
i find the reason in the AudioWriter Description:  An exception is thrown when other extensions are given. Note that to encode in mp3 format it is mandatory that FFmpeg was configured with mp3 enabled.
w change the output into .wav is fine

**Comment by lee-eunyeol** [comment]
thanks
