### ISSUE TITLE
[QUESTION] Classes of TensorflowPredictMusiCNN models

### ISSUE THREAD

**Issue by loretoparisi** [MTG/essentia#992]
Is there a documentation of all classes available for TensorflowPredictMusiCNN?
Are the same classes of **[musicnn](https://github.com/jordipons/musicnn)** or a subset?
Thank you.

**Comment by pabloEntropia** [comment]
Hi @loretoparisi,
the information about the classes predicted by each model suitable for TensorflowPredictMusiCNN is contained in the README files available in our [model repository](https://essentia.upf.edu/models/autotagging/msd/).
In the case of MusiCNN we support both, models trained in the [MagnaTagATune](https://essentia.upf.edu/models/autotagging/mtt/) and the [Millon Song Dataset](https://essentia.upf.edu/models/autotagging/msd/) top 50 labels.

Those models are exactly the same you can find in the original MusiCNN implementation so the classes are also the same.
