### ISSUE TITLE
Custom tensorflow build

### ISSUE THREAD

**Issue by hellseyfer** [MTG/essentia#993]
Has someone tried installing a custom tensorflow version build?

I get

> [323/323] Linking build/src/python/_essentia.cpython-36m-x86_64-linux-gnu.so
> /usr/bin/ld: no se puede encontrar -ltensorflow
> /usr/bin/ld: no se puede encontrar -ltensorflow_framework
> collect2: error: ld devolvió el estado de salida 1
> 

while trying to build  essentia (python3 waf). the first step (compilation) shows tensorflow was found.

I tried tensorflow for C https://www.tensorflow.org/install/lang_c#linker and it worked but that version is not compatible with my cpu.

thanks

**Comment by pabloEntropia** [comment]
We provide scripts for building our dependencies (TensorFlow is optionally included) in Linux, check [this script](https://github.com/MTG/essentia/blob/master/packaging/build_3rdparty_static_debian.sh). It creates static libraries for all our dependencies.
Then you will have to add `--with-static-dependencies` to your `python3 waf configure` step to link against those.
