### ISSUE TITLE
UBUNTU 20.04: essentia_streaming_extractor_music_svm: error while loading shared libraries: libQtCore.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Ogala** [MTG/essentia#995]
I recently upgraded to Ubuntu 20.04 and I have been unable to run the music extractor svm binaries since then. The error message indicates it has something do with `libQtCore`. 

error: `essentia_streaming_extractor_music_svm: error while loading shared libraries: libQtCore.so.4: cannot open shared object file: No such file or directory`

According to this newsletter in Ubuntu list ([Removing Qt 4 from Ubuntu before the 20.04 release](https://lists.ubuntu.com/archives/ubuntu-devel/2019-August/040783.html)) its developer, Simon Quigley, was discontinuing the QT4 library for the 20.04 release.

Has anyone found a workaround for this error and is there going to be an update to the binaries?

**Comment by dbogdanov** [comment]
We are updating to QT5 in Gaia (https://github.com/MTG/gaia/issues/101), but meanwhile you can always build Essentia with static dependencies. This way you'll also build static Gaia with QT4. 

https://essentia.upf.edu/FAQ.html#linux-osx-static-builds

So, 
```
./packaging/build_3rdparty_static_debian.sh --with-gaia
python3 waf configure --static-dependencies <...>
```

**Comment by Ogala** [comment]
Thanks, @dbogdanov. This worked for me. I think we can close it now.

If this solution doesn't work for anyone, the alternate solution is to dockerize them using Ubuntu 18.04 as a base image.
